### ISSUE TITLE
添加固定的头布局

### ISSUE THREAD

**Issue by openandroid9527** [scwang90/SmartRefreshLayout#10]
如题,我想在头部添加个 banner 布局该怎么实现

**Comment by scwang90** [comment]
可以的，你可以参考这个说明 [嵌套布局](https://github.com/scwang90/SmartRefreshLayout/blob/master/art/md_smart.md) 中的后一部分 【嵌套Layout作为内容】 

你看下面这个位置在 demo-实战-微博列表

![image](https://github.com/scwang90/SmartRefreshLayout/raw/master/art/gif_practive_feedlist.gif)

**Comment by openandroid9527** [comment]
好的.
