### ISSUE TITLE
嵌套scrollview并使用空白的上下越界，当惯性滑动到顶部或者底部时候会有一瞬间的卡顿

### ISSUE THREAD

**Issue by yucaigitup** [scwang90/SmartRefreshLayout#1002]
首先感谢作者，这是目前见过越界效果最接近ios的，然后说下问题，嵌套scrollview并使用空白的上下越界，当惯性（惯性滚动，已经松手了）滑动到顶部或者底部时会有一瞬间的卡顿，不严重，但是对比和recycleview的顺滑还是能看到，而且已经增加android:overScrollMode="never" 这个属性，其余的listview和RecyclerView都使用过效果都非常好，只有scrollview有问题

**Comment by yucaigitup** [comment]
最新发现，嵌套recyclerView和listview的时候也是有卡顿的，但是比较轻微，但是手动下拉，知道列表第一排结束马上要出来刷新框架头部的一瞬间会丢失焦点，我看了下代码，那一瞬间，手势判断还是在recyclerView中，如果此时你按部位有点击态的话是能观察到按压的，然后你再接着向下滑动，才会拉出框架头部，也就是说这个卡顿一下是，判断间隔导致的

**Comment by yucaigitup** [comment]
都没人回答吗？这个问题我都问了好久了，我现在都不再scrollview外层使用这个刷新了，recycleview的外层使用还可以，你们都没遇到过这个问题？

**Comment by scwang90** [comment]
demo 也有 scrollview 的例子，可以参考一下

**Comment by feng612266** [comment]
> 都没人回答吗？这个问题我都问了好久了，我现在都不再scrollview外层使用这个刷新了，recycleview的外层使用还可以，你们都没遇到过这个问题？

你好，现在用哪个刷新
