### ISSUE TITLE
1.1.0版ClassicsFooter自动加载更多，到没有更多数据的时候，还显示了loading

### ISSUE THREAD

**Issue by qq549631030** [scwang90/SmartRefreshLayout#1003]
refreshLayout.setEnableAutoLoadMore(true)
        refreshLayout.setEnableFooterFollowWhenNoMoreData(true)

到没有更多数据的时候，还显示了loading，希望这个时候不要显示loading了

**Comment by sceneren** [comment]
我也遇到这个问题了 如果只有1页的时候是正常的 如果是多页就有问题了

**Comment by makecloud** [comment]
我也遇到了这个问题。上拉加载完数据，调用了finishLoadMoreWithNoMoreData，但是那个转圈的loading动画view还在存在。单页的情况就不会这样。

**Comment by a1227308812** [comment]
同问

**Comment by xuehuashi** [comment]
mRefreshLayout.resetNoMoreData();//setNoMoreData(false)
mRefreshLayout.finishLoadMore();
可以解决bug

**Comment by shuangqingfeng** [comment]
这个问题怎么解决呢

**Comment by oneornone** [comment]
> 这个问题怎么解决呢

https://github.com/scwang90/SmartRefreshLayout/issues/1073

**Comment by scwang90** [comment]
看常见问题

**Comment by PokerMman** [comment]
> 看常见问题

应该是显示了没有数据的文字调用了finishLoadMoreWithNoMoreData  但是还是显示loading的View ，文字状态都变成了加载完毕了
