### ISSUE TITLE
setEnableFooterFollowWhenNoMoreData没有生效

### ISSUE THREAD

**Issue by EdminhPeng** [scwang90/SmartRefreshLayout#1006]
**详细描述**
使用androidx，从1.1.0-andx-4升级至1.1.0，全局设置没有更多数据之后 Footer 跟随内容。

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0' 
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0' 
```
**使用代码**
```java
SmartRefreshLayout.setDefaultRefreshInitializer((context, layout) -> layout.setEnableFooterFollowWhenNoMoreData(true));
```

**问题重现**
问题重现操作不走:
1. 上拉加载更多，直至加载到最后一页，显示没有更多了的view，底部Footer并没有跟随内容，会被回弹消失

**预期行为**
没有更多数据之后 Footer 跟随内容。

**Comment by jeromekai** [comment]
1.refreshlayout 要配置 app:srlEnableFooterFollowWhenNoMoreData="true"
2. if (list.isEmpty()){
                mBinding.refreshLayout.finishLoadMoreWithNoMoreData()
            } else {
                mBinding.refreshLayout.finishLoadMore()
            }
