### ISSUE TITLE
大家有没有觉得 上拉加载 感觉怪怪的 不是很自然

### ISSUE THREAD

**Issue by VipMinF** [scwang90/SmartRefreshLayout#101]
上拉加载 感觉怪怪的 不是很自然 仅是第一次会出现，像是一个动画 和上拉距离无关

**Comment by MartinLi2015** [comment]
是的；第一次进来时，感觉view在整个footer在content之上，消失的时候看的特别别扭

**Comment by scwang90** [comment]
关闭自动加载可以解决问题，app:srlEnableAutoLoadmore = false

**Comment by huashengzzz** [comment]
大多数情况下就是要自动加载啊，就是感觉卡卡的感觉
