### ISSUE TITLE
PathsDrawable 在华为mate 10 青春版不显示

### ISSUE THREAD

**Issue by inshyma** [scwang90/SmartRefreshLayout#1012]
no version    no layout.xml
我使用您的PathsDrawable类创建Drawable 在华为mate 10 青春版(android 9.1)手机上不显示

**Comment by scwang90** [comment]
PathsDrawable 不兼容 android P，这个问题目前没有找到解决方案

**Comment by inshyma** [comment]
能大概说一下是哪里的api不兼容或者哪里出了问题  不想换图片或者写vector

**Comment by inshyma** [comment]
刚找到个替换方案 你看下是否可以 https://github.com/pskink/PathDrawable

**Comment by scwang90** [comment]
谢谢，有时间参考一下
