### ISSUE TITLE
没有更多数据要上拉时才可见，如何放出来呢？

### ISSUE THREAD

**Issue by ZINK001** [scwang90/SmartRefreshLayout#1013]
下拉之后
refreshLayout.finishRefresh();

上拉之后
refreshLayout.finishLoadMore();
refreshLayout.finishLoadMoreWithNoMoreData();

头尾使用
ClassicsHeader
ClassicsFooter

“没有更多数据”这个条目没有驻留，必须上拉之后才可见，松手之后又回弹为不可见了
@scwang90 请问是还要做其他设置，才可以让“没有更多数据”驻留在内容部分的尾部吗？

**Comment by gysssss** [comment]
这个问题遇到过  但是我的需求是让他不可见。我是禁用了下拉刷新之后 ，上拉加载到最后一条数据的时候设置没有更多内容的提示的，然后再上拉一次，他那个条目就不会回弹了

**Comment by xj913492952** [comment]
还有就是数据不满一页的时候，上拉加载是隐藏在屏幕下面的，不是像其他app那样跟随在列表后面的，不知道怎么解决

**Comment by xj913492952** [comment]
这个问题貌似不好解决，如果设置高度包裹列表，当列表数据为空时导致刷新view高度也为0，没法下拉

**Comment by yangle610** [comment]
同问

**Comment by Juslt** [comment]
同问

**Comment by omyrobin** [comment]
我也需要让没有更多驻留在底部 而不是上拉才可以见到

**Comment by scwang90** [comment]
参考 demo 中的 例子->没有更多数据
