### ISSUE TITLE
主题中添加了全局背景色为白色(<item name="android:background">@color/c_fff</item>),添加了SmartRefreshLayout的RecycleView中加载的数据显示不出来

### ISSUE THREAD

**Issue by catch-pig** [scwang90/SmartRefreshLayout#1015]
**具体说下**
...
<style name="AppTheme" parent="AppThemeBarStyle">
        
        <item name="colorPrimary">@android:color/white</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:background">@color/c_fff</item>
        <item name="android:textColor">@color/c_333</item>
        <item name="android:screenOrientation">portrait</item>
    </style>

主题颜色中设置了android:background属性,RecycleView的Adapter里面的数据显示不出来
**为什么**
把android:background的属性去掉,就能看到Adapter显示的数据

**Comment by catch-pig** [comment]
使用的header是MaterialHeader

**Comment by scwang90** [comment]
问题无法重现
