### ISSUE TITLE
上拉加载卡顿

### ISSUE THREAD

**Issue by yzjssyzj** [scwang90/SmartRefreshLayout#1016]
**具体说下**
我是SmartRefreshLayout里面嵌套了netscrollview
我的布局文件类似这样
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".activity.TestActivity">

   <com.scwang.smartrefresh.layout.SmartRefreshLayout
       android:layout_width="match_parent"
       android:layout_height="match_parent">

       <com.scwang.smartrefresh.header.MaterialHeader
           android:layout_width="match_parent"
           android:layout_height="wrap_content" />
       <android.support.v4.widget.NestedScrollView
           android:id="@+id/never_scroll_id"
           android:layout_width="match_parent"
           android:layout_height="match_parent">

           <LinearLayout
               android:layout_width="match_parent"
               android:layout_height="match_parent"
               android:orientation="vertical">

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <TextView
                   android:layout_width="match_parent"
                   android:layout_height="40dp"
                   android:text="xxxxxxxxxxxxxx" />

               <android.support.v7.widget.RecyclerView
                   android:id="@+id/recyclerView"
                   android:layout_width="match_parent"
                   android:layout_height="match_parent"
                   android:overScrollMode="never"
                   tools:listitem="@android:layout/simple_list_item_2" />
           </LinearLayout>
       </android.support.v4.widget.NestedScrollView>

       <com.scwang.smartrefresh.layout.footer.ClassicsFooter
           android:id="@+id/fooder_my"
           android:layout_width="match_parent"
           android:layout_height="wrap_content" />
   </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</LinearLayout>
我列表加载方式是
GridLayoutManager layoutManagernew = new GridLayoutManager(getActivity(), 2, GridLayoutManager.VERTICAL, false);
问题如下：
页面刚进入刷新加载正常，当我上拉加载几次，上拉加载更多几次数据，页面滑动就开始卡顿了
不知道作者有没有遇到过这样的问题，谢谢，可以给出解决方案吗？谢谢，期待作者的回复。

**Comment by wangliuweihehe** [comment]
我也是

**Comment by Erichkko** [comment]
+1

**Comment by xingyufeng** [comment]
真的好卡 一样的问题 加上拉加载就会出现这种情况 还有遇到这个问题的么

**Comment by scwang90** [comment]
用 NestedScrollView 做上拉加载，卡顿是正常的
