### ISSUE TITLE
使用autoRefreshAnimationOnly()有时候会关闭不了刷新

### ISSUE THREAD

**Issue by wucomi** [scwang90/SmartRefreshLayout#1019]
**具体说下**
网络请求时使用autoRefreshAnimationOnly()自动刷新, 请求成功了关闭刷新有时关闭不了, 一直刷新

**为什么**
...

**Comment by xuehuashi** [comment]
同样的问题，全部加载完，还在loading

**Comment by StarkSongV** [comment]
我也碰到了...
第一次autoRefreshAnimationOnly ,然后关闭下拉刷新.
第二次手动滑动屏幕触发下拉刷新的时候,有时候不走 onRefreshListener 方法

**Comment by scwang90** [comment]
1.1.1 版本即将发布修复
