### ISSUE TITLE
更新1.0.3之后，找不到 RefreshLayout 这个类

### ISSUE THREAD

**Issue by hw20101101** [scwang90/SmartRefreshLayout#102]
也找不到 SmartRefreshLayout 这个类

**Comment by scwang90** [comment]
这个问题作者也帮不了你

**Comment by hw20101101** [comment]
666

**Comment by NicodeLee** [comment]
给你找一个，https://github.com/scwang90/SmartRefreshLayout/blob/master/refresh-layout/src/main/java/com/scwang/smartrefresh/layout/SmartRefreshLayout.java

**Comment by hw20101101** [comment]
@NicodeLee 你说这个我看到过，但是我更新为1.0.3之后，之前用的 ```RefreshLayout``` 却报错，改成 ```SmartRefreshLayout``` 之后，使用快捷键导包时却没有```import class```这个选项
