### ISSUE TITLE
使用SmartRefreshLayout 嵌套 RecyclerView , 点击条目，界面黑屏

### ISSUE THREAD

**Issue by chengmenghuiAndroid** [scwang90/SmartRefreshLayout#1027]
使用版本 com.scwang.smartrefresh:SmartRefreshLayout:1.1.0，点击条目 界面黑屏
![image](https://user-images.githubusercontent.com/20322861/64472711-49343000-d195-11e9-9e0e-61e194f1b5dd.png)

**Comment by lucf1103** [comment]
出现一样的问题，我的布局是Activity+4个Fragment。
在Fragment最外层是LinearLayout，然后就是SmartRefreshLayout，
设置srl的刷新属性：
 smartRefreshLayout.setEnableLoadMore(true);
        smartRefreshLayout.setHeaderTriggerRate(0.8f);
        smartRefreshLayout.setHeaderMaxDragRate(1.6f);//最大显示下拉高度/Header标准高度
        smartRefreshLayout.setRefreshHeader(new ClassicsHeader(getActivity()));//标准的
        smartRefreshLayout.setRefreshFooter(new ClassicsFooter(getActivity()).setSpinnerStyle(SpinnerStyle.FixedBehind));
        smartRefreshLayout.setEnableAutoLoadMore(false);//使上拉加载具有弹性效果：

之后点击到这个界面的时候，整个App的布局就卡死了，不会更新了。（但实际对应位置的按钮是能响应到的，就是布局卡死，没刷新）

**Comment by scwang90** [comment]
界面黑屏一般与显存不足有关，注意减小内存和显存的优化
