### ISSUE TITLE
finishRefesh(fase) 会有空指针。

### ISSUE THREAD

**Issue by androidflying** [scwang90/SmartRefreshLayout#1028]
**详细描述**
在请求失败的时候 noMoreData 会有空指针异常

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0' 
```
**使用代码**
```java
   @Override
            protected void onFailed(String failed) {
                smartRefreshLayout.finishLoadMore(false);
                smartRefreshLayout.finishRefresh(false);<=========
                if (pageNo == 1) {
                    holder.withData(failed).showLoadFailed();
                } else {
                    ToastHelper.showShort(failed);
                }
            }
```
**附加信息**
 /**
     * finish refresh.
     * 完成加载
     *
     * @param success 数据是否成功刷新 （会影响到上次更新时间的改变）
     * @return RefreshLayout
     */
    @Override
    public RefreshLayout finishRefresh(boolean success) {
        if (success) {
            long passTime = System.currentTimeMillis() - mLastOpenTime;
            int delayed = (Math.min(Math.max(0, 300 - (int) passTime), 300) << 16);//保证加载动画有300毫秒的时间
            return finishRefresh(delayed, true, Boolean.FALSE);
        } else {
            return finishRefresh(0, false, null);<-------这里赋值为null，引起空指针
          return finishRefresh(0, false, Boolean.TRUE);<-----改成这样合适不合适？
        }
    }

**Comment by scwang90** [comment]
需要提供错误信息与堆栈

**Comment by androidflying** [comment]
昨天能复现，今天咋弄都复现不了了。
