### ISSUE TITLE
java.lang.NoClassDefFoundError: com.scwang.smartrefresh.layout.impl.RefreshContentWrapper$RecyclerViewScrollComponent$1

### ISSUE THREAD

**Issue by orzlenmo** [scwang90/SmartRefreshLayout#103]
您好！这个是什么原因？
java.lang.NoClassDefFoundError: com.scwang.smartrefresh.layout.impl.RefreshContentWrapper$RecyclerViewScrollComponent$1
![qq 20170802134242](https://user-images.githubusercontent.com/14181981/28859235-caeace7e-7788-11e7-8173-37b8aa375e30.png)

**Comment by NicodeLee** [comment]
如果自己解决了
提供下过程给后面的朋友提供帮助。

**Comment by scwang90** [comment]
这个问题嗯奇怪啊，自己解决啦？

**Comment by scwang90** [comment]
楼主应该是使用了老版本，然后更新新版本之后就好了~

**Comment by orzlenmo** [comment]
对的，是recyclerview版本问题，我旧项目recyclerview是23的，而这个库中recyclerview用到OnFlingListener这个监听是在25版本上才有的。所有就找不到。
