### ISSUE TITLE
加载更多时多出部分空白布局，请问怎么去掉？

### ISSUE THREAD

**Issue by Kriy** [scwang90/SmartRefreshLayout#1033]
![image](https://user-images.githubusercontent.com/4261669/64801685-99f3c080-d5bb-11e9-9d70-19a7c79c4588.png)

如上图片展示，在fragment中使用时（很简单的布局，直接内部嵌套recyclerview），加载更多时底部布局多出了部分空白区域，导致加载更多间距变大，请问如何处理？

**Comment by krcdxnh** [comment]
同样有着问题

**Comment by wufan-hash** [comment]
我使用的下拉刷新，头部有空白，兄弟怎么解决的，找半天了
