### ISSUE TITLE
Canvas: trying to draw too large(105304960bytes) bitmap.

### ISSUE THREAD

**Issue by ban54** [scwang90/SmartRefreshLayout#1034]
**详细描述**
听云统计中发现部分三星手机在Android9上报如下错误。代码中未使用自定义的header，都用的ClassicsHeader和ClassicsFooter。

**使用版本**
```
gradle-5.4.1-all
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0' 
```

**代码详情**
```
        //设置全局的Header构建器
        SmartRefreshLayout.setDefaultRefreshHeaderCreator(new DefaultRefreshHeaderCreator() {
            @Override
            public RefreshHeader createRefreshHeader(Context context, RefreshLayout layout) {
                ClassicsHeader header = new ClassicsHeader(context);
                header.setPrimaryColor(Color.TRANSPARENT);
                header.setTextSizeTitle(12f);
                header.setEnableLastTime(false);
                return header;
            }
        });
        //设置全局的Footer构建器
        SmartRefreshLayout.setDefaultRefreshFooterCreator(new DefaultRefreshFooterCreator() {
            @Override
            public RefreshFooter createRefreshFooter(Context context, RefreshLayout layout) {
                //指定为经典Footer，默认是 BallPulseFooter
                ClassicsFooter footer = new ClassicsFooter(context).setDrawableSize(20);
                footer.setPrimaryColor(Color.TRANSPARENT);
                footer.setTextSizeTitle(12f);
                return footer;
            }
        });
```

**崩溃详情**
```
Caused by: java.lang.RuntimeException: Canvas: trying to draw too large(105304960bytes) bitmap.
at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:101)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
at android.widget.ImageView.onDraw(ImageView.java:1360)
at android.view.View.draw(View.java:21881)
at android.view.View.updateDisplayListIfDirty(View.java:20754)
at android.view.View.draw(View.java:21607)
at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
at android.support.v7.widget.RecyclerView.drawChild(SourceFile:4581)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
at android.view.View.draw(View.java:21884)
at android.support.v7.widget.RecyclerView.draw(SourceFile:3987)
at android.view.View.updateDisplayListIfDirty(View.java:20754)
at android.view.View.draw(View.java:21607)
at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
at com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SourceFile:824)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
at android.view.View.updateDisplayListIfDirty(View.java:20740)
```

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 三星 SM-N950F, 三星 SM-G950F
 - Android版本: Android9.0

**Comment by SjAndy88** [comment]
你的图片显示逻辑是啥？　glide吗？　使用oversize方法了没有？　　oversize方法如果传入的参数是超大的，那么解析并显示就会出现这个问题

**Comment by xiagea** [comment]
我也有不少机型出现这个问题，Canvas: trying to draw too large(147953600bytes) bitmap

android.view.ViewGroup.drawChild + 4337 (ViewGroup.java:4337)
--
  | com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild + 854 (SmartRefreshLayout.java:854)
  | android.view.ViewGroup.dispatchDraw + 4114 (ViewGroup.java:4114)
  | android.view.View.draw + 20264 (View.java:20264)
  | android.view.View.updateDisplayListIfDirty + 19136 (View.java:19136)
  | android.view.View.draw + 19989 (View.java:19989)
  | android.view.ViewGroup.drawChild + 4337 (ViewGroup.java:4337)
  | android.view.ViewGroup.dispatchDraw + 4114 (ViewGroup.java:4114)
  | android.view.View.draw + 20264 (View.java:20264)
  | android.view.View.updateDisplayListIfDirty + 19136 (View.java:19136)

错误堆栈也只能定位到SmartRefreshLayout，不知道啥原因

**Comment by ban54** [comment]
> 你的图片显示逻辑是啥？　glide吗？　使用oversize方法了没有？　　oversize方法如果传入的参数是超大的，那么解析并显示就会出现这个问题

嗯，是用的Glide方法，也用了oversize方法，不过oversize里宽最大也只传了屏幕宽度，再根据宽度按比例算出了一个高度。我把oversize去掉上线再看看。

**Comment by SjAndy88** [comment]
> 我也有不少机型出现这个问题，Canvas: trying to draw too large(147953600bytes) bitmap
> 
> ## android.view.ViewGroup.drawChild + 4337 (ViewGroup.java:4337)
>   | com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild + 854 (SmartRefreshLayout.java:854)
>   | android.view.ViewGroup.dispatchDraw + 4114 (ViewGroup.java:4114)
>   | android.view.View.draw + 20264 (View.java:20264)
>   | android.view.View.updateDisplayListIfDirty + 19136 (View.java:19136)
>   | android.view.View.draw + 19989 (View.java:19989)
>   | android.view.ViewGroup.drawChild + 4337 (ViewGroup.java:4337)
>   | android.view.ViewGroup.dispatchDraw + 4114 (ViewGroup.java:4114)
>   | android.view.View.draw + 20264 (View.java:20264)
>   | android.view.View.updateDisplayListIfDirty + 19136 (View.java:19136)
> 
> 错误堆栈也只能定位到SmartRefreshLayout，不知道啥原因

SmartRefreshLayout只是被View刷新，系统自动调用到了而已。问题不在SmartRefreshLayout

**Comment by scwang90** [comment]
不要帅锅噢~
