### ISSUE TITLE
本人不才，求助demo中的实现原理

### ISSUE THREAD

**Issue by zgnckzn** [scwang90/SmartRefreshLayout#1036]
**具体说下**
在demo中的第二个案例（页面切换）中，左边小兔子风格的header知道如何实现，右边Material风格的footer，在代码中是怎么设置的，读了源码，没找到，实在没办法了，求助大家，各位大侠切莫嘲笑

**Comment by scwang90** [comment]
可以使用 RefreshFooterWrapper 做适配
```
setRefreshFooter(new RefreshFooterWrapper(new MaterialHeader()))
```
