### ISSUE TITLE
【建议】setDefaultRefreshHeaderCreator时header、footerview自带的LayoutParams会被无视

### ISSUE THREAD

**Issue by weimingjue** [scwang90/SmartRefreshLayout#1038]
**具体说下**
如下代码，我想直接创建一个100px高的header，但这样写确无效
`

        SmartRefreshLayout.setDefaultRefreshHeaderCreator(new DefaultRefreshHeaderCreator() {

            @NonNull
            @Override
            public RefreshHeader createRefreshHeader(@NonNull final Context context, @NonNull RefreshLayout layout) {
                final ImageView header = new AppCompatImageView(context);
                header.setLayoutParams(new SmartRefreshLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 100));
                header.setImageResource(...);
                return new RefreshHeader() {

                    @NonNull
                    @Override
                    public View getView() {
                        return header;
                    }

                    @NonNull
                    @Override
                    public SpinnerStyle getSpinnerStyle() {
                        return SpinnerStyle.Translate;
                    }
                    ...
`
我必须在onInitialized重新再次设置高度让他再onInitialized一遍才有效，但这对一个合格的程序员来讲肯定是不允许的

**为什么**
在SmartRefreshLayout的低400行左右有一段
`setRefreshHeader(sHeaderCreator.createRefreshHeader(thisView.getContext(), this));`
setRefreshHeader没有使用view自带的，使用了默认的MATCH_PARENT, WRAP_CONTENT

建议：在setRefreshHeader(@NonNull RefreshHeader header)里判断，如果view有LayoutParams则取LayoutParams
建议：增加setRefreshHeader(@NonNull RefreshHeader header,LayoutParams params)

建议参考：ViewGroup的addView

**Comment by scwang90** [comment]
使用 1.1.2 版本以上即可
