### ISSUE TITLE
在 Android studio 中无法预览布局

### ISSUE THREAD

**Issue by KunMinX** [scwang90/SmartRefreshLayout#1039]
**详细描述**
在 windows 10 的 as 3.5.0 中

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0' 
```
凡嵌套了 SRL，其中的布局内容都无法展示，这个有没有解决办法？

（macOs 的 as 3.5.0 中没这个问题）

**Comment by KunMinX** [comment]
解决了，是 as 3.5.0 的 apply change 的问题。删除 build 文件夹重新 build 即可

**Comment by EdisonRXG** [comment]
??3.5.1 删除build 还不行啊

**Comment by winter521** [comment]
![image](https://user-images.githubusercontent.com/57278862/68065385-76e7c080-fd63-11e9-88d6-21cad062d961.png)
AS 3.5.1删除build文件，重新编译，依然无法预览布局

**Comment by winter521** [comment]
> 解决了，是 as 3.5.0 的 apply change 的问题。删除 build 文件夹重新 build 即可

怎么解决的啊，求指导
