### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/design/widget/CoordinatorLayout;

### ISSUE THREAD

**Issue by yeming1001** [scwang90/SmartRefreshLayout#104]
/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/design/widget/CoordinatorLayout;com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.findScrollableView(RefreshContentWrapper.java:90)
com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.setupComponent(RefreshContentWrapper.java:294)
com.scwang.smartrefresh.layout.SmartRefreshLayout.onAttachedToWindow(SmartRefreshLayout.java:395)

**Comment by yeming1001** [comment]
![qq 20170802160636](https://user-images.githubusercontent.com/5943707/28863703-9662dc82-779c-11e7-8cb1-ba17d8286e23.png)

**Comment by scwang90** [comment]
请更新到最新版本
