### ISSUE TITLE
数据加载完成，没有更多数据之后的问题

### ISSUE THREAD

**Issue by a1227308812** [scwang90/SmartRefreshLayout#1042]
**具体说下**
数据加载完成，没有更多数据之后调用
refreshLayout.finishLoadMore();//结束刷新
refreshLayout.finishLoadMoreWithNoMoreData();//标记没有更多数据
但是手动上拉还是会出现正在加载更多的footer，并且不会消失，但是不会触发加载更多监听。
**为什么**
正常情况下是没有更多数据之后加载更多数据监听不会触发，正在加载更多footer在上拉时也不应该出现。只会出现没有更多数据的footer。
使用的ClassicsFooter
版本：1.1.0-alpha-24

**Comment by czm0408** [comment]
和我碰到的问题一样，请问解决了吗？

**Comment by nan403** [comment]
我也有这个问题 1.1.0-alpha-21

**Comment by scwang90** [comment]
finishLoadMore 和 finishLoadMoreWithNoMoreData 不要同时调用，他们是状态冲突的
可以使用
方式一
```java
if(还有数据){
   refreshLayout.finishLoadMore();
} else {
   refreshLayout.finishLoadMoreWithNoMoreData();
}
方式二：
```java
   refreshLayout.finishLoadMore();
   if(没有数据) {
      refreshLayout.setNoMoreData(true);
   }
```
