### ISSUE TITLE
国际化问题（已参考常见问题，依然无法实现）！

### ISSUE THREAD

**Issue by Cazaea** [scwang90/SmartRefreshLayout#1049]
版本：1.1.5
国际化语言，应用内手动切换，SmartFreshLayout必须应用重启才能重新渲染Header和Footer, 这个问题可以解决吗？ issues 常见问题也看了，无法解决问题；

**Comment by Cazaea** [comment]
资源文件已经覆盖，应用内切换语言，仍然是无效的吗？

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/67659695-f0fcfb80-f997-11e9-8781-a5b822e94ed7.png)

我在application里定义了相关操作的语言文字
app支持3种语言
也有这个问题

**Comment by Cazaea** [comment]
我不得不将所有string文件override, 并且重新初始化

```
private void language() {
        ClassicsHeader.REFRESH_HEADER_PULLING = getString(R.string.srl_header_pulling);
        ClassicsHeader.REFRESH_HEADER_REFRESHING = getString(R.string.srl_header_refreshing);
        ClassicsHeader.REFRESH_HEADER_LOADING = getString(R.string.srl_header_loading);
        ClassicsHeader.REFRESH_HEADER_RELEASE = getString(R.string.srl_header_release);
        ClassicsHeader.REFRESH_HEADER_FINISH = getString(R.string.srl_header_finish);
        ClassicsHeader.REFRESH_HEADER_FAILED = getString(R.string.srl_header_failed);
        ClassicsHeader.REFRESH_HEADER_UPDATE = getString(R.string.srl_header_update);
        ClassicsHeader.REFRESH_HEADER_UPDATE = getString(R.string.srl_header_update);
        ClassicsHeader.REFRESH_HEADER_SECONDARY = getString(R.string.srl_header_secondary);

        ClassicsFooter.REFRESH_FOOTER_PULLING = getString(R.string.srl_footer_pulling);
        ClassicsFooter.REFRESH_FOOTER_RELEASE = getString(R.string.srl_footer_release);
        ClassicsFooter.REFRESH_FOOTER_LOADING = getString(R.string.srl_footer_loading);
        ClassicsFooter.REFRESH_FOOTER_REFRESHING = getString(R.string.srl_footer_refreshing);
        ClassicsFooter.REFRESH_FOOTER_FINISH = getString(R.string.srl_footer_finish);
        ClassicsFooter.REFRESH_FOOTER_FAILED = getString(R.string.srl_footer_failed);
        ClassicsFooter.REFRESH_FOOTER_NOTHING = getString(R.string.srl_footer_nothing);
    }
```

**Comment by Dizner** [comment]
@Cazaea @lizhuoyuan   我也是这个问题，目前我使用的是1.1.0-alpha-1，override静态常量后可以使用，
在1.1.0及以后的版本，由于ClassicsHeader.java中对于ClassicsHeader.REFRESH_HEADER_PULLING 等资源的加载方式发生变化（将静态常量赋值到ClassicsHeader的成员变量），导致动态override不起作用，我的建议是在你动态修改语言时，通过反射修改ClassicsHeader.java中相关的成员变量，达到动态override的目的。代码如下：
` ClassicsHeader refreshHeader = (ClassicsHeader) smartRefreshLayout.getRefreshHeader();
        try {
            Class headerClass = Class.forName(ClassicsHeader.class.getName());
            Field mTextPulling = headerClass.getDeclaredField("mTextPulling");
            Field mTextRefreshing = headerClass.getDeclaredField("mTextRefreshing");
            Field mTextRelease = headerClass.getDeclaredField("mTextRelease");
            Field mTextUpdate = headerClass.getDeclaredField("mTextUpdate");
            Field mLastUpdateFormat = headerClass.getDeclaredField("mLastUpdateFormat");

            mTextPulling.setAccessible(true);
            mTextRefreshing.setAccessible(true);
            mTextRelease.setAccessible(true);
            mTextUpdate.setAccessible(true);
            mLastUpdateFormat.setAccessible(true);

            mTextPulling.set(refreshHeader, getString(R.string.xialashauxin));
            mTextRefreshing.set(refreshHeader, getString(R.string.zhengzaishuaxin));
            mTextRelease.set(refreshHeader, getString(R.string.shifangshuaxin));
            mTextUpdate.set(refreshHeader, getString(R.string.shuaxinshijian));

            mLastUpdateFormat.set(refreshHeader, new SimpleDateFormat(getString(R.string.shuaxinshijian), Locale.getDefault()));


            mTextPulling.setAccessible(false);
            mTextRefreshing.setAccessible(false);
            mTextRelease.setAccessible(false);
            mTextUpdate.setAccessible(false);
            mLastUpdateFormat.setAccessible(false);

        } catch (NoSuchFieldException | IllegalAccessException | ClassNotFoundException e) {
            e.printStackTrace();
        }`
以上反射的成员变量不全，只做示例，具体请根据需求进行反射。

**Comment by lizhuoyuan** [comment]
@Dizner  3q 回头试试这种方式

**Comment by scwang90** [comment]
使用最新版本就可以了

**Comment by liukepeng** [comment]
2.0.3版本，在application初始化ClassicsHeader、ClassicsFooter的文案。应用切换成繁体，出现英文，【Refreshing/Refresh Success】。但【释放立即刷新】却成功切换成繁体。请问有人知道怎么处理吗？
