### ISSUE TITLE
ll_refreshLayout.setVisibility(View.GONE); 

### ISSUE THREAD

**Issue by zst1303939801** [scwang90/SmartRefreshLayout#105]
com.scwang.smartrefresh.layout.SmartRefreshLayout  不能使用id来调用setVisibility方法

**Comment by scwang90** [comment]
这个并不是问题，需要自己实现

**Comment by scwang90** [comment]
ll_refreshLayout.getLayout().setVisibility(View.GONE);

**Comment by zst1303939801** [comment]
谢谢
