### ISSUE TITLE
StaggeredGridLayoutManager与setEnableOverScrollDrag冲突

### ISSUE THREAD

**Issue by beiger** [scwang90/SmartRefreshLayout#1051]
with(mBinding.refreshLayout) {
           setEnableRefresh(false)
           setEnableLoadMore(false)
           setEnableOverScrollDrag(true)//是否启用越界拖动
}

with(mBinding.recyclerView) {
            layoutManager = StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL)
            itemAnimator = DefaultItemAnimator()
}

开启越界拖动，
item设置android:layout_height="wrap_content"，如果有两个以上的item，当某个item高度超过屏幕高度时，显示不全

**Comment by scwang90** [comment]
问题无法重现，参考最新demo
