### ISSUE TITLE
autoRefresh 触发后，快速切换底部tab, up事件穿透，没有触发onRefresh()回调刷新

### ISSUE THREAD

**Issue by xuehuashi** [scwang90/SmartRefreshLayout#1053]
主界面四个tab,刚进入第一个tab,初始化数据调用mRefreshLayout.autoRefresh();在回调监听里请求数据，下拉刷新箭头出来后，快速切换其他tab,日志打印没有进到onRefresh监听，触发网络请求，导致界面空白。
我看了之前有个相似的问题，并没有解决就关闭了，状态的确时空闲的时候刷新。
 smartRefreshLayout  版本 '1.1.0-alpha-14',
代码如下：
mRefreshLayout.setOnRefreshLoadMoreListener(new OnRefreshLoadMoreListener() {
            @Override
            public void onRefresh(@NonNull RefreshLayout refreshLayout) {
                LogUtil.debug("liveallsubfr_onRefresh");
                isRefresh = true;
                mPresenter.requestData(object);
              // initdata();
            }
            @Override
            public void onLoadMore(@NonNull RefreshLayout refreshLayout) {
               。。。
            }
        });

@Override
    protected void initData() {
        mRefreshLayout.autoRefresh();
        LogUtil.debug("liveallsubfr_initdata");
//        isRefresh = true;
//        mPresenter.requestData(object);
    }

日志只有：liveallsubfr_initdata，而没有onRefresh监听里liveallsubfr_onRefresh

初始化数据直接用initdata() 注释代码是可以的

**Comment by xuehuashi** [comment]
调试源码发现，PullDownToRefresh状态时，切换tab抬起后 , SmartRefreshLayout类的dispatchTouchEvent事件分发触发up事件,但是up没有 break穿透到cancle事件，触发调用了overSpinner()方法，设置mKernel.setState(RefreshState.PullUpCanceled);应该导致刷新监听回调进去.

调用autoRefresh()方法，期望在OnRefreshLoadMoreListener的onrefesh()中请求网络。下拉刷新时，快速切换到其他地方，存在临界状态（PullDownToRefresh）的bug。

没有仔细的阅读相关代码， 期待作者修复

**Comment by and1990** [comment]
@xuehuashi 我也用TabLayout+ViewPager，每个tab的Fragment自动刷新，结果第3个tab的onRefresh没有回调。你的问题解决了吗？

**Comment by scwang90** [comment]
initData内部的逻辑改为
```java
protected void initData() {
    mRefreshLayout.autoRefreshAnimationOnly();
    LogUtil.debug("liveallsubfr_initdata");
    isRefresh = true;
    mPresenter.requestData(object);
}
```
