### ISSUE TITLE
自定义Header 与 extendHeight 中的背景不一致，请问怎么设置 extendHeight 对应的背景色

### ISSUE THREAD

**Issue by zhoujunwei-android** [scwang90/SmartRefreshLayout#1055]
自定义Header 与 extendHeight 中的背景不一致，请问怎么设置 extendHeight 对应的背景色

**Comment by scwang90** [comment]
参考 InternalClassics 源代码
···java
    @Override
    public void onInitialized(@NonNull RefreshKernel kernel, int height, int maxDragHeight) {
        mRefreshKernel = kernel;
        mRefreshKernel.requestDrawBackgroundFor(this, mBackgroundColor);
    }
···
