### ISSUE TITLE
某种情况下，加载更多不能触发的问题

### ISSUE THREAD

**Issue by sucwaker** [scwang90/SmartRefreshLayout#1057]
**具体说下**
设置了刷新和加载更多：
this.setRefreshHeader(ClassicsHeader(context))
this.setRefreshFooter(ClassicsFooter(context))
设置了加载更多监听

情况1：
没有设置刷新监听，而是this.setEnableRefresh(false)
这种时候加载更多不能触发

情况2：
设置了刷新监听，和this.setEnableRefresh(false)
这种时候加载更多可以触发

**为什么**
不知道为什么

**Comment by scwang90** [comment]
就是这样设计的
