### ISSUE TITLE
加载数据完成后底部提示“没有更多数据”会被隐藏

### ISSUE THREAD

**Issue by jzm369** [scwang90/SmartRefreshLayout#1059]
**具体说下**
数据加载完成后，能否底部显示提示，不被隐藏

**为什么**
...

**Comment by fqingyang** [comment]
foot跟随属性设置为true就好

**Comment by fqingyang** [comment]
就是跟随recyclerview还是不跟随，就是字面意思

**Comment by fqingyang** [comment]
app:srlEnableFooterFollowWhenNoMoreData="true"

**Comment by jzm369** [comment]
@fqingyang 设置了app:srlEnableFooterFollowWhenNoMoreData="true"，当recyclerview没数据时还是得往上拉才能看到“没有更多数据”的提示。。谢谢您的回答

**Comment by jzm369** [comment]
我期望的结果是当没数据时设置finishLoadMoreWithNoMoreData后“没有更多数据”固定在底部，暴怒要每次上拉才可以看到

**Comment by jzm369** [comment]
我期望的结果是当没数据时设置finishLoadMoreWithNoMoreData后“没有更多数据”固定在底部，不要每次上拉才可以看到

**Comment by fqingyang** [comment]
当没数据时是通过空布局来实现的，而当有数据的时候，只是当前不能占满一屏幕，finishLoadMoreWithNoMoreData可以控制“没有数据”标签是显示在底部还是跟随最后的item，好像没理解你的需求，抱歉

**Comment by jzm369** [comment]
@fqingyang   “没有数据”标签跟随最后的item要怎么设置呢，设置了  <android.support.v7.widget.RecyclerView
                    android:id="@+id/category_list_rv"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:srlEnableFooterFollowWhenNoMoreData="true"
                     />还是在底部

**Comment by jzm369** [comment]
@fqingyang 嗯。。这个了解。。我的需求是“没有数据”标签，要往上拉才可以看见，，不能一直在显示在底部

**Comment by cctxwan** [comment]
app:srlEnableFooterFollowWhenLoadFinished="true"
这个设置为true就可以了

**Comment by scrylove** [comment]
> 我期望的结果是当没数据时设置finishLoadMoreWithNoMoreData后“没有更多数据”固定在底部，不要每次上拉才可以看到

这个问题也困扰了我很久，太坑了。注意，要想在没用更多数据后再底部显示“没有更多了”，必须与mRefreshLayout.setEnableLoadMore(true)结合使用，不能设为false.

**Comment by omyrobin** [comment]
> @fqingyang 嗯。。这个了解。。我的需求是“没有数据”标签，要往上拉才可以看见，，不能一直在显示在底部

我也有这个需求，想问最后是怎么解决的呢，试了很多api的组合都达不到效果，其实就是类似上拉加载更多 不调用结束方法 但是这样肯定是有问题的....只是UI效果达到了

**Comment by scwang90** [comment]
1.保证 srlEnableLoadMore= true （一直都是）
2.开启 srlEnableFooterFollowWhenNoMoreData=true Footer跟随功能

**Comment by WDevaloper** [comment]
srlEnableFooterFollowWhenNoMoreData=true Footer跟随功能，但是“没有更多了”会浮动在RecycleView上，而不是在底部？这个问题怎么解决？

**Comment by aijason** [comment]
> srlEnableFooterFollowWhenNoMoreData=true Footer跟随功能，但是“没有更多了”会浮动在RecycleView上，而不是在底部？这个问题怎么解决？
同样遇到，会浮在列表上

**Comment by JayRichrd** [comment]
> > 我期望的结果是当没数据时设置finishLoadMoreWithNoMoreData后“没有更多数据”固定在底部，不要每次上拉才可以看到
> 
> 这个问题也困扰了我很久，太坑了。注意，要想在没用更多数据后再底部显示“没有更多了”，必须与mRefreshLayout.setEnableLoadMore(true)结合使用，不能设为false.

mRefreshLayout.setEnableLoadMore(true)设置后虽然能展示footer了，但此时列表还能继续上拉回弹，照理说都已经展示无更多数据的footer了，就不想要继续上拉回弹效果。大佬这个是怎么解决的呢
