### ISSUE TITLE
越界回弹动画时长自定义

### ISSUE THREAD

**Issue by lilingxi01** [scwang90/SmartRefreshLayout#1060]
（不是越界划动，是惯性滚动到头时的越界回弹）
越界回弹动画的速度太过仓促，回弹效果与其他内容相比有些生硬，想要自己修改降速，但是好像并没有找到类似越界划动那样的速度设置方法。

**Comment by scwang90** [comment]
目前只能用子类继承 Smart 来自定义回弹动画了
