### ISSUE TITLE
自动加载更多不能用 滑动到最下面不能自动加载，需要在上拉一下才能刷新

### ISSUE THREAD

**Issue by INTKILOW** [scwang90/SmartRefreshLayout#1064]
自动加载更多不能用 滑动到最下面不能自动加载，需要在上拉一下才能刷新

**Comment by INTKILOW** [comment]
SmartRefreshLayout+NestedScrollView+RecyclerView 导致上拉加载底部view 和adapter视图重叠

**Comment by alferd0806** [comment]
有解决办法么？

**Comment by INTKILOW** [comment]
层数嵌套太多了减少层数布局 禁止recycleview默认滚动

**Comment by scwang90** [comment]
参考demo中的基本使用，有自动加载更多的用法
