### ISSUE TITLE
SmartRefreshLayout 中嵌套  CoordinatorLayout，CoordinatorLayout内容不显示

### ISSUE THREAD

**Issue by protectedMan** [scwang90/SmartRefreshLayout#1065]
SmartRefreshLayout:1.1.0-andx-11

当我把红色区域用SmartRefreshLayoutbao包起来后，CoordinatorLayout里面的内容全部都不显示了
![image](https://user-images.githubusercontent.com/17565737/68095677-7166b380-fee6-11e9-8d81-9dff58ac0fc6.png)

**Comment by protectedMan** [comment]
我又尝试了其他的含有CoordinatorLayout的布局，我发现只要被SmartRefreshLayout包裹，CoordinatorLayout就不显示

**Comment by style-wujianxiong** [comment]
我也发现这个问题，我用代码调以下方法解决
smartRefreshLayout.requestLayout();

**Comment by style-wujianxiong** [comment]
我也发现这个问题，我添加了一行代码后可以显示了
smartRefreshLayout.requestLayout();

**Comment by style-wujianxiong** [comment]
NestedScrollView嵌套RecyclerView后，被SmartRefreshLayout包裹也会导致RecyclerView不显示

**Comment by protectedMan** [comment]
我在CoordinatorLayout外层嵌套一个线性布局，然后用SmartRefreshLayout包裹这个线性布局就可以了

**Comment by bunny-pu** [comment]
> NestedScrollView嵌套RecyclerView后，被SmartRefreshLayout包裹也会导致RecyclerView不显示

请问是一直不显示，还是偶尔不显示？

**Comment by protectedMan** [comment]
> > NestedScrollView嵌套RecyclerView后，被SmartRefreshLayout包裹也会导致RecyclerView不显示
> 
> 
> 
> 请问是一直不显示，还是偶尔不显示？

一直啊
