### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by RuoYuHoney** [scwang90/SmartRefreshLayout#1066]
**详细描述**
ANR Input dispatching timed out (com.xxxxx.MainActivity, Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 2. Wait queue head age: 11327.1ms.)  com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:841)

dalvik.system.VMRuntime.newNonMovableArray(Native Method)
--
2 android.graphics.Bitmap.nativeCreate(Native Method)
3 android.graphics.Bitmap.createBitmap(Bitmap.java:890)
4 android.graphics.Bitmap.createBitmap(Bitmap.java:850)
5 android.view.View.buildDrawingCacheImpl(View.java:16433)
6 android.view.View.buildDrawingCache(View.java:16364)
7 android.view.View.updateDisplayListIfDirty(View.java:16177)
8 android.view.View.draw(View.java:16980)
9 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
10 android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
11 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
12 android.view.View.draw(View.java:17217)
13 android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
14 android.view.View.updateDisplayListIfDirty(View.java:16196)
15 android.view.View.draw(View.java:16980)
16 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
17 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
18 android.view.View.updateDisplayListIfDirty(View.java:16191)
19 android.view.View.draw(View.java:16980)
20 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
21 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
22 android.view.View.draw(View.java:17217)
23 android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1658)
24 android.view.View.updateDisplayListIfDirty(View.java:16196)
25 android.view.View.draw(View.java:16980)
26 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
27 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
28 android.view.View.updateDisplayListIfDirty(View.java:16191)
29 android.view.View.draw(View.java:16980)
30 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
31 android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
32 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
33 android.view.View.draw(View.java:17217)
34 android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
35 android.view.View.updateDisplayListIfDirty(View.java:16196)
36 android.view.View.draw(View.java:16980)
37 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
38 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
39 android.view.View.updateDisplayListIfDirty(View.java:16191)
40 android.view.View.draw(View.java:16980)
41 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
42 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
43 android.view.View.updateDisplayListIfDirty(View.java:16191)
44 android.view.View.draw(View.java:16980)
45 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
46 android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
47 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
48 android.view.View.draw(View.java:17217)
49 android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
50 android.view.View.updateDisplayListIfDirty(View.java:16196)
51 android.view.View.draw(View.java:16980)
52 android.view.ViewGroup.drawChild(ViewGroup.java:3729)
53 com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:841)
54 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-26' 
```

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 红米 REDMI 5 PLUS
 - Android版本:Android 7.1.2,level 25
 - 系统版本（手机厂商定制rom）XiaoMi/MIUI

**Comment by scwang90** [comment]
不要甩锅
