### ISSUE TITLE
为什么我自定义Head以后设置背景色无效

### ISSUE THREAD

**Issue by leeyushi** [scwang90/SmartRefreshLayout#1067]
为什么我自定义Head以后，给我的Head设置背景色：
mChHeader.setBackColor(color);
并且也强调了主题色：
mSrlRefreshHead.setPrimaryColors(color);
实际效果就是这样的，困扰很长时间了：
![image](https://user-images.githubusercontent.com/23522084/68279398-44fd9380-00ae-11ea-81d2-e92f910176c9.png)

**Comment by leeyushi** [comment]
@Override
        public RefreshKernel requestDrawBackgroundFor(@NonNull RefreshInternal internal, int backgroundColor) {
            if (mPaint == null && backgroundColor != 0) {
                mPaint = new Paint();
            }
            if (internal.equals(mRefreshHeader)) {
                mHeaderBackgroundColor = backgroundColor;
            } else if (internal.equals(mRefreshFooter)) {
                mFooterBackgroundColor = backgroundColor;
            }
            return this;
        }
你这里这段internal.equals(mRefreshHeader)是equals，导致我自定义的Header不符合，能换成
mRefreshHeader instanceof RefreshInternal 吗，这样就符合了

**Comment by leeyushi** [comment]
已经解决了：
    /**
     * 设置主题颜色 （如果自定义的Header没有注意颜色，本方法可以什么都不处理）
     *
     * @param colors 对应Xml中配置的 srlPrimaryColor srlAccentColor
     */
    @Override
    public void setPrimaryColors(int... colors) {
//        mBackgroundColor=colors[0];
//        setBackgroundColor(mBackgroundColor);
        mRefreshKernel.requestDrawBackgroundFor(this, colors[0]);
    }
    protected RefreshKernel mRefreshKernel;
    /**
     * 尺寸定义初始化完成 （如果高度不改变（代码修改：setHeader），只调用一次, 在RefreshLayout#onMeasure中调用）
     *
     * @param kernel        RefreshKernel 核心接口（用于完成高级Header功能）
     * @param height        HeaderHeight or FooterHeight
     * @param maxDragHeight 最大拖动高度
     */
    @Override
    public void onInitialized(@NonNull RefreshKernel kernel, int height, int maxDragHeight) {
        mRefreshKernel = kernel;
//        mRefreshKernel.requestDrawBackgroundFor(this, mBackgroundColor);
    }

**Comment by scwang90** [comment]
👍
