### ISSUE TITLE
在全局设置主题的时候，只有Header生效，Footer不生效，

### ISSUE THREAD

**Issue by lihangleo2** [scwang90/SmartRefreshLayout#1069]
代码就是README里的。Footer并不生效啊
static {
        //设置全局的Header构建器
        SmartRefreshLayout.setDefaultRefreshHeaderCreator((mContext, layout) -> {
            layout.setPrimaryColorsId(R.color.white, R.color.status_background);//全局设置主题颜色
            return new ClassicsHeader(mContext);
        });
        //设置全局的Footer构建器
        SmartRefreshLayout.setDefaultRefreshFooterCreator((mContext, layout) -> {
            layout.setPrimaryColorsId(R.color.white, R.color.status_background);//全局设置主题颜色
            return new ClassicsFooter(mContext);
        });
    }

**Comment by lihangleo2** [comment]
`return new ClassicsFooter(mContext).setPrimaryColorId(R.color.white).setAccentColorId(R.color.status_background);`
只能通过属性来设置，才能成功

**Comment by scwang90** [comment]
ClassicsFooter 不支持主题颜色，如果需要，可以自定义其他的 footer
