### ISSUE TITLE
必现问题：使用WaveSwipeHeader 取消刷新后Progress箭头没有完全消失

### ISSUE THREAD

**Issue by yzhdillon** [scwang90/SmartRefreshLayout#107]
class WaveSwipeHeader
...    源代码
            case PullDownCanceled:
                mCircleView.setProgressStartEndTrim(0f, 0f);
                mWaveView.startWaveAnimation(mLastFirstBounds);
                mLastFirstBounds = 0;
                break;
...
-----------------------------------
复制了一份出来，添加mCircleView.showArrow(false);后才能解决
 case PullDownCanceled:
                mCircleView.showArrow(false);
                mCircleView.setProgressStartEndTrim(0f, 0f);
                mWaveView.startWaveAnimation(mLastFirstBounds);
                mLastFirstBounds = 0;
                Log.d(TAG,"PullDownCanceled");
                break;

**Comment by scwang90** [comment]
非常感谢！
