### ISSUE TITLE
当 refreshLayout.setNoMoreData(true)与MaterialHeader连用时，底部的“没有更多数据”标签会出现一个跳跃现象

### ISSUE THREAD

**Issue by fqingyang** [scwang90/SmartRefreshLayout#1072]
**Describe the bug**
当 refreshLayout.setNoMoreData(true)与MaterialHeader连用时，第一屏不满一屏幕时，底部的“没有更多数据”标签会出现一个跳跃现象，可以优化吗？
**Version**
```gradle
 implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'
 implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0'
```

**Layout**
 <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        app:srlEnableOverScrollDrag="true"
        app:srlAccentColor="@android:color/white"
        app:srlPrimaryColor="@color/colorPrimary"
        app:srlEnableFooterFollowWhenNoMoreData="true">

        <com.scwang.smartrefresh.header.MaterialHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:srlAccentColor="#aaa"
            app:srlPrimaryColor="@color/colorBackgroundDark" />
        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:overScrollMode="never"
            android:orientation="vertical"
            app:layoutManager="android.support.v7.widget.LinearLayoutManager"
            tools:itemCount="3"
            tools:listitem="@android:layout/simple_list_item_2" />
        <com.scwang.smartrefresh.layout.footer.ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

**Comment by scwang90** [comment]
参考 demo 用例 NoMoreData 模块
