### ISSUE TITLE
没有更多数据，底部loading状态异常

### ISSUE THREAD

**Issue by AndMy** [scwang90/SmartRefreshLayout#1073]
**详细描述**
2.0版本：
refreshLayout.finishLoadMoreWithNoMoreData();调用没有更多数据之后，底部的loading布局状态异常；最终底部loading布局是：左边的loading imageview在转圈圈，右边的布局显示为“没有更多数据了”
2.0之前：
refreshLayout.finishLoadMoreWithNoMoreData();调用没有更多数据之后，最终底部loading布局是：左边的loading imageview隐藏了，右边的布局显示为“没有更多数据了”
**使用版本**
```gradle
    implementation  'com.scwang.smart:refresh-header-material:2.0.0-alpha-1'    //谷歌刷新头
    implementation  'com.scwang.smart:refresh-layout-kernel:2.0.0-alpha-1'
    implementation  'com.scwang.smart:refresh-footer-classics:2.0.0-alpha-1'//经典加载
```
**使用代码**
```java
回调
if (page<=0){
            if (!StringUtils.isNotEmptyList(communityHotBeans)){
                showLoadEmpty();
            }else {
                if (communityHotList!=null)communityHotList.clear();
                communityHotList.addAll(communityHotBeans);
                adapter.notifyDataSetChanged();
            }
        }else {
            if (!StringUtils.isNotEmptyList(communityHotBeans)){
                refreshLayout.finishLoadMoreWithNoMoreData();//这句代码和2.0之前的效果不一样了
            }else {
                communityHotList.addAll(communityHotBeans);
                adapter.notifyDataSetChanged();
            }
        }

**Comment by JackFung2015** [comment]
在调用finishLoadMoreWithNoMoreData（）方法之前不能调用finishLoadMore（）方法，可参考demo中BasicExampleActivity的代码：`       refreshLayout.setOnLoadMoreListener(new OnLoadMoreListener() {
            @Override
            public void onLoadMore(@NonNull final RefreshLayout refreshLayout) {
                refreshLayout.getLayout().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        if (mAdapter.getItemCount() > 30) {
                            Toast.makeText(getApplication(), "数据全部加载完毕", Toast.LENGTH_SHORT).show();
                            refreshLayout.finishLoadMoreWithNoMoreData();//将不会再次触发加载更多事件
                        } else {
                            mAdapter.loadMore(initData());
                            refreshLayout.finishLoadMore();
                        }
                    }
                }, 2000);
            }
        });
每次加载更多的时候，如果不是最后一页，使用finishLoadMore（）结束加载更多；如果是最后一页，使用finishLoadMoreWithNoMoreData（）结束加载更多，我遇到的情况跟你一样，原因就是在最后一页同时调用了这两个方法，希望可以帮到你。

**Comment by AndMy** [comment]
> 在调用finishLoadMoreWithNoMoreData（）方法之前不能调用finishLoadMore（）方法，可参考demo中BasicExampleActivity的代码：` refreshLayout.setOnLoadMoreListener(new OnLoadMoreListener() {
> @override
> public void onLoadMore(@nonnull final RefreshLayout refreshLayout) {
> refreshLayout.getLayout().postDelayed(new Runnable() {
> @override
> public void run() {
> if (mAdapter.getItemCount() > 30) {
> Toast.makeText(getApplication(), "数据全部加载完毕", Toast.LENGTH_SHORT).show();
> refreshLayout.finishLoadMoreWithNoMoreData();//将不会再次触发加载更多事件
> } else {
> mAdapter.loadMore(initData());
> refreshLayout.finishLoadMore();
> }
> }
> }, 2000);
> }
> });
> 每次加载更多的时候，如果不是最后一页，使用finishLoadMore（）结束加载更多；如果是最后一页，使用finishLoadMoreWithNoMoreData（）结束加载更多，我遇到的情况跟你一样，原因就是在最后一页同时调用了这两个方法，希望可以帮到你。

感谢啊，谢谢老哥了
