### ISSUE TITLE
出现闪退

### ISSUE THREAD

**Issue by asnm66** [scwang90/SmartRefreshLayout#1078]
**具体说下**
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3bb88ee
com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:824)

**为什么**
com.scwang.smartrefresh:SmartRefreshLayout:1.1.0
com.scwang.smartrefresh:SmartRefreshHeader:1.1.0

请问有什么办法解决？

**Comment by scwang90** [comment]
注意不要使用已经回收的Bitmap

**Comment by wlmxj** [comment]
> 注意不要使用已经回收的Bitmap

我没有用bitmap，就是简单使用下拉，加载更多，也出现这个crash，如何解决？？？？大佬

**Comment by 1982582704** [comment]
出现闪退  
![1692701402602](https://github.com/scwang90/SmartRefreshLayout/assets/17525427/93d0fe71-39b7-4b9a-85fd-20e8d2df5f72)
