### ISSUE TITLE
autoRefreshAnimationOnly引发的问题

### ISSUE THREAD

**Issue by StarkSongV** [scwang90/SmartRefreshLayout#1082]
**详细描述**
第一次autoRefreshAnimationOnly ,然后关闭下拉刷新.
第二次手动滑动屏幕触发下拉刷新的时候,有时候不走 onRefreshListener 方法

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-andx-16
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-andx-16' 
```
**使用代码**
```java
SmartRefreshLayout().autoRefreshAnimationOnly();
```
**问题重现**
问题重现操作步骤:
1. 设置仅执行刷新动画 autoRefreshAnimationOnly
2.在网络请求成功后,关闭了刷新动画
3.第二次快速下拉刷新,没有走onRefresh的回调. 一直显示刷新动画

**问题补充**
刚刚打印了 Header的log，在调用autoRefreshAnimationOnly 的时候，刷新结束时，有时候会不走 Header的onFinish方法。这个时候再次刷新就不会触发onRefresh 的回调

**Comment by sijifairy** [comment]
是的 有问题 不要用这个方法了

**Comment by iostyle** [comment]
同样的问题，一直没有被修复？

**Comment by scwang90** [comment]
1.1.1 版本即将发布，修复问题
