### ISSUE TITLE
如下布局，NestedScrollView嵌套SmartRefreshLayout，导致两个问题：1、无法惯性滑动到底部加载更多 2、手动上拉加载后，再次下拉刷新阻力很大。

### ISSUE THREAD

**Issue by junyao-yu** [scwang90/SmartRefreshLayout#1086]
<androidx.core.widget.NestedScrollView
        android:id="@+id/mNetView"
        android:fillViewport="true"
        android:focusableInTouchMode="true"
        android:focusable="true"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:orientation="vertical">
            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="138dp">
                <ImageView
                    android:id="@+id/imageView"
                    android:layout_width="match_parent"
                    android:layout_height="118dp"/>
            </FrameLayout>
            <com.scwang.smartrefresh.layout.SmartRefreshLayout
                android:layout_marginTop="95dp"
                android:id="@+id/swipeRefreshLayout"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <androidx.recyclerview.widget.RecyclerView
                    android:id="@+id/mRecyclerView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"/>
            </com.scwang.smartrefresh.layout.SmartRefreshLayout>
        </FrameLayout>

    </androidx.core.widget.NestedScrollView>

NestedScrollView嵌套SmartRefreshLayout，导致两个问题：
1、无法惯性滑动到底部加载更多 2、手动上拉加载后，再次下拉刷新阻力很大。

**Comment by YoYo-YY-YoYo** [comment]
阻尼问题可以通过 `refreshLayout.setDragRate(0.5f)` 进行设置,或者在布局文件中设置属性`app:srlDragRate="value"` 进行设置.

**Comment by jzm369** [comment]
一样的问题，请问解决了吗

**Comment by junyao-yu** [comment]
没有

**Comment by junyao-yu** [comment]
> 一样的问题，请问解决了吗

没有，后来不采用这种嵌套来做了。

**Comment by IDoBelieve** [comment]
同样遇到了该问题，你是不使用NestedScrollView了么？

**Comment by Gui-Ji** [comment]
> 同样遇到了该问题，你是不使用NestedScrollView了么？

请问如何解决的

**Comment by Gui-Ji** [comment]
> 一样的问题，请问解决了吗

请问解决了吗

**Comment by jzm369** [comment]
> > 一样的问题，请问解决了吗
> 
> 请问解决了吗

没有。后面改成不做嵌套了

**Comment by scwang90** [comment]
这是正常现象

**Comment by Terry999555** [comment]
> 这是正常现象

大佬，这个有办法处理吗，涉及到很古老的代码，需要处理一下。滑动次数多了之后，阻尼系数越来越大。

**Comment by fox0830** [comment]
同样遇到了这个问题，我改成了把整个NestedScrollView包裹在了SmartRefreshLayout里面
