### ISSUE TITLE
手动调用 autoRefresh 无效的问题

### ISSUE THREAD

**Issue by RockyQu** [scwang90/SmartRefreshLayout#1088]
**详细描述**
手动调用 autoRefresh 无效的没有触发，是在Fragment里使用的

**Comment by WangStormstout** [comment]
我在onResume里面调用的确有时不会触发

**Comment by scwang90** [comment]
autoRefresh  不能保证每次都成功，只有在空闲状态时才会成功

**Comment by scwang90** [comment]
autoRefresh 返回 false 表示状态不符合，刷新不成功

**Comment by iostyle** [comment]
有时返回true 依然不触发

**Comment by huangShan-gitHub** [comment]
mRefreshLayout.autoRefresh();触发刷新只会很快的闪一下，不会时长比较久的刷新，和下拉触发的时间相比，这个只是快速闪现一下
