### ISSUE TITLE
集成  implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'报错

### ISSUE THREAD

**Issue by xuzhu19930323** [scwang90/SmartRefreshLayout#1091]
**详细描述**
对问题进行清晰而简明的描述，把握问题的关键点。

**使用版本**
android studio 版本 3.1.2，
gradle distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0' 
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0' 
```
错误：
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.scwang.smartrefresh:SmartRefreshLayout:1.1.0.

提问：请问这个是什么问题？

**Comment by scwang90** [comment]
网络问题
