### ISSUE TITLE
请问设置主题色以后怎么让它立即生效

### ISSUE THREAD

**Issue by leeyushi** [scwang90/SmartRefreshLayout#1096]
**具体说下**
 mSrlRefreshHead.setPrimaryColors(color);
在设置了主题色后，我发现代码只是更改了主题色的色值，但是并不会立即更新颜色，或者可以提供支持立即生效主题色的方法吗

**为什么**
因为我在做一些头部动画的时候，刷新头部颜色是根据Banner的颜色拖动实时改变的，这样就导致我的颜色老是慢一拍，跟Banner不对应

**Comment by leeyushi** [comment]
或者告知一下，怎么样手动设置刷新的头部高度为默认高度，设置刷新动画总时长，如果是300的话，在正在刷新中的时候它会快速还原到默认位置，但是设置总时长为1200，它会比较慢，总有那么一条线的缝隙，我又想要1200的总时长，又想要它开始刷新后，头部的高度还原到默认高度，而不是有一条缝隙,因为这条线的缝隙跟我的Header的颜色不对应,总是慢半拍

**Comment by scwang90** [comment]
手动更新一下即可
```java
refreshLayout.getLayout().invalidate();
```

**Comment by leeyushi** [comment]
我设置过这个了，但是如果是手托着滑动，颜色值是正常的，如果是Banner那样自动切换过去，这个速度因为比较快，refreshLayout的颜色值就会丢掉一些过渡，直接到了结尾，而其它同步更新的View又不会丢掉，所以看起来也不自然，轻微的不自然，现在一是没时间管，二也是没有更好的办法了，只能暂时放着了，后面实在不行，就只能重构，更换实现方式了。。。
像Header头部，设置它的背景色，就可以实时生效，Banner自动滑动过去也不会丢掉颜色值，但是Header的 头部，和refreshLayout可滑动的区域，有一部分是不同的

**Comment by scwang90** [comment]
demo 中有动态切换主题演示的例子，可以去参考一下
