### ISSUE TITLE
兼容ScrollableLayout

### ISSUE THREAD

**Issue by cwyrzz** [scwang90/SmartRefreshLayout#11]
作者你好，麻烦您看下能不能兼容一下这个库https://github.com/cpoopc/ScrollableLayout
配合这个库使用的时候，会出现一种情况就是，当下拉出现刷新头部，此时手指不松开，然后上拉，会触发recyclerview的滑动，recyclerviewiew内容会滑上去，此时再下拉就会截掉一部分

**Comment by scwang90** [comment]
我先去研究一下 ScrollableLayout

**Comment by scwang90** [comment]
另外，你在体验我的Demo的时候，遇到过 [体验问题5](https://github.com/scwang90/SmartRefreshLayout/issues/5) 中的问题描述：“另外下拉的时候有时候会卡死一会，刷新中ui完全不见了，只有等刷新成功ui才恢复正常。”吗？

**Comment by cwyrzz** [comment]
体验问题5 中的问题描述：“另外下拉的时候有时候会卡死一会，刷新中ui完全不见了，只有等刷新成功ui才恢复正常"
暂时没有遇到过的

**Comment by scwang90** [comment]
ScrollableLayout 这个库是支持 android-Ultra-Pull-To-Refresh

**Comment by monkeylwp** [comment]
麻烦问一下，为什么只有1.0.2版本中有setRefreshScrollBoundary 方法？后面被删了么？

**Comment by MIkeeJY** [comment]
@scwang90 麻烦问一下，为什么只有1.0.2版本中有setRefreshScrollBoundary 方法？后面被删了么？

**Comment by MIkeeJY** [comment]
@monkeylwp setScrollBoundaryDecider
