### ISSUE TITLE
设置某个header后，再设置其他header，后者的展示高度还是前的高度，即没有重新计算新设置header的高度

### ISSUE THREAD

**Issue by JunhuaLin** [scwang90/SmartRefreshLayout#1100]
设置某个header后，再设置其他header，后者的展示高度还是前的高度，即没有重新计算新设置header的高度

**Comment by scwang90** [comment]
demo 中有动态切换 Header 的例子，可以参考一下

**Comment by JunhuaLin** [comment]
> demo 中有动态切换 Header 的例子，可以参考一下

demo也存在这问题，我录制了下视频

PhoenixHeader的高度为200dp
MaterialHeader的高度为100dp

默认先设置MaterialHeader刷新头部，第一次动态设完PhoenixHeader刷新头部后，再动态设置MaterialHeader刷新头部，此时MaterialHeader的高度为200dp和预期的100dp不符合

![5cjh1-sutu1](https://user-images.githubusercontent.com/20511081/71649716-e8d08c00-2d4b-11ea-9930-b95f5307f496.gif)

**Comment by JunhuaLin** [comment]
> demo 中有动态切换 Header 的例子，可以参考一下

由于新设置的MaterialHeader没有走测量逻辑，高度直接复用了上一个header的高度导致的！具体为什么没有走测量还没有发现问题……
