### ISSUE TITLE
finishRefresh(delayed)调用后，RecyclerView的条目点击会触发onRefresh回调

### ISSUE THREAD

**Issue by lqq1312** [scwang90/SmartRefreshLayout#1101]
**详细描述**
先调用autoRefreshAnimationOnly()，然后获取数据列表，紧接着调用finishRefresh(delayed)，当点击RecyclerView条目时，会触发onRefresh回调

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0'
```
**使用代码**
```java
mSmartLayout.autoRefreshAnimationOnly();
getList(true);
mSmartLayout.finishRefresh(200);
```

**布局代码**
```xml
<com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/smartLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" /></com.scwang.smartrefresh.layout.SmartRefreshLayout>
```

**问题重现**
问题重现操作步骤:
1. 进入列表自动触发下拉刷新动画，并访问服务器拉取数据，延迟200毫秒后完成刷新
2.点击列表条目，进入详情
3.在进入到详情页面前，onRefresh方法被调用，而且下拉刷新动画也出现了

**预期行为**
点击列表条目不要自动触发下拉刷新

**屏幕截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 非手机设备
 - Android版本: Android 7.1.1
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by scwang90** [comment]
mSmartLayout.autoRefreshAnimationOnly(); 的动画执行要 300
mSmartLayout.finishRefresh(200); 在动画没结束的时候就关闭了，但是300的动画还在继续，状态错乱

mSmartLayout.finishRefresh();要么不加延时，要么要大于 300，或者吧Smart 的动画时间设置到 200
