### ISSUE TITLE
设置某个header后，再设置其他header，后者的展示高度还是前的高度，即没有重新计算新设置header的高度，Demo中同样存在该问题！！！

### ISSUE THREAD

**Issue by JunhuaLin** [scwang90/SmartRefreshLayout#1103]
设置某个header后，再设置其他header，后者的展示高度还是前的高度，即没有重新计算新设置header的高度

demo也存在这问题，我录制了下视频

PhoenixHeader的高度为200dp
MaterialHeader的高度为100dp

默认先设置MaterialHeader刷新头部，第一次动态设完PhoenixHeader刷新头部后，再动态设置MaterialHeader刷新头部，此时MaterialHeader的高度为200dp和预期的100dp不符合

由于新设置的MaterialHeader没有走测量逻辑，高度直接复用了上一个header的高度导致的！具体为什么没有走测量还没有发现问题……

![71649716-e8d08c00-2d4b-11ea-9930-b95f5307f496](https://user-images.githubusercontent.com/20511081/71658598-a6c13d80-2d7f-11ea-89e8-3f24157e1f63.gif)

**Comment by scwang90** [comment]
demo 的问题已经修复
