### ISSUE TITLE
finishRefresh(true)调用后，RecyclerView的条目点击会触发onRefresh回调

### ISSUE THREAD

**Issue by BIGMONK** [scwang90/SmartRefreshLayout#1104]
**详细描述**
先调用autoRefreshAnimationOnly()，然后获取数据列表，紧接着调用finishRefresh(true)，当点击RecyclerView条目时，会触发onRefresh回调

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0'
```
**使用代码**
```java
mSmartLayout.autoRefreshAnimationOnly();
mSmartLayout.finishRefresh(true);
```

**问题重现**
首次进入页面发起网络请求时调用autoRefreshAnimationOnly()，网络请求结束调用.finishRefresh(true),此时点击RecycleView条目或者滑动列表都偶发触发刷新onRefresh，
尝试finishRefresh(400,true,false),结果导致下拉刷新有动画不执行onRefresh回调

**预期行为**
点击列表条目不要触发onRefresh

**附加信息**
在此处添加任何有关该问题的任何其他说明。
怀疑是autoRefreshAnimationOnly执行未结束就调用.finishRefresh(true)引发的错乱，尝试finishRefresh(400,true,false),结果导致下拉刷新有动画不执行onRefresh回调

**Comment by scwang90** [comment]
1.1.1 修复完毕
