### ISSUE TITLE
上下拉列表会卡住

### ISSUE THREAD

**Issue by zhangnin** [scwang90/SmartRefreshLayout#1106]
**具体说下**
屏幕只有一屏数据时，执行下拉操作，然后马上执行向上滑【没有上拉加载更多功能】再执行下拉操作，反复这样，最终列表卡住了

**为什么**
列表滑动事件冲突

**Comment by Jusenr** [comment]
@zhangnin  建议这样设置
` srl_view.setDisableContentWhenRefresh(true);//是否在刷新的时候禁止列表的操作
        srl_view.setDisableContentWhenLoading(true);//是否在加载的时候禁止列表的操作`

**Comment by xxiao-endless** [comment]
@zhangnin 这个问题解决了吗？

**Comment by scwang90** [comment]
需要提供更多信息
