### ISSUE TITLE
SmartRefreshLayout + CoordinatorLayout + RecyclerView 置顶bug

### ISSUE THREAD

**Issue by veriosZhu** [scwang90/SmartRefreshLayout#1107]
当正在加载更多时，调用 `refreshLayout.closeHeaderOrFooter() 和 recyclerView.scrollToPosition(0)` 后会发生 RecyclerView 没有完全置顶的问题。

Demo 中可以复现这个问题，修改 嵌套滑动->整体嵌套 代码，如下：
![置顶 bug](https://user-images.githubusercontent.com/8703758/71903318-c4870c00-319e-11ea-85c9-2a54377c0518.png)

**Comment by scwang90** [comment]
关闭Smat显示新数据的功能
```java
                    refreshLayout.setEnableScrollContentWhenLoaded(false);
                    refreshLayout.closeHeaderOrFooter();
                    refreshLayout.setEnableScrollContentWhenLoaded(true);
                    mRecyclerView.scrollToPosition(0);
```
