### ISSUE TITLE
和WebView滑动冲突问题

### ISSUE THREAD

**Issue by hanhailong** [scwang90/SmartRefreshLayout#111]
SmartRefreshLayout嵌套WebView之后，如果WebView内容过长，会和SmartRefreshLayout滑动冲突

**Comment by scwang90** [comment]
请参考 demo 中的 WebView 用例来使用

**Comment by Leo00001** [comment]
我是这样解决的，通过webview 的getWebScrollY

`mRefreshLayout.setScrollBoundaryDecider(new ScrollBoundaryDecider() {
            @Override
            public boolean canRefresh(View content) {
                return mWebView**_.getWebScrollY()_** <= 0;
            }

            @Override
            public boolean canLoadMore(View content) {
                return false;
            }
        });`

**Comment by dazeGitHub** [comment]
> 我是这样解决的，通过webview 的getWebScrollY
> 
> `mRefreshLayout.setScrollBoundaryDecider(new ScrollBoundaryDecider() {
> @override
> public boolean canRefresh(View content) {
> return mWebView**_.getWebScrollY()_** <= 0;
> }
> 
> ```
>         @Override
>         public boolean canLoadMore(View content) {
>             return false;
>         }
>     });`
> ```

为啥我的 webview 没有 getWebScrollY() 方法？
