### ISSUE TITLE
发生ANR了

### ISSUE THREAD

**Issue by breakwhile** [scwang90/SmartRefreshLayout#1115]
AppNotResponding : Application not responsive since: Mon Dec 23 10:16:52 GMT+01:00 2019
	0	android.text.StaticLayout.nComputeLineBreaks (StaticLayout.java)
1	android.text.StaticLayout.generate (StaticLayout.java : 743)
2	android.text.StaticLayout.<init> (StaticLayout.java : 561)
3	android.text.StaticLayout.<init> (StaticLayout.java)
4	android.text.StaticLayout$Builder.build (StaticLayout.java : 374)
5	android.widget.TextView.makeSingleLayout (TextView.java : 6963)
6	android.widget.TextView.makeNewLayout (TextView.java : 6803)
7	android.widget.TextView.onMeasure (TextView.java : 7176)
8	androidx.appcompat.widget.AppCompatTextView.onMeasure(int,int) (AppCompatTextView.java : 501)
9	android.view.View.measure (View.java : 19875)
10	androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(int,int) (ConstraintLayout.java : 1227)
11	androidx.constraintlayout.widget.ConstraintLayout.onMeasure(int,int) (ConstraintLayout.java : 1572)
12	android.view.View.measure (View.java : 19875)
13	android.view.ViewGroup.measureChildWithMargins (ViewGroup.java : 6083)
14	android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java : 1464)
15	android.widget.LinearLayout.measureVertical (LinearLayout.java : 758)
16	android.widget.LinearLayout.onMeasure (LinearLayout.java : 640)
17	android.view.View.measure (View.java : 19875)
18	android.view.ViewGroup.measureChildWithMargins (ViewGroup.java : 6083)
19	android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java : 1464)
20	android.widget.LinearLayout.measureVertical (LinearLayout.java : 758)
21	android.widget.LinearLayout.onMeasure (LinearLayout.java : 640)
22	android.view.View.measure (View.java : 19875)
23	android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java : 715)
24	android.widget.RelativeLayout.onMeasure (RelativeLayout.java : 461)
25	android.view.View.measure (View.java : 19875)
26	android.view.ViewGroup.measureChildWithMargins (ViewGroup.java : 6083)
27	android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java : 1464)
28	android.widget.LinearLayout.measureVertical (LinearLayout.java : 758)
29	android.widget.LinearLayout.onMeasure (LinearLayout.java : 640)
30	android.view.View.measure (View.java : 19875)
31	androidx.constraintlayout.widget.ConstraintLayout.onMeasure(int,int) (ConstraintLayout.java : 1676)
32	android.view.View.measure (View.java : 19875)
33	androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(android.view.View,int,int) (RecyclerView.java : 9119)
34	androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.RecyclerView$State,androidx.recyclerview.widget.LinearLayoutManager$LayoutState,androidx.recyclerview.widget.LinearLayoutManager$LayoutChunkResult) (LinearLayoutManager.java : 1583)
35	androidx.recyclerview.widget.LinearLayoutManager.fill(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.LinearLayoutManager$LayoutState,androidx.recyclerview.widget.RecyclerView$State,boolean) (LinearLayoutManager.java : 1517)
36	androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.RecyclerView$State) (LinearLayoutManager.java : 612)
37	com.glip.widgets.recyclerview.WrapLinearLayoutManager.onLayoutChildren(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.RecyclerView$State) (WrapLinearLayoutManager.java : 28)
38	androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2() (RecyclerView.java : 3924)
39	androidx.recyclerview.widget.RecyclerView.dispatchLayout() (RecyclerView.java : 3641)
40	androidx.recyclerview.widget.RecyclerView.onLayout(boolean,int,int,int,int) (RecyclerView.java : 4194)
41	android.view.View.layout (View.java : 17655)
42	android.view.ViewGroup.layout (ViewGroup.java : 5575)
43	com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(boolean,int,int,int,int) (SmartRefreshLayout.java : 666)

com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(boolean,int,int,int,int) (SmartRefreshLayout.java : 666)
在这个位置发生了ANR

**Comment by scwang90** [comment]
不要学特朗普甩锅噢
