### ISSUE TITLE
自定义Footer时，Loading时不应该调用onMoving

### ISSUE THREAD

**Issue by 54binge** [scwang90/SmartRefreshLayout#1116]
**详细描述**
当RefreshState=RefreshState.Refreshing时onMoving不会被调用，这个很正确
但是当RefreshState=RefreshState.Loading时onMoving还在调用，这个是故意这么设计的吗？
**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-andx-14' 
```
**日志**
oldState:PullUpToLoad  newState:Loading
startRefreshingAnim
startAnim  mPosition:0
dragPercent:2.2476192  offsetY:236
dragPercent:2.6761904  offsetY:281
dragPercent:3.1238096  offsetY:328
dragPercent:3.5142858  offsetY:369
dragPercent:3.8095238  offsetY:400
dragPercent:3.9619048  offsetY:416
dragPercent:3.7523808  offsetY:394
dragPercent:3.1809523  offsetY:334
dragPercent:2.6857142  offsetY:282
dragPercent:2.4  offsetY:252
dragPercent:2.2380953  offsetY:235
dragPercent:2.142857  offsetY:225
dragPercent:2.0857143  offsetY:219
dragPercent:2.047619  offsetY:215
dragPercent:2.0285714  offsetY:213
dragPercent:2.0190477  offsetY:212
dragPercent:2.0095239  offsetY:211
oldState:Loading  newState:LoadFinish
dragPercent:2.0  offsetY:210
onFinish()

**Comment by scwang90** [comment]
只要 header 发生了移动都会调用，如果你的header不希望 loading 的时候执行动画，请自行通过 state 来过滤，如果框架改动，将会影响到很多 header，自带的 header 的动画执行都与 是否 loading 无关
