### ISSUE TITLE
RecyclerView底部被遮盖

### ISSUE THREAD

**Issue by Juslt** [scwang90/SmartRefreshLayout#1117]
布局：-- SmartRefreshLayout 
           --CoordinatorLayout 
           --RecyclerView  

RecyclerView使用StaggeredGridLayoutManager ， 每一个Viewholder高度是动态计算的。
现在我遇到的问题是，recyclerview 最后一个item会存在底部被遮盖,显示不全的情况

**Comment by kakaxiii** [comment]
我在RecyclerView+StaggeredGridLayoutManager 时也会概率性出现最后一个item被部分遮挡的情况,请问是怎么解决的

**Comment by yizuochengchi** [comment]
老哥请问解决了么
