### ISSUE TITLE
大佬们，帮我看下这里怎么修改吧

### ISSUE THREAD

**Issue by dapanjimianpaigumian** [scwang90/SmartRefreshLayout#1120]
![1584351846(1)](https://user-images.githubusercontent.com/24210547/76743572-c9bf9300-67ad-11ea-9b01-46063fa5a647.jpg)

这里的颜色怎么修改呢？
群满了只好在这里提问

**Comment by 1017161726** [comment]
这个地方是你页面底层的背景。

**Comment by 1017161726** [comment]
承载这个SmartLayout的根Layout，设置和页头一样的颜色，页头下方的灰白色背景单独指定，就可以了 。
