### ISSUE TITLE
setEnableLoadMore(false) 不起作用

### ISSUE THREAD

**Issue by X287210480X** [scwang90/SmartRefreshLayout#1122]
代码中设置了 setEnableLoadMore(false)，下拉列表依旧显示正在加载....

**Comment by Jusenr** [comment]
@X287210480X  setEnableLoadMore(false);
是控制 ClassicsFooter   （加载更多），而不是控制  ClassicsHeader（下拉刷新）。

**Comment by X287210480X** [comment]
首问描述错误，应该是：
代码中设置了 setEnableLoadMore(false)，依旧可以上拉加载更多。
发现是因为在BaseApplication中设置了全局打开加载更多，去掉就好了，但是按文档所说BaseApplication中的设置优先级最低。

**Comment by GuoAxiang** [comment]
同样问题,设置了setEnableLoadMore(false),还是可以上拉加载,请问怎么解决的?

**Comment by X287210480X** [comment]
> 同样问题,设置了setEnableLoadMore(false),还是可以上拉加载,请问怎么解决的?

上面不是写了我的原因的吗？

**Comment by GuoAxiang** [comment]
如果我在全局关掉加载更多,那在使用的时候,setEnableLoadMore(true)又不起作用了..

**Comment by scwang90** [comment]
关闭加载请使用 finishLoadMore
