### ISSUE TITLE
[ConstraintLayout约束位置布局显示不全]

### ISSUE THREAD

**Issue by zabio** [scwang90/SmartRefreshLayout#1123]
**详细描述**
在使用ConstraintLayout布局中，指定SmartRefreshLayout位于某个view之下预览recycleView高度不能完全展开，运行时高度也不能撑满SmartRefreshLayout
SmartRefreshLayout设置为wrap_content，数据多就不能滚动，因为已经超出屏幕底部
recycleView只能指定高度dp才能适配上
**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2' 
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.2' 
```

**布局代码**
```xml
<androidx.constraintlayout.widget.ConstraintLayout>
<tv/>
<tv/>

<!--希望SmartRefreshLayout占据固定的屏幕高度 50% 70% ... -->

 <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/refresh"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_marginTop="@dimen/dp_6"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/tv_h1">

        <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_product"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:overScrollMode="never"
                tools:itemCount="12"
                tools:listitem="@layout/item_rank_product_full" />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by colorbitch** [comment]
> **详细描述**
> 在使用ConstraintLayout布局中，指定SmartRefreshLayout位于某个view之下预览recycleView高度不能完全展开，运行时高度也不能撑满SmartRefreshLayout
> SmartRefreshLayout设置为wrap_content，数据多就不能滚动，因为已经超出屏幕底部
> recycleView只能指定高度dp才能适配上
> **使用版本**
> 
> ```groovy-gradle
> implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2' 
> implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.2' 
> ```
> 
> **布局代码**
> 
> ```
> <androidx.constraintlayout.widget.ConstraintLayout>
> <tv/>
> <tv/>
> 
> 
> 
>  <com.scwang.smartrefresh.layout.SmartRefreshLayout
>             android:id="@+id/refresh"
>             android:layout_width="0dp"
>             android:layout_height="0dp"
>             android:layout_marginTop="@dimen/dp_6"
>             app:layout_constraintBottom_toBottomOf="parent"
>             app:layout_constraintEnd_toEndOf="parent"
>             app:layout_constraintStart_toStartOf="parent"
>             app:layout_constraintTop_toBottomOf="@id/tv_h1">
> 
>         <androidx.recyclerview.widget.RecyclerView
>                 android:id="@+id/rv_product"
>                 android:layout_width="match_parent"
>                 android:layout_height="match_parent"
>                 android:overScrollMode="never"
>                 tools:itemCount="12"
>                 tools:listitem="@layout/item_rank_product_full" />
> 
>     </com.scwang.smartrefresh.layout.SmartRefreshLayout>
> </androidx.constraintlayout.widget.ConstraintLayout>
> ```

+1

**Comment by colorbitch** [comment]
> **详细描述**
> 在使用ConstraintLayout布局中，指定SmartRefreshLayout位于某个view之下预览recycleView高度不能完全展开，运行时高度也不能撑满SmartRefreshLayout
> SmartRefreshLayout设置为wrap_content，数据多就不能滚动，因为已经超出屏幕底部
> recycleView只能指定高度dp才能适配上
> **使用版本**
> 
> ```groovy-gradle
> implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2' 
> implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.2' 
> ```
> 
> **布局代码**
> 
> ```
> <androidx.constraintlayout.widget.ConstraintLayout>
> <tv/>
> <tv/>
> 
> 
> 
>  <com.scwang.smartrefresh.layout.SmartRefreshLayout
>             android:id="@+id/refresh"
>             android:layout_width="0dp"
>             android:layout_height="0dp"
>             android:layout_marginTop="@dimen/dp_6"
>             app:layout_constraintBottom_toBottomOf="parent"
>             app:layout_constraintEnd_toEndOf="parent"
>             app:layout_constraintStart_toStartOf="parent"
>             app:layout_constraintTop_toBottomOf="@id/tv_h1">
> 
>         <androidx.recyclerview.widget.RecyclerView
>                 android:id="@+id/rv_product"
>                 android:layout_width="match_parent"
>                 android:layout_height="match_parent"
>                 android:overScrollMode="never"
>                 tools:itemCount="12"
>                 tools:listitem="@layout/item_rank_product_full" />
> 
>     </com.scwang.smartrefresh.layout.SmartRefreshLayout>
> </androidx.constraintlayout.widget.ConstraintLayout>
> ```

高度设置为0dp

**Comment by scwang90** [comment]
问题不能重现

**Comment by whereareu** [comment]
https://github.com/scwang90/SmartRefreshLayout/issues/1160
这里有答案
