### ISSUE TITLE
上拉加载问题

### ISSUE THREAD

**Issue by NerdAnonymous** [scwang90/SmartRefreshLayout#1124]
**详细描述**
下载demo项目，进入实战-Repast，上拉加载，加载最后一条数据时底部出现上拉加载，正在上拉加载时，立刻在进行上拉拖拽（上拉并且手不离开屏幕）手势，接着你就会发现在显示没有更多数据的情况下，加载的动画同时也在转

**使用版本**
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2'

**使用代码**
网站上下载的demo

**Comment by scwang90** [comment]
最新版本已经修复
