### ISSUE TITLE
结合沉浸式使用 2.0.0 版本SmartRefreshLayout

### ISSUE THREAD

**Issue by Ymars1990** [scwang90/SmartRefreshLayout#1128]
**具体说下**
沉浸式下，使用SmartRefreshLayout作为root 布局，上面布局直接顶出屏幕歪了，下拉刷新，看不到header或者要下拉不少距离才能看到
不好意思看到想用的问题，但是marginTop 这个值应该依据什么设置，请问原作者，谢谢

**Comment by scwang90** [comment]
demo 中有例子，需要使用工具类计算
