### ISSUE TITLE
属性文档里的ClassicHeader在布局文件中如何使用的示例代码好像有错误

### ISSUE THREAD

**Issue by kouhengsheng** [scwang90/SmartRefreshLayout#1130]
**具体说下**
https://github.com/scwang90/SmartRefreshLayout/blob/master/art/md_property.md

**为什么**
属性文档里的ClassicHeader在布局文件中如何使用的示例代码好像有错误
在属性文档中，先提供了ClassicHeader在java代码中的示例代码，然后下面就应该提供ClassicHeader在XML中的示例代码，但是实际上这个位置却粘贴的是ClassicFooter在XML中的示例代码，也就是说ClassicFooter的XML示例代码在属性文档中出现了两次，而且我没找到ClassicHeader在XML中的示例代码

**Comment by scwang90** [comment]
谢谢，
