### ISSUE TITLE
如何 加载更多  在RV滑动到底部的时候一直显示，目前只找到在没有更多数据的时候才可以一直显示

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#1145]
已看现有的issue，很早看到有这个属性，现在再看文档没有了，别人回答的属性，现在也没有了

**Comment by scwang90** [comment]
不支持一直显示

**Comment by xyZangGit** [comment]
> 不支持一直显示

可否提供一下支持的思路  我尝试继承SmartRefreshLayout，实现拉到底部一直显示加载更多，一直不成功

**Comment by scwang90** [comment]
只能自己 再 adapter 末尾添加一个 view
