### ISSUE TITLE
大佬 库内部报错了啊

### ISSUE THREAD

**Issue by androidLeeGX** [scwang90/SmartRefreshLayout#116]
在  
/**
 * 智能刷新布局
 * Intelligent Refreshlayout
 * Created by SCWANG on 2017/5/26.
 */
     public class SmartRefreshLayout extends ViewGroup implements RefreshLayout{
}
这页
 CoordinatorLayout 报错了

**Comment by scwang90** [comment]
这是是什么错？可否贴出错误截图

**Comment by scwang90** [comment]
你是使用 源码编译吗？
