### ISSUE TITLE
在xml里写布局的时候 SmartRefreshLayout里写布局无法预览布局

### ISSUE THREAD

**Issue by Vanrevfront** [scwang90/SmartRefreshLayout#1161]
在xml里写布局的时候 SmartRefreshLayout里写布局无法预览布局

**Comment by scwang90** [comment]
build 一下

**Comment by Vanrevfront** [comment]
build过了哦 不行哦 就是把布局放在里面就无法实时预览哦&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 树朾 <notifications@github.com&gt;
发送时间: 2020年5月22日 22:32
收件人: scwang90/SmartRefreshLayout <SmartRefreshLayout@noreply.github.com&gt;
抄送: Vanrevfront <841637953@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[scwang90/SmartRefreshLayout] 在xml里写布局的时候 SmartRefreshLayout里写布局无法预览布局 (#1161)





 
build 一下

**Comment by FlyInTheSkyToMe** [comment]
我也遇到了这个问题。当界面View很多的时候，对查看和修护很不友好。
相关版本：
Android Studio：4.2.2
SmartRefreshLayout：1.1.3

如下是测试的Demo：

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".MainActivity">

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Hello World!" />
        </LinearLayout>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

</LinearLayout>

![image](https://user-images.githubusercontent.com/13445528/127854756-6b8e7e87-fda3-43cf-a904-bd319b0eadc3.png)

**Comment by FlyInTheSkyToMe** [comment]
导致问题所在的原因如下：
我们使用的是AndroidX，已经不存在android.support包，但是SmartRefreshLayout项目仍然在使用android.support。所以导致了这个问题的发生。希望能得到解决，感谢！
@scwang90 @keenorchen @chengzhijun0706

**Comment by FlyInTheSkyToMe** [comment]
经过验证：
1、新建测试项目，Use legacy android.support libraries，就不会存在该问题。
2、把SmartRefreshLayout项目中的 android.support 替换为Androidx，也不会存在该问题。
所以，是因为SmartRefreshLayout项目和我们本身的libraries不一致，导致的。请作者尽快升级项目到Androidx
