### ISSUE TITLE
多次调用autoRefresh或者autoRefreshAnimationOnly转圈时候中间的动画圆弧会直接变成圆形

### ISSUE THREAD

**Issue by 951AB159BA** [scwang90/SmartRefreshLayout#1164]
如题。正常来说，转圈中间的动画是带箭头弧形的，但是多次调用refresh后，直接变成圆形。
用的是这种类别：srl.setRefreshHeader(new MaterialHeader(this));

多次调用后，ui错误，变成圆形而不是箭头动画的弧形
srl.autoRefreshAnimationOnly();
srl.autoRefreshAnimationOnly();
srl.autoRefreshAnimationOnly();

**Comment by scwang90** [comment]
在 demo 中添加如下代码，并未发现问题
```
        mToolbar.setOnLongClickListener(v -> {
            mRefreshLayout.autoRefreshAnimationOnly();
            mRefreshLayout.autoRefreshAnimationOnly();
            mRefreshLayout.autoRefreshAnimationOnly();
            return true;
        });
```
