### ISSUE TITLE
为何先执行onStartAnimator，后执行onReleasing？

### ISSUE THREAD

**Issue by gitgeek4dx** [scwang90/SmartRefreshLayout#117]
对于我这种想要实现三段式下拉刷新动画的需求，基本上就无法实现第二步-手指抬起到回到触发刷新的位置这段时间的动画了。
我们的三段分别为：
第一段，手指下拉过程的动画
第二段，手指抬起之后的动画，如果此时的位置大于可触发刷新的最小位置，则做动画，回到刷新头保持的位置。如果此时位置小于可触发刷新的最小位置，则逆向执行第一段动画。
第三段，刷新头回到触发刷新位置（刷新过程中刷新头保持的位置），此时才应该开始执行刷新的动画。
但是使用过程发现，SmartRefreshLayout无法做第二段动画，直接执行第三段。

**Comment by scwang90** [comment]
可否看看你的动画设计搞？

**Comment by gitgeek4dx** [comment]
​横线我是用的动态绘制矩形，横线出现和消失，是动画的第一步和第二步。分别是下拉过程触发（第一步）和松手回弹时做的（第二步）。
第三步文字，是在回弹到触发刷新（刷新头保持的位置）之后，开始做的动画。现在问题就是，onStartAnimator和onReleasing执行顺序的问题，先执行onStartAnimator后执行onReleasing，导致我无法实现第二步动画。

2017-08-09 11:38 GMT+08:00 树朾 <notifications@github.com>:

**Comment by scwang90** [comment]
什么横线？你的设计稿呢？

**Comment by gitgeek4dx** [comment]
是一个动态图，我通过邮箱回复的你，没想到gif还是显示不出，怎么给你？

**Comment by scwang90** [comment]
没有收到邮件~

**Comment by senjoeson** [comment]
请问一下, 为什么加载更多之后,会直接滑动到顶部,而不是我之前停留的位置?大佬,求解答

**Comment by lancewong2014** [comment]
@senjoeson 你是不是重新setAdatper了

**Comment by senjoeson** [comment]
@lancewong2014 重新设置适配器会刷新位置吗?

**Comment by lancewong2014** [comment]
@senjoeson adapter都不一样了，位置还能一样？
