### ISSUE TITLE
finishLoadMoreWithNoMoreData或者setNoMoreData之后，如何使列表滚动到底部之后Footer再显示出来？

### ISSUE THREAD

**Issue by 2173432565** [scwang90/SmartRefreshLayout#1170]
期望的效果是，finishLoadMoreWithNoMoreData或者setNoMoreData之后，需要等列表滚动到底部之后Footer再显示出来，现在的效果是，Footer会直接先浮在列表Layout底部，等列表滚动到底部之后才会再追加的列表后面

**Comment by flyjiang2014** [comment]
public RefreshLayout finishLoadMore(final int delayed, final boolean success, final boolean noMoreData)    用这个方法  替换 finishLoadMoreWithNoMoreData方法，设定个延时时间。

**Comment by 2173432565** [comment]
@flyjiang2014 多谢，这样确实可以了

**Comment by fdh19979** [comment]
你这个有可能是使用`AsyncListDiffer`，因为是异步计算列表更新，就会出现：如果数据回来，你更新列表，并立刻设置finishLoadMoreWithNoMoreData，效果就是显示出现footer，然后列表更新，footer就变成了附在列表底部

正确的做法不是增加延时，而是AsyncListDiffer.addListListener，在列表更新完成以后再finishLoadMoreWithNoMoreData，UI视觉效果就正确了。
