### ISSUE TITLE
在DialogFragment中使用时出现java.lang.IllegalArgumentException: Illegal pattern character 't'

### ISSUE THREAD

**Issue by hyhyhykw** [scwang90/SmartRefreshLayout#1173]
**详细描述**
使用ClassicsHeader 必出现 定位源代码位置是ClassicsHeader 205行 DateFormat初始化的地方
       mLastUpdateFormat = new SimpleDateFormat(mTextUpdate, Locale.getDefault());

**使用版本**
```gradle
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2' 
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.2' 
```

**Comment by hyhyhykw** [comment]
sorry，好像是我这里修改出错了，忘记加单引号了

**Comment by bxxasn** [comment]
api  'com.scwang.smart:refresh-layout-kernel:2.0.1'      //核心必须依赖
    api  'com.scwang.smart:refresh-header-classics:2.0.1'    //经典刷新头
    api  'com.scwang.smart:refresh-footer-classics:2.0.1'    //经典加载

也出现这个错误.Classicsheader.java中的214行.

**Comment by bxxasn** [comment]
mLastUpdateFormat = new SimpleDateFormat(mTextUpdate, Locale.getDefault());

mTextUpdate的结果:  Last updated M-d HH:mm
 Locale.getDefault()的结果: en_US

**Comment by MoonSawyer** [comment]
implementation  'io.github.scwang90:refresh-header-classics:2.0.5'

我也碰见这个问题，自查然后发现ClassicsHeader.REFRESH_HEADER_UPDATE的参数，正常在中文里没事，但是在英文里就会报错，感觉像是小写被改成大写，然后SimpleDateFormat转换报错了。作者改下textAllCaps试试呢？
