### ISSUE TITLE
纯滚动模式和越界回弹

### ISSUE THREAD

**Issue by flztsj** [scwang90/SmartRefreshLayout#118]
现在越界回弹是做在刷新机制上面的吗？ 
如果让纯滚动模式也有回弹效果应该如何实现？

比如我想让一个没有刷新和加载的列表可以有在上拉下拉的时候有ios的回弹效果？

**Comment by scwang90** [comment]
难道现在不行吗？你用的版本是？你是不是把越界回弹功能关闭了？

**Comment by flztsj** [comment]
现在用的版本就是最新的代码，现在纯滚动模式是直上直下的效果，没有弹性

**Comment by fiona0419** [comment]
mSmartRefreshLayout.setReboundInterpolator(new DecelerateInterpolator());

**Comment by flztsj** [comment]
这个方法Ok
