### ISSUE TITLE
androidx版本，当调用.setPrimaryColorsId时，报错  找不到android.support.v4.view.NestedScrollingParent的类文件

### ISSUE THREAD

**Issue by xiaolinziwang** [scwang90/SmartRefreshLayout#1188]
androidx版本，当调用.setPrimaryColorsId时，报错  找不到android.support.v4.view.NestedScrollingParent的类文件；
api androidx.appcompat:appcompat:1.0.0

**Comment by Young-D-Sun** [comment]
Androidx版本
错误: 无法访问NestedScrollingParent
找不到android.support.v4.view.NestedScrollingParent的类文件

**Comment by scwang90** [comment]
gradle.properties 中添加
```
useAndroidX=true
android.enableJetifier=true
```

**Comment by li-xiaojun** [comment]
useAndroidX=true
android.enableJetifier=true
只能处理一级引用，还是有很大隐患问题的。我的androidx类库引用了你的，你的类引用了support包，我的类库在使用的时候就会有问题。
