### ISSUE TITLE
京东 淘宝 做活动的那种 下拉样式有吗？

### ISSUE THREAD

**Issue by ljackChen001** [scwang90/SmartRefreshLayout#12]
类似于京东，淘宝,QQ  做活动的时候 下拉到一定 的高度的时候出现活动互动的界面

**Comment by scwang90** [comment]
暂时没有，这个功能在开发计划中，但是至少要一两个星期之后，如果你现在项目急需，你可以使用这个

[SmoothRefreshLayout](https://github.com/dkzwm/SmoothRefreshLayout)

![](https://segmentfault.com/img/bVQxCA?w=324&h=576)

![](https://segmentfault.com/img/bVQxCD?w=324&h=576)

**Comment by ljackChen001** [comment]
不急，就是之前看到过那种效果挺好，看到你开源了，就顺便问一下，也可以学习一下

**Comment by fg2q1q3q** [comment]
博主好贴心，弱弱问一句，有没有“淘宝二楼”的计划
