### ISSUE TITLE
新版本中无法再布局中监听刷新等事件吗

### ISSUE THREAD

**Issue by clbDream** [scwang90/SmartRefreshLayout#1206]
app:onRefreshListener

使用的版本    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'
    implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0'

**Comment by clbDream** [comment]
错了,是这个    implementation  'com.scwang.smart:refresh-layout-kernel:2.0.1'
    implementation  'com.scwang.smart:refresh-header-classics:2.0.1'
    implementation  'com.scwang.smart:refresh-footer-ball:2.0.1'

**Comment by scwang90** [comment]
可以，参考 demo

**Comment by iminminxu** [comment]
demo没有看到 @scwang90 ，我使用databinding引用app:onRefreshListener也构建失败
