### ISSUE TITLE
希望改进一下刷新状态的代码还有判断，现在真的太难用，判断是否正在刷新都有困难

### ISSUE THREAD

**Issue by Ayvytr** [scwang90/SmartRefreshLayout#1208]
到底用哪个才表示正在刷新？（就是下拉刷新的动画只要开始了，一直到下拉刷新头完全隐藏，就认为是刷新，这种状态如何判断？）试了好多判断都不准。而且能否考虑下精简这个状态，对外开放简单的方法判断。现在明显太复杂了
refresh_layout.state.isFinishing || refresh_layout.state == RefreshState.Refreshing
refresh_layout.state != RefreshState.None

**Comment by scwang90** [comment]
看常见问题
