### ISSUE TITLE
下拉加载自动滑动问题

### ISSUE THREAD

**Issue by itljw** [scwang90/SmartRefreshLayout#1209]
setEnableRefresh从true设置为false，下拉加载后，手往上移然后停住不动，页面还是会往上移动...

**Comment by AndroidYuki** [comment]
如果使用的是Recyclerview的话，可以试试设置recyclerview.setNestedScrollingEnabled(false)。解决滑动冲突问题。希望可以帮到你。

**Comment by itljw** [comment]
抱歉，忘记回复你了，刚试了下，可以解决这个问题，谢谢呀
