### ISSUE TITLE
2.0.1版本在ViewPager里的fragment使用时,调用autoRefresh快速滑动切换fragment后不触发onRefresh监听

### ISSUE THREAD

**Issue by q296494327** [scwang90/SmartRefreshLayout#1217]
2.0.1版本在ViewPager里的fragment使用时,调用autoRefresh快速滑动切换fragment后不触发onRefresh监听
如果一个一个的慢点滑动,会正常触发onRefresh,只要一快速滑动,就触发不了onRefresh监听,并且有时候刷新的圈圈一直停留在页面

**Comment by q296494327** [comment]
刚刚又试了下,不使用autoRefresh, 纯手动下拉刷新,刷完马上快速切换ViewPager

**Comment by q296494327** [comment]
刚刚发现了问题原因,是因为BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT

**Comment by qq764215676** [comment]
我也碰到了类似的问题，ViewPager2里的每个Fragment都添加了下拉刷新，在点击某个Fragment的时候，另一个Fragment的Create方法会回调，然后执行autoRefresh，但是发现onRefresh没有被回调，不知道是不是因为那个Fragment还没有显示出来的原因

**Comment by q296494327** [comment]
今天把官方demo下载下来后,发现demo也有同样的问题,Demo主页面也是用的ViewPager
 例如:我对tabIndex2下拉刷新,然后马上滑动切换到tabIndex1,接着再次回到tabIndex2,刷新的圈圈就一直停留在那里转,并且打死都不能再下拉了
![1](https://user-images.githubusercontent.com/20579810/89136242-425c9b80-d565-11ea-8d0b-8dd11bc82c22.jpg)

**Comment by q296494327** [comment]
刚刚发现不是没走onRefresh回调,而是网络请求成功的回调没有走,导致没有关闭刷新动画
我是使用rxjava_retrofit进行网络请求,在请求时绑定了生命周期.compose(RxLifecycleUtils.bindToLifecycle(iView));
然后我尝试把绑定生命周期的compose删掉,发现刷新动画能正常关闭了
