### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by Reginer** [scwang90/SmartRefreshLayout#122]
希望楼主可以把AndroidManifest.xml中的，除了必要的内容都删掉

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.scwang.smartrefresh.layout"
</manifest>

每次从本地删除android:allowBackup这种属性不太好 。

**Comment by fairytale110** [comment]
你可以这样
`
<application  tools:replace="android:allowBackup"/> `

**Comment by Reginer** [comment]
下次更新再删也来得及，毕竟现在最高sdk25，26也已经出了。

**Comment by scwang90** [comment]
1.0.4 版本将会修复这个问题
