### ISSUE TITLE
布局中如何加入自己的view

### ISSUE THREAD

**Issue by SagittariusSum** [scwang90/SmartRefreshLayout#1225]
<com.scwang.smart.refresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <com.fractalist.haowai.view.viewpager.CarouselViewPager
            android:id="@+id/carousel_viewPager"
            android:layout_width="match_parent"
            android:layout_height="150dp"/>
        <android.support.v7.widget.RecyclerView
            android:id="@+id/temperate_recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:overScrollMode="never"/>
    </com.scwang.smart.refresh.layout.SmartRefreshLayout>
为什么CarouselViewPager 会变成 header？
怎么不让他变成header

**Comment by scwang90** [comment]
用一个线性布局，或者帧布局，把  CarouselViewPager RecyclerView 包起来
