### ISSUE TITLE
多Tab情况下，初始化中采用autoRefresh方法，在加载动画未结束时，快速切换tab，会导致请求不成功

### ISSUE THREAD

**Issue by SirBad** [scwang90/SmartRefreshLayout#1244]

**Comment by KAICW** [comment]
同样遇到这样的问题，在页面autoRefresh动画为完成之前，直接跳转页面也会出现

**Comment by scwang90** [comment]
tab 切换界面，Smart 会被 removeFromWindow ，Smart将会取消所有操作（为了避免正常界面关闭时导致的内存泄漏）
所以这样的情况，建议 使用 autoRefreshAnimationOnly （只执行动画），然后自己用代码调用 网络请求
