### ISSUE TITLE
上拉加载更多的问题

### ISSUE THREAD

**Issue by WANZIzZ** [scwang90/SmartRefreshLayout#1251]
版本是 1.1.0

~~~
<com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.scwang.smartrefresh.layout.header.ClassicsHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingStart="6dp"
        android:paddingTop="6dp"
        android:paddingEnd="6dp" />

    <com.scwang.smartrefresh.layout.footer.ClassicsFooter
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</com.scwang.smartrefresh.layout.SmartRefreshLayout>
~~~

在上拉加载更多的时候，列表会立马返回当前页顶部，然后才会走 ***setOnLoadMoreListener*** 里的 ***onLoadMore***。

比如当前页是0，然后往上滑，滑动到底部后，列表会立马跑到0页的顶部，然后调用加载更多。

加载完后，继续上滑，滑动到1页的底部后，列表会立马跑到1页的顶部，然后调用加载更多，以此类推。

**Comment by WANZIzZ** [comment]
调用的代码是 

~~~
        with(refreshLayout) {
            setOnRefreshListener {
                refresh()
            }
            setOnLoadMoreListener {
                loadMore()
            }
        }
~~~

我尝试注释过 loadMore() 然后运行，但是还是会在滑动到底部后，立马跳到顶部，然后下面是正在加载

**Comment by WANZIzZ** [comment]
经过测试，需要在 RecyclerView 外面包裹一个约束布局（不一定是约束布局，只有约束布局测试了）

~~~
<?xml version="1.0" encoding="utf-8"?>
<com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.scwang.smartrefresh.layout.header.ClassicsHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:paddingStart="6dp"
            android:paddingTop="6dp"
            android:paddingEnd="6dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
    </androidx.constraintlayout.widget.ConstraintLayout>

    <com.scwang.smartrefresh.layout.footer.ClassicsFooter
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</com.scwang.smartrefresh.layout.SmartRefreshLayout>
~~~

**Comment by lzy6** [comment]
请问现在有更好的解决方法么，我也遇到了这个问题

**Comment by WANZIzZ** [comment]
> 请问现在有更好的解决方法么，我也遇到了这个问题

你看下我上面的回复，就是在 RecyclerView  外面包裹一层布局就可以了

**Comment by lzy6** [comment]
大佬我包裹了ConstraintLayout，还是不起作用，但是包裹NestedScrollView就可以了，但感觉每个列表都包裹个NestedScrollView感觉很不好

**Comment by WANZIzZ** [comment]
> 大佬我包裹了ConstraintLayout，还是不起作用，但是包裹NestedScrollView就可以了，但感觉每个列表都包裹个NestedScrollView感觉很不好

我看看你的布局

**Comment by lzy6** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/background"
    android:orientation="vertical">

    <include layout="@layout/include_title" />

    <com.scwang.smart.refresh.layout.SmartRefreshLayout
        android:id="@+id/refresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_list"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
                app:spanCount="2"
                tools:listitem="@layout/item_goods" />
        </androidx.constraintlayout.widget.ConstraintLayout>
    </com.scwang.smart.refresh.layout.SmartRefreshLayout>
</LinearLayout>`

**Comment by WANZIzZ** [comment]
> `
> ```
> <include layout="@layout/include_title" />
> 
> <com.scwang.smart.refresh.layout.SmartRefreshLayout
>     android:id="@+id/refresh"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent">
> 
>     <androidx.constraintlayout.widget.ConstraintLayout
>         android:layout_width="match_parent"
>         android:layout_height="match_parent">
> 
>         <androidx.recyclerview.widget.RecyclerView
>             android:id="@+id/rv_list"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
>             app:spanCount="2"
>             tools:listitem="@layout/item_goods" />
>     </androidx.constraintlayout.widget.ConstraintLayout>
> </com.scwang.smart.refresh.layout.SmartRefreshLayout>
> ```
> 
> `

是不是根布局的原因？ 我那个的根布局就是 com.scwang.smartrefresh.layout.SmartRefreshLayout

**Comment by lzy6** [comment]
我的外面还有一层LinearLayout跟布局没贴出来，另一个界面跟布局是SmartRefreshLayout，里面用约束布局也不行，只有NestedScrollView可以，不知道后面会修复这个问题不

**Comment by lzy6** [comment]
问题解决了，出现这个问题应该都用了骨骼加载吧，只要在第一次加载的时候hide骨骼加载，翻页的时候不要去hide，就没问题了
