### ISSUE TITLE
开启了越界拖动，在viewpage嵌套smartRefresh->RV,切到后台再回来，偶现下拉越界高度超大，导致要下拉很远才能刷新

### ISSUE THREAD

**Issue by Alexxiaopang** [scwang90/SmartRefreshLayout#1264]
smartRefresh最新版本，如题：viewpage嵌套smartRefresh->RV，四个Fragment，把app切到后台，再次回来，发现无法刷新，尝试一直下拉smartRefresh，拉到屏幕一半出现头部刷新！越界高度占了屏幕一半，不知道为啥这个越界的高度变得那么高了，能否设置越界高度

**Comment by scwang90** [comment]
Smart 的 demo 首页也是 viewpage嵌套smartRefresh->RV ，你看看能在 demo 中重新这个问题吗？
