### ISSUE TITLE
下拉子View的任何可滑動控件時，一旦子View被下拉到最頂，剩餘的動作即使不放開手指也會被SmartRefreshLayout攔截消費

### ISSUE THREAD

**Issue by siralam** [scwang90/SmartRefreshLayout#1274]
這可能是 by deisgn 的，但很不符合直覺，故此我想我可能是漏掉了什麼，所以想問一下

### 期望效果：
當我在一個子view的scrollview滑動時，我的目的是操作這個scrollview，即使我已經滑過界了，也不代表我希望下拉刷新。因此，當我在一個**上面還有剩餘滑動空間**的子scrollview向下滑動，到達頂部之後，作為母view的SmartRefreshLayout不應該攔截之後的ACTION_MOVE。（補充說明：但如果我在一個上面已經沒有剩餘滑動空間的子scrollview向下滑動，則代表我明知道已經沒有可以滑動的空間了還要向下拉，代表我希望下拉刷新，這時母SmartRefreshLayout應該要響應）

### 實際效果：
當我在一個**上面還有剩餘滑動空間**的子scrollview向下滑動，到達頂部之後，不放開手指繼續滑動，其後的ACTION_MOVE會被作為母view的SmartRefreshLayout攔截／繼續消耗，變為執行下拉刷新的動作。
這個效果在一個**上面還有剩餘滑動空間**的子scrollview向下fling時也會發生，代表fling所剩餘的velocity也會被SmartRefreshLayout攔截／消耗。

### 已經試過：
setEnableNestedScroll(true) 無效；
setEnableOverScrollDrag(false) 無效；
setEnableOverScrollBounce(false) 無效

**Comment by scwang90** [comment]
1.可以给 scrollview 添加事件监听，在接收到 scrollview 滚动后，refreshLayout.setEnableRefresh（false） ，当  scrollview 滚动事件释放后，refreshLayout.setEnableRefresh（true）

2.或者尝试重写 smart 当 canRefresh 方法来实现

**Comment by siralam** [comment]
OK，這好像可以。謝謝回覆！
