### ISSUE TITLE
上拉加载更多会置顶, 这应该是一个bug

### ISSUE THREAD

**Issue by skycn-android-2016** [scwang90/SmartRefreshLayout#1276]
加了经典头和尾, 当上拉加载更多一页, 会发生列表置顶, 找了网上的解决方案, recycleview外层嵌套NestedScrollView可以解决这个问题, 但是列表item不复用了, 这个有童鞋遇到过吗? 期待你的解决方案.

**Comment by lzy6** [comment]
请问你解决了么,我也遇到了

**Comment by skycn-android-2016** [comment]
我是列表加了骨架, 每次hide都会重新设置adater, 把hide逻辑调整一下即可

**Comment by lzy6** [comment]
> 我是列表加了骨架, 每次hide都会重新设置adater, 把hide逻辑调整一下即可

问题解决了，只要在第一次加载的时候hide骨骼加载，翻页的时候不要去hide，就没问题了

**Comment by liaodongxiaoxiao** [comment]
> > 我是列表加了骨架, 每次hide都会重新设置adater, 把hide逻辑调整一下即可
> 
> 问题解决了，只要在第一次加载的时候hide骨骼加载，翻页的时候不要去hide，就没问题了

能给下代码片段吗？我也遇到类似的问题了。

**Comment by liangke21** [comment]
我也遇到这个问题
