### ISSUE TITLE
子类实现NestedScrollingParent2 嵌套RecyclerView

### ISSUE THREAD

**Issue by PokerMman** [scwang90/SmartRefreshLayout#1279]
我子类实现NestedScrollingParent2 处理嵌套RecyclerView 嵌套RecyclerView  类似于淘宝的那种吸顶布局，但是 在fling 滑动到顶部之后，smartRefresh 无法下拉刷新了

**Comment by PokerMman** [comment]
找到问题了，发现嵌套的时候fling 一直在执行，导致下拉刷新无效。

**Comment by gslovemy** [comment]
可以给一个demo吗，目前项目的需求跟你一样
