### ISSUE TITLE
PagerAdapterWrapper不存在？！

### ISSUE THREAD

**Issue by TroyRay** [scwang90/SmartRefreshLayout#128]
compile 'com.android.support:appcompat-v7:25.3.1'
我必须要使用这个版本才能引入PagerAdapterWrapper？这根本就不合适吧，没其他解决办法么？？

**Comment by scwang90** [comment]
兼容包是必须的，没有其他办法

**Comment by TroyRay** [comment]
@scwang90  那我为什么不能用26的，只能用25的？这限定死了就不是兼容了吧？

**Comment by scwang90** [comment]
demo apk 源码使用的就是 26 的版本，并没有你所描述的问题
