### ISSUE TITLE
只有一页数据时 下拉刷新 后马上 上拉加载更多 onLoadMore偶尔会回调

### ISSUE THREAD

**Issue by fugx** [scwang90/SmartRefreshLayout#1282]
只有1页数据时  数据回调结束后  调用refresh.finishLoadMoreWithNoMoreData();
再立即 上拉加载更多，有时会触发 onLoadMore回调，请求第二页得数据

**Comment by LvZhenDong** [comment]
确实有这个问题，我也遇到了

**Comment by scwang90** [comment]
如果下拉刷新之后，数据还是只有一页的话，可以调用 finishRefreshWithNoMoreData 代替 finishRefresh

**Comment by fugx** [comment]
//判断是否还有更多数据
if (pushStatisticBeans.size() &gt;= response.getTotal()) {
    refresh.finishRefreshWithNoMoreData();
    refresh.finishLoadMoreWithNoMoreData();
} else {
    refresh.finishRefresh();
    refresh.finishLoadMore();
}
finishRefreshWithNoMoreData（）   代替  finishRefresh（）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scwang90/SmartRefreshLayout"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [scwang90/SmartRefreshLayout] 只有一页数据时 下拉刷新 后马上 上拉加载更多 onLoadMore偶尔会回调 (#1282)





 
确实有这个问题，我也遇到了
