### ISSUE TITLE
嵌套CoordinatorLayout使用的时候，如果CoordinatorLayout 里面的RecyclerView为空或隐藏，上滑AppBarLayout布局滑出了屏幕回不来了

### ISSUE THREAD

**Issue by yuchangliang** [scwang90/SmartRefreshLayout#1283]
如题，嵌套CoordinatorLayout使用的时候，如果CoordinatorLayout 里面的RecyclerView为空或隐藏，上滑AppBarLayout布局。滑出了整个屏幕然后拖不回不来了，下面是一大片空白。

![WechatIMG110](https://user-images.githubusercontent.com/6687803/101305373-821df180-387d-11eb-9391-10b3e0cccea1.jpeg)

如上图，这是我故意留了一点便于理解。 其实是全部滑出屏幕，然后屏幕就是一片空白。请问大家有遇到过嘛，怎么解决。我试了下面的很多种方法都不行。

<img width="889" alt="image" src="https://user-images.githubusercontent.com/6687803/101305494-cad5aa80-387d-11eb-8780-10b3ac930ddf.png">

  求解！@scwang90

**Comment by liudaohong** [comment]
自己根据 appbar  的状态来控制  smart的 下拉刷新是否为可用

**Comment by Masksam** [comment]
> 自己根据 appbar 的状态来控制 smart的 下拉刷新是否为可用

怎么判断呢？？
