### ISSUE TITLE
运行gradle build和导入as运行不一致

### ISSUE THREAD

**Issue by lizuojing** [scwang90/SmartRefreshLayout#129]
as导入之后运行能通过，但是通过gradle build命令编译包ClassicsHeader_srlFinishDelay和ClassicsFooter_srlFinishDelay资源找不到

**Comment by scwang90** [comment]
更新到最新再运行 ClassicsHeader_srlFinishDelay 是在 1.0.2 中才存在的属性

**Comment by lizuojing** [comment]
![image](https://user-images.githubusercontent.com/4328469/29399093-682fd026-835a-11e7-98a0-8efdd4e97103.png)
![Uploading image.png…]()
第一个图为当前使用版本和gradle build后报的错误，第二个图为as编译后正常通过的图。

**Comment by lizuojing** [comment]
![image](https://user-images.githubusercontent.com/4328469/29399205-d5e89f08-835a-11e7-9235-04f30ad3ad78.png)
![image](https://user-images.githubusercontent.com/4328469/29399214-e6fbe980-835a-11e7-91b9-bf30f2980884.png)
第一个图为当前使用版本和gradle build后报的错误，第二个图为as编译后正常通过的图。

**Comment by lizuojing** [comment]
![image](https://user-images.githubusercontent.com/4328469/29399323-58f9af86-835b-11e7-800b-289ad889f28c.png)
![image](https://user-images.githubusercontent.com/4328469/29399354-74a784ce-835b-11e7-8338-fcae29a62934.png)

第一个图为当前使用版本和gradle build后报的错误，第二个图为as编译后正常通过的图。建议as编译过去之后执行下gradle build命令。
