### ISSUE TITLE
请问是否支持在RecyclerView未到底部时就可以触发自动加载更多, 而不是到了底部之后才可以触发?

### ISSUE THREAD

**Issue by zhaoxuan365** [scwang90/SmartRefreshLayout#1292]
setFooterTriggerRate()参数设置为0, 0.1或1, 没有发现有什么区别啊,

 布局是

`<SmartRefreshLayout>`
`<NestedScrollView>`
`<LinearLayout>`
`...`
` <RecyclerView>`
`<LinearLayout>`
`<NestedScrollView>`
`<SmartRefreshLayout>`

**Comment by Ha2ryZhang** [comment]
怎么解决的

**Comment by zhaoxuan365** [comment]
SmartRefreshLayout不支持这个功能，我后来参考了其他思路实现的。[参考1](https://juejin.cn/post/6885146484791050247)，[参考2](https://www.jianshu.com/p/b502c5b59998)
