### ISSUE TITLE
listview等空布局显示

### ISSUE THREAD

**Issue by 900326** [scwang90/SmartRefreshLayout#1300]
SmartRefreshLayout嵌套listview时,listview设置空布局,不显示,时本身不支持还是有特殊用法

**Comment by scwang90** [comment]
空布局 Smart 的 demo 中有例子的

**Comment by Jack-bin183** [comment]
将你需要设置空布局的listview 包裹到LinearLayout里就可以了
<SmartRefreshLayout>
<LinearLayout/>
<listview/>
</SmartRefreshLayout>
