### ISSUE TITLE
JCenter 要关闭了， 请问有向mavenCentral 迁移的计划么？

### ISSUE THREAD

**Issue by edwinhan** [scwang90/SmartRefreshLayout#1308]
JCenter 要关闭了， 请问有像mavenCentral 迁移的计划么？

**Comment by scwang90** [comment]
有段时间没开发安卓了，谢谢提醒

**Comment by rockyoung** [comment]
从jCenter往mavenCentral迁移了吗

**Comment by li-xiaojun** [comment]
@scwang90  直接迁移到jitpack把，5分钟搞定，不费时间的

**Comment by scwang90** [comment]
现在可以使用

io.github.scwang90:refresh-layout-kernel:2.0.5
