### ISSUE TITLE
1.0.3，as能编译过去，gradle build编译不过

### ISSUE THREAD

**Issue by lizuojing** [scwang90/SmartRefreshLayout#131]
![image](https://user-images.githubusercontent.com/4328469/29399323-58f9af86-835b-11e7-800b-289ad889f28c.png)
![image](https://user-images.githubusercontent.com/4328469/29399354-74a784ce-835b-11e7-8338-fcae29a62934.png)

第一个图为当前使用版本和gradle build后报的错误，第二个图为as编译后正常通过的图。建议as编译过去之后执行下gradle build命令。

**Comment by scwang90** [comment]
你是下载项目，编译吗？

**Comment by lizuojing** [comment]
不是下载的项目，即使导入的库，然后自定义了header，用到了jar里面的资源。


原始邮件
发件人:树朾notifications@github.com
收件人:scwang90/SmartRefreshLayoutSmartRefreshLayout@noreply.github.com
抄送:lizuojinglizuojing111@163.com; Authorauthor@noreply.github.com
发送时间:2017年8月18日(周五) 17:30
主题:Re: [scwang90/SmartRefreshLayout] 1.0.3，as能编译过去，gradle build编译不过 (#131)


Closed #131.

**Comment by scwang90** [comment]
FinishDelay 本来就没有，不要用 FinishDelay了
