### ISSUE TITLE
Android 11大量出现Canvas: trying to draw too large

### ISSUE THREAD

**Issue by HeQuanLi** [scwang90/SmartRefreshLayout#1312]
java.lang.RuntimeException
Canvas: trying to draw too large(187151216bytes) bitmap.
com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:811)

版本：1.1.2

**Comment by scwang90** [comment]
不能甩锅呀

**Comment by scwang90** [comment]
自己注意图片压缩就好
