### ISSUE TITLE
Cannot access 'android.support.v4.view.NestedScrollingParent' which is a supertype of 'com.scwang.smart.refresh.layout.SmartRefreshLayout'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by ldc2017** [scwang90/SmartRefreshLayout#1344]
Cannot access 'android.support.v4.view.NestedScrollingParent' which is a supertype of 'com.scwang.smart.refresh.layout.SmartRefreshLayout'. Check your module classpath for missing or conflicting dependencies

**Comment by ldc2017** [comment]
kotlin 项目 1.4.32   提示这个玩意

**Comment by SkyD666** [comment]
请问是如何解决的这个问题？

**Comment by 287138531** [comment]
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
后面遇到这个问题的小伙伴，自己引入这个就好
还有gradle.properties加
android.useAndroidX=true
android.enableJetifier=true
