### ISSUE TITLE
苹果水滴问题

### ISSUE THREAD

**Issue by ytsxg123** [scwang90/SmartRefreshLayout#135]
![_20170821133433](https://user-images.githubusercontent.com/22367186/29504892-88a13e62-8675-11e7-9218-da4d647838f0.png)
 如图。这种问题是什么原因。

**Comment by ytsxg123** [comment]
加载未覆盖到白色圈圈

**Comment by scwang90** [comment]
问题在下一个版本修复，这个版本的解决方案是 不要改变Header的高度，具体使用方法参考 demo
