### ISSUE TITLE
建议把库迁移到 jitpack 或者 maven

### ISSUE THREAD

**Issue by wqandroid** [scwang90/SmartRefreshLayout#1355]
jcenter已经不支持更新了。Google的很多库也做了迁移

**Comment by BobEve** [comment]
+1

**Comment by Matchas-xiaobin** [comment]
+1

**Comment by zhpanvip** [comment]
jcenter明年初就要关了，作者这个库迁移到其他地方？

**Comment by xiepeng-xp** [comment]
+1

**Comment by zhpanvip** [comment]
> +1
jitpack上已经有了

https://jitpack.io/#scwang90/SmartRefreshLayout

**Comment by zhpanvip** [comment]
不过，最新的版本作者并没有发release，jitpack上目前最新版本是2.0.0

**Comment by bayshier** [comment]
压根就没传啊 	implementation 'com.github.scwang90.SmartRefreshLayout:refresh-drawable-paint:V2.0.0'
这啥呀？

**Comment by liangjingkanji** [comment]
永远可用

JFrog（这家公司维护着很多 Android 项目使用的 JCenter 工件库）已于 2021 年 3 月 31 日将 JCenter 设为只读代码库。根据公告，JCenter 将无限期地提供现有工件供用户下载。

https://developer.android.com/studio/build/jcenter-migration?hl=zh-cn

**Comment by wqandroid** [comment]
> JCenter

这辈子 不维护的库 你项目敢加？

**Comment by bayshier** [comment]
确实

王琼 ***@***.***> 于2021年7月19日周一 上午9:56写道：

**Comment by scwang90** [comment]
现在可以使用
io.github.scwang90:refresh-layout-kernel:2.0.5
