### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by JacksenLaw** [scwang90/SmartRefreshLayout#1365]
2个bug
1、设置 setEnableAutoLoadMore(false) 时 ，滑动到列表最后一项后，会自动回弹至前一条数据，最后一条数据还有，但是在屏幕之外
2、上拉加载时， footer 会覆盖在最后一条数据之上

搞的很难受

**Comment by stevenwsg** [comment]
我遇到了，header覆盖在第一条数据上
