### ISSUE TITLE
Mac和Windows下引用的版本不一致

### ISSUE THREAD

**Issue by 1109993488** [scwang90/SmartRefreshLayout#137]
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.3'
在Mac下引用的代码和Windows引用的会不一致，这个问题怎么解决？

**Comment by 1109993488** [comment]
mac下引用的应该是1.0.3tag版本，而windows下引用的好像是master版本，为什么出现这种情况，不是都是去jcenter上下代码吗

**Comment by scwang90** [comment]
可能是 Jcenter 的 Bug吧 ，我也不清楚，无法解决你的问题

**Comment by scwang90** [comment]
建议删除 gradle-SmartRefreshLayout 的本地缓存，重新引用

**Comment by 1109993488** [comment]
你可以重新上传下，mac上传的代码是1.0.3的，RefreshScrollBoundary这个名字，而window拉下的代码ScrollBoundaryDecider这个类，这个类是在1.0.3后上传的，那你现在发布的1.0.3 是以tag打的还是以master上打的？

**Comment by scwang90** [comment]
没有，什么好上传的啦，都是最新的，你可以删除缓存，重新引用

**Comment by 1109993488** [comment]
删了还不行，怎么能叫都是最新的呢？类名字都不一致，按理说jcenter上的应该是你打的tag标签的版本，怎么会出现master上的版本，算了，我引源代码吧

**Comment by limuyang2** [comment]
大兄弟，这还真不区分mac和win版本。包打包后都是同一个链接版本，这玩意本身就不区分mac、win。
