### ISSUE TITLE
Could not find com.scwang.smart:refresh-layout-kernel:2.0.3.

### ISSUE THREAD

**Issue by qssq** [scwang90/SmartRefreshLayout#1376]
Could not find com.scwang.smart:refresh-layout-kernel:2.0.3.
Required by:
請問上傳到哪裏呢。

**Comment by gkj17** [comment]
可以在这查找 https://developer.aliyun.com/mvn/search

**Comment by scwang90** [comment]
现在可以使用
io.github.scwang90:refresh-layout-kernel:2.0.5

**Comment by AkashiWen** [comment]
试了，不行

**Comment by zdd** [comment]
> 现在可以使用 io.github.scwang90:refresh-layout-kernel:2.0.5

建议更新一下首页的文档，还是2.0.3呢。

**Comment by vinhhoang2402** [comment]
I just added maven { url 'https://maven.aliyun.com/repository/jcenter' } and it worked for me.
