### ISSUE TITLE
加了依赖，但就是找不到库

### ISSUE THREAD

**Issue by gudao20080** [scwang90/SmartRefreshLayout#1378]
加了：  implementation  'com.scwang.smart:refresh-layout-kernel:2.0.3'      //核心必须依赖
    implementation  'com.scwang.smart:refresh-header-classics:2.0.3'    //经典刷新头
但是就是找不到库

**Comment by liyujiang-gzu** [comment]
jcenter停止服务了，作者还没迁移到mavenCentral、jitpack之类的仓库

**Comment by liyujiang-gzu** [comment]
See [issues#1376](https://github.com/scwang90/SmartRefreshLayout/issues/1376)

**Comment by scwang90** [comment]
现在可以使用 

io.github.scwang90:refresh-layout-kernel:2.0.5
