### ISSUE TITLE
Header回调中从onStartAnimator到onFinish的间隔时间

### ISSUE THREAD

**Issue by HolenZhou** [scwang90/SmartRefreshLayout#138]
我发现Header回调中从onStartAnimator到onFinish之间固定有间隔1s左右的时间，这个时间可以由开发者来自定义吗，因为有时我并需要这1s的延时，而是希望立即执行onFinish，我在onFinish之中再执行一个简短的结束动画就够了

**Comment by scwang90** [comment]
调用 finishRefresh(0) 就可以了

**Comment by HolenZhou** [comment]
多谢，可以了
