### ISSUE TITLE
新改的依赖地址是什么？能方便贴出来吗？你这边介绍说改了包名，然后自己也更改包名，依赖的话就出错进不了，导致还是只能用旧版本的，能帮忙详细的贴一下？

### ISSUE THREAD

**Issue by huangShan-gitHub** [scwang90/SmartRefreshLayout#1389]
新改的依赖地址是什么？能方便贴出来吗？你这边介绍说改了包名，然后自己也更改包名，依赖的话就出错进不了，导致还是只能用旧版本的，能帮忙详细的贴一下？

**Comment by scwang90** [comment]
io.github.scwang90:refresh-layout-kernel:2.0.5
