### ISSUE TITLE
自动加载更多的问题

### ISSUE THREAD

**Issue by TinhoXu** [scwang90/SmartRefreshLayout#14]
现有的效果是滑动到底部触发加载更多（显示加载更多 footer）。
然后我有一个比较无理取闹的想法，能不能做到即将到底部（剩余未加载 item 数量 或者 剩余可滑动距离），然后回调加载更多（不显示加载更多 footer）？
例如：
前提，启用 RefreshHeader 且 关闭 RefreshFooter（关闭显示效果，不关闭回调）。
场景，一共有100条数据，每次加载20条数据，现在我滑动显示到第15条，这时候去回调加载更多，加载接下来的21-40条数据。

**Comment by scwang90** [comment]
想法不错~

**Comment by AcgnCodeMonkey** [comment]
这样肯定不行，如果网络不好怎么办？

**Comment by TinhoXu** [comment]
@AcgnCodeMonkey 
可以进一步优化成：下拉刷新、自动加载、上拉加载这样的模式。
1、即将到底部（剩余未加载 item 数量 或者 剩余可滑动距离），回调加载更多（不显示加载更多 footer）
2、到达底部，上拉加载，回调加载更多（显示加载更多 footer）

**Comment by LoAlex** [comment]
> 现有的效果是滑动到底部触发加载更多（显示加载更多 footer）。
> 然后我有一个比较无理取闹的想法，能不能做到即将到底部（剩余未加载 item 数量 或者 剩余可滑动距离），然后回调加载更多（不显示加载更多 footer）？
> 例如：
> 前提，启用 RefreshHeader 且 关闭 RefreshFooter（关闭显示效果，不关闭回调）。
> 场景，一共有100条数据，每次加载20条数据，现在我滑动显示到第15条，这时候去回调加载更多，加载接下来的21-40条数据。

我也在找這個方法, 有代碼參考嗎?
