### ISSUE TITLE
autoRefresh刷新的问题

### ISSUE THREAD

**Issue by OrangeAppleFoot** [scwang90/SmartRefreshLayout#1412]
当RecyclerView有数据，并且数据超过一页的时候，我们滑动一段距离的时候后，这个我们调用autoRefresh的时候，我发现RecyclerView和下拉刷新视图会有叠层的问题。

**Comment by scwang90** [comment]
你可以先让 RecyclerView 滚动到顶部，再调用 autoRefresh
