### ISSUE TITLE
依赖下载不下来了 1.X  2.X都下载不下来

### ISSUE THREAD

**Issue by KwunYamShan** [scwang90/SmartRefreshLayout#1421]
//    api 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2'
//    api 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2'
//    implementation 'io.github.scwang90:refresh-layout-kernel:2.0.3' //核心必须依赖
//    implementation 'io.github.scwang90:refresh-header-classics:2.0.3' //经典刷新头
    implementation  'com.scwang.smart:refresh-layout-kernel:2.0.3'      //core
    implementation  'com.scwang.smart:refresh-header-classics:2.0.3'    //ClassicsHeader
都试过了 下载不下来

**Comment by KwunYamShan** [comment]
repositories {
        google()
        jcenter()
}
解决了 需要引入 jcenter库

**Comment by didikee** [comment]
jcenter不是慢慢不用吗，不准备去jitpack么
