### ISSUE TITLE
请问上拉的回弹效果不能单独设置？

### ISSUE THREAD

**Issue by pdog18** [scwang90/SmartRefreshLayout#146]
如果还是没有找到答案，提问请带上这几个必要信息
1.当前使用的版本号
`v1.0.3`
2.
我查看`demo`中`ProfilePracticeActivity`有回弹功能，查看`xml`中配置，发现开启了 
```
app:srlEnablePureScrollMode="true"
app:srlEnableLoadmore="true"
```
我的界面结构是
```
<srl>
  <recyclerview/>
</srl>
```

于是我就在自己的`demo`中增加了相应属性，发现这样就不能触发刷新的操作，列表中没有数据。
我的demo中有个列表想要有上拉的回弹功能，但是上拉加载的实现没有用到`srl`，而是通过自己实现的`adapter`来触发刷新的。

但是如果`app:srlEnablePureScrollMode="true"`修改为`false`的话，就会有`srl`库默认的`footer`显示。
所以想问下，上拉的回弹效果只能通过开启上拉加载来实现？而不是单独开启？

**Comment by scwang90** [comment]
使用 FalsifyFooter

**Comment by pdog18** [comment]
谢谢，我加上去以后发现有时上拉刷新完毕后，还有一块区域存在与列表的下方(覆盖在列表之上)。

**Comment by scwang90** [comment]
这样写
~~~xml
<SmartRefreshLayout
        app:srlEnableLoadmore="true"
        app:srlFooterMaxDragRate="0.9">
      <RecyclerView/>
        <FalsifyFooter
            android:layout_width="match_parent"
            android:layout_height="100dp"/>
</SmartRefreshLayout>
~~~

**Comment by pdog18** [comment]
谢谢这么快就回复了，
我试试，我还以为是finishRefresh（）里面的delayed 的问题，尝试了下在postdelayed之前removecallbacks (runnable)，也不行

想请问下作者大大DelayedRunable这个类有什么特殊作用吗？

重写postDelayed这个有点看不太懂，我再跟一下

**Comment by pdog18** [comment]
还是有一点点小问题，在快速上拉加载的时候会出现。
另外我如果Java代码中全局设置了下拉刷新，然后xml中只设置上拉加载footer布局这个时候，下拉刷新会没有，同时上拉加载的footer变成默认的下拉刷新样式


 描述一下我现在的情况哈~
我的设置：

我使用了smart的下拉刷新功能，自定义下拉刷新的header
没有使用smart的上拉加载，上拉加载由自己的adapter来实现
在入口处静态代码块全局设置了下拉刷新的header（已经修改为xml中设置）
在xml中设置了上拉加载的footer布局

现在的效果：
在上拉的时候会弹性的效果，但是在多次快速上拉的时候，有时弹性效果会滞留在Smart的下方（形成一块白色区域，区域大小和第二次回弹高度有关），然后又迅速消失

有可能我第二次上拉时第一次任务还未结束？（但是第二次上拉的时候第一次回弹动画已经结束了）

**Comment by flztsj** [comment]
包含FalsifyFooter.java的版本发布了吗？

**Comment by pdog18** [comment]
什么？ FalsifyFooter 不是一直就有吗？
package com.smartlayout.layout.footer;

**Comment by scwang90** [comment]
1.0.4-alpha-0

**Comment by scwang90** [comment]
@pdog18 当前的版本结局你的问题需要在 Xml 中定义 FalsifyFooter 才可以
~~~xml
<SmartRefreshLayout
        app:srlEnableLoadmore="true"
        app:srlFooterMaxDragRate="0.9">
      <RecyclerView/>
        <FalsifyFooter
            android:layout_width="match_parent"
            android:layout_height="100dp"/>
</SmartRefreshLayout>
~~~
