### ISSUE TITLE
WeiboPracticeActivity 微博列表 “留言” “关注”按钮设置点击事件被拦截

### ISSUE THREAD

**Issue by s3hengwu** [scwang90/SmartRefreshLayout#147]
“留言” “关注”按钮设置点击事件被拦截。
怎么获取点击事件？
 findViewById(R.id.attention1).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(v.getContext(), "111", Toast.LENGTH_LONG).show();
            }
        });

**Comment by scwang90** [comment]
新版 demo apk 已经上传，重新下载 按照 demo 书写代码就可以啦

**Comment by s3hengwu** [comment]
我想知道哪里不同。

**Comment by scwang90** [comment]
代码是你写的，不同的话你要自己比较，你问我也不知道~
