### ISSUE TITLE
7.0上出现的纸飞机Header画面丢失的问题

### ISSUE THREAD

**Issue by chengzhijun0706** [scwang90/SmartRefreshLayout#148]
这个问题只在7.0上出现,其他的没有问题,就是当刷新的时候原有的纸飞机的飞翔路径丢失了
![image](https://user-images.githubusercontent.com/13751034/29697125-cf18a92c-897f-11e7-92fc-6e9cf3bad835.png)
这是刷新中的
![image](https://user-images.githubusercontent.com/13751034/29697191-33915f16-8980-11e7-9010-46e9078375c6.png)
未刷新和刷新完成是正常的
![image](https://user-images.githubusercontent.com/13751034/29697209-5bced634-8980-11e7-8532-dcb8b74d0941.png)
只是刷新的时候路径丢失

**Comment by scwang90** [comment]
谢谢反馈
