### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by oeager** [scwang90/SmartRefreshLayout#15]
几天前关注到这个项目的时候，发现虽然效果不错，但是刷新时列表不能操作，就没太放心上。但是才几天过去，作者就优化掉这个问题了，点赞！
个人提点体验上的建议：
1.刷新时，刷新中这个状态，现在只能向上回退滚动，而不能继续向下拉然后回弹回刷新中的位置。若能像qq一样能刷新中继续下拉回弹就更赞了.
2.加载更多，当没有更多数据时，只有快速滚动时的回弹，而不能继续上拉。
3.加载更多，没有更多数据时，一般的产品会在末项追加一条“没有更多数据”这种footer。目前好像Refreshfooter收回了，只有在列表多加一种viewtype才能实现，若能直接让Refreshfooter不收回，显示这个状态就更棒了.

**Comment by scwang90** [comment]
谢谢你的反馈，你的提议很不错，已经加入开发计划中

**Comment by scwang90** [comment]
1.0.2-alpha-2 已经发布，你提出的宝贵建议已经完成
