### ISSUE TITLE
Failed to resolve: com.scwang.smart:refresh-layout-kernel

### ISSUE THREAD

**Issue by HugMua** [scwang90/SmartRefreshLayout#1504]
![image](https://user-images.githubusercontent.com/44063390/219849536-8b3c33e0-9b92-4080-9fa1-32ba57e08438.png)

AndroidStudio升级到电鳗版本，编译提示Failed to resolve，请问怎么解决啊？
项目有按要求配置以下这些：
implementation 'androidx.appcompat:appcompat:1.4.0'
android.useAndroidX=true
android.enableJetifier=true
jcenter()

**Comment by HugMua** [comment]
QQ帮助群都没人理的，把2.0.5改成2.0.3解决了。

**Comment by qianshengta** [comment]
我也是同样的问题，在2.0.5找不到库，但是2.0.3就可以

**Comment by qianshengta** [comment]
刚发现的，他依赖地址变了，你看下你地址该了没

**Comment by heianxiyi** [comment]
新的依赖地址是啥

**Comment by scwang90** [comment]
jcenter 需要使用阿里的镜像地址，或者使用最新版本就不需要了
