### ISSUE TITLE
内嵌recyclerview滑动冲突

### ISSUE THREAD

**Issue by NFLeo** [scwang90/SmartRefreshLayout#151]
描述：目前两个项目在调试，一个内嵌recyclerview不会冲突，另一个项目会冲突，冲突体现在下拉刷新，上拉加载不会。

解决：给recyclerview添加滑动监听，在滑动监听事件中设置可下拉刷新时机，如下：
int topRowVerticalPosition = (recyclerView == null || recyclerView.getChildCount() == 0) ? 0 : recyclerView.getChildAt(0).getTop();

refreshLayout.setEnableRefresh(topRowVerticalPosition == 0);

**Comment by scwang90** [comment]
自己解决了就好了
