### ISSUE TITLE
上下箭头的图标与加载的图标重叠 

### ISSUE THREAD

**Issue by liguangze** [scwang90/SmartRefreshLayout#1518]
第一次下拉没有问题，第二次就会出现这个问题
版本是1.0.0，
辛苦看一下，感谢开源

![WechatIMG124](https://github.com/scwang90/SmartRefreshLayout/assets/10549682/2871e550-2bf5-49d7-ae18-cc93412ac9ab)

**Comment by scwang90** [comment]
老版本不再维护，请使用新版本
