### ISSUE TITLE
顶部header部分空白，不消失，再次下拉就好了

### ISSUE THREAD

**Issue by haegyeong** [scwang90/SmartRefreshLayout#153]
当下拉刷新未完成时，切换页面，再切换回来时，顶部header部分空白，不消失，再次下拉就好了，这个bug怎么修复，已经等不及下个版本了，求赐教解决方法

**Comment by scwang90** [comment]
使用 1.0.4-alpha-0 版本

**Comment by haegyeong** [comment]
可以了，请收下双膝
