### ISSUE TITLE
没有material 的footer吗

### ISSUE THREAD

**Issue by sing1** [scwang90/SmartRefreshLayout#1530]

**Comment by sing1** [comment]
有大哥写好的吗？不想写了，有头没有尾或者不协调好难受，找个轮子，求求大哥们了

**Comment by liangjingkanji** [comment]
这辈子也没见过Material的上拉刷新Footer,  因为谷歌官方认为上拉刷新都是预加载不需要动画

**Comment by scwang90** [comment]
查看demo首页的三个页面，底部的 footer 是可以使用 header 替换的
