### ISSUE TITLE
上传到maven仓库的v2.0.6包不对

### ISSUE THREAD

**Issue by woniu163** [scwang90/SmartRefreshLayout#1532]
v2.0.6版本中SmartRefreshLayout类里面还有support的依赖，但是看v2.0.6的修改记录，是迁移到androidX了，所以严重怀疑maven仓库里面上传的包不是正确的v2.0.6的包

**Comment by Tan-Tshunglee** [comment]
![image](https://github.com/scwang90/SmartRefreshLayout/assets/6026909/de821513-5682-45e0-9b91-47c87e80af11)
是的，看起来上传到maven的代码还是老的

**Comment by Tan-Tshunglee** [comment]
![image](https://github.com/scwang90/SmartRefreshLayout/assets/6026909/9d0a6101-c36a-4e9e-aa83-1aaccb5a7d9b)
kan看起来是上传的代码是旧的

**Comment by weinierfei** [comment]
@scwang90 大佬，Maven上的代码跟库里的不一样呢。麻烦您抽空看看什么问题？

**Comment by qiuqiutang** [comment]
2.1.0 导的包也存在android.support.v4

**Comment by Orchid-Lee** [comment]
If you use AndroidX, add it to gradle.properties

android.useAndroidX=true
android.enableJetifier=true

**Comment by woniu163** [comment]
@Orchid-Lee I know what you said, but such a configuration will lead to a longer compilation time. My projects have no support package anymore, and I think it will be faster to compile projects by migrating all of them instead of using the configuration you recommended

**Comment by scwang90** [comment]
最新版 3.x 已经却换至 androidx
