### ISSUE TITLE
SmartRefreshLayout 2.06版本没法自定义列表头和尾

### ISSUE THREAD

**Issue by Mrjincheng** [scwang90/SmartRefreshLayout#1539]
@RestrictTo({LIBRARY,LIBRARY_GROUP,SUBCLASSES}) 
    int onFinish(@NonNull RefreshLayout refreshLayout, boolean success);
onFinish 被限制访问了 如果自定义下拉列表的头和尾那

**Comment by BTFTUK** [comment]
我也遇到了，看了他里面代码 继承了SimpleComponent 解决

**Comment by scwang90** [comment]
参考 demo 代码中的Header自定义： com.scwang.refreshlayout.activity.example.CustomExampleActivity.ClassicsHeader
