### ISSUE TITLE
2.0.6版本，onRefresh之后，马上调用finishRefresh，recyclerView点击无法响应

### ISSUE THREAD

**Issue by huihui4045** [scwang90/SmartRefreshLayout#1540]
smartRefreshLayout.setOnRefreshListener(new OnRefreshListener() {
            @Override
            public void onRefresh(@NonNull RefreshLayout refreshLayout) {
                smartRefreshLayout.finishRefresh();
            }
        });
onRefresh之后，马上调用finishRefresh，此时动画未关闭之前，recyclerView点击无法响应

**Comment by scwang90** [comment]
问题已修复，2.1.0 版本发布
