### ISSUE TITLE
refresh会重置loadmore设置的状态？

### ISSUE THREAD

**Issue by Elmagnifico12** [scwang90/SmartRefreshLayout#1543]
v1.1.0 看起来在下拉触发了onrefresh后 上一次在loadmore中设置的finishLoadMoreWithNoMoreData()会失效，在上拉的时候又会出现加载更多。 这两个状态可以分开判断吗？

**Comment by Elmagnifico12** [comment]
版本1.1.0 如果by design 有没有方法区分这两个状态呢？

**Comment by scwang90** [comment]
刷选的时候如果确定没有更多数据可以使用  finishRefreshWithNoMoreData
