### ISSUE TITLE
无法刷新的问题

### ISSUE THREAD

**Issue by 2391645784** [scwang90/SmartRefreshLayout#156]
在Fragment中刷新，动画未结束时切换到其他Fragment在快速切换回来，布局一直存在，虽然会出现刷新动画但不再执行刷新或加载更多的方法。

**Comment by scwang90** [comment]
1.0.4-alpha-0 已经修复

**Comment by 2391645784** [comment]
这样啊 1.0.4 正式版什么时候发布啊
