### ISSUE TITLE
2.1.0版本 空指针异常

### ISSUE THREAD

**Issue by mobilewhj** [scwang90/SmartRefreshLayout#1567]
bugly上报出java.lang.NullPointerException: Attempt to invoke interface method 'com.scwang.smart.refresh.layout.api.RefreshKernel com.scwang.smart.refresh.layout.api.RefreshKernel.onAutoRefreshAnimationEnd(android.animation.Animator, boolean)' on a null object reference这种异常，机型有vivo，oppo，realme，三星，没有其他类型手机，云机没复现。有遇见的大佬解决了的吗？

**Comment by BananaHuo** [comment]
遇到了

**Comment by mobilewhj** [comment]
> 怎么解决的，回退版本吗

没有，按照demo创建个对象执行构造方法，然后在xml中使用，给有问题的手机还在复现中。

**Comment by scwang90** [comment]
问题已经解决，新版本已经发布
