### ISSUE TITLE
master版本ClassicsHeader设置文字大小

### ISSUE THREAD

**Issue by JakeHao** [scwang90/SmartRefreshLayout#157]
![image](https://user-images.githubusercontent.com/16833509/30015100-e21e21aa-9181-11e7-9894-fa7d113153fa.png)

**Comment by scwang90** [comment]
有什么问题吗？

**Comment by JakeHao** [comment]
如果xml设置了文字大小，这里没有获取xml设置的文字大小，还是固定的。
![image](https://user-images.githubusercontent.com/16833509/30017512-1b1ac5bc-918c-11e7-8f42-45a95db40ddf.png)

**Comment by scwang90** [comment]
写了，已经修改提交
