### ISSUE TITLE
V2.1.0版本，demo案例，使用官方主题下拉刷新操作的时候，视图不可以滑动，但是响应点击，v2.0.6，v2.0.5没有这样的问题

### ISSUE THREAD

**Issue by CMzhizhe** [scwang90/SmartRefreshLayout#1576]
描述如题。
  在V2.1.0 未修改过如下配置
  refreshLayout.setDisableContentWhenRefresh(false);//是否在刷新的时候禁止列表的操作
  refreshLayout.setDisableContentWhenLoading(false);//是否在加载的时候禁止列表的操作

希望可以恢复在下拉刷新的时候，依旧可以滚动视图的操作。

**Comment by scwang90** [comment]
新版本已经解决，或者拉取最新的代码

**Comment by CMzhizhe** [comment]
邮箱已经收到
