### ISSUE TITLE
Failed to resolve: com.scwang.smartrefresh:SmartRefreshLayout:1.1.3

### ISSUE THREAD

**Issue by benedictcontawe** [scwang90/SmartRefreshLayout#1581]
I have already clean build ang sync build but can't able to fix the issue

**Comment by benedictcontawe** [comment]
> I have already clean build ang sync build but can't able to fix the issue
any updates

**Comment by vinhhoang2402** [comment]
I just added maven { url 'https://maven.aliyun.com/repository/jcenter' } and it worked for me.

**Comment by scwang90** [comment]
添加兼容仓库

        maven { url 'https://maven.aliyun.com/repository/google' } // 兼容旧版 google
        maven { url 'https://maven.aliyun.com/repository/jcenter' } // 兼容旧版 jcenter

**Comment by YueHua46** [comment]
> 添加兼容仓库
> 
> ```
>     maven { url 'https://maven.aliyun.com/repository/google' } // 兼容旧版 google
>     maven { url 'https://maven.aliyun.com/repository/jcenter' } // 兼容旧版 jcenter
> ```

very helpful.
