### ISSUE TITLE
关于上拉加载和viewpage2等多个可滑动布局的滑动冲突问题

### ISSUE THREAD

**Issue by lnzz123** [scwang90/SmartRefreshLayout#1582]
viewpage2加载的列表没有滑动到底就触发上拉加载了
我的布局层次结构大概是这样
SmartRefreshLayout
--ClassicsHeader
--CoordinatorLayout
----CollapsingToolbarLayout
------ViewPager2
----ViewPager2(RecyclerView)
--BallPulseFooter

https://github.com/user-attachments/assets/959819d1-3004-4f72-9b37-d182a936f106

**Comment by scwang90** [comment]
这种情况需要在内部使用 Adpter 的方法实现加载更多功能，或者需要把 Smart 放在 ViewPager2 的内部，可以参考demo 的嵌套滚动示例
