### ISSUE TITLE
main分支代码 编译app模块代码一直报错 报错的这些依赖是不是早就过时了？？？

### ISSUE THREAD

**Issue by lollo54851** [scwang90/SmartRefreshLayout#1586]
代码分支:  main
运行环境：
Android Studio Ladybug | 2024.2.1 Patch 2
Build #AI-242.23339.11.2421.12550806, built on October 25, 2024
Runtime version: 21.0.3+-79915917-b509.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  GsonOrXmlFormat (2.0)
  GsonFormatPlus (1.6.1)
  Dart (242.22855.32)
  wu.seal.tool.jsontokotlin (3.7.5)
  io.flutter (82.1.3)

报错信息：
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.flyco.roundview:FlycoRoundView_Lib:1.1.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/flyco/roundview/FlycoRoundView_Lib/1.1.4/FlycoRoundView_Lib-1.1.4.pom
       - https://repo.maven.apache.org/maven2/com/flyco/roundview/FlycoRoundView_Lib/1.1.4/FlycoRoundView_Lib-1.1.4.pom
       - https://plugins.gradle.org/m2/com/flyco/roundview/FlycoRoundView_Lib/1.1.4/FlycoRoundView_Lib-1.1.4.pom
       - https://jitpack.io/com/flyco/roundview/FlycoRoundView_Lib/1.1.4/FlycoRoundView_Lib-1.1.4.pom
     Required by:
         project :app
   > Could not find com.github.mmin18:realtimeblurview:1.0.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/mmin18/realtimeblurview/1.0.6/realtimeblurview-1.0.6.pom
       - https://repo.maven.apache.org/maven2/com/github/mmin18/realtimeblurview/1.0.6/realtimeblurview-1.0.6.pom
       - https://plugins.gradle.org/m2/com/github/mmin18/realtimeblurview/1.0.6/realtimeblurview-1.0.6.pom
       - https://jitpack.io/com/github/mmin18/realtimeblurview/1.0.6/realtimeblurview-1.0.6.pom
     Required by:
         project :app
   > Could not find com.wang.avi:library:2.1.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/wang/avi/library/2.1.3/library-2.1.3.pom
       - https://repo.maven.apache.org/maven2/com/wang/avi/library/2.1.3/library-2.1.3.pom
       - https://plugins.gradle.org/m2/com/wang/avi/library/2.1.3/library-2.1.3.pom
       - https://jitpack.io/com/wang/avi/library/2.1.3/library-2.1.3.pom
     Required by:
         project :app
   > Could not find com.youth.banner:banner:1.4.10.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/youth/banner/banner/1.4.10/banner-1.4.10.pom
       - https://repo.maven.apache.org/maven2/com/youth/banner/banner/1.4.10/banner-1.4.10.pom
       - https://plugins.gradle.org/m2/com/youth/banner/banner/1.4.10/banner-1.4.10.pom
       - https://jitpack.io/com/youth/banner/banner/1.4.10/banner-1.4.10.pom
     Required by:
         project :app
   > Could not find jp.wasabeef:recyclerview-animators:2.2.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/jp/wasabeef/recyclerview-animators/2.2.6/recyclerview-animators-2.2.6.pom
       - https://repo.maven.apache.org/maven2/jp/wasabeef/recyclerview-animators/2.2.6/recyclerview-animators-2.2.6.pom
       - https://plugins.gradle.org/m2/jp/wasabeef/recyclerview-animators/2.2.6/recyclerview-animators-2.2.6.pom
       - https://jitpack.io/jp/wasabeef/recyclerview-animators/2.2.6/recyclerview-animators-2.2.6.pom
     Required by:
         project :app

报错截图：
<img width="1168" alt="截屏2024-11-30 11 35 40" src="https://github.com/user-attachments/assets/f54b3dfa-9917-42a4-ab0b-3118d5c02d12">

<img width="1113" alt="error" src="https://github.com/user-attachments/assets/e1b84608-6270-42f0-8885-b07fccf58367">

**Comment by scwang90** [comment]
maven { url 'https://maven.aliyun.com/repository/google' } // 兼容旧版 google
        maven { url 'https://maven.aliyun.com/repository/jcenter' } // 兼容旧版 jcenter
        
        尝试添加兼容仓库
