### ISSUE TITLE
嵌套滚动事件冲突

### ISSUE THREAD

**Issue by aTesla** [scwang90/SmartRefreshLayout#159]
1.把下面的布局放在Activity里面：  
  <android.support.design.widget.CoordinatorLayout
        android:id="@+id/coordinator_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/app_bar_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.design.widget.CollapsingToolbarLayout
                android:id="@+id/collapsing_toolbar_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:expandedTitleMarginEnd="64dp"
                app:expandedTitleMarginStart="48dp"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                <ImageView
                    android:id="@+id/iv_gallery"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:contentDescription="@null"
                    android:scaleType="centerCrop"
                    app:layout_collapseMode="parallax"
                    app:layout_collapseParallaxMultiplier="0.7" />

                
                <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="#111111"
                    app:contentInsetStart="0dp"
                    app:layout_collapseMode="pin"
                    app:layout_scrollFlags="scroll|enterAlways">

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:gravity="center_vertical">

                        <TextView
                            android:id="@+id/tv_begin"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:layout_alignParentLeft="true"
                            android:layout_centerVertical="true"
                            android:gravity="center"
                            android:lines="1"
                            android:paddingLeft="15dp"
                            android:paddingRight="15dp"
                            android:textColor="#fff"
                            android:textSize="15sp"
                            android:textStyle="normal"
                            android:visibility="visible" />

                        <TextView
                            android:id="@+id/tv_center"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_centerInParent="true"
                            android:layout_gravity="center"
                            android:layout_toLeftOf="@+id/tv_end"
                            android:layout_toRightOf="@+id/tv_begin"
                            android:gravity="center"
                            android:lines="1"
                            android:maxLines="1"
                            android:textColor="#fff"
                            android:textSize="17sp"
                            android:textStyle="normal"
                            android:visibility="visible"
                            tools:text="" />

                        <TextView
                            android:id="@+id/tv_end"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:layout_alignParentRight="true"
                            android:layout_centerVertical="true"
                            android:gravity="center_vertical"
                            android:maxLines="1"
                            android:paddingLeft="15dp"
                            android:paddingRight="15dp"
                            android:textColor="#fff"
                            android:textSize="15sp"
                            android:textStyle="normal"
                            android:visibility="visible"
                            tools:drawableRight="@mipmap/ic_launcher" />
                    </RelativeLayout>
                </android.support.v7.widget.Toolbar>
            </android.support.design.widget.CollapsingToolbarLayout>

            <android.support.design.widget.TabLayout
                android:id="@+id/bottom_bar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:tabIndicatorColor="#ff374755"
                app:tabIndicatorHeight="1dp"
                app:tabSelectedTextColor="#404040"
                app:tabTextColor="#AAA" />
        </android.support.design.widget.AppBarLayout>

        <android.support.v4.widget.NestedScrollView
            android:id="@+id/nested_scroll_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="fill_vertical"
            android:fillViewport="true"
            android:overScrollMode="never"
            android:scrollbars="none"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <FrameLayout
                android:id="@+id/frame_layout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_behavior="@string/appbar_scrolling_view_behavior" />
        </android.support.v4.widget.NestedScrollView>

        
        <android.support.design.widget.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:layout_marginBottom="75dp"
            android:layout_marginRight="15dp"
            android:visibility="visible" />
    </android.support.design.widget.CoordinatorLayout>
2.然后使用FragmentManager动态添加一个fragment，加20条数据，出现嵌套滑动冲突，下拉刷新不起作用了，怎么办
fragment布局如下
    <FrameLayout
        android:id="@+id/layout_success"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="visible">

        <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/smart_refresh_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <com.scwang.smartrefresh.layout.header.ClassicsHeader
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycler_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:overScrollMode="never"
                android:scrollbars="none"
                app:layoutManager="android.support.v7.widget.LinearLayoutManager" />

            <com.scwang.smartrefresh.layout.footer.ClassicsFooter
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </com.scwang.smartrefresh.layout.SmartRefreshLayout>
    </FrameLayout>

**Comment by scwang90** [comment]
你的布局太复杂，
~~~xml
    <android.support.v4.widget.NestedScrollView
        android:id="@+id/nested_scroll_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="fill_vertical"
        android:fillViewport="true"
        android:overScrollMode="never"
        android:scrollbars="none"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <FrameLayout
            android:id="@+id/frame_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
    </android.support.v4.widget.NestedScrollView>
~~~

参照 demo-apk 简化你的布局

**Comment by genius158** [comment]
@aTesla 滑动事件被NestedScrollView吃掉了
![qq 20170905190252](https://user-images.githubusercontent.com/17870843/30058290-ef19b3d8-926c-11e7-968c-3e92a7643194.png)
