### ISSUE TITLE
NestLayout 滑动效果不是太流畅

### ISSUE THREAD

**Issue by lizhw123** [scwang90/SmartRefreshLayout#16]
<com.scwang.smartrefresh.layout.SmartRefreshLayout>
     <com.scwang.smartrefresh.layout.header.ClassicsHeader>
      <android.support.v4.widget.NestedScrollView>
              <LinearLayout>
                    <ImageView>
                    <android.support.v7.widget.RecyclerView>
              <LinearLayout>
       <android.support.v4.widget.NestedScrollView>
      <com.scwang.smartrefresh.layout.footer.ClassicsFooter>
<com.scwang.smartrefresh.layout.SmartRefreshLayout>

我的布局大概是这个结构，滑动不是太流畅，无法快速滑动。能麻烦你看下吗？

**Comment by scwang90** [comment]
能给一个页面静态截图嘛？我好用你给的代码结构还原你的真实结构

**Comment by lizhw123** [comment]
[Uploading Refresh.zip…]
这是demo，你可以跑起来看看

**Comment by lizhw123** [comment]
[Refresh.zip](https://github.com/scwang90/SmartRefreshLayout/files/1137859/Refresh.zip)
这是demo，你可以跑起来看看

**Comment by lizhw123** [comment]
@scwang90 麻烦你看下demo？

**Comment by scwang90** [comment]
可以的，下班之后抽空看一下

**Comment by AndrWang** [comment]
+1, NestedScrollView那个微博布局换上 RecycleView 发现没那么流畅

**Comment by AndrWang** [comment]
可以试试给 RecycleView 加上这属性setNestedScrollingEnabled(false);

**Comment by lizhw123** [comment]
@AndrWang 给 RecycleView 加上这属性setNestedScrollingEnabled(false);就好了，谢谢你！ @scwang90 已经解决，这是一个很棒的项目，点个赞

**Comment by scwang90** [comment]
@lizhw123 嗯，好的。你的Ddemo我看了。
问题分析是 NestedScrollView 和 RecyclerView 都支持嵌套滚动，冲突了。
感觉你是要给列表加上一个可以滚动的 Header
如果真的是这样，我建议你还是用常规的在Adapter 中去适配 Header
当然直接这样嵌套会简单很多，不过对App的新能会有影响。RecyclerView 没有起到Recycler（回收）功能  

以上观点仅供参考

**Comment by lizhw123** [comment]
@scwang90 谢谢

**Comment by andansky** [comment]
<com.scwang.smartrefresh.layout.SmartRefreshLayout>
<android.support.v4.widget.NestedScrollView>
<android.support.v7.widget.RecyclerView>
<android.support.v4.widget.NestedScrollView>
<com.scwang.smartrefresh.layout.SmartRefreshLayout>
目前发现这种结构有大问题啊，
RecyclerView加载数据越来越多的时候就会越来越卡。
这边监控出来是SmartRefreshLayout的onMesure方法耗时了。
每次添加RecyclerView的数据onMesure就会遍历所有item重新绘制，所以item越多越卡。我去掉NestedScrollView就好了。目前还没想到解决办法~

**Comment by andansky** [comment]
@scwang90
