### ISSUE TITLE
嵌套classicsHeader的布局放到viewpager里面作为fragment无法滑动，不包含嵌套头部正常。

### ISSUE THREAD

**Issue by qssq** [scwang90/SmartRefreshLayout#160]
这样的布局刷新不显示，滚动都滚动不了。

`<?xml version="1.0" encoding="utf-8"?>

<layout xmlns:android="http://schemas.android.com/apk/res/android">

    <data></data>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:descendantFocusability="blocksDescendants"
        android:orientation="vertical">

        <com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/swiperefreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <com.scwang.smartrefresh.layout.header.ClassicsHeader
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:srlClassicsSpinnerStyle="Scale"
                app:srlDrawableArrowSize="20dp"
                app:srlDrawableMarginRight="20dp"
                app:srlDrawableProgress="@drawable/ic_progress_hojder"
                app:srlDrawableProgressSize="20dp"
                app:srlEnableLastTime="true"
                app:srlFinishDuration="500"
                app:srlTextSizeTime="10dp"
                app:srlTextSizeTitle="16sp"
                app:srlTextTimeMarginTop="2dp"

                >

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recyclerview"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />

            </com.scwang.smartrefresh.layout.header.ClassicsHeader>

        </com.scwang.smartrefresh.layout.SmartRefreshLayout>
    </LinearLayout>

</layout>
`

**Comment by scwang90** [comment]
你的布局写错了，不能刷新很正常，请参考 demo-apk 使用 和 详细阅读文档

**Comment by qssq** [comment]
嗯，我眼瞎，你的demo是没有包裹。
