### ISSUE TITLE
建议 RefreshHeader的实现类有很多有getProgressView,建议给这些实现类再弄一个共性接口

### ISSUE THREAD

**Issue by qssq** [scwang90/SmartRefreshLayout#161]
这样我就可以定义一个工具类，统一根据类型强转 修改主题样式.

**Comment by qssq** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by scwang90** [comment]
getProgressView 并不是每个 Header 都有。不会添加

**Comment by scwang90** [comment]
在遇到问题请加QQ群，不要在这里发

**Comment by qssq** [comment]
很多有，你可以弄多个接口，这样可以统一修改不是

**Comment by scwang90** [comment]
只是个别有，不会添加
