### ISSUE TITLE
上拉加载更多，底部footer效果不佳

### ISSUE THREAD

**Issue by ysemylord** [scwang90/SmartRefreshLayout#165]
上拉加载更多时，加载完毕后，效果是先显示加载完的内容，再隐藏footer,这样看起来footer会把加载出来的内容遮住一部分
视频地址http://vm.tudou.com/video/list

**Comment by scwang90** [comment]
这是 有意这么设计的，如果不喜欢请查看属性文档，关闭该功能

**Comment by ysemylord** [comment]
是将回弹时间设置为0吗?refreshLayout.setReboundDuration

**Comment by ysemylord** [comment]
是将回弹时间设置为0吗?refreshLayout.setReboundDuration

**Comment by scwang90** [comment]
setEnableScrollContentWhenLoaded
