### ISSUE TITLE
当未联网，数据为空，再联网，上拉再下拉

### ISSUE THREAD

**Issue by xiayu98020214** [scwang90/SmartRefreshLayout#167]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:srlFixedHeaderViewId="@+id/filter_layout"
    app:srlEnablePreviewInEditMode="false"
    >

    <com.scwang.smartrefresh.layout.header.ClassicsHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:srlClassicsSpinnerStyle="FixedBehind"/>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/diver">

        <include layout="@layout/filter_layout"></include> 

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clipToPadding="false"
            android:paddingTop="43dp"
            tools:listitem="@android:layout/simple_list_item_1"/>

        <include layout="@layout/emptyview"/> //没有数据显示

        <include layout="@layout/no_net_refresh"></include>  //没有网络，显示
    </FrameLayout>

</com.scwang.smartrefresh.layout.SmartRefreshLayout>

用的recyclerview
1.断网，显示数据为空的界面。
2.联网，刷新有新数据。
3.上拉到底，加载更多。
4. 下拉的时候, 马上就出现刷新的view, 其实还有没到第一个数据。

**Comment by scwang90** [comment]
不要把其他布局放在 刷新内，本库只支持列表数据内容

**Comment by xiayu98020214** [comment]
谢谢，大神
