### ISSUE TITLE
刷新时GL error:  Out of memory！

### ISSUE THREAD

**Issue by kobebryantwx** [scwang90/SmartRefreshLayout#168]
1.0.3版本，使用ClassicsHeader，有时刷新头部显示的时候（刷新头部显示时间很长的时候容易出现），出现E/OpenGLRenderer: GL error:  Out of memory!信息一直打印，关闭头部后log不再打印。求解，谢谢。

**Comment by scwang90** [comment]
你的APP内存占用太高了，注意优化就好了
