### ISSUE TITLE
RefreshContentWrapper里面的onScroll方法里面死循环调用layout.autoLoadmore(0, 1);

### ISSUE THREAD

**Issue by tanghongbin** [scwang90/SmartRefreshLayout#169]
布局使用的是SmartRefreshLayout包裹ClassicsHeader,ListView,ClassicsFooter,加载数据完成后添加到adapter然后再调用finishLoadmore方法，就会在RefreshContentWrapper里面的onScroll方法里面死循环调用layout.autoLoadmore(0, 1);

**Comment by scwang90** [comment]
更新到版本 1.0.4-alpha-1 解决问题
