### ISSUE TITLE
Android Studio Xml 编辑器中无法预览 效果

### ISSUE THREAD

**Issue by wareine** [scwang90/SmartRefreshLayout#170]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:overScrollMode="never" />
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

**Comment by wshx21** [comment]
兄弟过分了~，自定义的控件要啥子预览哦
