### ISSUE TITLE
上拉加载footer默认消失动画可否增加可定制的属性？

### ISSUE THREAD

**Issue by HolenZhou** [scwang90/SmartRefreshLayout#179]
上拉加载更多的footer在默认情况下消失时，是一个类似slide out类型的动画，往下滑到屏幕底部消失的，可否增加一个指定这里的动画的属性呢，因为我希望footer可以直接消失掉，或者淡出，而不是slide out类似的动画。

**Comment by scwang90** [comment]
这个不行
