### ISSUE TITLE
当多布局的recycler第一个item设置为隐藏的时候，无法刷新

### ISSUE THREAD

**Issue by wumingXL** [scwang90/SmartRefreshLayout#181]
布局代码如下
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <LinearLayout
        android:id="@+id/item_parent"
        android:layout_width="@dimen/x750"
        android:layout_marginTop="@dimen/y20"
        android:layout_height="wrap_content"
        android:background="@color/colorWhite"
        android:orientation="vertical">

        <com.bjttsx.study.view.CustomDrawableTextView
            xmlns:app="http://schemas.android.com/apk/res-auto"
            style="@style/home_title_style"
            android:text="热门课程"
            app:imageHeight="@dimen/y30"
            app:imageWidth="@dimen/y30"
            app:leftImage="@mipmap/ic_home_plan"/>

        <android.support.v7.widget.RecyclerView
            android:layout_marginTop="@dimen/y32"
            android:layout_marginLeft="@dimen/x20"
            android:layout_marginRight="@dimen/x20"
            android:id="@+id/course_hot_recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

    </LinearLayout>
</LinearLayout>    

隐藏代码如下
View mView =  itemView.findViewById(R.id.item_parent);
        if (mView != null) {
            if (courseBean.isVisibility()) {
                mView.setVisibility(View.VISIBLE);
            } else {
                mView.setVisibility(View.GONE);
            }
       }
请忽略代码质量0.0，只有第一个条目为隐藏的时候才不显示，目前没有找到原因。

**Comment by scwang90** [comment]
这个问题时 recycler 再隐藏之后，边界判断功能异常导致的，所以目前没有找到解决办法

推荐的解决方案:再第一个Item外部包一层 Layout，隐藏的时候隐藏原来内部的 Layout
这样对于 recycler 来说Item数量就不会改变，只是第一项的子Layout 隐藏之后，高度变成0，不会就不会出现那个异常

**Comment by wumingXL** [comment]
才发现我的布局放少了
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent">
    <LinearLayout
        android:id="@+id/item_parent"
        android:layout_width="@dimen/x750"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.bjttsx.study.view.CustomDrawableTextView
            xmlns:app="http://schemas.android.com/apk/res-auto"
            style="@style/home_title_style"
            android:text="最新学习计划"
            app:imageHeight="@dimen/y30"
            app:imageWidth="@dimen/y30"
            app:leftImage="@mipmap/ic_home_plan"/>

        <android.support.v7.widget.RecyclerView
            android:layout_marginTop="@dimen/y32"
            android:layout_marginLeft="@dimen/x20"
            android:layout_marginRight="@dimen/x20"
            android:id="@+id/plan_recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
    </LinearLayout>
</FrameLayout>
那你的意思是在LinearLayout中再加一层吗，因为我现在没有用最外层的布局去显示隐藏，已经包裹了一层

**Comment by wumingXL** [comment]
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent">
    <LinearLayout
        android:id="@+id/item_parent"
        android:layout_width="@dimen/x750"
        android:layout_height="match_parent"
        android:orientation="vertical">
为什么总是放不全，这次放上面半截

**Comment by wumingXL** [comment]
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent">
    <LinearLayout
        android:id="@+id/item_parent"
        android:layout_width="@dimen/x750"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.bjttsx.study.view.CustomDrawableTextView
            xmlns:app="http://schemas.android.com/apk/res-auto"
            style="@style/home_title_style"
            android:text="最新学习计划"
            app:imageHeight="@dimen/y30"
            app:imageWidth="@dimen/y30"
            app:leftImage="@mipmap/ic_home_plan"/>

        <android.support.v7.widget.RecyclerView
            android:layout_marginTop="@dimen/y32"
            android:layout_marginLeft="@dimen/x20"
            android:layout_marginRight="@dimen/x20"
            android:id="@+id/plan_recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
    </LinearLayout>
</FrameLayout>
奇怪了布局放几次都只出现一半
我现在已经包裹了1层，你的意思是在LinearLayout中再包裹一层吗

**Comment by wumingXL** [comment]
<?xml version="1.0" encoding="utf-8"?>
------------
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent">
-----------------
    <LinearLayout
        android:id="@+id/item_parent"
        android:layout_width="@dimen/x750"
        android:layout_height="match_parent"
        android:orientation="vertical">
-------------------
        <com.bjttsx.study.view.CustomDrawableTextView
            xmlns:app="http://schemas.android.com/apk/res-auto"
            style="@style/home_title_style"
            android:text="最新学习计划"
            app:imageHeight="@dimen/y30"
            app:imageWidth="@dimen/y30"
            app:leftImage="@mipmap/ic_home_plan"/>

        <android.support.v7.widget.RecyclerView
            android:layout_marginTop="@dimen/y32"
            android:layout_marginLeft="@dimen/x20"
            android:layout_marginRight="@dimen/x20"
            android:id="@+id/plan_recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
    </LinearLayout>
---------------
</FrameLayout>
奇怪，我的布局总是只显示一半
我现在已经包裹一层，你的意思是再LinearLayout再包裹一层吗

**Comment by wumingXL** [comment]
代码显示了一半zaiLinearLayout外部有一层FrameLayout为根布局，我控制的是LinearLayout

**Comment by scwang90** [comment]
我自己测试了，一下，并没有发现你说的问题，如果你无法解决，还好尝试其他思路，不要使用 隐藏的这种方法
