### ISSUE TITLE
在Fragment中刷新不成功

### ISSUE THREAD

**Issue by 1762588562** [scwang90/SmartRefreshLayout#183]
使用ViewPager+TabLayout，viewPager中有两个Fragment，两个都使用了这个库，但是只有第一个下拉刷新有效，在第二个Fragment中，下拉刷新还是执行的第一个Fragment的下拉刷新的逻辑，这种冲突怎解决呢？

**Comment by flztsj** [comment]
在ViewPager里面每个页面使用刷新布局

**Comment by scwang90** [comment]
参考 主页 apk-demo 的用法
