### ISSUE TITLE
底部有Bar的情况，ClassicsFooter设置bottomMargin无法实现再Bar之上出现刷新View

### ISSUE THREAD

**Issue by flztsj** [scwang90/SmartRefreshLayout#184]
看了下onLayout的相关代码：

        if (mRefreshFooter != null) {
            final View footerView = mRefreshFooter.getView();
            final LayoutParams lp = (LayoutParams) footerView.getLayoutParams();
            final SpinnerStyle style = mRefreshFooter.getSpinnerStyle();
            int left = lp.leftMargin;
            int top = lp.topMargin + getMeasuredHeight();

            if (isInEditMode
                    || style == SpinnerStyle.FixedFront
                    || style == SpinnerStyle.FixedBehind) {
                top = top - mFooterHeight;
            } else if (style == SpinnerStyle.Scale || style == SpinnerStyle.Translate) {
                top = top - Math.max(Math.max(-mSpinner, 0) - lp.topMargin, 0); // 这边应该考虑下加上  + lp.bottomMargin
            }

            int right = left + footerView.getMeasuredWidth();
            int bottom = top + footerView.getMeasuredHeight();
            footerView.layout(left, top, right, bottom);
        }

**Comment by flztsj** [comment]
实现的效果如下

![screenshot_1505792144](https://user-images.githubusercontent.com/5946178/30574773-c332bfb8-9d2e-11e7-8ffa-95988b7bf0c5.png)

**Comment by scwang90** [comment]
谢谢你的反馈，问题已修复，下一个版本会更新
