### ISSUE TITLE
保留加载更多功能前提下，如何能让加载更多的时候拉到底部不因为滑动惯性自动加载？

### ISSUE THREAD

**Issue by summersrest** [scwang90/SmartRefreshLayout#185]
请问一下，如何能保留加载更多功能，并且不会拉到底部直接加载？
设置了app:srlEnableAutoLoadmore="false"之后，加载更多功能也不能用了，加上app:srlEnableLoadmore="true"也不行。

**Comment by scwang90** [comment]
srlEnableLoadmoreWhenContentNotFull=true
app:srlEnableLoadmore="true"
app:srlEnableAutoLoadmore="false"

应该没问题，你使用的是那个版本？

**Comment by summersrest** [comment]
加上app:srlEnableLoadmoreWhenContentNotFull=true这个属性以后，我找到原因了，因为我把recyclerview外层嵌套了一个RelativeLayout导致的。如果直接用SmartRefreshLayout嵌套recyclerview，是OK的。建议大神在文档里面加上说明，省的别人和我踩一样的坑。不过加app:srlEnableAutoLoadmore="false"没有影响。
