### ISSUE TITLE
公式 y = M(1-40^(-x/H))

### ISSUE THREAD

**Issue by ice-coffee** [scwang90/SmartRefreshLayout#186]
在`SmartRefreshLayout`类的`moveSpinnerInfinitely`方法里的`Math.min(M * (1 - Math.pow(100, -x / H)), x);// 公式 y = M(1-40^(-x/H))`

公式y = M(1-40^(-x/H))获取的值代表什么

**Comment by scwang90** [comment]
通过这个公式计算，可以计算出经过阻尼效果之后的Y坐标，去掉这个公式的话将失去阻尼效果

**Comment by ice-coffee** [comment]
好的, 感谢
