### ISSUE TITLE
滑动到底部自动加载更多的时候，如果最后一项高度较高，会自动多次调用加载更多

### ISSUE THREAD

**Issue by fishwjy** [scwang90/SmartRefreshLayout#19]
滑动到底部自动加载更多的时候，如果最后一项高度较高，会自动多次调用加载更多且自动上滑（当然这是为了让最后一项完全显示出来），直到最后一项完全显示出来，自动加载才会停止。
我有录屏但是这里没上传附件的功能
总体来说，这个刷新框架做的相当牛逼

**Comment by fishwjy** [comment]
总体来说，这个刷新框架做的相当牛逼

**Comment by scwang90** [comment]
谢谢你的反馈，我会好好从处理这个问题

**Comment by fishwjy** [comment]
[自动加载更多.mp4.zip](https://github.com/scwang90/SmartRefreshLayout/files/1140650/mp4.zip)

**Comment by scwang90** [comment]
谢谢，我研究之后会解决这个问题的

**Comment by scwang90** [comment]
问题已经解决，请使用 1.0.2-alpha-4 版本
