### ISSUE TITLE
关闭上拉加载后，回弹效果跟随消失

### ISSUE THREAD

**Issue by yuki-ryoko** [scwang90/SmartRefreshLayout#190]
当前使用版本号: 1.0.3，Header 和 Footer 均为经典。
====
我希望单独使用下拉刷新，关闭上拉加载。但关闭上拉加载后，回弹效果会跟随消失。请问应该如何设置以保留回弹？
谢谢作者的库，很好用 ( ﾟ∀ﾟ)

**Comment by scwang90** [comment]
不要敢比上啦加载功能，设置加载完成就可以，看常见问题
