### ISSUE TITLE
对于设置刷新时间，能否提供个直接设置字符串的方法

### ISSUE THREAD

**Issue by jyh149129** [scwang90/SmartRefreshLayout#196]
很好的库，谢谢作者！
比如我现在想显示为 “最后更新时间：xx分钟之前”，而setLastUpdateTime要的是Date类型参数，我如何弄？

**Comment by jyh149129** [comment]
已经直接设置TextView了，classicsHeader.getLastUpdateText().setText（。。）
但这样当下拉显示出来不放手的时候，显示的还是日期类型。。。

**Comment by scwang90** [comment]
下载 demo 参考 使用
