### ISSUE TITLE
嵌套ListVeiw 在靠近顶部下拉，并未先把ListView下拉

### ISSUE THREAD

**Issue by ytsxg123** [scwang90/SmartRefreshLayout#197]
![1506917120 1](https://user-images.githubusercontent.com/22367186/31063968-44244228-a76a-11e7-88a5-b11745ff4998.jpg)

**Comment by scwang90** [comment]
你需要自定义滚动边界，看属性文档

**Comment by haomini** [comment]
同样发现在一个老项目的聊天界面 使用的SmartRefreshLayout+ListView, 我这边问题出现的原因是listView设置了smoothScrollBar=false, 设置smoothScrollBar=true后, 问题得以解决.
