### ISSUE TITLE
关于滑动事件冲突的一个小问题

### ISSUE THREAD

**Issue by changshuai0512** [scwang90/SmartRefreshLayout#200]
楼主你好，感谢您的开源精神。
我在使用的时候，发现一个小问题：就是WebView模仿qq微信有背景：“网页有XXX.com提供”的时候，如果H5内部有一些向下滑动的控件，比如说从底下弹出滑动选择框，上下滑动这样的控件，整个页面也会跟着下拉。楼主能否解决一下呢？

**Comment by scwang90** [comment]
这个要从 WebVIew 内部的 HTml解决  java 代码无能为力
