### ISSUE TITLE
上拉刷新后页面定位的问题

### ISSUE THREAD

**Issue by zfdang** [scwang90/SmartRefreshLayout#201]
SmartRefreshLayout里嵌了一个RecyclerView，当滚动到页面底部是，上拉加载下一页。

现在的问题是，上拉、加载都没有问题，但是加载完后，新的一页，内容不是在最顶部，而是滚动了一小点。这个是什么问题呢？

我现在的解决方法是，加载完了之后，再延时一段时间，然后自动上滚一些距离。

**Comment by scwang90** [comment]
看属性文档

**Comment by zfdang** [comment]
哪个属性啊？

**Comment by scwang90** [comment]
设置 为 false

**Comment by zfdang** [comment]
这个根本就不算解决方案，因为这样设置的话，上拉刷新的提示就和正常内容搅和在一起了，效果非常差！

**Comment by zfdang** [comment]
即使这样设置之后，也能明显看出来有一个往上滚动的操作。能直接在加载的时候就定好位置，而不用再滚动么？

**Comment by scwang90** [comment]
你使用的方法不对，请下载 demo 参考操作
