### ISSUE TITLE
上拉加载更，列表多滚动问题

### ISSUE THREAD

**Issue by DaisyJin1** [scwang90/SmartRefreshLayout#203]
［现象］上拉加载，在加载中时，列表上滚，底部“ClassicsFooter”会保持在页面底部，和列表UI重叠。
［问题］怎样可以保持“ClassicsFooter”随着列表的滚动看不见？
［期望］上拉加载，和上拉刷新的“ClassicsHeader”效果一样，随着滚动，“正在加载...”布局可以消失不见
![image](https://user-images.githubusercontent.com/29156312/31426562-6e4e345e-ae96-11e7-9f53-df49c5c780bb.png)
＝＝＝＝＝＝＝＝＝＝＝＝＝
［代码设置如下］
 //设置 Header
        refreshLayout.setRefreshHeader(new ClassicsHeader(this).setEnableLastTime(false).setFinishDuration(0));
       
   //设置 Footer
        refreshLayout.setRefreshFooter(new ClassicsFooter(this).setFinishDuration(0));
refreshLayout.setOnRefreshLoadmoreListener(new OnRefreshLoadmoreListener() {
            @Override
            public void onLoadmore(RefreshLayout refreshlayout) {
                //上拉加载数据
            }

            @Override
            public void onRefresh(RefreshLayout refreshlayout) {
                //下拉刷新加载数据
            }
        });

**Comment by scwang90** [comment]
已经Q群解决

**Comment by zgs94328** [comment]
怎么解决的？
