### ISSUE TITLE
关于RecyclerView + MultiAdapter 下拉刷新的过程中事件冲突问题

### ISSUE THREAD

**Issue by wsf5918** [scwang90/SmartRefreshLayout#206]
首先非常感谢楼主提供这么好的工具。有一些问题我想反馈一下。关于RecyclerView + MultiAdapter 下拉刷新的过程中事件冲突问题
发现在使用SmartRefreshLayout的过程中，
最外层是如下：
![image](https://user-images.githubusercontent.com/5617446/31535165-a0e780a8-afbf-11e7-8686-c50be589778d.png)

另外使用了MultiTypeAdapter 内部有一个 
![image](https://user-images.githubusercontent.com/5617446/31535213-df7dff4a-afbf-11e7-8de1-3738c3f8caa4.png)

而这个小视图里面，又有一个小RecyclerView

![image](https://user-images.githubusercontent.com/5617446/31535268-223341e2-afc0-11e7-8d13-8abb0763f038.png)

内部Item的布局如下所示：
![image](https://user-images.githubusercontent.com/5617446/31535293-3c63c212-afc0-11e7-9c90-24aee7d1a174.png)

最后发现，下拉的事件冲突拉。

楼主可以试一下。

**Comment by HeyMouser** [comment]
我也遇到一个下拉冲突的问题，我的情况是这样的：在SmartRefreshLayout里面嵌套recyclerview，recyclerview的第一个item的布局是特殊的，根据得到的数据来判断是否显示第一个item，当第一个item设置隐藏的时候，这时候就不能下拉刷新了，相反就可以正常下拉刷新

**Comment by wsf5918** [comment]
@scwang90 有时间一起看看哈。

**Comment by scwang90** [comment]
@wsf5918 关闭 内部 RecyclerView 的嵌套滚动
@HeyMouser 用一个布局包裹你要隐藏的 item ，然后隐藏内部的 item ，布局 自适应为 0

**Comment by wsf5918** [comment]
@scwang90 已经修复了。谢谢。
