### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by gsc1234567890woshishui** [scwang90/SmartRefreshLayout#209]
Could not find class 'com.scwang.smartrefresh.layout.impl.RefreshContentWrapper$Api23ViewScrollComponent', referenced from method com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.setupComponent

**Comment by gsc1234567890woshishui** [comment]
运行在api  手机上报错！运行在7.0可以

**Comment by scwang90** [comment]
用 1.0.4 的版本吧
