### ISSUE TITLE
上拉加载更多的几种模式

### ISSUE THREAD

**Issue by mianjuhou** [scwang90/SmartRefreshLayout#21]
1.上拉到底部并且要拉动一段距离才触发加载
2.上拉到内容的最后一个条目时自动触发加载更多
3.上拉到倒数第n个条目时自动加载更多
第1类可以设置触发距离，第2类最后一个条目可以是内容的最后一个也可以是本控价的正在加载条目
第3类可以设置触发加载的倒数条目数还是滚动条滚动到达的比例
上面三类各有优点适用于不同的场景。

**Comment by scwang90** [comment]
你好，你提出的 三条中  1，2条现在已经实现，
现在默认是你的 第二条的情况
如果要变成第一条的情况，可以 setEnableAutoLoadmore(false) 就可以了

第三条，我会考虑添加

**Comment by joker-fu** [comment]
@scwang90 第三个实现了么 没找到方法
