### ISSUE TITLE
在fragment中与CoordinatorLayout结合

### ISSUE THREAD

**Issue by zengcanxiang** [scwang90/SmartRefreshLayout#210]
如题，下面一种布局，当在fragment中和Activity中表现不一致。在fragment中，完全不能滑动，不只是不能下拉刷新，连recyclerView都不能滑动了，但是在Activity中却不存在这个情况。
```java
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
      省略 没有影响
    </android.support.design.widget.AppBarLayout>

    <am.widget.stateframelayout.StateFrameLayout
        android:id="@+id/base_state_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        app:sflState="loading">
        <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/base_fragment_data_refresh"
            android:id="@+id/base_fragment_data_refresh"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:srlEnableNestedScrolling="true">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/base_fragment_data_list"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:overScrollMode="never" />
        </com.scwang.smartrefresh.layout.SmartRefreshLayout>
    </am.widget.stateframelayout.StateFrameLayout>
</android.support.design.widget.CoordinatorLayout>
```
如果把StateFrameLayout布局替换成  NestedScrollView，在fragment中就能滑动了。
但是，之前是使用的TwinklingRefreshLayout，把他更换回来，同样的布局，却没有这个情况。初步，查看代码，应该是NestedScroll机制没有兼容好，但是具体问题在那，还没发现，反馈给作者。

**Comment by scwang90** [comment]
需要开启潜逃滚动功能

**Comment by zengcanxiang** [comment]
@scwang90 在上述布局，无论是将srlEnableNestedScrolling=true还是false,都是无效的

**Comment by zengcanxiang** [comment]
@scwang90 调整位置试了一下，没有效果。在Activity中还是能刷新，滑动。而fragment中就不行。而且如果在SmartRefreshLayout外面套上一个NestScrollView，就都不能滑动了。 

StateFrameLayout是 ```  compile 'am.widget:stateframelayout:2.0.2' ``` ，原理就是一个帧布局，继承FrameLayout，显示不同状态下的布局。  

为了防止他有影响，我吧stateFrameLayout屏蔽，只留下了SmartRefreshLayout和RecyclerView，也还是
存在Activity中可以滑动，fragment中不能滑动的现象。

我看了一下，就是fragment所在的Activity的布局是CoordinatorLayout+NestedScrollView布局，fragment就存在Activity中的NestedScrollView中，然后fragment里又有CoordinatorLayout布局，会不会是这个有影响，现在去试一试。

**Comment by zengcanxiang** [comment]
![deepinscreenshot_select-area_20171018113105](https://user-images.githubusercontent.com/16033497/31699847-d8ed39fc-b3f7-11e7-8e34-245849fe3b07.png)
如图 将布局屏蔽只留下了SmartRefreshLayout 也还是存在Activity中可以，fragment中不可以的情况。两个类的布局，代码什么的都是一样的。。。。

**Comment by zengcanxiang** [comment]
![deepinscreenshot_select-area_20171018113105](https://user-images.githubusercontent.com/16033497/31699861-fc1713a8-b3f7-11e7-9e4d-7ea3a1ea82cc.png)

**Comment by zengcanxiang** [comment]
测试屏蔽大部分的控件。只留下了SmartRefreshLayout，但是还是存在Activity中可以，fragment中不可以的问题

**Comment by scwang90** [comment]
看了你的分析似乎是 fragment 引起的，但是 demo 中有十多个页面都是 fragment ，没有有不能刷新的问题，你可以下载demo看看demo中fragment 的代码，也建议你检查一下你 fragment 的初始化代码，而且之前也有很多用户都在 fragment 中使用刷新，并没有遇到不能刷新的问题。

**Comment by zengcanxiang** [comment]
@scwang90 现在表现为一下拉就会抛出日志  I/System.out: skip!。但是如果使用 autoRefresh() 能够有作用。

**Comment by zengcanxiang** [comment]
@scwang90 我在源码环境中测试，比较TwinklingRefreshLayout.把实现的NestedScrollingParent给删除了，就可以了。。。。

**Comment by zengcanxiang** [comment]
在最新的源码版本下，没有删除NestedScrollingParent好像也可以了。期待最新的正式版本在试一下

**Comment by conscious01** [comment]
搞了两天好不容易搞出个demo来，结果移植到项目里的fragment里发现竟然用不了！ 楼主是怎么解决的

**Comment by zengcanxiang** [comment]
@conscious01 在java代码中recyclerView.setNestedScrollingEnabled相关方法最好不要手动调用，其他的跟着文档接入就很简单了

**Comment by conscious01** [comment]
可以加个IM方式请教吗

**Comment by zengcanxiang** [comment]
@conscious01 你可以查看一下我的MVP-Practice-Project-Template项目里面的DataListActivity
