### ISSUE TITLE
滑动冲突

### ISSUE THREAD

**Issue by chenxi0203** [scwang90/SmartRefreshLayout#211]
SmartRefreshLayout 包裹RecyclerView 添加广告轮播控件后，当滑动图片进入最后一张图片时，下拉刷新列表完成，在滑动轮播控件，（设置轮播控件手动滑动，或者自动滑动时间隔时间延长确保刷新完成过程种图片还没滑动）能滑动到第一张图片，滑动到第二张图片就滑动不了啦，再次滑动就又可以啦，也就是说中间有一次是滑动没响应的，轮播控件用的demo中的，下拉样式是经典样式，头部跟随下拉。  部分代码截图：  
![6](https://user-images.githubusercontent.com/20221278/31698576-c8909a14-b383-11e7-81e6-1568055f4546.png)
![7](https://user-images.githubusercontent.com/20221278/31698577-c8c10c30-b383-11e7-8b5b-d7d3c6e8c19f.png)

**Comment by scwang90** [comment]
你这个问题无法重现啊

**Comment by chenxi0203** [comment]
提供的demo修改样式后就有这个问题。

**Comment by scwang90** [comment]
什么样式？
