### ISSUE TITLE
纸飞机动画在华为荣耀8上无效，看不到动画效果

### ISSUE THREAD

**Issue by 392354412** [scwang90/SmartRefreshLayout#213]
Android版本：7.0
EMUI版本：5.0.1
飞行的动画不可见

**Comment by scwang90** [comment]
谢谢你的反馈，刚好我没有这边没有荣耀手机，无法解决问题。还有纸飞机的源代码来自
https://github.com/race604/FlyRefresh
你可以去这里通知原作者
