### ISSUE TITLE
嵌套 webview的问题

### ISSUE THREAD

**Issue by jyh149129** [scwang90/SmartRefreshLayout#217]
嵌套了一个webview实现下拉刷新，页面比较长的时候，滑动一段距离后，在页面任意地方下拉都会触发下拉刷新。。。不知道是页面问题还是bug

**Comment by scwang90** [comment]
页面问题

**Comment by lizhw123** [comment]
@jyh149129

**Comment by lizhw123** [comment]
@scwang90

**Comment by lizhw123** [comment]
解决了，让HTML告诉APP webview是否到顶，然后在下拉刷新。希望对大家有用。

        mRefreshLayout.setScrollBoundaryDecider(new ScrollBoundaryDecider() {
            @Override
            public boolean canRefresh(View content) {
                //webview滚动到顶部才可以下拉刷新
                return TextUtils.equals(canReload, "1");
            }

            @Override
            public boolean canLoadmore(View content) {
                return false;
            }
        });

**Comment by jaime1990** [comment]
> 解决了，让HTML告诉APP webview是否到顶，然后在下拉刷新。希望对大家有用。
> 
> ```
>     mRefreshLayout.setScrollBoundaryDecider(new ScrollBoundaryDecider() {
>         @Override
>         public boolean canRefresh(View content) {
>             //webview滚动到顶部才可以下拉刷新
>             return TextUtils.equals(canReload, "1");
>         }
> 
>         @Override
>         public boolean canLoadmore(View content) {
>             return false;
>         }
>     });
> ```

您好，通过这种方式实现后，发现webview里输入框无法调起软键盘输入了。请问怎么解决呢？
