### ISSUE TITLE
在极端环境下会出现这个问题。。。

### ISSUE THREAD

**Issue by fuyifang** [scwang90/SmartRefreshLayout#219]
java.lang.IndexOutOfBoundsException
Inconsistency detected. Invalid item position 0(offset:1).state:7
com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:233)

**Comment by fuyifang** [comment]
详细Log:


android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
--
2 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
3 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
4 android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
5 android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
6 android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
7 android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
8 android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
9 android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
10 android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
11 android.view.View.layout(View.java:18799)
12 android.view.ViewGroup.layout(ViewGroup.java:5952)
13 com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:233)
14 com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:664)
15 android.view.View.layout(View.java:18799)
16 android.view.ViewGroup.layout(ViewGroup.java:5952)
17 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
18 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
19 android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
20 android.view.View.layout(View.java:18799)
21 android.view.ViewGroup.layout(ViewGroup.java:5952)
22 android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
23 android.view.View.layout(View.java:18799)
24 android.view.ViewGroup.layout(ViewGroup.java:5952)
25 android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
26 android.view.View.layout(View.java:18799)
27 android.view.ViewGroup.layout(ViewGroup.java:5952)
28 android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
29 android.view.View.layout(View.java:18799)
30 android.view.ViewGroup.layout(ViewGroup.java:5952)
31 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
32 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
33 android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
34 android.view.View.layout(View.java:18799)
35 android.view.ViewGroup.layout(ViewGroup.java:5952)
36 android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
37 android.widget.FrameLayout.onLayout(FrameLayout.java:261)
38 android.view.View.layout(View.java:18799)
39 android.view.ViewGroup.layout(ViewGroup.java:5952)
40 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
41 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
42 android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
43 android.view.View.layout(View.java:18799)
44 android.view.ViewGroup.layout(ViewGroup.java:5952)
45 android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
46 android.widget.FrameLayout.onLayout(FrameLayout.java:261)
47 android.view.View.layout(View.java:18799)
48 android.view.ViewGroup.layout(ViewGroup.java:5952)
49 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
50 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
51 android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
52 android.view.View.layout(View.java:18799)
53 android.view.ViewGroup.layout(ViewGroup.java:5952)
54 android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
55 android.widget.FrameLayout.onLayout(FrameLayout.java:261)
56 com.android.internal.policy.DecorView.onLayout(DecorView.java:822)
57 android.view.View.layout(View.java:18799)
58 android.view.ViewGroup.layout(ViewGroup.java:5952)
59 android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2627)
60 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2343)
61 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502)
62 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044)
63 android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
64 android.view.Choreographer.doCallbacks(Choreographer.java:702)
65 android.view.Choreographer.doFrame(Choreographer.java:638)
66 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
67 android.os.Handler.handleCallback(Handler.java:751)
68 android.os.Handler.dispatchMessage(Handler.java:95)
69 android.os.Looper.loop(Looper.java:154)
70 android.app.ActivityThread.main(ActivityThread.java:6646)
71 java.lang.reflect.Method.invoke(Native Method)
72 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
73 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by scwang90** [comment]
这个并非是 smart 的bug

**Comment by PrometNexus** [comment]
这个问题据说是google的锅，recyclerviewer就有这个问题，一般说是列表数据有变化了但没立即更新列表，手动立即调用notifyDataSetChanged()可以避免
