### ISSUE TITLE
使用模块部分崩溃

### ISSUE THREAD

**Issue by daitu-liang** [scwang90/SmartRefreshLayout#22]
给的demo apk   使用模块，  DefaultCenter  XMLDefine CodeDfine三个条目进入完成正在加载更多，就崩溃。
测试手机，乐视1s, android 6.0

**Comment by scwang90** [comment]
谢谢，正在解决中

**Comment by scwang90** [comment]
问题已经解决，下载最新版本 Demo APK

**Comment by ll418718** [comment]
github上也更新了吗？

**Comment by scwang90** [comment]
是的，刷新网页，下载 Demo就可以得到最新的 版本

**Comment by ll418718** [comment]
好的，谢谢
