### ISSUE TITLE
您好，我遇到一个嵌套滑动的问题

### ISSUE THREAD

**Issue by sea5241** [scwang90/SmartRefreshLayout#220]
您好，当我嵌套一个可以上下滑动的子view，然后SmartRefresh滑动到底部，这时只能触发上拉加载更多，子view无法向上滑动，如果不滑动到底部是正常的

**Comment by scwang90** [comment]
你的描述过于简单，无法解决你的问题

**Comment by sea5241** [comment]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlPrimaryColor="@color/colorPrimary"
        app:srlAccentColor="@android:color/white"
        app:srlEnableHeaderTranslationContent="true"
        app:srlEnableLoadmore="true">
        <com.scwang.smartrefresh.header.CircleHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
        <ScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                android:gravity="bottom">
                <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="800dp"/>
                <com.aigestudio.wheelpicker.WheelPicker
                    android:id="@+id/wheelpicker"
                    android:layout_width="123dp"
                    android:layout_height="117dp"
                    aigestudio:wheel_atmospheric="true"
                    aigestudio:wheel_curved="false"
                    aigestudio:wheel_cyclic="false"
                    aigestudio:wheel_indicator="true"
                    aigestudio:wheel_indicator_color="#13000000"
                    aigestudio:wheel_indicator_size="1.5dp"
                    aigestudio:wheel_item_align="right"
                    aigestudio:wheel_item_text_color="#FF4B4B4B"
                    aigestudio:wheel_item_text_size="11.5sp"
                    aigestudio:wheel_selected_item_text_color="#FF7A7A7A"
                    aigestudio:wheel_visible_item_count="5"/>
            </LinearLayout>
        </ScrollView>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>


您好，我在里面嵌套了一个自定义的模仿iphone可以滑动的时间选择器WheelPicker，它是在最底部的，当我整个页面没有滑动到最底部的时候，这个WheelPicker是可以向上滑动选择的，当整个页面滑动到最底部，再向上滑动这个WheelPicker，就只能触发上拉加载更多，不能滑动这个WheelPicker，是SmartRefreshLayout滑动到最底部的时候就把事件全部拦截了吗？

**Comment by scwang90** [comment]
你可以设置 srlEnableLoadmore=“false” 关闭上拉加载，但是如果上啦加载也是你必须的功能，这个冲突时必然存在的，实在不行你可以换其他的刷新库试试

**Comment by sea5241** [comment]
多谢

**Comment by sea5241** [comment]
public static boolean canScrollDown(View targetView, MotionEvent event) {
        if (canScrollDown(targetView) && targetView.getVisibility() == View.VISIBLE) {
            return true;
        }
        if (targetView instanceof ViewGroup && event != null) {
            ViewGroup viewGroup = (ViewGroup) targetView;
            final int childCount = viewGroup.getChildCount();
            PointF point = new PointF();
            for (int i = 0; i < childCount; i++) {
                View child = viewGroup.getChildAt(i);
                if(isTransformedTouchPointInView(viewGroup, child, event.getX(), event.getY(), point)&&child instanceof WheelPicker){
                    return true;
                }
                if (isTransformedTouchPointInView(viewGroup, child, event.getX(), event.getY(), point)) {
                    event = MotionEvent.obtain(event);
                    event.offsetLocation(point.x, point.y);
                    return canScrollDown(child, event);
                }
            }
        }
        return false;
    }

试着在这里加了如果滑动区域在我这个控件内就禁止SmartRefreshLayout滑动貌似可以临时解决

**Comment by sea5241** [comment]
`public static boolean canScrollDown(View targetView, MotionEvent event) {
        if (canScrollDown(targetView) && targetView.getVisibility() == View.VISIBLE) {
            return true;
        }
        if (targetView instanceof ViewGroup && event != null) {
            ViewGroup viewGroup = (ViewGroup) targetView;
            final int childCount = viewGroup.getChildCount();
            PointF point = new PointF();
            for (int i = 0; i < childCount; i++) {
                View child = viewGroup.getChildAt(i);
                if(isTransformedTouchPointInView(viewGroup, child, event.getX(), event.getY(), point)&&child instanceof WheelPicker){
                    return true;
                }
                if (isTransformedTouchPointInView(viewGroup, child, event.getX(), event.getY(), point)) {
                    event = MotionEvent.obtain(event);
                    event.offsetLocation(point.x, point.y);
                    return canScrollDown(child, event);
                }
            }
        }
        return false;
    }`

**Comment by scwang90** [comment]
如果通过这个改动可以解决，建议你使用 自定义滚动边界方法，判断边界，不用去改 smart 的源码

**Comment by leon2017** [comment]
@sea5241 
`//解决事件分发的冲突
    private float startY;
    private float startX;
    // 记录viewPager是否拖拽的标记
    private boolean mIsVpDragger;

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        int action = ev.getAction();
        switch (action) {
            case MotionEvent.ACTION_DOWN:
                // 记录手指按下的位置
                startY = ev.getY();
                startX = ev.getX();
                // 初始化标记
                mIsVpDragger = false;
                break;
            case MotionEvent.ACTION_MOVE:
                // 如果viewpager正在拖拽中，那么不拦截它的事件，直接return false；
                if(mIsVpDragger) {
                    setEnableRefresh(false);
                    return false;
                }

                // 获取当前手指位置
                float endY = ev.getY();
                float endX = ev.getX();
                float distanceX = Math.abs(endX - startX);
                float distanceY = Math.abs(endY - startY);
                // 如果X轴位移大于Y轴位移，那么将事件交给viewPager处理。
                if(distanceX > mTouchSlop && distanceX > distanceY) {
                    setEnableRefresh(false);
                    mIsVpDragger = true;
                    return false;
                }
                //重新打开下拉刷新
                new Handler().post(new Runnable() {
                    @Override
                    public void run() {
                        setEnableRefresh(true);
                    }
                });
                break;
            case MotionEvent.ACTION_UP:
            case MotionEvent.ACTION_CANCEL:
                //重新打开下拉刷新
                new Handler().post(new Runnable() {
                    @Override
                    public void run() {
                        setEnableRefresh(true);
                    }
                });
                // 初始化标记
                mIsVpDragger = false;
                break;
        }
        // 如果是Y轴位移大于X轴，事件交给swipeRefreshLayout处理。
        return super.onInterceptTouchEvent(ev);
    }`
