### ISSUE TITLE
demo中的整体滑动解决方法，不太友好，类：NestedScrollUsingFragmentIntegral

### ISSUE THREAD

**Issue by guominfang** [scwang90/SmartRefreshLayout#221]
如题，NestedScrollUsingFragmentIntegral的使用方式，滑动小于一半，回滚顶部。活动大于一半，滑动到下一个view顶部

**Comment by scwang90** [comment]
这个效果和 smart 是没有关系的，并不由 smart 控制，是内容自己控制的，并不是bug或者设计问题
