### ISSUE TITLE
上拉加载更多问题

### ISSUE THREAD

**Issue by tikeyc** [scwang90/SmartRefreshLayout#222]
我的是ListView
如果我第一页的数据显示不够超过整个屏幕，此时无法上拉滑动出现上拉加载更多（我这一页数据服务器就是返回这几条）
后来我把第一页的数据重复添加到listView上，当数据超过整个屏幕才会出现上拉加载更多。
我希望的时候只要设置了loadMore为true就一直可以上拉。

**Comment by scwang90** [comment]
你已经自行解决，值得嘉奖
