### ISSUE TITLE
关于主题改变问题

### ISSUE THREAD

**Issue by Deepblue1996** [scwang90/SmartRefreshLayout#225]
不知道为什么,不管我怎么改,好像主题都不会变,预览这样子,实际真机是白底,灰字
![image](https://user-images.githubusercontent.com/16926380/32112247-4b58e2c4-bb6f-11e7-87f1-7e93675dd046.png)
![image](https://user-images.githubusercontent.com/16926380/32112258-551364ce-bb6f-11e7-827e-ef3b0d396a3d.png)

**Comment by Deepblue1996** [comment]
尝试refreshLayout.setPrimaryColorsId(R.color.black, android.R.color.white);仍然失败,1.0.3稳定版

**Comment by scwang90** [comment]
主题颜色请使用 app:srlPrimaryColor 代替 background
