### ISSUE TITLE
setOnLoadmoreListener出错为什么

### ISSUE THREAD

**Issue by dengxingwen** [scwang90/SmartRefreshLayout#23]
`refreshLayout.setOnLoadmoreListener(new OnLoadmoreListener() {
            @Override
            public void onLoadmore(SmartRefreshLayout refreshlayout) {
                refreshlayout.finishLoadmore(2000);
            }
        });`
提示OnLoadmoreListener方法不是抽象的

**Comment by scwang90** [comment]
可以贴出 错误的堆栈信息吗？

**Comment by dengxingwen** [comment]
SmartRefreshLayout 换成RefreshLayout可以了

**Comment by dengxingwen** [comment]
Error:(80, 70) 错误: <匿名com.mark.appmark.FragmentHome$4>不是抽象的, 并且未覆盖OnLoadmoreListener中的抽象方法onLoadmore(RefreshLayout)

我安装教程写的出错，把加载更多的方法里面的SmartRefreshLayout 换成RefreshLayout可以了

**Comment by scwang90** [comment]
谢谢你的提醒，文档太老了，我更新一下
