### ISSUE TITLE
怎么主动去调用onRefresh（）方法

### ISSUE THREAD

**Issue by 596861134** [scwang90/SmartRefreshLayout#230]
我项目里面有个滑动冲突，所以想在滑动到某段距离的时候去主动触发onRefresh（）方法刷新，我应该怎么实现，在线等 谢谢

**Comment by scwang90** [comment]
autoRefresh

**Comment by 596861134** [comment]
我知道这个方法，刷新是刷新了，但是顶部刷新动画不出来

**Comment by scwang90** [comment]
不出来的话是bug，你加群，把你的效果视屏和代码截图发到群里
