### ISSUE TITLE
requestDisallowInterceptTouchEvent 这个处理看不懂

### ISSUE THREAD

**Issue by wanderJA** [scwang90/SmartRefreshLayout#233]
![image](https://user-images.githubusercontent.com/28772019/32314632-cbbf5038-bfe3-11e7-9b14-1042e8b5f5a8.png)
只有嵌套子布局可以决定父布局是否可以分发。
我现在ViewPager嵌套SmartRefreshLayout，嵌套的View需满足条件才能阻止父类的滑动。
不理解用意啊，，，需要一个更好的场景解释一下

**Comment by scwang90** [comment]
这段代码来自谷歌官方的 SwipeRefreshLayout 
应用场景已经在英文注释中解释清楚
大部分第三方下拉刷新库都保留了这段代码，本库也不例外
