### ISSUE TITLE
SDK 27 无法自动加载更多，并且上拉之后整个卡顿,后续中断

### ISSUE THREAD

**Issue by iota9star** [scwang90/SmartRefreshLayout#234]
如题，在最新的sdk上，无法加载更多，如图，演示视频传不上来，下面那个无法返回，无法消失，且整个视图滑动卡顿
无论是最新的1.0.4 -a9 还是稳定1.0.3皆是如此
![screenshot_20171105-104322](https://user-images.githubusercontent.com/21272154/32411498-b49540f4-c216-11e7-9e78-0c380f1dde25.png)

**Comment by scwang90** [comment]
我给 demo 源码切换从 api-27 了，并且使用 api-27模拟器运行，但是没有重现到这个问题，能否提供一下你的源码（有保密协议的话，可否写一个能重现这个问题的 demo ）我这边用于调试 解决问题。

**Comment by iota9star** [comment]
呃，这是写着耍的小玩意儿，只是现在没法儿了，我昨天全部改成了tkrefreshlayout，尴尬，主要是那个浪费了我一天多时间，我各种尝试都做了，代码和我以前一模一样都不行，感觉日了狗了，我使用的是kotlin开发。。。我很喜欢这个库，但是不行，真是日了狗了

**Comment by aheven** [comment]
我也遇见了这个问题，不知道是不是因为kotlin的原因，感觉应该没有很大的关系。

**Comment by iota9star** [comment]
@aheven 我最开始直接使用id，后面改成findById还是不行，最后各种方法都试了还是不行，只有换成其他了

**Comment by scwang90** [comment]
@aheven 可以提供你的代码，方便我调试解决问题吗？

**Comment by iota9star** [comment]
@scwang90 请问，新讨论群在吗？我这儿有录的视频，可以发出来

**Comment by scwang90** [comment]
@aheven 视频就不用了，要代码或者 demo
