### ISSUE TITLE
自动加载更多问题

### ISSUE THREAD

**Issue by iugg21** [scwang90/SmartRefreshLayout#237]
我现在的需求就是下拉刷新需要有回弹动画，而加载更多不需要回弹动画
该库好像只提供一种方法setReboundDuration（）设置回弹动画时长的，对下拉刷新和加载更多是一起生效的

**Comment by scwang90** [comment]
你可能需要使用 1.0.4 最新预览版
如果不能满足的话你只能 用子类继承 SmartRefreshLayout ，去写死 footer 的 时间为0
