### ISSUE TITLE
关于自定义PhoenixHeader问题

### ISSUE THREAD

**Issue by Kasail** [scwang90/SmartRefreshLayout#238]
很喜欢这个刷新动画，想要自己动手改一下里面的画风，看了阵子源代码，真正会改的也就颜色= =，其他的相关源码看了挺多还是头大，想知道这种String格式的path路径如何写，或者作者大大不嫌麻烦的话，能否也说一下这个Header的敲码思路呢？  盼回QAQ

**Comment by scwang90** [comment]
我也只是Phoenix的代码搬运工而已，Phoenix的源码地址是，你可以到这里看看
https://github.com/Yalantis/Phoenix
