### ISSUE TITLE
xml 里找不到这个srlEnablePureScrollMode属性

### ISSUE THREAD

**Issue by AndrWang** [scwang90/SmartRefreshLayout#24]
发现com.scwang.smartrefresh:SmartRefreshLayout:1.0.1里面确实没有这个属性

**Comment by scwang90** [comment]
srlEnablePureScrollMode 是在新版本里面的，请使用 
com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-3

**Comment by AndrWang** [comment]
确定不是com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-1?3你们有发布?

**Comment by scwang90** [comment]
正在发布中，马上就好了，
com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-1 是可以的

**Comment by AndrWang** [comment]
OK, 谢了

**Comment by AndrWang** [comment]
微博 CoordinatorLayout 这个 demo 中怎么样用图片作为toolbar 的背景...

**Comment by scwang90** [comment]
toolbar  和  AppBarLayout 的背景设为透明，在下面放置一张图片就可以了
