### ISSUE TITLE
能否实现滑动的时候固定某个View在顶部

### ISSUE THREAD

**Issue by souja** [scwang90/SmartRefreshLayout#240]
这个View一开始在中间位置，向上滚动到顶部时固定。
类似于CollapsingToolbarLayout的属性app:layout_collapseMode="pin"

或者这个功能已经有了？麻烦贴个使用方法，感谢。

**Comment by scwang90** [comment]
可以的，请下载 demo ->实战->微博列表

**Comment by souja** [comment]
我下载看过哈，demo里微博那个是一开始就在顶部固定住的，不是我所描述的一开始在中间，然后滚动到顶部再固定。
而且我代码里试过哈，设置固定的view的id的话，那个view一开始就会固定到顶部去，即便我layout里把view是放在中间位置，运行后它一开始就跑到顶部去了

**Comment by scwang90** [comment]
你说的这个功能喝 下拉刷新没有关系，需要自己实现

**Comment by zhenghengZN** [comment]
@scwang90  这个功能在拖动被固定住的顶部控件的时候会触发下拉刷新，这个要怎么解决

**Comment by scwang90** [comment]
@zhenghengZN 可以自己自定义滚动边界

**Comment by zhenghengZN** [comment]
@scwang90 能说下在哪改吗，我有点看不懂源码

**Comment by scwang90** [comment]
@zhenghengZN  不用改，是正常的设置，去看属性文档

**Comment by zhenghengZN** [comment]
好

**Comment by scwang90** [comment]
你可以这样写
~~~java
refreshLayout.setScrollBoundaryDecider(new ScrollBoundaryDeciderAdapter() {
            @Override
            public boolean canRefresh(View content) {
                return !ScrollBoundaryUtil.canScrollUp(listview);
            }
        });//设置滚动边界判断
~~~
