### ISSUE TITLE
alpha-12问题

### ISSUE THREAD

**Issue by Alex861** [scwang90/SmartRefreshLayout#246]
设置srlEnableLoadmore属性为false时，向上拉好像会出现默认的加载的foot(三个白色圆点)；设置srlEnableFooterTranslationContent为false时，中间内容不能上拉，但是刷新头的顶部会出现几个像素的横向空白区域

**Comment by scwang90** [comment]
这是1.0.4仿苹果新功能，可以关闭的

**Comment by Alex861** [comment]
设置srlEnableOverScrollDrag 为false去掉底部弹性效果，白点没有了，谢谢大神
