### ISSUE TITLE
怎么拿到手指正在下拉的方法

### ISSUE THREAD

**Issue by 1226362423** [scwang90/SmartRefreshLayout#249]
我用的是最新版本

**Comment by pandans** [comment]
下啦加载更多有bug。下啦然后释放不会自动加载，提示释放立即加载，需要再拉一下才能够开始加载

**Comment by scwang90** [comment]
@1226362423 使用多功能监听器，可以监听到手指下拉
@pandans 需要详细的信息才可以帮你 请跳转到 #73

**Comment by 1226362423** [comment]
谢谢
