### ISSUE TITLE
REFRESH_BOTTOM_PULLUP = "上拉加载更多"

### ISSUE THREAD

**Issue by dadakkk** [scwang90/SmartRefreshLayout#25]
这些提示语如果能配置就更好了

**Comment by scwang90** [comment]
可以的，直接在APP初始化的地方

ClassicsFooter.REFRESH_FOOTER_PULLUP = “XXXXXX”

请使用最新版本 
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-3'
