### ISSUE TITLE
你好,大神

### ISSUE THREAD

**Issue by tulongchao** [scwang90/SmartRefreshLayout#251]
代码如下
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <View
                android:layout_width="match_parent"
                android:layout_height="200dp"
                android:background="#ff0000"
                app:layout_scrollFlags="scroll|enterAlwaysCollapsed" />

            <Button
                android:id="@+id/button"
                android:layout_width="match_parent"
                android:layout_height="100dp"
                android:background="#0059ff"
                android:text="Hello" />
        </android.support.design.widget.AppBarLayout>

        <com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:apps="http://schemas.android.com/apk/res-auto"
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            apps:srlDisableContentWhenLoading="false"
            apps:srlEnableLoadmore="true"
            apps:srlEnableLoadmoreWhenContentNotFull="true"
            apps:srlEnableScrollContentWhenLoaded="false">

            <com.scwang.smartrefresh.layout.header.ClassicsHeader
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycle_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            <com.scwang.smartrefresh.layout.footer.ClassicsFooter
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    </android.support.design.widget.CoordinatorLayout>

</LinearLayout>
加载更多时，数据加载完成了，数据自动滚动了，但是正在加载还在显示，最终会消失，很容易复现

**Comment by scwang90** [comment]
可以发你的源代码到邮箱吗？

**Comment by tulongchao** [comment]
已发到你邮箱scwang90@hotmail.com，多加载几次，就可以发现问题。

**Comment by scwang90** [comment]
finishLoadmore(0) 传0，去掉自动延迟就可以啦

**Comment by tulongchao** [comment]
就是传0感觉还是不行，还有就是我第一次加载的时候是好的，在继续加载效果就不好了，数据会自动滚动，而不是我去向上滑动才显示的
