### ISSUE TITLE
上拉加载

### ISSUE THREAD

**Issue by wdh-1025** [scwang90/SmartRefreshLayout#259]
通过上拉加载模拟往RecyclerView不断添加数据（本地模拟，不存在网络延迟），这时候不断快速上拉加载会偶尔出现footer停留在那里，没有隐藏，得触摸一下列表才能隐藏（finishLoadmore(0)）,不知道是不是我的使用方法有问题

**Comment by lpengpeng** [comment]
更新新版本后上拉加载会时，底部正在加载赏上滑的过程中会出现卡顿现象。1.0.3版本好着呢

**Comment by scwang90** [comment]
无法重现所描述的问题，需要提供源码才能帮助你们解决问题

**Comment by wang709693972wei** [comment]
请教下各位大佬，为什么就升级1.0.5后  上拉加载到最后一页的时候回闪烁一下  [，就好像是停顿了那么一会儿才显示数据，只有加载最后一页的时候会这样。 @scwang90   如若描述不清楚，可以发视频你看下 希望能解决。
