### ISSUE TITLE
你好，我的webview中有长屏的js，结果就是下滑的时候直接下拉刷新了，有解决方法吗？

### ISSUE THREAD

**Issue by xeronly** [scwang90/SmartRefreshLayout#260]

**Comment by scwang90** [comment]
使用自带的方法不行，你可以试试 smartLayout 提供的 自定义滚动边界功能，详见 属性方法 页

**Comment by xeronly** [comment]
好的，我试一下~感谢回复

**Comment by lizhw123** [comment]
你最后怎么解决的？

**Comment by lizhw123** [comment]
@xeronly

**Comment by lizhw123** [comment]
解决了，让HTML告诉APP webview是否到顶，然后在下拉刷新。希望对大家有用。

        mRefreshLayout.setScrollBoundaryDecider(new ScrollBoundaryDecider() {
            @Override
            public boolean canRefresh(View content) {
                //webview滚动到顶部才可以下拉刷新
                return TextUtils.equals(canReload, "1");
            }

            @Override
            public boolean canLoadmore(View content) {
                return false;
            }
        });

**Comment by KomoriWu** [comment]
@lizhw123  哥们看到你这句话，恍然大悟，你是已经解决了吗？我去试看看  谢谢
