### ISSUE TITLE
下拉刷新自动出现结束!!

### ISSUE THREAD

**Issue by kimonic** [scwang90/SmartRefreshLayout#262]
private void finishRL() {
        Log.e("TAG", "finishRL: isRefreshing-----"+swipeRefreshLayout.isRefreshing());//值为false
        Log.e("TAG", "finishRL:isLoading -----"+swipeRefreshLayout.isLoading());//值为false

        if (swipeRefreshLayout.isRefreshing()) {
            swipeRefreshLayout.finishRefresh();
        } else if (swipeRefreshLayout.isLoading()) {
            swipeRefreshLayout.finishLoadmore();
        }
    }
listview 数据源有刷新
执行该代码后,延迟一小会下拉刷新会冒出来,如何解决??

**Comment by scwang90** [comment]
这是为了演示添加的自动关闭功能
