### ISSUE TITLE
嵌套recycleView,数据加载不出来

### ISSUE THREAD

**Issue by onion90** [scwang90/SmartRefreshLayout#267]
使用1.0.4版本,recycleView加载不出数据
布局文件代码:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:orientation="vertical"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
      <com.scwang.smartrefresh.layout.SmartRefreshLayout
          android:id="@+id/refreshLayout"
          android:layout_width="match_parent"
          android:layout_height="match_parent">
                <android.support.v7.widget.RecyclerView
                    android:id="@+id/ry_message"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:overScrollMode="never"
                    android:background="#fff"/>
      </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</LinearLayout>

**Comment by NicodeLee** [comment]
没错，检查RecyclerView是否正常，尝试去掉SmartRefreshLayout看看数据是否能加载.

**Comment by scwang90** [comment]
布局是没问题的，如果不会使用，建议下载 demo 和 源代码 看着用例来一遍
