### ISSUE TITLE
最后一次刷新的时间不更新

### ISSUE THREAD

**Issue by outhui** [scwang90/SmartRefreshLayout#27]
在build.gradle中引用了这个库，刷新的时候最后一次刷新时间不更新了！我以为是我的问题，直接把demo的布局跟代码拷贝过来也是一样

**Comment by scwang90** [comment]
新版本中已经解决了，
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-3'

也可以主动调用 header.setLastUpdateTime()

**Comment by outhui** [comment]
大神自己发现Bug也很有效率啊！这个库非常nice！我们正常开发的时候，一般都是只用一种风格的，如果能把各种风格分割成一个一个module，开发过程中只选择一个中意的去引用就更赞了！

**Comment by scwang90** [comment]
对于分包问题我也在纠结，现在已经有十多种Header了分包太多，还未选定解决方案，还需进一步观察再出结果，如果现在纠结代码冗余的问题，建议
只引用 
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-3'
不要
compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.2-alpha-3'

然后自己拷贝 想要的Header 代码到项目中。
