### ISSUE TITLE
禁止上拉加载，还是会显示footview的布局问题

### ISSUE THREAD

**Issue by GuoYangGit** [scwang90/SmartRefreshLayout#273]
1.版本号：1.0.4
2.
![image](https://user-images.githubusercontent.com/23092931/33676452-b8968f3a-daf0-11e7-98ab-9fccf596584e.png)
![Uploading image.png…]()

**Comment by GuoYangGit** [comment]
![image](https://user-images.githubusercontent.com/23092931/33676517-e39a0a4a-daf0-11e7-9d6e-77f0b705dc7c.png)
![image](https://user-images.githubusercontent.com/23092931/33676540-f29dfc7c-daf0-11e7-82ca-bcb2c9633a18.png)

**Comment by scwang90** [comment]
用 1.0.4-1版本
