### ISSUE TITLE
1.4版本，第一次加载更多的时候，底部加载加载UI不显示，内容不满一屏的时候也是如此，1.3版本没有此问题。

### ISSUE THREAD

**Issue by tulongchao** [scwang90/SmartRefreshLayout#277]
1.4版本
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <View
                android:layout_width="match_parent"
                android:layout_height="200dp"
                android:background="#ff0000"
                app:layout_scrollFlags="scroll|enterAlwaysCollapsed" />

            <Button
                android:id="@+id/button"
                android:layout_width="match_parent"
                android:layout_height="100dp"
                android:background="#0059ff"
                android:text="Hello" />
        </android.support.design.widget.AppBarLayout>

        <com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:apps="http://schemas.android.com/apk/res-auto"
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            apps:srlDisableContentWhenLoading="false"
            apps:srlEnableLoadmore="true"
            apps:srlEnableLoadmoreWhenContentNotFull="true"
            apps:srlEnableScrollContentWhenLoaded="false">

            <com.scwang.smartrefresh.layout.header.ClassicsHeader
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycle_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            <com.scwang.smartrefresh.layout.footer.ClassicsFooter
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    </android.support.design.widget.CoordinatorLayout>

</LinearLayout>
这种布局，加载更多有问题，有时候上拉没有效果，有时候有效果，但是加载更多现实的UI高度不对，

**Comment by scwang90** [comment]
把这个布局拷到项目中运行，没有发现异常，需要你提供更多的完整代码
