### ISSUE TITLE
取消刷新的操作

### ISSUE THREAD

**Issue by JueShouGitHub** [scwang90/SmartRefreshLayout#278]
请问作者，有没有一个取消当前刷新的方法，有时候切换按钮，重新填数的时候，前一个还没有刷新完，就进行了其他按钮的操作。。。展示就不友好了

**Comment by scwang90** [comment]
调用了 finishRefresh(false) 刷新就关闭了，目前只有这个，如果不符合你的需求，你可能要去自定义了
