### ISSUE TITLE
版本是否发布正确？

### ISSUE THREAD

**Issue by ActivityForXiaoqiang** [scwang90/SmartRefreshLayout#28]
Failed to resolve: Could not resolve com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-3. Required by: project :app Open File

**Comment by scwang90** [comment]
已经发布了的，请再次确认，如果还是不行，请先推倒
com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-2

**Comment by ActivityForXiaoqiang** [comment]
@scwang90  com.scwang.smartrefresh:SmartRefreshLayout:1.0.2-alpha-2 是可以的
