### ISSUE TITLE
正在刷新时，向上滑动一段小距离，刷新的头部会自动回收回去，不是结束刷新，是设置哪一个方法的。

### ISSUE THREAD

**Issue by sohandsome1** [scwang90/SmartRefreshLayout#280]
![g h0dfu 73rs 06xs8yop](https://user-images.githubusercontent.com/13551113/33825378-5ca032da-de9c-11e7-8381-278e01038d7b.png)
正在刷新时，向上滑动一段小距离，刷新的头部会自动回收回去，不是结束刷新，是设置哪一个方法的。
上面那张图片是刷新头部停留在那里，没有收回去

**Comment by scwang90** [comment]
设计就是这样的，刷新没有结束的时候，是不会回弹的
