### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by liuchenc** [scwang90/SmartRefreshLayout#283]
scrollview里面套线性布局,线性布局里面包括一个banner和tablayout及viewpager,viewpager对应的是fragment,fragment里面的recyclerview去用refresh-layout做上拉加载更多的时候无效,请问是什么导致的?

**Comment by scwang90** [comment]
你需要把最外面的 scrollview 去掉，如果你的需求一定要在最外层使用 scrollview，你需要切换其他的刷新库，本库不支持在 scrollview 的内部工作
