### ISSUE TITLE
上拉加载，是否支持 ListView 设置过 clipToPadding=false？

### ISSUE THREAD

**Issue by coderqjd** [scwang90/SmartRefreshLayout#284]
在 ListView 设置底部内边距后，上拉加载完成后，会强制 paddingBottom="0dp"
![ice_screenshot_20171213-230037](https://user-images.githubusercontent.com/26524827/33945430-0149530c-e05a-11e7-9dbf-03dd6d83df6c.png)

**Comment by scwang90** [comment]
smart 并没有去修改 内容的 padding 的，你需要自己调试找到 padding 的关键代码
