### ISSUE TITLE
反复刷新加载，最终页面底部会有上拉加载更多提示字样保留在页面底部

### ISSUE THREAD

**Issue by largeCabbage** [scwang90/SmartRefreshLayout#285]
1.0.4-4
  mRefreshLayout.setRefreshHeader(new ClassicsHeader(this));
 mRefreshLayout.setRefreshFooter(new ClassicsFooter(this));

**Comment by largeCabbage** [comment]
可能是  mRefreshLayout.setEnableLoadmore(false); mRefreshLayout.setEnableLoadmore(true);
切换导致

**Comment by liufsd** [comment]
我并没有设置过，但一样可以复现这个问题呢？

**Comment by luckyandyzhang** [comment]
@largeCabbage 我也遇到这个问题了，请问你解决了吗？
