### ISSUE TITLE
小米部分机型出现闪退

### ISSUE THREAD

**Issue by gaolh89** [scwang90/SmartRefreshLayout#286]
您好,我在使用smartrefreshLayout  1.0.3过程中,下拉刷新过程中,其他机型没有问题,但小米MI6、Note两款手机均多次出现闪退的现象(不是必现,但出现频次很高).
本人QQ:984992087.望您抽空看一下.

**Comment by NicodeLee** [comment]
提供下崩溃信息，这样解决问题更有效率。
能说明下复现的操作跟相关代码最好。

**Comment by scwang90** [comment]
已经进群讨论

**Comment by NicodeLee** [comment]
有些常见的问题能在issues解决的话，能给后面使用这个库的人搜索到。
免得同样的问题回答两遍，或者类似的问题也能给其他使用者一些参考。
当然也可以看下 https://github.com/scwang90/SmartRefreshLayout/issues/71

**Comment by 1982582704** [comment]
![1692701402606](https://github.com/scwang90/SmartRefreshLayout/assets/17525427/3bb5108c-0c70-4bec-a7b3-fba1b37ab383)
![1692701402602](https://github.com/scwang90/SmartRefreshLayout/assets/17525427/b22d0aba-732b-49c7-b208-bfff46d40aba)

**Comment by gaolhjy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
    您好,您发的邮件我已经收到.谢谢!(高磊华)
