### ISSUE TITLE
不能关闭上拉加载

### ISSUE THREAD

**Issue by hudongjian** [scwang90/SmartRefreshLayout#287]
app:srlEnableAutoLoadmore="false"
        app:srlEnableLoadmore="false"
设置这几个选项不起作用，代码设置也不作用

**Comment by scwang90** [comment]
用 finishLoadmore

**Comment by hudongjian** [comment]
用过了，不起作用，您看一下是不是什么地方用错了，就想实现下拉刷新，不需要上拉加载功能，但是上拉加载一直能拉出来，就不想让上拉加载显示出来
<com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlAccentColor="@color/gray_333"
        app:srlPrimaryColor="@color/gray_ddd"
        app:srlEnablePreviewInEditMode="true"
        app:srlEnableAutoLoadmore="false"
        app:srlEnableLoadmore="false"
        >

        <com.scwang.smartrefresh.layout.header.ClassicsHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />
       
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

代码中设置
   private void initSmartRefreshLayout() {
        refreshLayout.finishLoadmore();
        refreshLayout.setLoadmoreFinished(true);//不起作用
        refreshLayout.setOnRefreshListener(refreshlayout -> {
            stopRefresh();
        });
    }

**Comment by hudongjian** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">
    <include layout="@layout/view_title"/>

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlAccentColor="@color/gray_333"
        app:srlPrimaryColor="@color/gray_ddd"
        app:srlEnablePreviewInEditMode="true"
        app:srlEnableAutoLoadmore="false"
        app:srlEnableLoadmore="false"
        >

        <com.scwang.smartrefresh.layout.header.ClassicsHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />
       
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

</LinearLayout>
