### ISSUE TITLE
Header无法显示或者页面显示空白

### ISSUE THREAD

**Issue by Forevas** [scwang90/SmartRefreshLayout#290]
您好，我在使用SmartRefreshLayout时遇到了一点问题，希望您能帮忙解答一下，不胜感激。

我的页面布局是FragmentTabHost(主页面)+(ViewPager+FragmentPagerAdapter)(子页面)，当第一次打开子页面时，我在Fragment的onCreateView中使用SmartRefreshLayout.autoRefresh(0)来触发回调onRefresh加载数据，以下操作会产生问题。

1.如果我在加载数据时，快速切换ViewPager，再回来时，数据已经加载成功了，可以看到。但是Header却没有回弹，而且Header的部分显示空白，必须稍稍向下拉一下才能回弹显示正常。

2.如果我在加载数据时立即切换到FragmentTabHost的其它tab，再回来时发现页面空白，必须稍稍滑动一下才能显示出来，其实数据已经加载成功了。

但是如果我待在这个页面等待加载完成，则没有任何问题。还有如果我不调用SmartRefreshLayout.autoRefresh(0)，而是直接加载数据，也没有以上的问题。

**Comment by scwang90** [comment]
换成新版本就好，是使用方法参考 demo
