### ISSUE TITLE
严重BUG【上拉自动加载】

### ISSUE THREAD

**Issue by qianxinyi** [scwang90/SmartRefreshLayout#291]
![_20171220153115](https://user-images.githubusercontent.com/17667882/34195986-fd63cb82-e59a-11e7-85e2-54a774dbe311.jpg)
自动上拉加载还没加载完全不放手，再下拉。必会出现如图所示BUG。

**Comment by mhlistener** [comment]
+1  同问

**Comment by magiclonw** [comment]
你们用的哪个版本

**Comment by mhlistener** [comment]
最新版1.0.4-4，之前也存在这个问题

**Comment by tmexcept** [comment]
![image](https://user-images.githubusercontent.com/10299901/34252564-2d982f98-e67f-11e7-9255-62592da7fbf7.png)
出现原因是在【使用-->SpecifyStyle内部的item页面】多次下拉上拉刷新之后，返回主页面，点击【实战】，

再次点击【使用】出现如下
![image](https://user-images.githubusercontent.com/10299901/34252737-cb70b0b4-e67f-11e7-8edf-de0d210041de.png)
并且打开其他的页面有一部分是有这个下拉刷新的样式的，
![image](https://user-images.githubusercontent.com/10299901/34252870-40b12a48-e680-11e7-88c3-20e9a44fcc67.png)
并且刷新其他页面也不会消失

**Comment by scwang90** [comment]
@qianxinyi 按照你所描述的方法操作没有发现问题，如果你遇到这个问题无法解决，你可以进群，并录制一个重现bug的视频。
还有你是否对 demo 的代码做了改动

**Comment by mashibin1992** [comment]
我这是上拉不松手 会一直重复请求
