### ISSUE TITLE
TextView内容填充全屏的时候上拉不会出现加载动画

### ISSUE THREAD

**Issue by tmexcept** [scwang90/SmartRefreshLayout#295]
**当前版本号1.0.4-4**

**当mEnableLoadmoreWhenContentNotFull = true的时候**

使用Tab-->SpecifyStyle-->三个列表：ContentView为TextView的时候，如果TextView的内容填充全屏，上拉不会出现加载动画
冲突原因是当TextView的内容填充全屏与非全屏

![image](https://user-images.githubusercontent.com/10299901/34252458-b5336946-e67e-11e7-9043-53ce4e57e168.png)
全屏的时候 **mLayout.getHeight()** 是大于当前TextView的高度，非全屏的时候小于TextView高度

具体出问题的方法如下图：
![image](https://user-images.githubusercontent.com/10299901/34252360-3f206bf0-e67e-11e7-8e34-b8bf2cf131dc.png)

**Comment by scwang90** [comment]
你需要添加一个滚动布局
