### ISSUE TITLE
纯滚动模式（越界回弹）下配合侧滑返回（swipeback） ，侧滑返回时，页面错乱

### ISSUE THREAD

**Issue by shooe** [scwang90/SmartRefreshLayout#296]
//侧滑返回库
    compile 'com.aitangba:swipeback:1.0.1'

地址：
https://github.com/XBeats/and_swipeback

当前页面包含SmartRefreshLayout 包裹一个NestedScrollView  

侧滑返回时  ScrollView  自动翻滚到最下方

**Comment by scwang90** [comment]
这个问你你还是自己解决吧
