### ISSUE TITLE
使用Viewpager的跳动问题

### ISSUE THREAD

**Issue by hushiguang** [scwang90/SmartRefreshLayout#298]
版本1.0.3
问题：界面跳动
代码：
`   <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlEnablePreviewInEditMode="false"
        app:srlEnablePureScrollMode="true">
</com.scwang.smartrefresh.layout.SmartRefreshLayout>

问题详细附件：

![2017-12-21 21_08_05](https://user-images.githubusercontent.com/10889046/34257040-1b95dbc4-e693-11e7-8659-8ebd3d18ffdd.gif)

**Comment by scwang90** [comment]
使用新版本就好了
