### ISSUE TITLE
下拉刷新内存问题

### ISSUE THREAD

**Issue by douyav9** [scwang90/SmartRefreshLayout#302]
不知道作者有没有发现每次下拉刷新，在内存稳定后，应用内存暂用会比刷新之前增加1～2M。每次刷新都会增加1～2M。而且下拉刷新时，内存抖动比较厉害（瞬间内存波动在10～20M左右）。
我在我项目中接入了这个库，在列表一直下拉刷新，一会儿应用内存就从50M涨到了100多M，并且GC不掉。
clone你的项目到本地，运行Demo工程一样存在该问题，下拉10～20次，应用内存占用从30M上升到60M，并且GC不掉。

**Comment by scwang90** [comment]
在 demo 中试了一下，并没有所描述的问题，动画过程中内存波动很正常，下拉20从内存只涨1M，关闭页面再进，内存可以回复到原始状态，你说的 30M->60M 太夸张了，而且还不能GC

**Comment by douyav9** [comment]
![image](https://user-images.githubusercontent.com/10252523/34337271-000cc652-e999-11e7-9f1e-eff74bdbce9e.png)

**Comment by scwang90** [comment]
不好意思，我这边没有你描述的问题，也不知道怎么解决

**Comment by douyav9** [comment]
![image](https://user-images.githubusercontent.com/10252523/34337466-75c5c0be-e99a-11e7-83e3-564921072110.png)

**Comment by douyav9** [comment]
把这个控件换成v4里的SwipeRefreshLayout，发现没有该问题。大佬你要不要再看看？

**Comment by scwang90** [comment]
我这边没换也没发现问题呢

**Comment by douyav9** [comment]
http://blog.csdn.net/aa112901a/article/details/51569565
![image](https://user-images.githubusercontent.com/10252523/34356358-e9b34b9e-ea77-11e7-8b40-f9e1b70ba236.png)
亲测， view.setLayerType(View.LAYER_TYPE_SOFTWARE, null);可以解决该问题

**Comment by scwang90** [comment]
关于硬件加速，没研究过，之前从测试也都是在模拟器中运行，非常感谢！

**Comment by scwang90** [comment]
不过我用真机测试，在没有关闭硬件加速的时候，也没有发现内存显著增大的问题，是否要关闭硬件加速暂时不能确定。而且这个要算bug的话应该算硬件层的bug，你说你哪里都测到了，内存增加，还加那么多，但是我这边都没测到，而且那么多的其他用户都没测到，我怀疑是你那手机硬件层的bug
