### ISSUE TITLE
recyclerView设置setNestedScrollingEnabled();

### ISSUE THREAD

**Issue by zengcanxiang** [scwang90/SmartRefreshLayout#309]
当前使用的版本号
1.0.4
复现操作描述
recyclerView中还有recyclerView，所以会将其中的一个recyclerView设置setNestedScrollingEnabled(false).然后就会导致SmartRefreshLayout不能滑动

**Comment by scwang90** [comment]
问题不能重现，如果你需要解决，你可以进群，并提供源代码
