### ISSUE TITLE
onRefresh called after Activity onDestroy

### ISSUE THREAD

**Issue by yueban** [scwang90/SmartRefreshLayout#313]
版本: 1.0.3
问题描述: onRefresh called after Activity onDestroy

两个建议方案:
方案一:
在 `onDetachedFromWindow` 中 cancel 所有 animator，避免某些 animator 结束后回调 `onRefresh`,  `onLoadMore` 方法，此方案可以参考 `SwipeRefreshLayout`

方案二:
在 `onDetachedFromWindow` 中重置所有 listener 为 null

**Comment by scwang90** [comment]
非常感谢
