### ISSUE TITLE
三星S7 7.0 下拉刷新经典样式，菊花不转圈

### ISSUE THREAD

**Issue by cnyyk** [scwang90/SmartRefreshLayout#314]
三星S7 系统 7.0 下拉刷新经典样式，菊花不转圈，另外一个低版本4.3手机下拉转圈。

默认 DEMO 的 使用-》Basic（基本的使用）可见此问题

**Comment by scwang90** [comment]
我这边没有这个机型，还希望你能帮助找一下原因

**Comment by cnyyk** [comment]
好，空点看下

**Comment by redzealot2008** [comment]
红米3遇到同样的问题，菊花无动画
