### ISSUE TITLE
如果用webview 打开这个 加上SmartRefreshLayout无法滚动

### ISSUE THREAD

**Issue by liudao01** [scwang90/SmartRefreshLayout#315]
https://m.baidu.com/?from=844b&vit=fps#iact=wiseindex%2Ftabs%2Fnews%2Factivity%2Fnewsdetail%3D%257B%2522linkData%2522%253A%257B%2522name%2522%253A%2522iframe%252Fmib-iframe%2522%252C%2522id%2522%253A%2522feed%2522%252C%2522index%2522%253A0%252C%2522url%2522%253A%2522https%253A%252F%252Fmbd.baidu.com%252Fnewspage%252Fdata%252Flandingpage%253Fs_type%253Dnews%2526dsp%253Dwise%2526context%253D%25257B%252522nid%252522%25253A%252522news_9128466045664084564%252522%25257D%2526pageType%253D1%2526n_type%253D1%2526p_from%253D-1%2526innerIframe%253D1%2522%252C%2522isThird%2522%253Afalse%252C%2522title%2522%253Anull%257D%257D 

我直接替换的github上面的例子 替换的网页 
 可以尝试先打开百度 
然后在百度首页点一个新闻详情  新闻详情就不可以滚动了

**Comment by scwang90** [comment]
这个和你网页内容有关，我帮不了你的
