### ISSUE TITLE
使用 setEnableAutoLoadmore 属性,快速上拉多次footer 没有隐藏

### ISSUE THREAD

**Issue by Jungchen** [scwang90/SmartRefreshLayout#318]
refreshLayout.setEnableAutoLoadmore(false);//开启自动加载功能（非必须）
在基本的功能使用(BasicUsingActivity)中 注释 setEnableAutoLoadmore(false) 
连续快速上拉会出现加载控件还在显示

**Comment by liufsd** [comment]
这个问题，有发布版本么？？？

**Comment by scwang90** [comment]
问题已经修复

**Comment by liufsd** [comment]
1.0.4-5 ?

**Comment by liufsd** [comment]
亲测，并没有修复，问题依然存在。
