### ISSUE TITLE
关于数据全部加载完毕 

### ISSUE THREAD

**Issue by ScWen7** [scwang90/SmartRefreshLayout#32]
设置全部加载完毕，调用如下代码
refreshlayout.setLoadmoreFinished(true);

两种情况：
页面静止状态，并且继续上拉布局不能上拉
页面快速拖动，到底部会出现  “全部加载完毕” 的Footer 

我在想 能不能将这两种情况合并，匀速滑动与快递滑动保持一致

**Comment by scwang90** [comment]
你好，谢谢你提的建议，你列出来的两条是现有功能吗？
如果你使用了 1.0.2-alpha-3 不存在你提出的第一种情况，还是可以继续上啦的，只是不会触发加载事件
你说的第二种情况 是越界回弹功能，

如果你用的是 1.0.1 版本，那么 1.0.2-alpha-3  适合你的需求

**Comment by ScWen7** [comment]
好的，我再去升级使用测试一下
