### ISSUE TITLE
SmartRefreshLayout 嵌套CoordinatorLayout 设置loadmore完成后，底部footerview一直在，而且高度错误

### ISSUE THREAD

**Issue by liufsd** [scwang90/SmartRefreshLayout#320]
亲测，即使demo工程依然也有这个问题，把BasicUsingActivity的数据改为30条，load时间改500，也是必现的。

**Comment by liufsd** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by liufsd** [comment]
![image](https://user-images.githubusercontent.com/1910405/34593078-87e943bc-f203-11e7-8005-2e43e60d9f4a.png)

**Comment by tangyaogang** [comment]
解决了吗  我也遇到这个问题

**Comment by liufsd** [comment]
没有解决，作者也木有回答/

**Comment by tangyaogang** [comment]
refreshLayout.setEnableFooterFollowWhenLoadFinished(false);//是否在全部加载结束之后Footer跟随内容1.0.4  我是设置这个方法之后footerview有时候并不是跟随内容  而是一直卡在底部

**Comment by liufsd** [comment]
这是个bug.

**Comment by luckyandyzhang** [comment]
+1

**Comment by MinchinWang** [comment]
+1

**Comment by luckyandyzhang** [comment]
目前的workaround是避免使用setEnableLoadmore()来控制是否可以上拉加载，替代的方法为
setLoadmoreFinished()。

希望作者有空可以修一下此问题，貌似遇到的人蛮多的
1.4.0
1.0.4-5
1.4.0-7 均有问题

**Comment by rcj60560** [comment]
@scwang90  我发现楼上的人都不艾特一波  艾特了才能收到邮件

**Comment by luckyandyzhang** [comment]
@rcj60560 有watch就会收到，不用艾特也可以

**Comment by scwang90** [comment]
1.0.5-alpha-3 版本已经发布，大家更新试试，如果没有解决及时反馈，不过 1.0.5 对API 的命名全部更变，需要注意，loadMore
