### ISSUE TITLE
淘宝二楼功能出现问题

### ISSUE THREAD

**Issue by leojiao123** [scwang90/SmartRefreshLayout#321]
版本: 1.0.4-5
问题: 淘宝二楼功能出现的问题 
描述: 直接下载源码的demo中，下拉释放到二楼后，直接上滑回到列表内容，在前几次是可以的，在第3次或者更多的尝试后，会导致列表不能滑动

**Comment by wangyao5018** [comment]
我用demo也碰到过这个问题,但是在我的应用里没有出现过这个问题,我遇到了其他问题

**Comment by scwang90** [comment]
1.0.4-7 发布，问题修复

**Comment by scwang90** [comment]
2018-1-25 二楼刷新，有重大BUG（一小部分机型会崩溃）更新，请及时升级，
