### ISSUE TITLE
加载更多加载不了，以下是布局

### ISSUE THREAD

**Issue by MinchinWang** [scwang90/SmartRefreshLayout#325]
<com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/main_theme_color"
    app:srlEnableFooterTranslationContent="false"
    app:srlEnableHeaderTranslationContent="false"
    app:srlEnableLoadmore="true">

    <com.scwang.smartrefresh.header.MaterialHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.design.widget.CollapsingToolbarLayout
                android:id="@+id/toolbar_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/main_theme_color"
                app:contentScrim="?attr/colorPrimary"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical"
                    app:layout_collapseMode="parallax">

                    <include layout="@layout/include_nearby_index" />

                    <include layout="@layout/include_line" />

                </LinearLayout>

                <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="top"
                    android:minHeight="?attr/actionBarSize"
                    app:contentInsetStart="0dp"
                    app:layout_collapseMode="pin">

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="90px"
                        android:layout_below="@+id/line"
                        android:layout_marginTop="@dimen/status_padding_top">

                        <TextView
                            android:id="@+id/location_tv"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:layout_centerVertical="true"
                            android:drawableLeft="@mipmap/shouye_map_btn"
                            android:drawablePadding="15px"
                            android:gravity="center"
                            android:paddingLeft="30px"
                            android:paddingRight="30px"
                            android:text="定位中..."
                            android:textColor="@color/white"
                            android:textSize="@dimen/sub_size"
                            android:visibility="visible" />

                        <TextView
                            android:id="@+id/search_tv"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_centerInParent="true"
                            android:layout_centerVertical="true"
                            android:layout_toLeftOf="@+id/msg_tv"
                            android:layout_toRightOf="@+id/location_tv"
                            android:background="@drawable/bg_main_search_style"
                            android:drawableLeft="@mipmap/shouye_search_btn"
                            android:drawablePadding="10px"
                            android:gravity="center_vertical"
                            android:hint="搜索"
                            android:paddingRight="20px"
                            android:textSize="28px" />

                        <TextView
                            android:id="@+id/msg_tv"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_alignParentRight="true"
                            android:layout_centerVertical="true"
                            android:drawablePadding="15px"
                            android:drawableTop="@mipmap/sy_xiaoxi"
                            android:gravity="center"
                            android:padding="30px"
                            android:text="消息"
                            android:textColor="@color/white"
                            android:textSize="8sp" />

                    </RelativeLayout>

                </android.support.v7.widget.Toolbar>

            </android.support.design.widget.CollapsingToolbarLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                android:orientation="vertical">

               
            </LinearLayout>

        </android.support.design.widget.AppBarLayout>

        <android.support.v4.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="20px"
                android:background="@color/white"
                android:orientation="vertical">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/white"
                    android:gravity="center_vertical"
                    android:orientation="horizontal"
                    android:paddingBottom="25px"
                    android:paddingLeft="30px"
                    android:paddingTop="25px">

                    <View
                        android:layout_width="10px"
                        android:layout_height="30px"
                        android:background="@color/title_bg_color" />

                    <TextView
                        android:layout_width="wrap_content"

                        android:layout_height="wrap_content"
                        android:layout_gravity="center_horizontal"
                        android:layout_marginLeft="15px"
                        android:gravity="center"
                        android:text="附近商家"
                        android:textColor="@color/color_text_normal"
                        android:textSize="@dimen/sub_size" />

                </LinearLayout>

                <View
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/line_height"
                    android:background="@color/line_small" />

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/rec_lv"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:nestedScrollingEnabled="false" />
            </LinearLayout>
        </android.support.v4.widget.NestedScrollView>

    </android.support.design.widget.CoordinatorLayout>

    <com.scwang.smartrefresh.layout.footer.BallPulseFooter
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:srlAccentColor="@color/colorAccent"
        app:srlClassicsSpinnerStyle="Scale"
        app:srlPrimaryColor="@color/colorAccent" />

</com.scwang.smartrefresh.layout.SmartRefreshLayout>

**Comment by scwang90** [comment]
看常见问题
