### ISSUE TITLE
淘宝二楼finishTwoLevel时候不会自动关闭

### ISSUE THREAD

**Issue by yyBetter** [scwang90/SmartRefreshLayout#327]
使用淘宝二楼功能，在过程中跳转进入新的页面。快速关闭新页面返回会发现二楼状态卡死，部分时候不可点击，部分时候底部可以拖动拉回。升级新版本后，还会有部分手机出现卡主状态。
调用finishTwoLevel后发现RefreshState并没有切换回none

**Comment by yyBetter** [comment]
使用1.0.4-7

**Comment by scwang90** [comment]
进讨论群，拍视频，发代码截图，详细了解一下
