### ISSUE TITLE
【Suggestion】希望ClassicFooter 提供方法修改 加载时、加载失败显示的文字。现在只能用反射修改

### ISSUE THREAD

**Issue by WolfAloneA** [scwang90/SmartRefreshLayout#328]
ClassicsFooter footer = new ClassicsFooter(context);
            try {
                Class<? extends ClassicsFooter> f = footer.getClass();
                Field fa = f.getField("REFRESH_FOOTER_FAILED");
                fa.setAccessible(true);
                fa.set(footer, "没有更多数据了");
            } catch (NoSuchFieldException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }
            return footer;

**Comment by scwang90** [comment]
没必要用反射啊，是public 的，直接修改就好了
