### ISSUE TITLE
为了方便自定义Header，请教下如何获取几个关键参数

### ISSUE THREAD

**Issue by gitgeek4dx** [scwang90/SmartRefreshLayout#33]
1：下拉时，手指的当前位置，currentPosition。
2：触发刷新的位置 mPositionToRefresh
3：刷新时，刷新头保持在的位置 mHeaderKeepPosition
4：手指抬起时的位置 mFingerUpPosition
5：用户是否触摸  isTouching

**Comment by scwang90** [comment]
你可以实现 RefreshHeader 这个接口


1：下拉时，手指的当前位置，currentPosition  -> onPullingDown：offset
2：触发刷新的位置 mPositionToRefresh -> headerHeight
3：刷新时，刷新头保持在的位置 mHeaderKeepPosition -> headerHeight
4：手指抬起时的位置 mFingerUpPosition -> onReleasing：offset
5：用户是否触摸 isTouching -> status != pulltorefresh && status != resrasetorefresh
