### ISSUE TITLE
app崩溃后出现的问题

### ISSUE THREAD

**Issue by it0003** [scwang90/SmartRefreshLayout#335]
我在真机调试时，强行stop 运行的程序，有时候app不会退出而是崩溃。这时候app还可以使用，结果smartrefreshlayout出现一些bug，首先是刷新和上拉加载时可以点击（原本设置的不可点）；还有就是，刷新时，最底层会出现其他页面的数据。居然还可以点击。

**Comment by scwang90** [comment]
进群，提供详细信息
