### ISSUE TITLE
CoordinatorLayout、AppBarLayout

### ISSUE THREAD

**Issue by KobeBryant824** [scwang90/SmartRefreshLayout#336]
<android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_scrollFlags="scroll">

                <com.rgbvr.wawa.widget.MyVerticalViewPager
                    android:id="@+id/home_vertical_vp"
                    android:layout_width="match_parent"
                    android:layout_height="68dp"
                    android:layout_below="@+id/arc_banner"
                    android:layout_marginTop="-10dp"
                    android:background="@drawable/bg_home_broadcust"
                    android:paddingBottom="3dp"
                    android:visibility="gone"
                    app:layout_scrollFlags="scroll" />

                <com.rgbvr.wawa.widget.ArcLayout
                    android:id="@+id/arc_banner"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:arc_height="@dimen/arc_height"
                    app:layout_scrollFlags="scroll">

                    <com.youth.banner.Banner
                        android:id="@+id/banner_home"
                        android:layout_width="match_parent"
                        android:layout_height="125dp"
                        android:background="@color/C_FFFFFF"
                        android:visibility="gone"
                        app:image_scale_type="center_crop"
                        app:indicator_drawable_selected="@drawable/banner_select"
                        app:indicator_drawable_unselected="@drawable/banner_unselect"
                        app:indicator_height="@dimen/x7"
                        app:indicator_width="@dimen/x70" />

                </com.rgbvr.wawa.widget.ArcLayout>

            </RelativeLayout>

            <net.lucode.hackware.magicindicator.MagicIndicator
                android:id="@+id/magicindicator"
                android:layout_width="match_parent"
                android:layout_height="40dp" />
        </android.support.design.widget.AppBarLayout>

        <android.support.v4.view.ViewPager
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />

    </android.support.design.widget.CoordinatorLayout>

**Comment by scwang90** [comment]
加群，发代码，拍视频

**Comment by KobeBryant824** [comment]
当禁用自动加载更多（改成手拉的）或者滑动recyclerview不是快速的（缓慢的）就不会出现新数据往上顶（跳跃感）

**Comment by KobeBryant824** [comment]
mRecyclerView.scrollToPosition(lastVisibleItemPosition); 用这个替代方式了

**Comment by shangqianglong** [comment]
lastVisibleItemPosition 是个啥

**Comment by shangqianglong** [comment]
歪日 666

**Comment by scwang90** [comment]
见
#727
