### ISSUE TITLE
如果是打砖块 Header，在下拉到一定距离后放开又快速点击，会出现打砖块Header悬浮在列表上面的问题。

### ISSUE THREAD

**Issue by HuangShengHuan** [scwang90/SmartRefreshLayout#337]
解决方案：
FunGameBase.java

@Override
    public boolean onTouchEvent(MotionEvent event) {
        if (mState == RefreshState.Refreshing || mState == RefreshState.RefreshFinish) {
            //刷新时将偏移量置0
            if(getTranslationY()!=0) setTranslationY(0);
            ...
    }

**Comment by scwang90** [comment]
非常感谢
