### ISSUE TITLE
当禁用上拉加载的时候，设置mEnableFooterTranslationContent或者mEnableHeaderTranslationContent为false的问题

### ISSUE THREAD

**Issue by hwra2008** [scwang90/SmartRefreshLayout#338]
当禁用上拉加载的时候或者禁用下拉刷新的时候，且设置mEnableFooterTranslationContent或者mEnableHeaderTranslationContent为false的时候,滑动到底部后不松手继续上滑一段距离，在下滑，视图不移动

**Comment by scwang90** [comment]
smart 的特性就是这样的，如果页面不需要 下拉刷新功能，去掉就好了，不要加上之后又 set false

**Comment by hwra2008** [comment]
哦
