### ISSUE TITLE
建议规范下版本号

### ISSUE THREAD

**Issue by cnyyk** [scwang90/SmartRefreshLayout#339]
当前版本1.0.4-5，Android studio 一直提示发现新版本1.0.4
<img width="773" alt="qq20180115-094400 2x" src="https://user-images.githubusercontent.com/275233/34923646-b578c078-f9d8-11e7-9b87-5bfe5d5e1d2b.png">

事实上的新版本是1.0.4-7
<img width="1180" alt="qq20180115-094259 2x" src="https://user-images.githubusercontent.com/275233/34923666-d895062a-f9d8-11e7-9fcb-c77744872417.png">

**Comment by cnyyk** [comment]
更改为最新的1.0.4-7，仍然提示有1.0.4新版本。
如果版本号规范了应该没有这个问题。。。

**Comment by scwang90** [comment]
谢谢
