### ISSUE TITLE
setEnableScrollContentWhenRefreshed(true)

### ISSUE THREAD

**Issue by q805699513** [scwang90/SmartRefreshLayout#345]
setEnableScrollContentWhenRefreshed好像能看到往上收Header的动画。不知道能不能改成透明的或者去掉这种。

**Comment by scwang90** [comment]
以后的版本会考虑，目前的做法可以在 结束刷新之前 设置回弹动画时间为 0 ，然后延迟 1000毫秒之后，回复 动画时间为 默认的 250
~~~
refreshLayout.setReboundDuration(0);
refreshLayout.finishReferesh();
refreshLayout.postDelayed(new Runnable(){
    void run(){
         refreshLayout.setReboundDuration(250);
    }
},1000);
~~~

**Comment by q805699513** [comment]
这样的话就没有了setEnableScrollContentWhenRefreshed的效果，刷新头区域不会显示新数据

**Comment by scwang90** [comment]
你不是已经 setEnableScrollContentWhenRefreshed(true) 了嘛，怎么会没有

**Comment by q805699513** [comment]
我这边的效果是刷新头区域不会显示内容，只是把刷新头收回，然后列表弹上去。

**Comment by scwang90** [comment]
这就不清楚了，我这边是可以的
