### ISSUE TITLE
纯滚动模式下只有上拉有回弹，下拉没有回弹

### ISSUE THREAD

**Issue by hushiguang** [scwang90/SmartRefreshLayout#346]
` compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.4-5'
    compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.4-5'`

代码
`<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/normal_color_white"
    android:orientation="vertical">

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/widget_toolbar"
        app:srlDragRate="1"
        app:srlEnableLoadmore="false"
        app:srlEnablePureScrollMode="true">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
       </LinearLayout>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</FrameLayout>
`

**Comment by scwang90** [comment]
拷贝你发的代码，去调试，没发现问题
