### ISSUE TITLE
下拉刷新的图标无法收起

### ISSUE THREAD

**Issue by yourge** [scwang90/SmartRefreshLayout#347]
#下拉刷新 #我使用的是仿swipeRefreshlayout的下拉刷新样式 , 在viewPager的fragment中使用,当下拉图标出现后快速切换到另一个fragment,再切换回来,发现那个下拉图标固定在切换的位置回不去了,请问这个有什么办法解决么?(问题现象: 图中的图标固定在了那个位置,只有重新下拉一次才会消失)
![d0ab37c84fec4011e13a065ed04bb7cb](https://user-images.githubusercontent.com/23035622/35082533-639fa6fc-fc55-11e7-9c0f-c1e486c9c084.jpg)

**Comment by scwang90** [comment]
换新版本吧
