### ISSUE TITLE
越界问题

### ISSUE THREAD

**Issue by yhbuao** [scwang90/SmartRefreshLayout#35]
java.lang.ArrayIndexOutOfBoundsException: length=14; index=-1
at com.scwang.refreshlayout.fragment.RefreshStylesFragment.onItemClick(RefreshStylesFragment.java:149)
at com.scwang.refreshlayout.adapter.SmartViewHolder.onClick(SmartViewHolder.java:42)

**Comment by scwang90** [comment]
问题已经解决，刷新页面重新下载 Demo 即可

**Comment by jamin918** [comment]
@scwang90 代码老半天下不下来，在线看了下，SmartViewHolder中改动就是下面：
`

@Override
--
  | public void onClick(View v) {
  | if (mListener != null) {
  | int position = getAdapterPosition();
  | if(position >= 0){
  | mListener.onItemClick(null, v, position, getItemId());
  | }
  | }
  | }

`
这个getAdapterPosition();得到的值永远是-1，请问其他地方还有改动吗？
