### ISSUE TITLE
demo的基本使用界面，全部加载完后列表滑动卡顿

### ISSUE THREAD

**Issue by huashengzzz** [scwang90/SmartRefreshLayout#351]

**Comment by scwang90** [comment]
没发现这个问题

**Comment by huashengzzz** [comment]
我用了多次，你的项目我也运行过，那个界面底部全部加载完成快速滑动会卡在那地方

**Comment by scwang90** [comment]
你不用运行项目，你直接下 demo 就好了

**Comment by huashengzzz** [comment]
我接入后效果和你git的demo效果是一样的，就是底部布局和recyclerview的滑动不连贯，偶尔会有卡在底部和列表布局连接的地方

**Comment by scwang90** [comment]
那你还是进群吧

**Comment by huashengzzz** [comment]
layout.setEnableFooterFollowWhenLoadFinished(true);这个设置后，你确定全部加载完后的底部布局和普通的recyclerview或者listview衔接处没有卡顿情况？

**Comment by scwang90** [comment]
我只是确认没有发现
