### ISSUE TITLE
footer没有显示完全就开始加载更多

### ISSUE THREAD

**Issue by freedoem** [scwang90/SmartRefreshLayout#353]

**Comment by freedoem** [comment]
- 
![cb9f589e8a3a23e749973d37707cae1b](https://user-images.githubusercontent.com/16286996/35149796-72091b76-fd52-11e7-8ce0-de95dae1e110.jpg)
![Uploading 7CAE5B99D7F1BCF82F8DEC70DF32D742.jpg…]()

**Comment by scwang90** [comment]
setEnableAutoLoadmore(false)
