### ISSUE TITLE
CoordinatorLayout 加载下一页，数据已经完成了，动画还在加载，延迟一两秒，然后列表就自动滑上去了

### ISSUE THREAD

**Issue by MinchinWang** [scwang90/SmartRefreshLayout#357]
CoordinatorLayout 加载下一页，数据已经完成了，动画还在加载，延迟一两秒，然后列表就自动滑上去了

RecyclerView设置属性android:nestedScrollingEnabled="false"，正常，但是上滑折叠没有效果
RecyclerView设置属性android:nestedScrollingEnabled="true"，不正常，会自动滑上去，但是CoordinatorLayout 折叠效果正常

**Comment by scwang90** [comment]
进群吧，把你遇到的问题拍成视频，发到群里
