### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by caoqianghui** [scwang90/SmartRefreshLayout#364]
希望增加功能，如系统的SwipeRefreshLayout，做自动刷新时，只load刷新动画，不做实际onrefresh回调，提供结束动画的接口（会存在数据刷新很快，布局还没展开或者展开中的情况哦，作者处理下）

**Comment by scwang90** [comment]
虽然之前觉得这个功能可以添加，但是经过分析之后，这个功能会引起你问题中描述的严重问题，要解决这些问题，要改动非常多的核心算法，综合考虑下来，将不打算添加这个功能。

**Comment by AvatarQing** [comment]
现在， `Android Architecture Components` 的 `Paging`库 接管了上下拉刷新数据的触发，按照[`Paging`库的demo](https://github.com/googlesamples/android-architecture-components/blob/master/PagingWithNetworkSample/app/src/main/java/com/android/example/paging/pagingwithnetwork/reddit/ui/RedditActivity.kt#L97)来看，里面用的是`SwipeRefreshLayout`，需要下拉刷新的View提供 “只load刷新动画，不做实际onrefresh回调”的功能，不知能否再考虑一下实现下此功能？
