### ISSUE TITLE
Header不会隐藏，一直显示

### ISSUE THREAD

**Issue by Yanqilong** [scwang90/SmartRefreshLayout#365]
版本：compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.4-7'

Header不会隐藏，一直显示，Footer正常。
1、默认进入页面头部就会显示出来
2、可以触发下拉刷新，刷新时的状态也是对的，刷新完成后头部不会隐藏

请看下效果图，问题出在哪里呢？
![效果图](http://or45zpyfw.bkt.clouddn.com/18-1-27/8836433.jpg)

如果需要 demo 可提供

**Comment by Yanqilong** [comment]
经过我再三调试，问题解决了，需要给 RecyclerView 设置背景才能正常显示，这个实在蛋疼
```ruby
android:background="@android:color/white"
```
这是一个bug吧，问题所在应该是 header 在 SmartRefreshLayout 内绘制顺序的问题，需要在SmartRefreshLayout 绘制背景绘制前 绘制好 header，在请大大检查下！

**Comment by scwang90** [comment]
把 Header 设置成 平移样式就好了

**Comment by Yanqilong** [comment]
什么是平移样式？ @scwang90
