### ISSUE TITLE
NestedScrollView 嵌套Recyclview并且Recycview设置setNestedScrollingEnabled(false)，上拉加载失败

### ISSUE THREAD

**Issue by hezhipengzipp** [scwang90/SmartRefreshLayout#366]
上拉加载更多不会出现，设置了
app:srlEnableLoadmore="true"
app:srlEnableLoadmoreWhenContentNotFull="true"

**Comment by scwang90** [comment]
你的情况比较特殊需要使用 smart 提供的 自定义滚动边界功能，重写 canLoadmore

**Comment by hezhipengzipp** [comment]
public boolean canLoadmore(View content) {
                return false;
            }
这个方法我应该怎么去判断

**Comment by scwang90** [comment]
如果列表已经滚动到底部，就返回 true，否则 false
