### ISSUE TITLE
升级到1.0.4问题

### ISSUE THREAD

**Issue by wzgl5533** [scwang90/SmartRefreshLayout#367]
使用setEnableOverScrollDrag(true) ，在数据不满一页时（数据装填完成我已调用setEnableLoadmore(false)），一进页面，我立即上拉，竟然还会出现上拉加载footer，而且不消失，这是不是bug？

**Comment by scwang90** [comment]
你需要提供更详细的信息，如果复杂的话，你需要进群

**Comment by wzgl5533** [comment]
这个问题我看不复杂，就是我想使用1.0.4的setEnableOverScrollDrag(true)功能，但在单页数据的时候，我进入页面就往上拉页面，很大概率会出现这个问题，但是我只要延迟一会上拉就不会发生。很奇怪

**Comment by scwang90** [comment]
换成 1.0.4-7 版本试试

**Comment by wzgl5533** [comment]
1.0.4-7确实没有这个问题
