### ISSUE TITLE
English Readme

### ISSUE THREAD

**Issue by florent37** [scwang90/SmartRefreshLayout#37]
Please translate your Readme in English, 
Your lib is pretty, this will help user to download and use it ;)

**Comment by TuringHuang** [comment]
哈哈哈，老外要你翻译

**Comment by fg2q1q3q** [comment]
Ha ha ha, foreigners want you to translate

**Comment by scwang90** [comment]
Thank you for your advice, I will complete the translation within a few days~

**Comment by DHosseiny** [comment]
This is not done can u provide some English readme and docs. thanks in regard
