### ISSUE TITLE
能否有方法禁止惯性滑动导致的下拉刷新？

### ISSUE THREAD

**Issue by ImportEffort** [scwang90/SmartRefreshLayout#373]
SmartRefreshlayout 在嵌套的列表快速下滑的时候有个 fling 操作，滑动过快的时候下拉刷新就自动触发了。想要的效果：惯性滑动不触发头部展示。
效果图
https://ws4.sinaimg.cn/large/006tKfTcly1fo1yl8augog30f00qohe2.gif

![](https://ws4.sinaimg.cn/large/006tKfTcly1fo1yl8augog30f00qohe2.gif)

**Comment by scwang90** [comment]
关闭越界回弹就好了，认真看文档吧
