### ISSUE TITLE
CoordinatorLayout 的滑动效果有冲突

### ISSUE THREAD

**Issue by vickyleu** [scwang90/SmartRefreshLayout#374]
这是我的项目https://github.com/vickyleu/SunYatSinUniversity

问题布局https://github.com/vickyleu/SunYatSinUniversity/blob/master/app/src/main/java/com/superfactory/sunyatsin/Interface/BindingFragment/Note/NoteFragmentComponent.kt  

更新了1.0.5-alpha-3 ,日志页面滑动Appbarlayout没有任何反应,加了群没反应,搜索了issue没有找到相关解答

**Comment by vickyleu** [comment]
coordinatorLayout {
                fitsSystemWindows=true
            themedAppBarLayout(R.style.ThemeOverlay_AppCompat_Dark_ActionBar) {
                fitsSystemWindows=true
                backgroundColor=getActionBarColor(context)
                collapsingToolbarLayout {
                    expandedTitleMarginEnd=getActionBarSize(context)+dip(164)
                    expandedTitleMarginStart=getActionBarSize(context)
                    fitsSystemWindows=true
                    isTitleEnabled=false
                    statusBarScrim=ColorDrawable(Color.TRANSPARENT)
                    contentScrim=getAttrDrawablValue(context,R.attr.colorPrimary)
                    verticalLayout {
                        backgroundColor = Color.parseColor("#1688ff")
                        fitsSystemWindows=true
                    }.lparams {
                        width = matchParent
                        height = dip(64)
                        collapseMode=COLLAPSE_MODE_PIN
                    }
                }.lparams{
                    width = matchParent
                    height = dip(64)
                    scrollFlags = SCROLL_FLAG_SCROLL or SCROLL_FLAG_EXIT_UNTIL_COLLAPSED
                    //or SCROLL_FLAG_ENTER_ALWAYS
                }
            }.lparams {
                width = matchParent
                height = wrapContent
            }
            refresh {
                backgroundColor = Color.WHITE
                verticalLayout {
                    backgroundColor = Color.RED
                    lparams {
                        width = matchParent
                        height = matchParent
                    }
                    onClick {
                        doAsync {
                            ui.owner.setTitle("1122111")
//                    ui.owner.setBackIcon(R.mipmap.ic_launcher)
                            ui.owner.setBackTextSize(16)
                            ui.owner.setBackTextColor(Color.WHITE)
                            ui.owner.setRightTextSize(16)
                            ui.owner.setRightTextColor(Color.WHITE)


                            ui.owner.setBackgroundColor(Color.parseColor("#222222"))

//                        val left=TextView(ctx)
//                        left.text="jbok返回"
//                        left.textSize=14f
//                        ui.owner.setBackView(left)
                            ui.owner.setBackIcon("123")
                            ui.owner.setRightIcon("返回ojbk")
                        }
//                    viewModelSafe.notifyChange()

                    }
                }
                lparams {
                    width = ViewGroup.LayoutParams.MATCH_PARENT
                    height = ViewGroup.LayoutParams.MATCH_PARENT
                }
            }
            lparams {
                width = ViewGroup.LayoutParams.MATCH_PARENT
                height = ViewGroup.LayoutParams.MATCH_PARENT

                behavior = AppBarLayout.ScrollingViewBehavior()
            }
        }

**Comment by scwang90** [comment]
smart 内部需要放置 RecyclerView 或者 NestedScrollView ，如果你的布局中确实不需要 RecyclerView 和 NestedScrollView ，你可以尝试 去掉 smart 保留 内部从 verticalLayout ，会有一样的问题存在，这个问题和 smart 无关

**Comment by vickyleu** [comment]
群主牛逼,问题不是smart造成的,因为coordinate需要一个可滚动布局来做behavior,而smart本身是一个ViewGroup的实现,所以无法滑动,只需要在smart外面包裹一层nestScrollview或者其他滚动布局就能解决问题了.贴个解决方案在这里,给大家参考

**Comment by scwang90** [comment]
smart 必须放在 滚动布局的外层 ，你这样做后面会有更严重的问题
