### ISSUE TITLE
上拉加载更多的问题

### ISSUE THREAD

**Issue by ProerMo** [scwang90/SmartRefreshLayout#376]
上拉加载更多时设置了app:srlEnableAutoLoadMore="false"，到底部后上拉一点点，布局上移了，不回弹。
使用版本是最新的版本

**Comment by scwang90** [comment]
最新版中没有发现这个问题，你需要提供更详细的信息，参考 提问必看

**Comment by ProerMo** [comment]
https://github.com/ProerMo/SmartScrollViewDemo.git 这是我的demo，上拉一点点，布局不会回弹，麻烦您看看，些邪恶

**Comment by scwang90** [comment]
这是一个特殊场景才出现的问题，感谢你提出来，你现在可以等待新版本的修复，如果想立马解决，可以打开下拉刷新功能，不要禁止，就好了，如果不想要下拉刷新功能的话，可以把 Header 换成 内置虚拟Header

**Comment by ProerMo** [comment]
内置虚拟Header是什么?

**Comment by ProerMo** [comment]
找到虚拟Header了，谢谢大佬

**Comment by spynokia** [comment]
@ProerMo  请问是哪个Api  虚拟头部?

**Comment by ProerMo** [comment]
@spynokia FalsifyHeader
