### ISSUE TITLE
关于当发生下拉刷新的时候，手指向上拖拽。

### ISSUE THREAD

**Issue by leiiiooo** [scwang90/SmartRefreshLayout#377]
请问，当发生下拉刷新的时候，能否禁止手指拖拽关闭刷新。因为如果在中间状态下松开手指，此时动画还在播放，但是由于我们按照下拉百分比进行图片缩放的，此时动画会缩小，显得十分诡异。或者说现在已经有了关于次操作的api。

**Comment by scwang90** [comment]
有一个，刷新是禁止手势操作的功能，不过建议你在刷新的时候，根据状态不要去改变图片缩放
