### ISSUE TITLE
有没有办法代码移除 FixedHeaderView 方法，或者移除 FixedHeaderView 底部站位 Space 的方法

### ISSUE THREAD

**Issue by ImportEffort** [scwang90/SmartRefreshLayout#378]
我们产品需求是在横屏的时候隐藏 FixedHeaderView 但是设置FixedHeaderView为 Gone 以后，底部占位符仍存在。如下图所示：
[横屏后图片](https://ws3.sinaimg.cn/large/006tNc79ly1fo8vswasx3j30k00zkdhq.jpg)
[竖屏图片](https://ws2.sinaimg.cn/large/006tNc79ly1fo8vss2kk5j30k00zkmzp.jpg)

**Comment by scwang90** [comment]
Android 屏幕旋转是好像是会重新调用 onCreate 方法，和再次创建视图，有两种方法你可以参考一下
1. 禁用横屏功能
2. 分别为横屏和竖屏写两个 xml，他们的差别就在于，srlFixedHeaderViewId  的指定
3. 在xml 中 不要使用 srlFixedHeaderView Id，在 java中判断是竖屏之后使用 setFixedHeaderViewId
