### ISSUE TITLE
为什么这个上拉加载了以后 那个scroll那个滑动会重置到顶部

### ISSUE THREAD

**Issue by jjjjbababy** [scwang90/SmartRefreshLayout#379]
为什么这个上拉加载了以后 那个scroll那个滑动会重置到顶部

**Comment by liuleshuai** [comment]
view.loadUrl(String.format(Locale.CHINA, "javascript:document.body.style.paddingTop='%fpx'; void 0", DensityUtil.px2dp(webView.getPaddingTop())));
每次加载Web页面，整体下移，会闪一下

**Comment by scwang90** [comment]
Adapter适配器 的问题
