### ISSUE TITLE
能不能让Header显示一部分出来

### ISSUE THREAD

**Issue by coderloveryan** [scwang90/SmartRefreshLayout#388]
我们的需求是header显示一部分出来下拉时从显示的那部分开始下拉然后绘制贝塞尔曲线。我试过setRefreshHeader方法传入宽高发现不起作用，header默认还是整体隐藏

**Comment by scwang90** [comment]
不支持，可以参考纸飞机Header，内外结合

**Comment by mengchaoshen** [comment]
这个问题，最后解决了吗？我也有需要
