### ISSUE TITLE
上拉加载无法触发？

### ISSUE THREAD

**Issue by AcgnCodeMonkey** [scwang90/SmartRefreshLayout#39]
从 TwinklingRefreshLayout过来的，发现确实借鉴了很多 TwinklingRefreshLayout的东西，不过我为什么滑到底也无法触发上拉加载事件？难道需要设置什么特殊属性？

**Comment by scwang90** [comment]
setEnableLoadmore(true)
或者
srEnableLoadmore = true


上面其中一个加上加上
setLoadmoreFinish(false)

**Comment by AcgnCodeMonkey** [comment]
依然不行，我是直接用在项目里的，加了点封装的，我试试单独写个Demo

**Comment by AcgnCodeMonkey** [comment]
demo测试确实是可以上拉加载的，目前怀疑和侧滑菜单可能有冲突，我研究下

**Comment by AcgnCodeMonkey** [comment]
@scwang90 已经找到原因了，是因为和BaseRecyclerViewAdapterHelper这个库的添加footer功能冲突，我添加了footer造成上拉刷新的view出不来了，因为我的footer本来是全部数据加载完成才显示的，但是应该是被当成上拉view了，因为他默认是隐藏的

**Comment by AcgnCodeMonkey** [comment]
addFooterView(mFooter);

**Comment by AcgnCodeMonkey** [comment]
@scwang90 额外补充一个bug，配合recyclerview使用时，如果recyclerview向下拉动过猛的话，会因为recyclerview回弹，被刷新header遮住头部



![qq 20170713163406](https://user-images.githubusercontent.com/19161307/28157781-25e90466-67ea-11e7-8861-1d1c4bd819d3.png)

**Comment by scwang90** [comment]
第一个问题解决了可以的，你后面这个bug 很难理解，可以做成gif或者MP4吗

**Comment by AcgnCodeMonkey** [comment]
@scwang90 请注意看第三次下拉时的效果，视频链接https://pan.baidu.com/s/1qYdR6t2

**Comment by scwang90** [comment]
你使用的版本是？

**Comment by AcgnCodeMonkey** [comment]
@scwang90  compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.1'
    compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.1'

**Comment by scwang90** [comment]
你换成新版本试试

**Comment by AcgnCodeMonkey** [comment]
@scwang90 新版本已解决，我先去打赏一波，O(∩_∩)O哈！

**Comment by yuxingfafu** [comment]
BaseRecyclerViewAdapterHelper 使用这个还是不会加载更多，用的版本是
    compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.3'
    compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.3'//没有使用特殊Header，可以不加这行
