### ISSUE TITLE
在BottomSheetDialog的布局中使用这个库会出现问题

### ISSUE THREAD

**Issue by Vixb1122** [scwang90/SmartRefreshLayout#390]
在BottomSheetDialog中使用这个库，列表只能向上滑动，不能向下滑动。
就算禁用刷新也没用

**Comment by scwang90** [comment]
和 BottomSheetDialog 无关，是你列表的问题

**Comment by g19980115** [comment]
SmartRefreshLayout布局加上`app:srlEnableNestedScrolling="false"`可以解决这个问题，亲测
版本是`com.scwang.smart:refresh-layout-kernel:2.0.0`

**Comment by TheMandalorianHub** [comment]
似乎没发获取2.0.0的包了，编译获取提示502了。然后用最新的包2.0.5尝试增加这个属性，还是不兼容无法解决
