### ISSUE TITLE
我是中国人，但我翻译完了才发现是中国人在维护，算了我不改了。

### ISSUE THREAD

**Issue by lblblong** [scwang90/SmartRefreshLayout#391]
My English is not good, so this is translated from Google.
Suppose I do not have a network now, request a list ~
Oh, the request failed, there is no network!
Immediately display the wrong interface
When I touch the wrong interface to request again
The last refresh animation is not over
Cause this time the refresh lost
Nor will call back to the code to display the wrong interface
For this problem, my approach is:
When the request fails, the delay of two seconds, waiting for the refresh animation is completed, and then display the wrong interface.
Is there a better solution?

**Comment by scwang90** [comment]
用 finishRefresh(0) 强制结束刷新动画

**Comment by lblblong** [comment]
@scwang90 
我尝试了一下，当我使用 finishRefresh(0) 结束刷新后，很快速的再一次触发刷新，会出现刷新动画闪动一下马上消失不见。
但是使用 finishRefresh(0) 结束刷新后稍微等待一下，大概 Header 完全回弹的时间的样子，再次触发刷新，就没有问题。
经典刷新动画，和贝塞尔雷达，弹出圆圈，都会出现这个情况

**Comment by scwang90** [comment]
finishRefresh(0) 也会有一个关闭动画，要一些时间，你给你的行刷新请求添加一个额 250 的动画延时应该就可以了

**Comment by zcm-hu** [comment]
@lblblong 好的，谢谢，我再看一下吧

**Comment by umeitime** [comment]
希望能够支持像微博那种，直接回弹回去后，再刷新，不用等待动画。

**Comment by hxkdidi** [comment]
建议将动画结束的回调暴露出来
