### ISSUE TITLE
上拉加载更多，无法回弹的问题

### ISSUE THREAD

**Issue by maola2000** [scwang90/SmartRefreshLayout#393]
代码如下：
final RefreshLayout refreshLayout = (RefreshLayout) findViewById(R.id.refreshLayout);
refreshLayout.setEnableRefresh(false);
refreshLayout.setEnableAutoLoadMore(false);

上述代码现象：
在用户手动滑动“上拉加载更多”，没有触发回弹动画。

追查结果：
SmartRefreshLayout类中，1489行
mKernel.setState(RefreshState.PullDownCanceled);
状态是否应该是
mKernel.setState(RefreshState.PullUpCanceled);

**Comment by scwang90** [comment]
新版中已经解决
