### ISSUE TITLE
setNoMoreData问题

### ISSUE THREAD

**Issue by GodFan4** [scwang90/SmartRefreshLayout#396]
版本：1.1.0-alpha-1
设置setNoMoreData(true)依然可以上拉出现Footer，只是不执行onLoadMore方法

1.0.1版本时用的是setLoadmoreFinished

**Comment by scwang90** [comment]
这个并不是问题，也不是bug，设计就是这样的，如果你不希望能拉出footer，你应该用 setEnableLoadMore(false) 而不是 setNoMoreData(true)

这个正是 setNoMoreData 和 setEnableLoadMore 的差别所在

**Comment by GodFan4** [comment]
明白了，3Q
