### ISSUE TITLE
示例Basic列表下拉抖动

### ISSUE THREAD

**Issue by lancewong2014** [scwang90/SmartRefreshLayout#40]
重现：
示例Basic列表，在有数据的情况下。先稍微向下滚动，使可见的数据第一条为“第02条数据”之后的数据，再往回滚，“第01条数据”到“第00条数据”之间会有一个抖动跳跃。

**Comment by scwang90** [comment]
好的，谢谢你的反馈，确实存在，修复之后新版本会发出

**Comment by scwang90** [comment]
问题已经解决 1.0.2-alpha-5 发布
