### ISSUE TITLE
随意下拉就能把下拉头给拉出来，真的好？？

### ISSUE THREAD

**Issue by docwei2050** [scwang90/SmartRefreshLayout#400]
有一个问题就是这样的，，，我在页面中部进行下拉操作，下滑的惯性能把下拉刷新头刷出来，这不好吧，，，一般都是RecyclerView最顶部的item完全可见的时候，此时做下拉时才能把刷新头拉出来啊，，，，你这个动不动就能把刷新头拉下来，，不行的啊。。。

**Comment by scwang90** [comment]
关闭越界回弹就好了
