### ISSUE TITLE
BUG 下拉展示淘宝二楼，一楼布局没有完全被顶下去

### ISSUE THREAD

**Issue by SheepYang1993** [scwang90/SmartRefreshLayout#402]
![screenshot_2018-03-12-17-15-32-799_com scwang ref](https://user-images.githubusercontent.com/15150244/37275086-3a68b3bc-2619-11e8-85cd-8dafd61e393a.png)

**Comment by scwang90** [comment]
这个不是 bug，demo就是这么设计的
