### ISSUE TITLE
上拉加载更多跑到最上面了，而且怎么都隐藏不了，，，

### ISSUE THREAD

**Issue by yongfengnice** [scwang90/SmartRefreshLayout#403]
![bug](https://user-images.githubusercontent.com/8778433/37295265-b1ca1502-2652-11e8-93a6-839e17def6c4.png)

**Comment by scwang90** [comment]
哪个版本？

**Comment by ldpadelin** [comment]
我的是下拉刷新跑下来了，收不回去，我已经提了一个issue，版本1.0.4

**Comment by Eaydroid** [comment]
请问是怎么解决的，我目前也偶现过几次 @yongfengnice @scwang90
