### ISSUE TITLE
autoRefresh自动刷新刷新头部混乱的问题

### ISSUE THREAD

**Issue by ldpadelin** [scwang90/SmartRefreshLayout#404]
我遇到一个场景，是fragment+viewpager，其中fragment嵌套两层，外层4个tab，里层一共有14个tab，每个tab都在onCreateView方法中调用了refreshLayout.autoRefresh()方法，但是当我快速切换tab时候有可能会出现刷新头部混乱的情况，例如有的头部无法再拉下来，有的tab小箭头无法收回去，请问大神这个问题有没有解决办法？非常感谢！！！（PS：使用版本1.0.4）

![screenshot](https://user-images.githubusercontent.com/15277653/37401158-24b88dc6-27c2-11e8-848d-da2b3c7ea278.png)

**Comment by scwang90** [comment]
使用 1.0.5-1 新版本

**Comment by ruanbaojun1105** [comment]
我倒觉得是你的fragment+viewpager写的有问题----
