### ISSUE TITLE
关于“刷新完成”

### ISSUE THREAD

**Issue by hegelsu** [scwang90/SmartRefreshLayout#405]
我现在的想法是，下拉后在请求数据后因为我会去刷新列表，那么在视觉上会有一个明显的变化，用户也知道拉到数据了且刷新了，也就是在请求数据后我不再需要刷新控件去显示“刷新完成”，也不要回弹动画，就是说我拿到数据后，我自己去刷新列表就可以了，刷新控件就不需你再做任何事情，直接消失不见
现在的做法是把回调动画设为0，可以快速的回弹回去，但是那个“刷新完成”的不知道怎么去掉？

**Comment by scwang90** [comment]
把时间设置为0 就好了

**Comment by hegelsu** [comment]
SetReboundDuration(0);
FinishRefresh(0);
以上两个设为0还是会显示“刷新完成”这几个字后再回弹回去的。

**Comment by scwang90** [comment]
是 footer 的属性

**Comment by hegelsu** [comment]
怎么是Footer的属性呢
![1](https://user-images.githubusercontent.com/6879123/37467929-8583f264-289c-11e8-9eb6-66e61f5a3648.png)
如下图，我希望不显示红色区域这个直接回弹即可

**Comment by hegelsu** [comment]
另外每次启动程序运行没什么问题不过有个错误如下，你看看有没有用？
03-15 22:24:28.957 W/EGL_emulation( 4406): eglSurfaceAttrib not implemented
03-15 22:24:28.993 W/System.err( 4406): java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
03-15 22:24:28.993 W/System.err( 4406): 	at com.scwang.smartrefresh.layout.SmartRefreshLayout$3.run(SmartRefreshLayout.java:439)
03-15 22:24:28.993 W/System.err( 4406): 	at com.scwang.smartrefresh.layout.util.DelayedRunnable.run(DelayedRunnable.java:14)
03-15 22:24:28.993 W/System.err( 4406): 	at android.os.Handler.handleCallback(Handler.java:725)
03-15 22:24:28.993 W/System.err( 4406): 	at android.os.Handler.dispatchMessage(Handler.java:92)
03-15 22:24:28.993 W/System.err( 4406): 	at android.os.Looper.loop(Looper.java:137)
03-15 22:24:28.993 W/System.err( 4406): 	at android.app.ActivityThread.main(ActivityThread.java:5069)
03-15 22:24:28.993 W/System.err( 4406): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-15 22:24:28.993 W/System.err( 4406): 	at java.lang.reflect.Method.invoke(Method.java:511)
03-15 22:24:28.993 W/System.err( 4406): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-15 22:24:28.993 W/System.err( 4406): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
03-15 22:24:28.993 W/System.err( 4406): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by scwang90** [comment]
说错了，是Header的属性

**Comment by hegelsu** [comment]
我用的是最新1.10版，能说下具体是哪个属性吗，我每个属性都看了的，没有发现是哪个啊

**Comment by scwang90** [comment]
是的
