### ISSUE TITLE
上拉加载更多的时候，正在加载中不能滑动

### ISSUE THREAD

**Issue by zou1755815609** [scwang90/SmartRefreshLayout#408]
上拉加载更多的时候，正在加载中不能滑动，得加载完成，并把数据添加成功了才能继续滑动？

**Comment by zou1755815609** [comment]
加载完成这行字会显示10几秒，并且期间不能滑动

**Comment by zou1755815609** [comment]
demo使用界面第一行的功能也是加载完成这行字会显示10几秒，并且期间不能滑动，这个如何解决

**Comment by scwang90** [comment]
你把时间改成 0 就好了
