### ISSUE TITLE
每次只要下拉刷新，内存就会增加7M左右，只要刷新一直往上飚，怀疑有内存泄露

### ISSUE THREAD

**Issue by hi2hcs** [scwang90/SmartRefreshLayout#411]
//导入的版本
    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.4-7'
    implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.4-7'//没有使用特殊Header，可以不加这行   

代码仅仅加了下面这个，xml里面没有头部和尾部，就用SmartRefreshLayout包裹了一下RecyclerView
然后就发生每次只要下拉刷新，内存就会增加7M左右，只要刷新一直往上飚，但leakcanary却没有检测出泄露，但肯定是有某个地方内存泄露了

static {
        //设置全局的Header构建器
        SmartRefreshLayout.setDefaultRefreshHeaderCreater(new DefaultRefreshHeaderCreater() {
            @Override
            public RefreshHeader createRefreshHeader(Context context, RefreshLayout layout) {
                layout.setPrimaryColorsId(R.color.colorPrimary, android.R.color.white);//全局设置主题颜色
                return new ClassicsHeader(context);//.setTimeFormat(new DynamicTimeFormat("更新于 %s"));//指定为经典Header，默认是 贝塞尔雷达Header
            }
        });
        //设置全局的Footer构建器
        SmartRefreshLayout.setDefaultRefreshFooterCreater(new DefaultRefreshFooterCreater() {
            @Override
            public RefreshFooter createRefreshFooter(Context context, RefreshLayout layout) {
                //指定为经典Footer，默认是 BallPulseFooter
                return new ClassicsFooter(context).setDrawableSize(20);
            }
        });
    }

**Comment by scwang90** [comment]
应该是你自己的问题

**Comment by hi2hcs** [comment]
是硬件加速的问题
