### ISSUE TITLE
ClassicsHeader经典布局下拉刷新的时候样式是类似对话框往下弹出

### ISSUE THREAD

**Issue by qssq** [scwang90/SmartRefreshLayout#414]
如何改成以前的经典刷新滚动，而不是刷新头区域弹出遮盖内容区

**Comment by qssq** [comment]
另外一个很郁闷的问题 
  ```         classicsHeader.setPrimaryColor(SuperAppContext.getInstance().getResources().getColor(R.color.colorWhite));//
            classicsHeader.setAccentColor(SuperAppContext.getInstance().getResources().getColor(R.color.colorThemeColor)); ```
//为什么反过来依然是背景是 主题色，我是想字体改成主题色，背景改成红色

**Comment by qssq** [comment]
我都怀疑是编译器问题了，搞不懂了

**Comment by scwang90** [comment]
你的这些问题，demo中都有例子，下载 demo 和源码，好好看看
setPrimaryColor 是背景颜色
setAccentColor 是字体颜色

**Comment by qssq** [comment]
表示设置了根本没用一直是背景是红色，文字是白色。郁闷死了我调试也没问题

**Comment by qssq** [comment]
另外一个问题你没回答啊，另外一个问题应该是个bug,设置classicsHeader之后 这进度还是往下弹出的，实际上我也没设置什么，demo也没看出啥问题

**Comment by qssq** [comment]
我说的进度往下弹出是直接谈到内容区了，跟那个android5.0风格的圆形进度一样往下弹出了，搞不懂啥问题，重新编译也还是这样。另外设置颜色也一直没用

**Comment by qssq** [comment]
最痛苦的问题莫过于此，明明一切正常，设置没问题，却不是我想要的结果

**Comment by qssq** [comment]
问题越来越严重了，现在进度永远不消失了
