### ISSUE TITLE
当SmartRefreshLayout内的滚动组件是ScrollView时，ScrollView里面的元素失去了点击事件

### ISSUE THREAD

**Issue by 2534290808** [scwang90/SmartRefreshLayout#417]
当SmartRefreshLayout内的滚动组件是ScrollView时，ScrollView里面的元素失去了点击事件

**Comment by scwang90** [comment]
没有发现，demo 总也有使用 ScrollView 的页面，请参考 demo 使用

**Comment by 2534290808** [comment]
我看大多数都是RecyclerView

**Comment by 2534290808** [comment]
还有就是Header继承ViewGroup时ScrollView会失去点击事件，如果Header继承View则正常

**Comment by scwang90** [comment]
搜索一下就有了
