### ISSUE TITLE
难道没有人遇到fragment切换各种错乱的问题？

### ISSUE THREAD

**Issue by LatoAndroidw** [scwang90/SmartRefreshLayout#42]
还是我使用replacefragment的方法不对应该用hide和show。。。

**Comment by scwang90** [comment]
应该是 replacefragment 的姿势不对，Demo中主页面也使用了 replacefragment

不过这确实是 SmartRefreshLayout 的一个bug，现在已经修复了，1.0.2-alpha-5 版本发布
