### ISSUE TITLE
QQ群满了, 加不进去, 只好来这里问了, 判断是否正在刷新的方法isRefreshing()废弃后, 没有新方法替代吗? 没有找到啊

### ISSUE THREAD

**Issue by imjackzhao** [scwang90/SmartRefreshLayout#421]
//<editor-fold desc="丢弃的API">

//    /**
//     * 是否正在刷新
//     * @return 是否正在刷新
//     */
//    @Override
//    public boolean isRefreshing() {
//        return mState == RefreshState.Refreshing;
//    }

**Comment by scwang90** [comment]
getState() == RefreshState.Refreshing
