### ISSUE TITLE
加载更多完成之后能不能不回弹

### ISSUE THREAD

**Issue by Lightning627** [scwang90/SmartRefreshLayout#423]
看了看写 自定义Footer的文档好像也没有看到相关的api。
就是希望能在加载更多完成后不移动列表，Footer直接消失，新数据显示在Footer的位置。而不是需要手动划一下才能看到新数据。

**Comment by scwang90** [comment]
你说的这个 demo 都有的，照着 demo 一步步来，就好了，不要去搞个性的用法
