### ISSUE TITLE
MaterialHeader  头部不消失

### ISSUE THREAD

**Issue by XXiaoQing** [scwang90/SmartRefreshLayout#428]
版本：1.0.5.1
情形：使用 MaterialHeader，调用 autoRefresh （手动不存在这个问题），请求成功后，调用 finishRefresh 
问题：MaterialHeader 不消失

**Comment by scwang90** [comment]
使用 autoRefresh(0)

**Comment by XXiaoQing** [comment]
按照上面的使用方法，没有解决问题。  这种情形也不是每次调用 autoRefresh 都会出现

**Comment by XXiaoQing** [comment]
@scwang90 按照上面的方法，没有解决问题，这种情形是偶尔出现的

**Comment by scwang90** [comment]
用 finishRefresh(1000)  是可以的
