### ISSUE TITLE
java.lang.IllegalStateException Already in the pool!

### ISSUE THREAD

**Issue by tudou0digua** [scwang90/SmartRefreshLayout#429]
Android 5.1.1,level 22  小米 MI 4C
Android 7.1.1,level 25  小米 MI NOTE 3
Android 7.0,level 24     荣耀 BLN AL40
Android 7.1.1,level 25  VIVO X20
Android 8.0.0,level 26  荣耀 DUK AL20
Android 7.1.1,level 25  OPPO R11
偶现：
google一下：可能是 velocitytracke 造成的
https://developer.android.com/training/gestures/movement.html
https://stackoverflow.com/questions/26074907/velocitytracker-causes-crash-on-android-4-4

1 android.support.v4.i.n$b.release(Pools.java:113)
--
2 android.support.v7.widget.e.recycleUpdateOp(AdapterHelper.java:742)
3 android.support.v7.widget.e.a(AdapterHelper.java:749)
4 android.support.v7.widget.e.c(AdapterHelper.java:122)
5 android.support.v7.widget.e.e(AdapterHelper.java:556)
6 android.support.v7.widget.RecyclerView.K(RecyclerView.java:3531)
7 android.support.v7.widget.RecyclerView.n(RecyclerView.java:3266)
8 android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
9 android.view.View.layout(View.java:15718)
10 android.view.ViewGroup.layout(ViewGroup.java:5039)
11 com.scwang.smartrefresh.layout.d.a.layout(RefreshContentWrapper.java:182)
12 com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:722)
13 android.view.View.layout(View.java:15718)
14 android.view.ViewGroup.layout(ViewGroup.java:5039)
15 android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
16 android.view.View.layout(View.java:15718)
17 android.view.ViewGroup.layout(ViewGroup.java:5039)
18 android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
19 android.view.View.layout(View.java:15718)
20 android.view.ViewGroup.layout(ViewGroup.java:5039)
21 android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
22 android.view.View.layout(View.java:15718)
23 android.view.ViewGroup.layout(ViewGroup.java:5039)
24 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
25 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
26 android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
27 android.view.View.layout(View.java:15718)
28 android.view.ViewGroup.layout(ViewGroup.java:5039)
29 android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
30 android.widget.FrameLayout.onLayout(FrameLayout.java:514)
31 android.view.View.layout(View.java:15718)
32 android.view.ViewGroup.layout(ViewGroup.java:5039)
33 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
34 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
35 android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
36 android.view.View.layout(View.java:15718)
37 android.view.ViewGroup.layout(ViewGroup.java:5039)
38 android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
39 android.widget.FrameLayout.onLayout(FrameLayout.java:514)
40 android.view.View.layout(View.java:15718)
41 android.view.ViewGroup.layout(ViewGroup.java:5039)
42 android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2129)
43 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
44 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1103)
45 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5944)
46 android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
47 android.view.Choreographer.doCallbacks(Choreographer.java:601)
48 android.view.Choreographer.doFrame(Choreographer.java:571)
49 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
50 android.os.Handler.handleCallback(Handler.java:739)
51 android.os.Handler.dispatchMessage(Handler.java:95)
52 android.os.Looper.loop(Looper.java:135)
53 android.app.ActivityThread.main(ActivityThread.java:5298)
54 java.lang.reflect.Method.invoke(Native Method)
55 java.lang.reflect.Method.invoke(Method.java:372)
56 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
57 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)

**Comment by scwang90** [comment]
这个错误 和 smart 无关
