### ISSUE TITLE
StoreHouseHeader不能定义中文字符

### ISSUE THREAD

**Issue by Huwei1993** [scwang90/SmartRefreshLayout#433]
<com.scwang.smartrefresh.header.StoreHouseHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:shhText="@string/load_more"
            app:shhEnableFadeAnimation="true"/>

 app:shhText="@string/load_more"这个属性值不能写中文字符？
load_mare 是中文字符“加载更多...”
报错：
com.scwang.refreshlayout.app, PID: 9666
  android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class com.scwang.smartrefresh.header.StoreHouseHeader

写英文属于正常，怎么修改成可以写中文？

**Comment by scwang90** [comment]
看 demo
