### ISSUE TITLE
与RecyclerView的下拉冲突

### ISSUE THREAD

**Issue by suarezu** [scwang90/SmartRefreshLayout#436]
在mix2s和模拟器上都测试过，refreshEnabled/loadMoreDisabled, 如果RecyclerView里的item超过一竖屏，则向上拖到底部，此时：
1.如果向下滑动屏幕，则RecyclerView里的内容并不先滑动到第0个item，再refresh的header显示出来，而是直接显示header，就像RecyclerView里的内容不可滑动一样；
2.如果先向上滑动一下再向下滑动一下，则和预期的一样：RecylerView里的内容在向上滑动时保持在底部，随后的向下滑动会让RecylerView里的内容滑动到item0，然后再显示header。

我是一个Activity里面放多个fragment，activity的layout如下：

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/darker_gray">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:subtitleTextAppearance="@style/AppTitle.subtitle"
            app:titleTextAppearance="@style/AppTitle">

            <ProgressBar
                android:id="@+id/progress"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="end"
                android:backgroundTintMode="src_in"
                android:indeterminateTint="@android:color/white"
                android:padding="8dp"
                android:visibility="gone" />
        </android.support.v7.widget.Toolbar>
    </android.support.design.widget.AppBarLayout>

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refresher"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/appbar"
        app:srlAccentColor="@android:color/white"
        app:srlPrimaryColor="@color/colorPrimary">

        <com.scwang.smartrefresh.header.BezierCircleHeader
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <FrameLayout
            android:id="@+id/arena"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:padding="16dp" />
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</RelativeLayout>
`

**Comment by scwang90** [comment]
你的问题应该是一个常见问题，你提供的代码 在 demo 中也有这样的结构，demo 中是不存在这个问题的，一般这个的问题常见的原因有：
1.Adapter 有关，比如 Adapter 隐藏了某个 Item或者 把 item高度设为0
2.你肯那个在 FrameLayout 添加了 RecyclerView和其他 View，而其他View 挡住了，RecyclerView

如果这两个原因都不是，你需要加群，提供详细的 代码和描述，和错误演示视频。

**Comment by suarezu** [comment]
app:srlEnableNestedScrolling="true"，这样就好了，没想到这个缺省值是false

**Comment by cheetah747** [comment]
> app:srlEnableNestedScrolling="true"，这样就好了，没想到这个缺省值是false

マジすげーわ、誠に感謝!
