### ISSUE TITLE
麻烦回答一下关于事件冲突的问题

### ISSUE THREAD

**Issue by ZHughZhang** [scwang90/SmartRefreshLayout#438]
代码如下
`<android.support.design.widget.CoordinatorLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/CoordinatorLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#000000">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/AppBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/black"
        app:theme="@style/ToolbarTheme">

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/CollapsingToolbarLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:contentScrim="@color/black"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:navigationIcon="@mipmap/fanhui">
            <android.support.v7.widget.Toolbar
                android:id="@+id/Toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="#00ffffff"
                android:gravity="center_vertical"
                android:visibility="visible"
                app:layout_collapseMode="pin"
                app:navigationIcon="@mipmap/fanhui"
                app:theme="@style/ToolbarTheme"
                app:titleTextColor="#ffffff">

                <TextView
                    android:id="@+id/title"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginRight="@dimen/size_200pt"
                    android:gravity="center"
                    android:text="个人详情"
                    android:textColor="@color/white"
                    android:textSize="@dimen/size_50pt"
                    android:textStyle="bold"
                    android:visibility="gone" />
            </android.support.v7.widget.Toolbar>
        </android.support.design.widget.CollapsingToolbarLayout>

        <android.support.design.widget.TabLayout
            android:id="@+id/tablayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tabBackground="@drawable/tab_indicator"
            app:tabIndicatorHeight="0dp"
            app:tabSelectedTextColor="@color/white"
            app:tabTextColor="@color/white">

        </android.support.design.widget.TabLayout>
    </android.support.design.widget.AppBarLayout>

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/act_refreshlayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <com.kushao.takeout.ui.view.NoScrollViewPager
            android:id="@+id/act_viewpager"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:overScrollMode="never">

        </com.kushao.takeout.ui.view.NoScrollViewPager>

        <com.scwang.smartrefresh.layout.footer.ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</android.support.design.widget.CoordinatorLayout>`
当我在Viewpage里面添加Fragment，Fragment里面有RecycleView 的时候会事件冲突吗？
我看见demo里面SmartRefreshLayout+Viewpage 是没有事件冲突的,但是如次布局的时候事件冲突了。

**Comment by scwang90** [comment]
看你提供的 xml布局看不出问题源因，关键问题应该出于 ViewPager 的内部View
1.你可以尝试开启 smart 的潜逃滚动功能（估计没用）
2.你可以检查一下你的 Adapter 是否正常使用（有没有 隐藏某个Item 或者 Item高度设为0）
3.你可以把 smart 换成 谷歌官方的 刷新控件，看看问题是否同样存在（来确定是否Smart 的问题）
