### ISSUE TITLE
在fragment使用时出现了以下问题

### ISSUE THREAD

**Issue by kangzhenguo** [scwang90/SmartRefreshLayout#439]
W/System.err: java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
W/System.err:     at com.scwang.smartrefresh.layout.SmartRefreshLayout$3.run(SmartRefreshLayout.java:448)
W/System.err:     at com.scwang.smartrefresh.layout.util.DelayedRunnable.run(DelayedRunnable.java:14)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)

**Comment by scwang90** [comment]
使用文档中的 最新版本就好了
