### ISSUE TITLE
金色校园效果出不来

### ISSUE THREAD

**Issue by zouzhenglu** [scwang90/SmartRefreshLayout#44]
如题，其他的样式效果能出来，试过了三种方式都不行

**Comment by scwang90** [comment]
你使用的版本是？可以贴出你的代码吗？

**Comment by zouzhenglu** [comment]
版本是1.0.1，代码写了几种，举个例子，就是在布局里面加了标签
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context="com.sqsd.homemaking.modules.MainActivity">

    <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

        <android.support.v7.widget.Toolbar
                app:layout_scrollFlags="scroll|enterAlwaysCollapsed|snap"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>

        <TextView
                android:id="@+id/tv"
                android:layout_width="match_parent"
                android:layout_height="40dp"
                android:text="Hello World!"/>
    </android.support.design.widget.AppBarLayout>

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/refresh"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            app:srlPrimaryColor="@color/colorPrimary"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        <com.scwang.smartrefresh.layout.header.ClassicsHeader
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>

        <android.support.v7.widget.RecyclerView
                android:id="@+id/rv"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>


</android.support.design.widget.CoordinatorLayout>
`
这里的classic我那时候用了金色校园那个就不行了，预览的时候可以看得到的

**Comment by scwang90** [comment]
代码没问题，你换成最新版本试试，如果还是有问题，截图来看看

**Comment by zouzhenglu** [comment]
升级后可以了。建议打个tag，方便大家查看已经出了哪些版本。#close

**Comment by scwang90** [comment]
谢谢提醒
