### ISSUE TITLE
是否可加入禁止下拉或上拉回弹效果的方法？

### ISSUE THREAD

**Issue by baiyuliang** [scwang90/SmartRefreshLayout#440]
是否可加入禁止下拉或上拉回弹效果的方法？也就是拉到底后不能再越界继续拉...

**Comment by baiyuliang** [comment]
setEnableOverScrollDrag这个方法并不起作用，所以不知道是我没理解对这个方法的作用还是什么0.0？版本1.0.5.1

**Comment by scwang90** [comment]
这是越界拖动，和越界回弹没关系，还是好好看文档吧
