### ISSUE TITLE
参数不匹配异常

### ISSUE THREAD

**Issue by shiyanjie** [scwang90/SmartRefreshLayout#446]
使用版本：
com.scwang.smartrefresh:SmartRefreshLayout:1.0.5

崩溃位置：
com.scwang.smartrefresh.layout.SmartRefreshLayout 》 drawChild（）

崩溃日志：
#7822 java.lang.IllegalArgumentException

radius must be > 0

com.scwang.smartrefresh.layout.SmartRefreshLayout.boolean drawChild(android.graphics.Canvas,android.view.View,long)

**Comment by scwang90** [comment]
这个错误和 smart 无关
