### ISSUE TITLE
onloadmorelistener中的onloadmore回调失效

### ISSUE THREAD

**Issue by 317764920** [scwang90/SmartRefreshLayout#448]
如果分开去监听是没有问题的
说错了，是onrefreshloadmorelistener

**Comment by scwang90** [comment]
提供的信息太少，没法帮你，而且这个问题几乎没人遇到过，你自己好好参考 demo 一步步来做吧

**Comment by 317764920** [comment]
好像今天又可以了- -
估计是缓存把
