### ISSUE TITLE
和ConstraintLayout布局的一个bug

### ISSUE THREAD

**Issue by laiying** [scwang90/SmartRefreshLayout#449]
布局如下:
<android.support.constraint.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
            android:id="@+id/title_bar"
            android:layout_width="match_parent"
            android:layout_height="@dimen/title_height"
            android:text="@string/picture_list"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            />

        <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/main_color"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/title_bar"
            app:srlAccentColor="@android:color/white"
            app:srlPrimaryColor="#444444">
            
            
            
            <com.scwang.smartrefresh.header.MaterialHeader
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="#fff"
                android:overScrollMode="never" />

            <com.scwang.smartrefresh.layout.footer.ClassicsFooter
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    </android.support.constraint.ConstraintLayout>
使用ConstraintLayout布局，title_bar并不显示出来，SmartRefreshLayout会把title_bar覆盖掉

**Comment by scwang90** [comment]
这个问题和 smart 无关

**Comment by LillteZheng** [comment]
确实不行呀，下载了demo，也没看到ConstraintLayout 的，建议作者试试呢
