### ISSUE TITLE
RecyclerView不显示内容，求救

### ISSUE THREAD

**Issue by chengzhijun0706** [scwang90/SmartRefreshLayout#455]
在fragment中使用刷新等，在布局树中是可以看到的，但是就是不显示
![image](https://user-images.githubusercontent.com/13751034/38803027-8a22e72c-41a0-11e8-9350-ab1aeeda6977.png)
![image](https://user-images.githubusercontent.com/13751034/38803071-a8adf7c2-41a0-11e8-950d-0abf2a5656f5.png)
![image](https://user-images.githubusercontent.com/13751034/38803103-c74da7ae-41a0-11e8-8946-5c14a38c0468.png)
![image](https://user-images.githubusercontent.com/13751034/38803186-03d9f998-41a1-11e8-9335-cd316789f7f2.png)

**Comment by scwang90** [comment]
这个情况没有遇见过，看你的代码操作也没有发现什么问题，你可以吧 你自定义的 Header Footer 换成自带的试试，如果还是不行， 建议下载 demo 一步一步参考来做

**Comment by chengzhijun0706** [comment]
我试过了，把header和footer都去掉，换是有问题，感觉好像是我的recyclerview没有让加载进来一样，可是在view树又是有的，我加您QQ了，您同意一下，很奇怪的问题，只要去掉就能显示


| |
me
邮箱：18804881344@163.com
|

签名由 网易邮箱大师 定制

在2018年04月16日 18:58，树朾 写道：

这个情况没有遇见过，看你的代码操作也没有发现什么问题，你可以吧 你自定义的 Header Footer 换成自带的试试，如果还是不行， 建议下载 demo 一步一步参考来做

**Comment by bunny-pu** [comment]
我也遇到这个情况了，求助啊
