### ISSUE TITLE
谷歌材质化风格头部有时候不消失大佬知道如何解决吗？

### ISSUE THREAD

**Issue by qssq** [scwang90/SmartRefreshLayout#456]
我发现使用谷歌的都有这个问题，我用您们这个也有这个概率发生

**Comment by scwang90** [comment]
没有遇过这个问题呢，你需要提供更详细的信息

**Comment by qssq** [comment]
...........这没法提供了，但是众所周知，很多人度知道材质化头部有bug,不过没想到你们的也有这个问题 ，
