### ISSUE TITLE
Android P上会出现java.lang.IllegalArgumentException  width and height must be > 0异常

### ISSUE THREAD

**Issue by JsonChao** [scwang90/SmartRefreshLayout#458]
![image](https://user-images.githubusercontent.com/17464480/38853223-247b4e14-424f-11e8-92ce-d401b507f108.png)

**Comment by JsonChao** [comment]
a nice tips： https://stackoverflow.com/questions/17605662/illegalargumentexception-width-and-height-must-be-0-while-loading-bitmap-from

**Comment by scwang90** [comment]
## 官方bug
经过分析，问题是在 Android P 开发者预览版中的 
~~~
android.graphics.Region 
~~~
类出现bug，无法计算矢量图的边缘尺寸，返回结果都是0

这个问题应该会在  Android P 正式版发布之后官方修复。

## 解决（仅兼容处理）
在这之前，已经发布
~~~
 1.1.0-alpha-5
~~~
 版本兼容这个问题。
