### ISSUE TITLE
在代码中添加的子控件（RecyclerView)会滑动冲突。

### ISSUE THREAD

**Issue by kaixuanluo** [scwang90/SmartRefreshLayout#466]
SmartRefreshLayout.addView(RecyclerView);

**Comment by scwang90** [comment]
使用 setRefreshContent 方法，使用 addView 在smart中不合法

**Comment by kaixuanluo** [comment]
用这个方法也会滑动冲突。

**Comment by kaixuanluo** [comment]
因为我的recyclerView外面嵌套了一层其他控件（FrameLayout），导致了滑动冲突，请问有什么解决方法吗？

**Comment by scwang90** [comment]
demo 中有很多页面 列表也是在 FrameLayout 内部的，参考一下
