### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1

### ISSUE THREAD

**Issue by EvlinLee** [scwang90/SmartRefreshLayout#468]
看到该close issue，我这边也遇到这个问题，网络应该没问题的

**Comment by scwang90** [comment]
你们下载不了，贴到这里我也不能帮你们解决啊，JCenter 又不是我家开的，这个版本不行换别的版本嘛

https://bintray.com/scwang90/maven/SmartRefreshLayout/1.0.5.1
