### ISSUE TITLE
淘宝二楼问题

### ISSUE THREAD

**Issue by tuzanhua** [scwang90/SmartRefreshLayout#473]
淘宝二楼目前存在的问题: 1.当我出发二楼之后上划手指不离开屏幕在某个位置header和content可以停止不动.(header无法正常回到顶部初始状态).
2. 只有demo 那种写法才正确,将demo的scrollview去掉 淘宝二楼就不是demo 的那种方式了(header方式为fixbehind 没看懂是怎么实现translation的功能的).

第二: 在现有的基础上如何实现 淘宝二楼header 为Translation 方式.(header 高度需要是matchpartent).

**Comment by scwang90** [comment]
1. 在demo的二楼页面中测试，再二楼状态不放手，并不会阻止 Header 回到初始状态。
2. 是的，要按照demo 操作，自己随意扩展的不行
3. 有办法实现的，好好阅读源码，不过也不简单，需要自己有自定义View基础，并不是简单的配置就得到
