### ISSUE TITLE
ClassicsHeader 在viewpager内fragment重建时高度错误

### ISSUE THREAD

**Issue by xiang23** [scwang90/SmartRefreshLayout#474]
外部为布局
        <android.support.v4.view.ViewPager
            android:id="@+id/content_view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
             />
使用 FragmentStatePagerAdapter 嵌套fragment
内部fragment布局
    <FrameLayout
        android:layout_width="match_parent"
        android:background="#f5f5f5"
        android:layout_height="match_parent">

        <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/smart_refresh_layout"
            android:layout_width="match_parent"
            android:background="#f5f5f5"
            android:layout_height="match_parent">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/content_recycler_view"
                android:layout_width="match_parent"
                android:paddingTop="5dp"
                android:layout_height="match_parent" />
        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    </FrameLayout>

正常使用一切正常，当配置引起fragment重建时出现高度错误如下图（非viewpager里并不会我使用BezierRadarHeader也不会有问题 就ClassicsHeader会有这个问题）
里面就使用setRefreshHeader（new ClassicsHeader（context））
版本1.0.5.1

![image](https://user-images.githubusercontent.com/14964761/39165917-841dbef0-47b9-11e8-8f93-c2a7714d5731.png)

**Comment by scwang90** [comment]
自动计算高度不对的话，setRefreshHeader 有另一个重载方法 可以指定一个高度的
