### ISSUE TITLE
ClassicsHeader背景色设置在replace的Fragment中无效

### ISSUE THREAD

**Issue by huburt-Hu** [scwang90/SmartRefreshLayout#477]
版本：1.0.5.1

场景是这样：
我设置了颜色，这里ReFreshLayout是SmartRefreshLayout的子类，只是用于打印日志
```
<com.banban.app.common.widget.ReFreshLayout
        android:id="@+id/refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlAccentColor="@android:color/white"
        app:srlEnableHeaderTranslationContent="true"
        app:srlEnableLoadMore="true"
        app:srlPrimaryColor="@color/colorPrimary">
```
![device-2018-04-26-164055](https://user-images.githubusercontent.com/18179161/39295414-f6d29d68-4970-11e8-9428-36bbb61cd3b5.png)

在第一个fragment中表现是正常的，然后我使用replace切换到第二个fragment（与第一个Fragment是同一个类的不同实例），表现是这样的，恢复了默认的颜色：
![device-2018-04-26-164120](https://user-images.githubusercontent.com/18179161/39295491-2783c8a6-4971-11e8-8724-3131189c5110.png)

我追踪过代码，了解到header的背景色是在SmartRefreshLayout类的设置的
```
    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        if (mPrimaryColors != null) {
            mRefreshHeader.setPrimaryColors(mPrimaryColors);
            mRefreshFooter.setPrimaryColors(mPrimaryColors);
        }
    }
```
通过日志可以看到第一个Fragment：
```
onAttachedToWindow:[-12478731, -1]
setPrimaryColor(Color:-12478731)
onInitialized:-12478731
```
而第二个Fragment：
```
onAttachedToWindow:[-12478731, -1]
onInitialized:0
```
对比出第二个Fragment没有执行setPrimaryColor方法。

但是诡异的是，我通过断点查看过程发现程序明明是执行了setPrimaryColor方法的。从整个逻辑看mPrimaryColors在构造中就完成了初始化，不可能为null，因此代码层面也应该是会执行的。可是日志以及最终的效果反应都是没有执行。

我bebug了一下午也没有想明白到底是哪个环节出了问题。不知道作者能否解答的疑惑，万分感谢！

**Comment by Vence0815** [comment]
我也遇到了，最后发现是application里面设置了默认颜色，把application里面的改了就好了

**Comment by scwang90** [comment]
经过测试，没有发现楼主提出的诡异现象，不过问题确实存在，问题和 Vence0815 分析的一样，xml中没有直接指定 Header 的话，会使用全局默认的 Header ，同时主题颜色也会被全局设置的覆盖。新版本将提供一个独立的全局属性设置 ，并设置优先级为最低，不会覆盖 Xml中设置的任何值。
