### ISSUE TITLE
猜测应该是嵌套引起的

### ISSUE THREAD

**Issue by tuzanhua** [scwang90/SmartRefreshLayout#478]
CoordinatorLayout +  appbarlayout + smartRefresh  + recycerview  会有类似的这种问题
下面是视频转换的gif地址

[https://media.giphy.com/media/5nbf3r1VDK3lPem831/giphy.gif](url)

**Comment by tuzanhua** [comment]
[https://media.giphy.com/media/5nbf3r1VDK3lPem831/giphy.gif](url)

**Comment by tuzanhua** [comment]
经过调试发现是由于回调了 onNestedScroll 方法同时 dyUnconsumed 未消费的y轴方向的值会突然变得很大.

代码按照下面修改发现可以处理嵌套的问题,但是会有一个新的问题 dDy  这个值到底取多少比较合适?会影响快速的收拾滑动(快速下拉或者两个手指快速替换着下拉) 希望作者可以给个建议如何优雅的避免新出现的问题:

    protected int oldDyUnconsumed;

    @Override
    public void onNestedScroll(@NonNull View target, int dxConsumed, int dyConsumed, int dxUnconsumed, int dyUnconsumed) {
        // Dispatch up to the nested parent first
        mNestedChild.dispatchNestedScroll(dxConsumed, dyConsumed, dxUnconsumed, dyUnconsumed, mParentOffsetInWindow);
        // This is a bit of a hack. Nested scrolling works from the bottom up, and as we are
        // sometimes between two nested scrolling views, we need a way to be able to know when any
        // nested scrolling parent has stopped handling events. We do that by using the
        // 'offset in window 'functionality to see if we have been moved from the event.
        // This is a decent indication of whether we should take over the event stream or not.
        if (oldDyUnconsumed != 0) {
            int dDy = Math.abs(Math.abs(dyUnconsumed) - Math.abs(oldDyUnconsumed));
            oldDyUnconsumed = dyUnconsumed;
            if (dDy > 50) {

            } else {
                int dy = dyUnconsumed + mParentOffsetInWindow[1];
                if (dy != 0 && (mEnableOverScrollDrag || (dy < 0 && isEnableRefresh()) || (dy > 0 && isEnableLoadMore()))) {
                    if (mViceState == RefreshState.None) {
                        mKernel.setState(dy > 0 ? RefreshState.PullUpToLoad : RefreshState.PullDownToRefresh);
                    }
                    moveSpinnerInfinitely(mTotalUnconsumed -= dy);
                }
            }
        } else {
            oldDyUnconsumed = dyUnconsumed;
            int dy = dyUnconsumed + mParentOffsetInWindow[1];
            if (dy != 0 && (mEnableOverScrollDrag || (dy < 0 && isEnableRefresh()) || (dy > 0 && isEnableLoadMore()))) {
                if (mViceState == RefreshState.None) {
                    mKernel.setState(dy > 0 ? RefreshState.PullUpToLoad : RefreshState.PullDownToRefresh);
                }
                moveSpinnerInfinitely(mTotalUnconsumed -= dy);
            }
        }

    }

**Comment by scwang90** [comment]
是的，有问题，不过最近比较忙，后面的版本会优化这些问题，感谢你提出来，那么溜的操作，才能看出这些问题

**Comment by tuzanhua** [comment]
嵌套引起的问题,目前解决方案在自定义的header中动态的设置SmartRefreshLayout的是否可以使用嵌套滚动setNestedScrollingEnabled.

在刷新的状态为None的时候设置为true,在finish 的时候设置为false .  解决跳动的问题的方案.

**Comment by heiniuniu** [comment]
@tuzanhua gif打不开了。方便再发一下吗 ? 我可能遇到了跟你相同的问题。

**Comment by tuzanhua** [comment]
@heiniuniu  复制链接然后在浏览器上直接打开就行了. 另外这个跳动可以通过上面那种方式处理一下.

**Comment by scwang90** [comment]
新版本已经解决了这个问题

**Comment by blackberry2016** [comment]
NestedScrollView还是存在该问题

**Comment by yuan7016** [comment]
我把 smartRefresh 放在了最外层，里面有CoordinatorLayout + NestedScrollView+RecyclerVIew  感觉还行.
