### ISSUE TITLE
淘宝二楼

### ISSUE THREAD

**Issue by tuzanhua** [scwang90/SmartRefreshLayout#479]
问题出现步骤: 下拉到进入二楼的状态,松手进入二楼的过程中,手指重新按到屏幕上,refreshcontet停止滚动到底部. 下面是gif,video的链接(复制链接到地址栏可以查看(直接跳转找不到资源)).
[https://giphy.com/gifs/1BdJdt9kqBBthjydFo/html5](url)

[https://media.giphy.com/media/1BdJdt9kqBBthjydFo/giphy.gif](url)

**Comment by scwang90** [comment]
你的操作很666呀，非常感谢，后面的版本应该可以优化这个问题

**Comment by zy4569575** [comment]
问题解决了吗？我也遇到这个问题了。

**Comment by scwang90** [comment]
新版本已经解决这个问题
