### ISSUE TITLE
没有更多数据后，为什么还能往上拉

### ISSUE THREAD

**Issue by liulance** [scwang90/SmartRefreshLayout#481]
您好，在没有更多数据后，设置了RefreshLayout.setNoMoreData(true);，但是往上拉的时候，还能看到footer，能否设置，没有更多数据，就不能往上拉了？footer隐藏，谢谢

**Comment by scwang90** [comment]
具体使用方法看 demo 吧，demo 中有例子的

**Comment by liulance** [comment]
@scwang90 麻烦说下demo在哪个页面，我没看到这个功能呢？谢谢

**Comment by scwang90** [comment]
基本使用

**Comment by liulance** [comment]
您好，你demo上面
![image](https://user-images.githubusercontent.com/22095781/39407224-1500b1ae-4bf5-11e8-8330-515695ef841a.png)没有更多后，这个会一直显示，我现在的需求是，没有更多后，下面的footer隐藏不显示，请问怎么设置，谢谢

**Comment by scwang90** [comment]
关闭上啦功能就好了

**Comment by superzhangbao** [comment]
@liulance mSmartRefreshLayout.setEnableLoadMore(false);
