### ISSUE TITLE
在ViewPager中，会有左右滑动的问题

### ISSUE THREAD

**Issue by yanfulei** [scwang90/SmartRefreshLayout#482]
在ViewPager中，慢慢往一个方向拖，会拖出来第二个ViewPager
![image](https://user-images.githubusercontent.com/13723893/39408263-24aec3be-4c06-11e8-93cb-ebf2f8b56752.png)
版本

    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1'
    implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.5.1'

**Comment by scwang90** [comment]
ViewPager 的使用参考 demo ，都有例子的
