### ISSUE TITLE
在SmartRefreshLayout中使用viewstub的问题

### ISSUE THREAD

**Issue by wenjian1314** [scwang90/SmartRefreshLayout#483]
SmartRefreshLayout只有一个子view是viewstub，在onrefresh中调用viewstub.inflate()时，viewstub所引用的布局并不显示。但如果将SmartRefreshLayout改为其他的布局（如FrameLayout），则调用viewstub.inflate()时可以正常显示viewstub所引用的布局。

**Comment by scwang90** [comment]
是的，必须使用 FrameLayout，只有 smart 是不行的
