### ISSUE TITLE
如何借助现有的属性方法实现自动回弹功能

### ISSUE THREAD

**Issue by zwping** [scwang90/SmartRefreshLayout#485]
来源启发于斗鱼Windows客户端，从底部快速滑动至顶部会有一个轻微的缓冲过程

简化代码过程是：scrollTo(0,-50) -> scrollTo(0,0)，这个位移过程持续200ms

通过SmartRefreshLayout嵌套的布局应当怎么实现这个现象呢？

**Comment by scwang90** [comment]
自动回弹功能已经自带了，也默认开启的
