### ISSUE TITLE
滑到底部，再往上滑动出现卡顿，不流畅。

### ISSUE THREAD

**Issue by SuperBeagleDog** [scwang90/SmartRefreshLayout#486]
注：这里的上滑，准确点应该是“下滑”。因为，我的手势是，自上而下。

当这个值，设置为true时。
app:srlEnableFooterFollowWhenLoadFinished="true"
然后，滑到底部，出现，“没有更多数据”的时候，再往上“用力滑”。
会发现，只滑了一小段距离。
重现率8、90%，偶尔操作，则可以快速上滑。
但大部分时候，还是只滑了一小段距离。希望，优化。

**Comment by scwang90** [comment]
对上拉加载有高度体验要求请使用 Adapter 实现的库

https://github.com/CymChad/BaseRecyclerViewAdapterHelper

**Comment by ThugKd** [comment]
我也遇到这个问题了

**Comment by SuperBeagleDog** [comment]
@ThugKd 这控件总体还是不错，但只算半免费品吧。抽空，还是自己封一个，免得处处受制于人。
