### ISSUE TITLE
美图手机崩溃问题(android系统版本号4.4.4)

### ISSUE THREAD

**Issue by tuzanhua** [scwang90/SmartRefreshLayout#488]
abstract method not implemented\n\tat com.scwang.smartrefresh.layout.SmartRefreshLayout.stopNestedScroll(SourceFile)\n\tat android.support.v4.view.ViewCompat$ViewCompatBaseImpl.stopNestedScroll(SourceFile\:840)\n\tat android.support.v4.view.ViewCompat.stopNestedScroll(SourceFile\:3335)\n\tat android.support.v4.view.NestedScrollingChildHelper.setNestedScrollingEnabled(SourceFile\:70)\n\tat com.scwang.smartrefresh.layout.SmartRefreshLayout.setNestedScrollingEnabled(SourceFile\:1668)\n\tat 

解决方案1.1.0.5 alpha 版本未实现此方法造成的(查看历史之前的版本是重写了此方法的) 
     @Override
     @Deprecated
    public void stopNestedScroll() {
        mNestedChild.stopNestedScroll();
    }

**Comment by scwang90** [comment]
非常感谢，这是一个很严重的问题

**Comment by SuperBeagleDog** [comment]
这是一个严重的问题，那你们怎么还不修改.... ....我这边在低版本机上也遇到了

**Comment by scwang90** [comment]
新版本已经解决这个问题
