### ISSUE TITLE
你好，refreshLayout.autoRefresh();调用了，头部也下来了，但是就是没有回调onRefresh方法。

### ISSUE THREAD

**Issue by leguang** [scwang90/SmartRefreshLayout#489]
你好，refreshLayout.autoRefresh();调用了，头部也下来了，但是就是没有回调onRefresh方法。
一进入也面，我调用了refreshLayout.autoRefresh();，有效果，也请求了网络，但是由于我们要验证短信，所以等短信验证完了，我再发广播到这个也面的某个地方调用的了refreshLayout.autoRefresh();
此时界面上，下拉刷新的头部显示了，但是没有回调setOnRefreshListener方法所设置的监听器的onRefresh方法。这就尴尬了。难道是不能多次调用autoRefresh？
```
refreshLayout.setOnRefreshListener(l -> {
            Logger.e("222");
            mPresenter.postPurseBalance(params);
        });
```

```
 switch (intent.getAction()) {
                    case Constants.BROADCAST_GRANT_CODE:
                        Logger.e("111");
                        refreshLayout.autoRefresh();
                        break;
                    default:
                        break;
                }
```
在验证完短信后111有打印出来，头部也显示了，但是222没打印。
不知是不是我调用错了Api，望告知一二。

**Comment by scwang90** [comment]
autoRefresh 地触发是有条件的，需要在空闲状态才行

**Comment by leguang** [comment]
哦，我不是很明白，请问我想完成我这个功能的话，是需要做什么操作吗？也看是能手动触发下拉刷新，界面上会下拉，同时，里面的回调也会触发。

**Comment by leguang** [comment]
我看源码里面没有对mState进行操作的方法，有一个resetStatus方法，但是protected的。

**Comment by chaozaiai** [comment]
@leguang 我也遇到这个问题了。请问你是怎么解决的呢？

**Comment by chaozaiai** [comment]
调用autoRefresh之前做个判断
if (refreshLayout.getState() != RefreshState.None) {
                    return;
                }
