### ISSUE TITLE
finishLoadMoreWithNoMoreData之后不能恢复为finishLoadMoreWithMoreData

### ISSUE THREAD

**Issue by T-mans** [scwang90/SmartRefreshLayout#490]
当SmartRefreshLayout控件调用了finishLoadMoreWithNoMoreData之后，我重新下啦刷新请求了前十条数据，然后尝试调用smart_refresh.finishLoadMore(0,true,false)来使得控件可以继续loadmore。但是我看源码似乎只有类似
if (noMoreData) {
 setNoMoreData(true);
}
但是没有else的设置，
@scwang90 这个是这个库故意这么设置的吗？还是一个bug？

Thanks

**Comment by scwang90** [comment]
怎么回事bug啊，大兄弟

**Comment by T-mans** [comment]
是我傻了，setNoMoreData(false)竟然是public的。没好好看
