### ISSUE TITLE
smartrefreshlayout中的内容初次加载时，页面内容不是从头开始显示的

### ISSUE THREAD

**Issue by wenjian1314** [scwang90/SmartRefreshLayout#491]
smartrefreshlayout中的内容初次加载时，页面内容不是从头开始显示的，而是从中间的某个recyclerview开始显示的，要通过手动滑动才能滑到最上面
请问有什么方法可以解决吗

**Comment by scwang90** [comment]
用代码手动把内容滚动到顶部就好了
