### ISSUE TITLE
onDetachFromWindow执行之后 再次执行onAttachedToWindow 之前的刷新请求丢失了

### ISSUE THREAD

**Issue by holleQiang** [scwang90/SmartRefreshLayout#492]
我把包含smartRefreshLayout的view remove掉，再重新add,之前调用的autorefresh 就无效了，希望能保存这个状态啊。。

**Comment by scwang90** [comment]
1.建议不要使用 remove，建议使用动态隐藏和显示
2.remove 的时候必须停掉任何的动画额状态，不然会有内存泄漏的bug

**Comment by holleQiang** [comment]
唉，想搞个工具类，要remove掉控件在外面再包一个FrameLayout，然后在FrameLayout里面插入其他控件，就这个刷新有问题，，
