### ISSUE TITLE
有没有正在下拉的监听

### ISSUE THREAD

**Issue by wayuhan** [scwang90/SmartRefreshLayout#496]
我在xml文件里面给recyclerview添加了一个header，然后吧recyclerview滑到中间，再在页面顶部直接下拉，这样也会触发到下拉刷新，

**Comment by scwang90** [comment]
看来你对 smart 的原来还不认识呀，“在xml文件里面给recyclerview添加了一个header” 这句话太神了。你多看看文档和 demo 的例子吧
