### ISSUE TITLE
1.0版本不支持ViewPager刷新

### ISSUE THREAD

**Issue by tonycheng93** [scwang90/SmartRefreshLayout#497]
你好，请教一个问题，现在做了一个类似抖音那样上下滑动，切换视频的页面，改写了viewpager支持竖直滑动，使用1.0版本的smartrefreshlayout始终只有一个item,而1.1版本的是可以正常刷新的，由于历史原因，现在不能进行版本升级，请问这两个版本对于viewpager的支持有什么不一样吗

**Comment by scwang90** [comment]
1.0 版本功能不完善，也有bug，功能也没新版的多。如果你有特殊原因要使用1.0版本，你可能需要自己去阅读新版的源码，来修复 1.0 的问题

**Comment by tonycheng93** [comment]
@scwang90 多谢解答，方便问下，现在1.1版本的有稳定版吗，我看1.1版本都还是alpha版本

**Comment by only0315** [comment]
@tonycheng93 方便加下我好友吗，请教些问题，qq:1029303041
