### ISSUE TITLE
导入项目报错..

### ISSUE THREAD

**Issue by ylmyg** [scwang90/SmartRefreshLayout#499]
为什么导入项目都会报错
Compilation failed; see the compiler error output for details.
AS 3.0.1 gradle3.3 AS 3.1.2 gradle4.4都是这样
请问该怎么解决

**Comment by ylmyg** [comment]
我把gradle将为3.3 AS2.3.3
还是报错Process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe'' finished with non-zero exit value 1 不知道哪个包冲突了

**Comment by ylmyg** [comment]
按照网上方法，修改了项目两个类命名错误，重启AS，再安装成功，OK

**Comment by su1216** [comment]
和as版本无关,使用命令行编译也有同样的错误.

**Comment by lqb12172** [comment]
无语了，你倒是说一下修改了哪两个类的命名啊！
