### ISSUE TITLE
上拉加载更多，能不能添加一个没有更多的回调

### ISSUE THREAD

**Issue by T-mans** [scwang90/SmartRefreshLayout#50]
很多时候，上拉加载更多已经拉取完了所有的服务器数据，我们需要给用户一个提示：
表示     “数据加载完毕”
或者     “我们是有底限的←_←“
但是我现在找不到这样的功能，是框架没有这个功能，还是我没有找到>﹏<

**Comment by T-mans** [comment]
我的意思是在footer的位置显示“数据加载完毕”。并且不再触发loadmore接口，

**Comment by AcgnCodeMonkey** [comment]
这个是需要自己实现的，别人怎么知道你什么时候完成

**Comment by JavaBoyHW** [comment]
@T-mans 你可以在没有更多数据加载时。设置setLoadmoreFinished(true);并在此后面添加提示信息。
