### ISSUE TITLE
[Feature]: 下拉手势没有触发下拉，同样的手势微信聊天列表可以下拉

### ISSUE THREAD

**Issue by biaomingzhong** [scwang90/SmartRefreshLayout#500]
1.当前使用的版本号：`1.1.0-alpha-3`
2.复现操作描述

只有 RecyclerView 作为 Content 的时候才会

```
已经下拉了一段距离后（ **足够长的距离** ），最后手势稍微抖一下或横向有移动的情况下就会导致不能下拉，影响用户体验

正确的示例对比：

**同样的手势** 在微信的聊天列表页中是可以下拉出来小程序的
```

3.使用代码：`demo 样式举例中 Classics`
4.crash日志：`无`
5.视频
https://pan.baidu.com/s/1BMwTb0sSQBG-pIaETnFjuw

**Comment by scwang90** [comment]
你开启嵌套滚动就可以了

**Comment by biaomingzhong** [comment]
@scwang90 所以嵌套滚动的智能开启是什么意思？为啥 RecyclerView 没有智能开启

**Comment by biaomingzhong** [comment]
目前我使用继承 SmartRefreshLayout 的自己封装的 baseRefreshLayout，做了一些额外的事情：

可以直接在 onFinishInflate 加一个全局对 RecyclerView 开启嵌套滚动吗？

``` Kotlin
override fun onFinishInflate() {
    super.onFinishInflate()

    if (mRefreshContent != null && mRefreshContent.view is RecyclerView) {
        // 开启嵌套滚动，解决部分手势 RecyclerView 没有触发下拉的问题
        setEnableNestedScroll(true)
    }
}
```

**Comment by scwang90** [comment]
不可以的，需要手动开启
