### ISSUE TITLE
DropboxStyleActivity 错误

### ISSUE THREAD

**Issue by DovSnier** [scwang90/SmartRefreshLayout#503]
`
SmartRefreshLayout\app\src\main\java\com\scwang\refreshlayout\activity\style\DropboxStyleActivity.java:26: 错误: 类DropBoxStyleActivity是公共的, 应在名为 DropBoxStyleActivity.java 的文件中声明
`
```
SmartRefreshLayout\app\src\main\java\com\scwang\refreshlayout\activity\practice\WebviewPracticeActivity.java:23: 错误: 类WebViewPracticeActivity是公共的, 应在名为 WebViewPracticeActivity.java 的文件中声明
public class WebViewPracticeActivity extends AppCompatActivity {
```

这个DropboxStyleActivity .java 文件应该改为DropBoxStyleActivity.java 吧 ？
同样WebviewPracticeActivity.java -> WebViewPracticeActivity.java

**Comment by scwang90** [comment]
嗯是的
