### ISSUE TITLE
华为4.4.2手机上SmartRefreshLayout嵌套滑动View有阻力

### ISSUE THREAD

**Issue by huwenyong** [scwang90/SmartRefreshLayout#505]
SmartRefreshLayout嵌套NestedScrollView，NestedScrollView里嵌套了一个RecyclerView，RecyclerView设置了nestedScrollingEnabled这个属性为false，小米5（Android7.0），红米（Android6.0），华为（Android8.0）都可以惯性滑动，没问题，原生4.4模拟器我也试了下，失去了惯性滑动。不知道其它人有没有遇见这个问题。
SmartRefreshLayout版本是1.0.5.1，这个我再仔细看一下吧

**Comment by scwang90** [comment]
把 SmartRefreshLayout 去掉之后就好了吗？
