### ISSUE TITLE
全局设置相关

### ISSUE THREAD

**Issue by ycx974577817** [scwang90/SmartRefreshLayout#509]
我在Application内用静态代码块设置了默认配置
`SmartRefreshLayout.setDefaultRefreshHeaderCreator { context, layout ->
                layout.setEnableAutoLoadMore(false)
                layout.setDisableContentWhenLoading(true)
                layout.setDisableContentWhenRefresh(true)
                layout.setEnableLoadMoreWhenContentNotFull(false)
                layout.setEnableScrollContentWhenLoaded(false)
                ClassicsHeader(context).setSpinnerStyle(SpinnerStyle.Translate)
            }`
然后因为我在项目内会用到ClassicsHeader与MaterialHeader，使用MaterialHeader时就不能加载默认配置。请问我需要怎样才能实现这种需求。
谢谢解答

**Comment by scwang90** [comment]
不能实现，全局默认只能默认一个，不能默认两个
