### ISSUE TITLE
关于CoordinatorLayout+AppBarLayout+ViewPager+SmartRefreshLayout+RecyclerView事件冲突问题

### ISSUE THREAD

**Issue by RaymanMartin** [scwang90/SmartRefreshLayout#511]
在项目使用中，发现当后台返回的数据列表只有几个的时候，就会出现AppBarLayout不能折叠的事件冲突（准确来说数据列表的高度没有到达一定高度）。

然后发现每次当我滚动列表的时候可以分为三种情况
第一种：AppBarLayout是有移动的趋势的，但是划着突然就回来了
第二种：在SmartRefreshLayout的Header和Footer显示出来之前，慢慢滑动的情况下，能正常折叠。但是速度稍微快点就不能了，页面效果和第一种一样，AppBarLayout都有趋势，但是被弹回来
第三种：是基于第二种的，当折叠之后再下拉（因为数据只有两三条而且没有填充满页面，所以希望是AppBarLayout扩展开，而不是加载数据）。但是效果就是AppBarLayout不能展开，只能交由SmartRefreshLayout去执行刷新手势。

之后看到了同样的issue，我尝试过直接用RecyclerView是可以正常折叠的，使用系统的SwipeRefreshLayout也是能正常折叠。

布局上面都是比较简单的布局。
Activity：最外层CoordinatorLayout+AppBarLayout实现折叠+ViewPager切换Fragment
Fragment：LinearLayout+SmartRefreshLayout+RecyclerView

Activity布局：
![image](https://user-images.githubusercontent.com/20057298/40358204-17656e2c-5df1-11e8-9aaa-2555475ae095.png)

Fragment布局：
![image](https://user-images.githubusercontent.com/20057298/40358415-bf8dbed8-5df1-11e8-9bd2-76dbdd34ade8.png)

**Comment by RaymanMartin** [comment]
问题算是解决了，看了下源码发现提供了setNestedScrollingEnabled方法设置SmartRefreshLayout是否能响应对应的Behavior。只需要根据Adapter的ItemCount去判断就是否响应就可以了。但是交互的效果还有待优化。

**Comment by ThugKd** [comment]
请问一下  你下面列表中有没有加载更多功能  我执行了加载更多之后就会出现在主界面上滑的时候  下面列表和整个布局同时滑动（各自都执行了滑动事件）

**Comment by scwang90** [comment]
亲测没能复现楼主提的这个问题。请确保楼主使用的是最新版本。
demo中 NestedScrollExampleFragmentViewPager 页面的布局和楼主的相差无几，没发现冲突问题
