### ISSUE TITLE
微博列表的例子

### ISSUE THREAD

**Issue by xiayu98020214** [scwang90/SmartRefreshLayout#515]
微博列表例子的布局文件，SmartRefreshLayout\app\src\main\res\layout\activity_practice_feedlist.xml
给SmartRefreshLayout添加， app:srlEnableLoadMoreWhenContentNotFull="false"。上拉加载更多就不行了，但是数据肯定是满屏的，应该可以上拉加载。

**Comment by scwang90** [comment]
确实是这样子的，谢谢提出来，下一个斑斑将修复

**Comment by scwang90** [comment]
新版本已经解决这个问题
