### ISSUE TITLE
java.lang.RuntimeException: 最多只支持3个子View，Most only support three sub view

### ISSUE THREAD

**Issue by hehehe5** [scwang90/SmartRefreshLayout#52]
在fragment里面的选项卡里面使用  选项卡里面的布局用的都是同一个 布局里面子view我只写了三  然后滑动的次数多就会出现这个错误

**Comment by scwang90** [comment]
收到

**Comment by scwang90** [comment]
可以看一下你的Xml 布局结构代码吗？

**Comment by hehehe5** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <pl.droidsonroids.gif.GifImageView
            android:layout_width="wrap_content"
            android:layout_height="@dimen/common_sw320_80dp"
            android:scaleType="centerCrop"
            android:src="@mipmap/recyclerview_loading"/>

        <ListView
            android:id="@+id/listview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/white"
            android:divider="@null"
            android:dividerHeight="@dimen/margin_3dp"
            android:overScrollMode="never"/>

        <pl.droidsonroids.gif.GifImageView
            android:layout_width="wrap_content"
            android:layout_height="@dimen/common_sw320_80dp"
            android:scaleType="centerCrop"
            android:src="@mipmap/recyclerview_loading"/>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</LinearLayout>
因为都是一个列表  所以几个fragment用的都是这一个xml

**Comment by hehehe5** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <pl.droidsonroids.gif.GifImageView
            android:layout_width="wrap_content"
            android:layout_height="@dimen/common_sw320_80dp"
            android:scaleType="centerCrop"
            android:src="@mipmap/recyclerview_loading"/>

        <ListView
            android:id="@+id/listview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/white"
            android:divider="@null"
            android:dividerHeight="@dimen/margin_3dp"
            android:overScrollMode="never"/>

        <pl.droidsonroids.gif.GifImageView
            android:layout_width="wrap_content"
            android:layout_height="@dimen/common_sw320_80dp"
            android:scaleType="centerCrop"
            android:src="@mipmap/recyclerview_loading"/>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</LinearLayout>

**Comment by scwang90** [comment]
1.0.2-alpha-7 发布，问题已经修复，
