### ISSUE TITLE
列表快速上滑到底部触发“加载更多”的问题

### ISSUE THREAD

**Issue by Chen-Sir** [scwang90/SmartRefreshLayout#524]
使用的经典footer，关闭了“滑动到底部自动加载更多”功能。
快速滑动列表，滑动到底部时，再快速上滑，触发了加载更多功能，列表停止滚动，但是加载完成后列表自动惯性滑动，此时footer“加载完成”还在显示。
惯性滑动这样感觉很不好。
还有就是上拉加载完成后如何取消“加载完成”这个提示

**Comment by scwang90** [comment]
1.惯性滑动和 smart 没有关系的，需要自己检查
2.footer 可以把完成提示的时间设为0，文档中有提到；
