### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by junchenChow** [scwang90/SmartRefreshLayout#525]
> <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlEnableLoadMoreWhenContentNotFull="false"
        app:srlEnableScrollContentWhenLoaded="true">
        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

我给adapter加了headers 和 footers 然后加载更多就不起作用了 
必须要setEnableNestedScroll(true)才有作用，
但是嵌套滑动开启之后 加载更多完成的回弹动作 非常僵硬 一点平滑效果都没有。

**Comment by scwang90** [comment]
经过测试，没有发现 setEnableNestedScroll(true) 会对加载完成回弹动画造成影响；
你可以加群传视频，大家可以帮你分析原因。

**Comment by junchenChow** [comment]
有个疑问 为什么recyclerview adapter加了headers 和 footers 然后加载更多就不起作用了
