### ISSUE TITLE
动态设定setNoMoreData true，progress 没有删除

### ISSUE THREAD

**Issue by nnbb923** [scwang90/SmartRefreshLayout#528]
ClassicsFooter , loadmore 数据后，设置setNoMoreData = true，ProgressView 依然存在。

**Comment by scwang90** [comment]
需要调用 finishLoadMore

**Comment by nnbb923** [comment]
@scwang90 
调用finishLoadMore不好使。我指的是先是有数据的情况loadmore，然后再设置setNoMoreData = true。 这时候progress 始终显示。（和常规问题12 不是一个问题）

**Comment by nnbb923** [comment]
@scwang90 
没能动态调用setNoMoreData = true，直接调用finishLoadMoreWithNoMoreData。可以解决此问题。
