### ISSUE TITLE
上拉加载的时候，顶部悬浮的view给顶出屏幕外的问题？有什么解决方案吗？

### ISSUE THREAD

**Issue by Anayuta** [scwang90/SmartRefreshLayout#529]
如题

**Comment by scwang90** [comment]
用 srlFooterTranslationViewId 指定为列表控件Id，具体用法可以参考demo

**Comment by Anayuta** [comment]
@scwang90 demo上没发现有,我的那个悬浮view是listview中的一个item，滚动后悬浮的，但是上拉加载的时候把那个item顶到屏幕外边了

**Comment by scwang90** [comment]
view 在 listview 中的话，只能使用多功能监听器来监听上啦的偏移量，手动对你的view 做向下偏移。来平衡原来的上偏移。参考 demo中的 微博主页
