### ISSUE TITLE
为什么finishLoadMoreWithNoMoreData必须在触发框架本身的刷新或者LoadMore后才起作用？

### ISSUE THREAD

**Issue by T-mans** [scwang90/SmartRefreshLayout#531]
首先介绍我的编译环境：
SDK 27 
SmartRefreshLayout:1.1.0-alpha-6
刷新header和footer个人使用的是Classic的

我的问题和@KingsleyCheng遇到的是一样的。就是以下#387issue提的问题。
> 
我分页加载，每页10条数据，现在我总的数据小于10条，我mRefreshLayout.finishLoadmoreWithNoMoreData()禁止加载更多了，但是还会触发加载跟多，为什么呢
> 
只不过我的是初始化就分页加载20条

首先针对我的问题，个人参考了以下提问
#387 
#463 
#384 
作者让参照demo使用

然后我去看了demo，在BasicExampleActivity里面的发现作者的页面初始化是调用了refreshLayout.autoRefresh()实现的
我这样试着用了后，发现的确没有问题了。
举一反三，我是使用了refreshLayout.autoLoadMore()来初始化页面，发现也没问题了。

然而这会触发一个问题：使用refreshLayout.autoRefresh()就必然会触发refreshLayout的下拉刷新动画，而使用refreshLayout.autoLoadMore()就必然触发上拉的动画。
这样进入页面就会立即触发自动下拉或者上拉加载更多的动画。
但我希望下拉还是上拉的动画是用户自己触发的，这样才符合用户的心里预期。所以我的页面初始化使用了类似ios的菊花loading，然后后续的分页让用户来控制不再显示菊花loading。

所以我想问作者的是：finishLoadMoreWithNoMoreData为什么必须在refreshLayout的autoRefresh或者autoLoadMore之后才有效呢？

还是我根本就分析错了？

@scwang90  

Thanks!

**Comment by T-mans** [comment]
我贴一下我的关键代码：

override fun onRecordGot(recordData: RewardRecordRsp.Data?) {
        smart_refresh.finishRefresh()//关闭刷新动画
        pagingReq.totalPage = recordData?.pages ?: 0
        if (pagingReq.Page < pagingReq.totalPage) {//根据情况关闭loadmore动画
            smart_refresh.finishLoadMore()
            smart_refresh.setNoMoreData(false)//还有更多数据
        } else {
            smart_refresh.finishLoadMoreWithNoMoreData()//没有更多数据
        }
//数据源的刷新
        if (pagingReq.Page == 1) {
            mData.clear()
        }
        recordData?.list?.forEach {
            mData.add(it)
        }
//RecyclerView数据绑定和刷新
        if (recycler_view.adapter == null) {
            recycler_view.layoutManager = LinearLayoutManager(this)
            mAdapter = RewardRecordAdapter(mData)
            mAdapter.setEmptyView(R.layout.activity_reward_record_empty, recycler_view)
            recycler_view.adapter = mAdapter
        } else {
            mAdapter.notifyDataSetChanged()
        }
    }

**Comment by T-mans** [comment]
个人进一步分析了finishLoadMoreWithNoMoreData，发现：
@Override
    public SmartRefreshLayout finishLoadMoreWithNoMoreData() {
        long passTime = System.currentTimeMillis() - mLastOpenTime;
        return finishLoadMore(Math.max(0, 300 - (int) passTime), true, true);
    }
问题出在mLastOpenTime上面，由于没有触发框架的刷新或者loadmore，mLastOpenTime默认是0的。
Math.max(0, 300 - (int) passTime)制定了一个延迟，然而由于long passTime是一个long，所以Math.max(0, 300 - (int) passTime)计算出来的是一个很大的数值（因为超过了int上限，这里会随机变成一个int，通常这个数字很大，所以可能是好几亿）。然后由于延迟非常大，所以最后setNoMoreDate根本等不到执行。

**Comment by T-mans** [comment]
所以我最后解决问题的方式是：不调用finishLoadMoreWithNoMoreData，
我直接调用了finishLoadMore(300, true, true)。写死了只延迟300ms

**Comment by T-mans** [comment]
所以我最后解决问题的方式是：不调用finishLoadMoreWithNoMoreData，
我直接调用了finishLoadMore(0, true, true)。

**Comment by scwang90** [comment]
finishLoadMoreWithNoMoreData 的设计就是为了结束正在加载状态的，如果当时没有处于加载状态，那么finishLoadMoreWithNoMoreData就会自动无效，这是正常的逻辑。


如果没有处于加载状态，想直接更改结果可以使用 
setNoMoreData(true)
代替
finishLoadMoreWithNoMoreData

**Comment by guoleifei** [comment]
finishLoadMoreWithNoMoreData = finishLoadMore + setNoMoreData 不对吧
源码中
![image](https://user-images.githubusercontent.com/16201257/54591780-effd0680-4a65-11e9-8f3e-7d03b7a218ad.png)
setNoMoreData  调用的finishLoadMoreWithNoMoreData 
这么说不对吧。
还有确实有问题的是 finishLoadMoreWithNoMoreData  在第一页就没有更多数据的时候 调用这个有时候会失效 虽然没有深究 但是确实存在这个问题。

**Comment by protectedMan** [comment]
同此问题

> finishLoadMoreWithNoMoreData = finishLoadMore + setNoMoreData 不对吧
> 源码中
> ![image](https://user-images.githubusercontent.com/16201257/54591780-effd0680-4a65-11e9-8f3e-7d03b7a218ad.png)
> setNoMoreData 调用的finishLoadMoreWithNoMoreData
> 这么说不对吧。
> 还有确实有问题的是 finishLoadMoreWithNoMoreData 在第一页就没有更多数据的时候 调用这个有时候会失效 虽然没有深究 但是确实存在这个问题。

赞成
