### ISSUE TITLE
如何增大拖动高度

### ISSUE THREAD

**Issue by sieml** [scwang90/SmartRefreshLayout#535]
往下拖动到屏幕一半时，就很难再继续往下拉动了。
能否达到可以把整个内容布局拖到屏幕外边(我是两根手指连续拖的)，请问有什么办法修改吗

**Comment by scwang90** [comment]
文档中有相关方法，常见问题中也有提到

**Comment by sieml** [comment]
就算设置1，也并不能滑出到屏幕外，而且阻尼效果很生硬
