### ISSUE TITLE
上拉刷新和下拉刷新有冲突？？？求助

### ISSUE THREAD

**Issue by bbsbin** [scwang90/SmartRefreshLayout#537]
使用SwipeRefreshLayout时，先是上拉加载一次，到两次请求数据，再下拉刷新后，就不能够上拉加载了，只显示加载完成了，数据是后台分页给的，请问这是怎么一个回事

**Comment by WRainbow** [comment]
应该是在数据返回end时使用了finishLoadMoreWithNoMoreData()方法，记得在refresh后使用setNoMoreData(false)方法恢复为初始状态

**Comment by scwang90** [comment]
使用方法参考demo
