### ISSUE TITLE
autoRefresh的问题

### ISSUE THREAD

**Issue by Amoryan** [scwang90/SmartRefreshLayout#547]
![image](https://user-images.githubusercontent.com/15521440/41280147-ce74955a-6e60-11e8-9c70-ab773f75a7b8.png)

如果列表滚动到某个位置，然后返回这个页面调用autorefresh的时候，就会出现部分覆盖的情况，因为列表没有滚动到最顶部导致的。这个可以避免掉吗，还是说需要手动调用scrollxxx方法

**Comment by scwang90** [comment]
需要手动滚动到顶
