### ISSUE TITLE
autoRefresh刷新时间问题

### ISSUE THREAD

**Issue by bairenxing** [scwang90/SmartRefreshLayout#548]
第一次进入页面调用autoRefresh方法，数据出来后，下拉刷新的动画还要过会儿才消失，我想让刷新动画在数据出来的同时就结束掉，请问要怎么做呢？

**Comment by scwang90** [comment]
finishRefresh(0)

如果还不想显示 “刷新成功” 

可以把 header 的 刷新完成延时 时间设置为0
