### ISSUE TITLE
列表不满一屏的时候，能否取消加载更多？

### ISSUE THREAD

**Issue by lichao315** [scwang90/SmartRefreshLayout#55]
如题，我使用SmartRefreshLayout同时支持下拉刷新和上拉加载更多的功能，现在我有个列表，如果全部铺满屏幕需要10条，现在我只有2条数据，这时候上拉加载更多就没有意义了，而且一直存在的话，用户体验也不好。
不知道现在有没有可以判断这种不满一屏取消掉上拉加载的功能或者解决方案？谢谢！！！

**Comment by scwang90** [comment]
setEnableLoadmore(false)

**Comment by 838514984** [comment]
心疼作者

**Comment by scwang90** [comment]
@838514984 唉，没办法，他们提问之前都不阅读文档的，可能过一断时间，我在Issue区域只处理BUG，其他都只在QQ群处理

**Comment by lichao315** [comment]
setEnableLoadmore(false)是关闭加载更多啊，我的意思是，一个列表可能铺满了屏幕，可能没有铺满屏幕，如果没有铺满屏幕的情况下，说明数据有限，不需要加载更多的功能了。
这种情况下，需要我们自己判断列表是否铺满屏幕，再设置setEnableLoadmore(boolean)???

**Comment by 838514984** [comment]
可以根据数据的条数判断是否开启加载更多。一般来说10条数据是能填充满屏幕了。
比如：
 if(list.size()<10)
setEnableLoadmore(false)

**Comment by scwang90** [comment]
@lichao315  是的，加载更多功能的开启和关闭都有使用者自己判断
