### ISSUE TITLE
scrollview滑到底部，往上拖。就会有加载更多的view出现

### ISSUE THREAD

**Issue by NW0LC** [scwang90/SmartRefreshLayout#553]
<SmartRefreshLayout
      ClassicsHeader
           NestedScrollView
SmartRefreshLayout>

     没有footer且只设置下拉加载监听。滑动到底部，再往上拖。停顿一下。必然会出现 三个圆点，目测是默认的footer

**Comment by l455202325** [comment]
mRefreshLayout.setEnableLoadmore(false);

**Comment by NW0LC** [comment]
我试过了的。setEnableLoadmore(false);也会有的。

**Comment by Reginer** [comment]
和我一样，我设置了noMore

**Comment by scwang90** [comment]
设计的时候就是这样的，不同的使用场景demo中都有例子，可以去参考以下
