### ISSUE TITLE
我建议setRefreshContent不要创建LayoutParams

### ISSUE THREAD

**Issue by liangjingkanji** [scwang90/SmartRefreshLayout#555]
![image](https://user-images.githubusercontent.com/21078112/41475548-ad764cac-70f1-11e8-8359-9220f3f75da1.png)

这样做布局替换的时候LayoutParams无法还原

**Comment by liangjingkanji** [comment]
例如我给RecyclerView写了个paddingTop, 然后我扩展SmartRefreshLayout实现了个多状态布局的功能

**Comment by liangjingkanji** [comment]
不知道作者有否考虑做多状态布局的扩展

**Comment by liangjingkanji** [comment]
我扩展封装了自动加载更多/刷新完成和分页处理以及多状态布局

**Comment by scwang90** [comment]
多状态布局需要自己再套一个 FrameLayout 能直接使用 smart 来做切换

**Comment by scwang90** [comment]
状态切换 使用 hide visible 方式效率要高
setRefreshContent 会 remove 之前的 content，效率低

setRefreshContent 的设计初中不是为了切换状态，而是为了在 非 xml 布局时，可以通过代码添加 content

不过如果你觉得使用它切换没问题就行，不过后面出问题了，建议套一层 FrameLayout

**Comment by scwang90** [comment]
谢谢你对 smart 的好评，对于 你的问题：是否考虑做多状态布局的扩展？

开源库要做到 专、精、小、轻，现在smart 已经失去了 小、轻
不会再做任何与刷新无关的扩展，

github上也有很多，好用的状态切换库，如果以后要扩展，那也是另写一个 状态切换的 库，不会集成在 smart 中
