### ISSUE TITLE
滑动冲突问题

### ISSUE THREAD

**Issue by xwtao** [scwang90/SmartRefreshLayout#559]
下拉刷新时候，我的recyclerview还没用滑到顶部就出现了刷新的，上拉时候也是还没滑动底部就出现加载的视图了，要快速滑动底部才行。使用了个第三方的自定义的个LayoutManager叫SpannedGridLayoutManager。应该是这个LayoutManager的滑动处理和该下拉刷新控件的有冲突。有什么好的解决办法吗？

**Comment by scwang90** [comment]
开启嵌套滚动功能

**Comment by xiaobaDev** [comment]
怎么开启嵌套滚动？
