### ISSUE TITLE
SmartRefreshLayout+CoordinatorLayout+CollapsingToolbarLayout下拉有问题，折叠的下拉会显示不全或不显示

### ISSUE THREAD

**Issue by Equalzys** [scwang90/SmartRefreshLayout#56]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        style="@style/AppTheme.Toolbar"
        app:navigationIcon="@drawable/ic_arrow_back_white_24dp"
        app:title="@string/title_activity_practice_feedlist"/>

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/smartLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlAccentColor="#fff"
        app:srlEnablePreviewInEditMode="false"
        app:srlFixedHeaderViewId="@+id/profile"
        app:srlPrimaryColor="#444">

        <com.scwang.smartrefresh.layout.header.ClassicsHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />

        <android.support.design.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.design.widget.AppBarLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                >

                <android.support.design.widget.CollapsingToolbarLayout
                    android:id="@+id/toolbarlayout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:layout_scrollFlags="scroll|exitUntilCollapsed">

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:layout_collapseMode="parallax">

                        <TextView
                            android:layout_width="match_parent"
                            android:layout_height="350dp"
                            android:text="上边消失的"/>
                    </RelativeLayout>

                </android.support.design.widget.CollapsingToolbarLayout>
            </android.support.design.widget.AppBarLayout>

            <android.support.v4.widget.NestedScrollView
                android:id="@+id/nsv_ftc"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_behavior="@string/appbar_scrolling_view_behavior">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        android:background="#99ffffff"
                        android:text="11111111"/>

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="300dp"
                        android:background="#66ffffff"
                        android:text="22222"/>

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="400dp"
                        android:background="#11ffffff"
                        android:text="333333"/>

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="500dp"
                        android:background="#44ffffff"
                        android:text="44444"/>

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="600dp"
                        android:background="#77ffffff"
                        android:text="55555"/>
                </LinearLayout>
            </android.support.v4.widget.NestedScrollView>
        </android.support.design.widget.CoordinatorLayout>

        <com.scwang.smartrefresh.layout.footer.ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>
</LinearLayout>

**Comment by Equalzys** [comment]
![image](https://user-images.githubusercontent.com/17246251/28257834-37e17306-6b00-11e7-9708-f25648116360.png)

**Comment by Equalzys** [comment]
另demo中 个人中心 下面并没有上拉回弹效果（上拉不动）

**Comment by Equalzys** [comment]
在https://github.com/canyinghao/CanRefresh 这个库里看到个这样的布局 没有出现下拉不显示的问题，大大可以看下为什么，小白表示看不懂

**Comment by scwang90** [comment]
AppBarLayout appBarLayout = (AppBarLayout) findViewById(R.id.appbar_layout);
appBarLayout.addOnOffsetChangedListener(new AppBarLayout.OnOffsetChangedListener() {
    @Override
    public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
        if (verticalOffset >= 0) {
            refreshLayout.setEnableRefresh(true);
        } else {
            refreshLayout.setEnableRefresh(false);
        }
    }
});

暂时先这样

**Comment by scwang90** [comment]
1.0.2-alpha-7 发布，问题已经解决

**Comment by Equalzys** [comment]
下拉 没问题了   但是上拉又有问题了 。 上拉折叠部分  直接显示footer 而不是向上滑动了

**Comment by Equalzys** [comment]
就是上拉 这一块 。
.......
  <android.support.design.widget.CollapsingToolbarLayout
                android:id="@+id/toolbarlayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:layout_collapseMode="parallax">

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="350dp"
                        android:text="上边消失的"/>
                </RelativeLayout>

            </android.support.design.widget.CollapsingToolbarLayout>
...

**Comment by Equalzys** [comment]
额  刚发现 1.0.2-alpha-6 上拉也有问题

**Comment by scwang90** [comment]
~~~java
AppBarLayout appBarLayout = (AppBarLayout) findViewById(R.id.appbar_layout);
appBarLayout.addOnOffsetChangedListener(new AppBarLayout.OnOffsetChangedListener() {
    @Override
    public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
        if (verticalOffset >= 0) {
            refreshLayout.setLoadmore(true);
        } else {
            refreshLayout.setLoadmore(false);
        }
    }
});
~~~
先用这个缓解一下

**Comment by Equalzys** [comment]
ok .  下个项目应该会用这套框架  所以来找找bug

**Comment by scwang90** [comment]
1.0.2-alpha-8 完美解决
