### ISSUE TITLE
突然下拉加载的文字和刷新的文字变成了英文

### ISSUE THREAD

**Issue by liu1070832898** [scwang90/SmartRefreshLayout#561]
![image](https://user-images.githubusercontent.com/29189440/41828393-8ff4ddce-7867-11e8-911e-a3887a0ac219.png)

**Comment by scwang90** [comment]
支持多语言

**Comment by zxm1243** [comment]
@liu1070832898 请问怎么切换？

**Comment by scwang90** [comment]
把安卓习题的语言切换成中文的

**Comment by qishengtao** [comment]
解决办法  1.适配国际化  2.自定义Header  3.写死  下面是写死的使用
找到你使用的默认的头  可以写死或者更改

ClassicsHeader.REFRESH_HEADER_PULLING = "下拉可以刷新";
        ClassicsHeader.REFRESH_HEADER_REFRESHING = "正在刷新...";
        ClassicsHeader.REFRESH_HEADER_LOADING = "正在加载...";
        ClassicsHeader.REFRESH_HEADER_RELEASE = "释放立即刷新";
        ClassicsHeader.REFRESH_HEADER_FINISH = "刷新完成";
        ClassicsHeader.REFRESH_HEADER_FAILED = "刷新失败";
        ClassicsHeader.REFRESH_HEADER_UPDATE = "上次更新 M-d HH:mm";
        ClassicsHeader.REFRESH_HEADER_SECONDARY = "释放进入二楼";

        ClassicsFooter.REFRESH_FOOTER_PULLING = "上拉加载更多";
        ClassicsFooter.REFRESH_FOOTER_RELEASE = "释放立即加载";
        ClassicsFooter.REFRESH_FOOTER_LOADING = "正在加载...";
        ClassicsFooter.REFRESH_FOOTER_REFRESHING = "正在刷新...";
        ClassicsFooter.REFRESH_FOOTER_FINISH = "加载完成";
        ClassicsFooter.REFRESH_FOOTER_FAILED = "加载失败";
        ClassicsFooter.REFRESH_FOOTER_NOTHING = "没有更多数据了";
