### ISSUE TITLE
 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by shuruncs** [scwang90/SmartRefreshLayout#569]
包裹一个recyclerview，删除recyclerview的item的时候容易出现该异常到处崩溃。
Inconsistency detected. Invalid item position 2(offset:2).state:3 android.support.v7.widget.RecyclerView{9be523c VFED..... .F....ID 0,0-1080,1541 #7f100191 app:id/recyclerView}, adapter:com.nursinghome.monitor.ui.adpter.DeviceListAdapter@ac2244d, layout:android.support.v7.widget.LinearLayoutManager@c471b02, context:com.nursinghome.monitor.ui.activity.MainActivity@d777b9a

com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:661)

android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5654)
--
2 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
3 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
4 android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
5 android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
6 android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
7 android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
8 android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
9 android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
10 android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
11 android.view.View.layout(View.java:16697)
12 android.view.ViewGroup.layout(ViewGroup.java:5593)
13 com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:661)
14 android.view.View.layout(View.java:16697)
15 android.view.ViewGroup.layout(ViewGroup.java:5593)
16 android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
17 android.widget.FrameLayout.onLayout(FrameLayout.java:273)
18 android.view.View.layout(View.java:16697)
19 android.view.ViewGroup.layout(ViewGroup.java:5593)
20 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
21 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
22 android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
23 android.view.View.layout(View.java:16697)
24 android.view.ViewGroup.layout(ViewGroup.java:5593)
25 android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
26 android.widget.FrameLayout.onLayout(FrameLayout.java:273)
27 android.view.View.layout(View.java:16697)
28 android.view.ViewGroup.layout(ViewGroup.java:5593)
29 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
30 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
31 android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
32 android.view.View.layout(View.java:16697)
33 android.view.ViewGroup.layout(ViewGroup.java:5593)
34 android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
35 android.widget.FrameLayout.onLayout(FrameLayout.java:273)
36 android.view.View.layout(View.java:16697)
37 android.view.ViewGroup.layout(ViewGroup.java:5593)
38 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
39 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
40 android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
41 android.view.View.layout(View.java:16697)
42 android.view.ViewGroup.layout(ViewGroup.java:5593)
43 android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
44 android.widget.FrameLayout.onLayout(FrameLayout.java:273)
45 android.view.View.layout(View.java:16697)
46 android.view.ViewGroup.layout(ViewGroup.java:5593)
47 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
48 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
49 android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
50 android.view.View.layout(View.java:16697)
51 android.view.ViewGroup.layout(ViewGroup.java:5593)
52 android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
53 android.widget.FrameLayout.onLayout(FrameLayout.java:273)
54 com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2819)
55 android.view.View.layout(View.java:16697)
56 android.view.ViewGroup.layout(ViewGroup.java:5593)
57 android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2209)
58 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1950)
59 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1126)
60 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6155)
61 android.view.Choreographer$CallbackRecord.run(Choreographer.java:892)
62 android.view.Choreographer.doCallbacks(Choreographer.java:704)
63 android.view.Choreographer.doFrame(Choreographer.java:640)
64 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:878)
65 android.os.Handler.handleCallback(Handler.java:739)
66 android.os.Handler.dispatchMessage(Handler.java:95)
67 android.os.Looper.loop(Looper.java:148)
68 android.app.ActivityThread.main(ActivityThread.java:5628)
69 java.lang.reflect.Method.invoke(Native Method)
70 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
71 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by scwang90** [comment]
和smart无关
