### ISSUE TITLE
上拉加载更多问题

### ISSUE THREAD

**Issue by chenxi0203** [scwang90/SmartRefreshLayout#57]
上拉完成后能否不回弹，导致下一页数据没法显示一部分出来，还得再上拉才出来，还有个问题，上拉数据全部加载完成后这个时候回到顶部无法触发下拉刷新拉，而且上拉全部加载完成后在上下滑动时有卡顿，上拉加载的footer有时候无法显示或显示不全。

**Comment by scwang90** [comment]
回弹功能是可以改期和关闭的，请认真阅读文档，请先加载更多完成之后，请先调用 finishLoadmore才可以继续刷新，请参照demo使用控件

**Comment by zejiaohe** [comment]
已设置拉finishLoadmore，再上拉如果没有更多数据则设置setLoadmoreFinished(true)，这个时候显示出来啦全部加载完成，在上下滑动列表时，‘全部加载完成的’ 的footer有时是显示不出来的，有时能显示一部分，而且有卡顿现象，这个时候回到第一页顶部在下拉时只能显示出来下拉的header，无法刷新。

**Comment by scwang90** [comment]
把你 调用 finishLoadmore 的代码贴出来看看

**Comment by zejiaohe** [comment]
![2](https://user-images.githubusercontent.com/20221278/28259722-3b8a5252-6b0a-11e7-9cb7-a1be997ae99e.png)
![3](https://user-images.githubusercontent.com/20221278/28259730-44ca3350-6b0a-11e7-8b27-33c17fc7f150.png)

一个图是触发下拉刷新，上拉加载时请求数据，另一个图是请求完成时设置加载完成
