### ISSUE TITLE
注释文字错误

### ISSUE THREAD

**Issue by chrissen0814** [scwang90/SmartRefreshLayout#573]
文件位置：SmartRefreshLayout.java 173,174行
` /**
     * 底部高度
     */
    protected int mFooterHeight;
    protected DimensionStatus mFooterHeightStatus = DimensionStatus.DefaultUnNotify;

    protected int mHeaderInsetStart;    // Header 起始位置便宜
    protected int mFooterInsetStart;    // Footer 起始位置便宜
    protected int mHeaderExtendHeight;  //扩展高度
    protected int mFooterExtendHeight;  //扩展高度`

**Comment by scwang90** [comment]
谢谢，已经修复
