### ISSUE TITLE
用autoRefresh刷新，立马点击屏幕，刷新动画被弹回去

### ISSUE THREAD

**Issue by SuperBeagleDog** [scwang90/SmartRefreshLayout#574]
用autoRefresh刷新，立马点击屏幕，刷新动画被弹回去。

请问，这算是个问题吗？还是你们设计之初，就是这样设计的。

**Comment by bbbBBBSG** [comment]
大佬，你的不满一屏时的上拉加载会闪屏吗，然后再出现刷新

**Comment by scwang90** [comment]
新版已经发布

**Comment by SuperBeagleDog** [comment]
@scwang90 我刚更新到alpha-9， 这问题仍然还在。我还没仔细看过你们的代码，里面逻辑看着有些复杂，事件分发处，建议增补些注释。我觉得应该在autoRefresh方法一执行后，就应该得加个标识。不然一点列表，就自动滚动。。。必现的问题，你可以把回弹时间调到2000毫秒，然后，在刚刚弹出刷新部分时，就快速、快速、快速点击列表，就会出现自动滚动。
