### ISSUE TITLE
BezierCircleHeader 在新版上显示有问题

### ISSUE THREAD

**Issue by jyh149129** [scwang90/SmartRefreshLayout#579]
![qq 20180704223045](https://user-images.githubusercontent.com/7726240/42282949-a34d9f94-7fda-11e8-9a8a-5068a919e776.jpg)
新版上出现这个问题，旧版正常。并且如果列表有数据，手动刷新的话，显示正常。

**Comment by scwang90** [comment]
新本版已经发布 1.1.0-11
