### ISSUE TITLE
SmartRefreshLayout关于上拉加载的问题

### ISSUE THREAD

**Issue by moon1993zs** [scwang90/SmartRefreshLayout#582]
咱们的刷新库的footer可否跟随列表滑动？除了滑动到列表底部自动触发加载更多，可否再添加一个点击加载更多的操作呢？

**Comment by scwang90** [comment]
这个功能需要 自己再 adapter 末尾添加 item 实现，通过layout方式没法实现

**Comment by moon1993zs** [comment]
如果在adapter末尾添加item实现的话，需要把咱们库自己的上拉加载禁用掉吗？
