### ISSUE TITLE
同时下拉刷新和上拉加载时，上拉加载的状态错误

### ISSUE THREAD

**Issue by Liby94** [scwang90/SmartRefreshLayout#584]
如果在刷新的同时去加载更多，展示的状态是错误的，如果上拉的时候禁止其它操作感觉怪怪的

**Comment by Liby94** [comment]
实站-->微博列表-->里面同时下拉和上拉，上拉展示的状态是正在刷新，下拉刷新结束后，这里的文字状态才正常变成正在加载

**Comment by scwang90** [comment]
就是这样的
