### ISSUE TITLE
recyclerview一键置顶后footer也跟着上去了

### ISSUE THREAD

**Issue by AndyZDL** [scwang90/SmartRefreshLayout#585]
srlEnableFooterFollowWhenLoadFinished="true"时，点击recyclerview一键置顶scrollToPosition(0)后，底部的footer也跟随到当前页面的底部，怎么能消除这个问题呢

**Comment by XiaoDada** [comment]
我也遇到了这个问题，作者这个该怎么解决呢

**Comment by scwang90** [comment]
1.1.0-14 发布，添加 closeHeaderOrFooter 方法，可以在置顶的时候调用
