### ISSUE TITLE
好像没有完美兼容vlayout

### ISSUE THREAD

**Issue by bean-liu** [scwang90/SmartRefreshLayout#587]
使用vlayout对RecycleView进行布局之后，SmartRefreshLayout下拉是正常的，自动加载更多上拉不正常，SmartRefreshLayout最新的alpha版还是正式版都试过了，正式版是上拉RecycleView有偏移但是不显示那个footer，alpha版上拉整个RecycleView都没有偏移了。有遇到这个问题的同学可以一起讨论下哦

**Comment by cc365774016** [comment]
@bean-liu 你也用了vlaout嘛，你用的时候上拉加载出现问题了啊

**Comment by bean-liu** [comment]
不要意思是因为自己配置不当导致的

**Comment by scwang90** [comment]
可以分享一下 配置，让后人少走弯路

**Comment by bean-liu** [comment]
@scwang90 app:srlEnableLoadMore="false" copy代码的时候把这个也copy过来了😂
