### ISSUE TITLE
关于finishRefresh(true)自动设置setNoMoreData(false)的问题

### ISSUE THREAD

**Issue by jklwan** [scwang90/SmartRefreshLayout#588]
在1.1.0-alpha9之后，在finishRefresh(int delayed, final boolean success) 方法中，如果success有这样一段代码，
- ` if (success) { setNoMoreData(false); }`
不知道是怎样考虑的，下拉刷新成功不一定有更多的数据吧。现在下拉刷新成功如果要设置没有更多的数据还要延时设置，希望给予回复。
谢谢。

**Comment by scwang90** [comment]
这个根据你自己的需求来做就好了
