### ISSUE TITLE
ListView的setOnScrollListener回调失效

### ISSUE THREAD

**Issue by T-mans** [scwang90/SmartRefreshLayout#59]
我想监听滑动，当开始滑动则收起item菜单，但是整个接口当两个方法都不会被回调。
框架提供了smartRefreshLayout.setOnScrollChangeListener。但是提示必须至少API23才可以用。
所以，有解决当办法吗？

**Comment by T-mans** [comment]
补充：侧滑框架是androidswipelayout

**Comment by scwang90** [comment]
使用多功能监听器，在文档中找找

**Comment by scwang90** [comment]
也可以 setOnTouchEvent 判断滑动，（注意返回false）

**Comment by T-mans** [comment]
谢谢，多功能监听器setOnMultiPurposeListener处理的是头部和尾部的状态回调，没法解决我的问题。
我通过listView.setOnTouchListener处理了这个问题。

**Comment by coolegos** [comment]
这个确实是一个问题吧？老代码中存在大量的`ListView`，然后`setOnScrollListener` 的两个方法里面有一些特殊的逻辑。比如在`onScrollStateChanged`中判断`scrollState==SCROLL_STATE_FLING`暂停图片框架的网络请求等等，还有在`onScroll`中判断当`firstVisibleItem`为某个值的时候一些特殊逻辑。
