### ISSUE TITLE
viewpage管理多个fragment,fragment重建后，下拉刷新失效、

### ISSUE THREAD

**Issue by zhongxiong00** [scwang90/SmartRefreshLayout#590]
设置缓存多个fragment或者重写destroyItem不走父类方法就没事了。 望作者改改这个bug

**Comment by scwang90** [comment]
fragment 的使用 demo 中有例子

**Comment by zhongxiong00** [comment]
原来你是用的一个SmartRefreshLayout，但是每个fragment都有一个SmartRefreshLayout的话，就有问题了。

**Comment by scwang90** [comment]
demo 中有例子的，好好找找

**Comment by yulu1121** [comment]
请问怎么解决的，Fragment中嵌套的ViewPager和Fragment，只有其中1个不能刷新，其他的都能，代码布局是一模一样的，我尝试让不能刷新的Fragment中的RecylcerView不能滑动，它是可以刷新的，是滑动冲突吗？
