### ISSUE TITLE
楼主大大，请问一下怎么添加滑动监听，我想做些控件的隐藏与显示

### ISSUE THREAD

**Issue by zyw1995** [scwang90/SmartRefreshLayout#591]
如题，refreshLayout.setOnScrollChangeListener有API lever限制，添加之后滑动监听函数没调用到，请问没有滑动监听函数的接口吗？

**Comment by zyw1995** [comment]
刚才加了recycleview.addOnScrollListener这个监听后，可以实现view的显示与隐藏，但是长按住手机屏幕上下滑动，列表一直抖动。。这是怎么了？？

**Comment by scwang90** [comment]
这个和 刷新库没关系，需要自己解决
