### ISSUE TITLE
ViewPager下使用SmartRefreshLayout下拉刷新无效

### ISSUE THREAD

**Issue by donlan** [scwang90/SmartRefreshLayout#594]
使用场景：
Activity根布局：

     <?xml version="1.0" encoding="utf-8"?>
     <LinearLayout
      android:orientation="vertical"
      xmlns:android="http://schemas.android.com/apk/res/android" 
      android:layout_width="match_parent"
      android:layout_height="match_parent">

     <android.support.design.widget.TabLayout
        android:id="@+id/trip_tab"
        android:layout_width="match_parent"
        android:layout_height="@dimen/action_bar_height" />

    <android.support.v4.view.ViewPager
        android:id="@+id/pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
    </LinearLayout>

ViewPager每一页的页面都是使用如下布局：

     <com.scwang.smartrefresh.layout.SmartRefreshLayout 
     xmlns:android="http://schemas.android.com/apk/res/android"
     android:id="@+id/refresh_layout"
     android:layout_width="match_parent"
     android:layout_height="match_parent">

     <android.support.v7.widget.RecyclerView
        android:id="@+id/common_rv"
        android:overScrollMode="never"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
     </com.scwang.smartrefresh.layout.SmartRefreshLayout>

当不用ViewPager,Activity根布局就直接是上面的布局内容时，下拉刷新可以正常使用。

使用版本：compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-12'

**Comment by scwang90** [comment]
你提供的代码没有问题，demo 中又 viewPager 的例子 ，你去参考一下

**Comment by GDPCCoder** [comment]
> 你提供的代码没有问题，demo 中又 viewPager 的例子 ，你去参考一下

你代码里的viepager是 在smarrefreshlayout下的，不是提问者这种写法
