### ISSUE TITLE
listview item不断的被重复绘制没有复用

### ISSUE THREAD

**Issue by qulong** [scwang90/SmartRefreshLayout#598]
![image](https://user-images.githubusercontent.com/6110023/43184289-adebecf8-901a-11e8-9da6-13b7f7215042.png)

我的adapter 里面有两个样式的View 
@Override
    public View getView(int position, View convertView, ViewGroup parent) {
 int type = getItemViewType(position);
        if (convertView == null) {
            switch (type) {
                case 0:
这里会被重复调用好几次，明明已经创建了，还是会进来
                    DebugLog.e("HOtVideoDetailAdapter","new HotVideoItem");
                    convertView = new HotVideoItemCell(mContext,videoToPayCallback);
                    break;

                default:
                    convertView = new DynamicCommentItem(mContext);
                    break;
            }
        }
...........
...........
return convertView;
}

SmartRefreshLayout.java中的这两个方法一直被调用
onLayout()
onMeasure(） 好像是这个方法一直不停的的在计算重新绘制界面，

**Comment by scwang90** [comment]
这个问题和smart没关系，你可以去百度一下其他原因
