### ISSUE TITLE
DefaultRefreshInitializer使用弱引用导致自身配置无法生效

### ISSUE THREAD

**Issue by foolchen** [scwang90/SmartRefreshLayout#603]
在master分支的[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout/blob/master/refresh-layout/src/main/java/com/scwang/smartrefresh/layout/SmartRefreshLayout.java#L2720-L2722)中使用了弱引用来存放`DefaultRefreshInitializer`对象，导致在使用时获取到的对象为空：

```java
DefaultRefreshInitializer initializer = sRefreshInitializer == null ? null : sRefreshInitializer.get();
// 此处获取到的DefaultRefreshInitializer必然为空，导致全局初始化无效
if (initializer != null) {
    initializer.initialize(context, this);//调用全局初始化
}
```

**Comment by scwang90** [comment]
先使用 1.1.0-12 把，13这个确实有问题，

**Comment by scwang90** [comment]
1.1.0-alpha-14 已经恢复
