### ISSUE TITLE
怎么关闭惯性刷新

### ISSUE THREAD

**Issue by kakasi163** [scwang90/SmartRefreshLayout#604]
刷新这块有没有类似惯性滑动关闭上拉加载的方法，当快速滑动到顶部时，会自动弹出刷新header,有什么方法可以屏蔽这个问题，谢谢

**Comment by scwang90** [comment]
有的，看文档

**Comment by bilx** [comment]
你好，我在文档上只看到了惯性加载更多的api开关 ，并没有看到刷新。请问你使用的是哪个？

**Comment by scwang90** [comment]
@bilx 你说的应该是关闭越界回弹

**Comment by bilx** [comment]
@scwang90  是的，开始没理解概念，已经解决了，谢谢

**Comment by Alexxiaopang** [comment]
> @scwang90 是的，开始没理解概念，已经解决了，谢谢

请问你是怎么解决的，我感觉很灵敏，调整阻尼感觉有拉不动
