### ISSUE TITLE
游戏header跟RecyclerView使用顶部出现黑边遮挡内容

### ISSUE THREAD

**Issue by shijia109** [scwang90/SmartRefreshLayout#605]
如题，RecyclerView内容被遮挡，大概两个状态栏高度，不管刷新与否都遮挡

**Comment by scwang90** [comment]
不能重现问题

**Comment by shijia109** [comment]
只能说明你测试还不到位，RecyclerView与vlayout配合smartrefresh一起使用就会这样

**Comment by shijia109** [comment]
http://b-cartoon.heiyanimg.com/recommend/online/1532671964206_1589273429.jpg
http://b-cartoon.heiyanimg.com/recommend/online/1532671975360_1916083698.jpg
上面是截图，并且无法控制游戏

**Comment by shijia109** [comment]
刚才别的页面都试了，不管是否使用Vlayout都这样，26.1.0版本RecyclerView，targetApi26，compile也是26
