### ISSUE TITLE
自定义下设置内容不偏移没有任何效果

### ISSUE THREAD

**Issue by anaivez** [scwang90/SmartRefreshLayout#607]
自定义下设置内容不偏移没有任何效果
 <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="100dp"
                android:gravity="center"
                android:text="HHH"
                android:textColor="#fff" />
    <android.support.v7.widget.RecyclerView
                android:id="@+id/rlv"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:descendantFocusability="blocksDescendants"
                android:overScrollMode="never" />

        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

Java：
   refreshLayout.setEnableFooterTranslationContent(false);

**Comment by anaivez** [comment]
内容不偏移不是主体不偏移 下拉刷新就是把TextView拉下来吗。

**Comment by scwang90** [comment]
smart 不支持这个效果，smart 只能用来做刷新
