### ISSUE TITLE
游戏header跟RecyclerView使用顶部出现黑边遮挡内容

### ISSUE THREAD

**Issue by shijia109** [scwang90/SmartRefreshLayout#608]
http://b-cartoon.heiyanimg.com/recommend/online/1532671964206_1589273429.jpg
http://b-cartoon.heiyanimg.com/recommend/online/1532671975360_1916083698.jpg
既然说无法复现，上面是我的截图作为证据，并且无法控制游戏，26.1.0版本RecyclerView，targetApi26，compile也是26

**Comment by scwang90** [comment]
还是无法重现

**Comment by shijia109** [comment]
你意思是我太倒霉吗？是还我太无聊拿个造假图片？反正我也不用这个刷新头，有问题也没关系，想不想关注这个问题在于你
