### ISSUE TITLE
现在在短距离拖动时会触发ContentView内元素的onClick事件，怎样在拖动时阻止contentview内元素触发onClick事件啊？

### ISSUE THREAD

**Issue by 2534290808** [scwang90/SmartRefreshLayout#609]
现在在短距离拖动时会触发ContentView内元素的onClick事件，怎样在拖动时阻止contentview内元素触发onClick事件啊？

**Comment by 2534290808** [comment]
![untitled](https://user-images.githubusercontent.com/24295236/43436810-ad65e818-94b8-11e8-888a-535bb23f3dc6.gif)
就像这样

**Comment by scwang90** [comment]
去参考 demo 中的方法
