### ISSUE TITLE
没法跟emptylayout结合

### ISSUE THREAD

**Issue by yyliang** [scwang90/SmartRefreshLayout#61]
emptylayout具体的地址：https://github.com/alamkanak/Android-Empty-Layout
因此，对于数据为空、数据加载中、数据网络异常的常驻提示显示非常不友好。
望改进，或者有什么提示，请指教

**Comment by scwang90** [comment]
你好，谢谢你的反馈，我想知道你之前使用的下拉刷新是什么库？这样我就可以参照那个库快速的兼容 emptylayout 的结合
