### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by TonyJason** [scwang90/SmartRefreshLayout#614]
上拉加载更多完成后，新增加的数据也成功了，但是新增加的数据(新增加的数据的第一条)没有出现在屏幕的可见范围内。这样用户不知道数据有没有加载到，需要用户再往下拉才看到数据？这是什么原因呢、？感谢

**Comment by scwang90** [comment]
1。尝试添加数据之后再 finishLoadMore 
2。需要自己书写滚动列表代码
