### ISSUE TITLE
mFooterLocked 的作用？

### ISSUE THREAD

**Issue by LinXiaoTao** [scwang90/SmartRefreshLayout#617]
* 版本：1.0.5.1
* 说明：
当前控件处理加载更多时候，不调用 ```finishLoadMore()```（比如网络请求缓慢时），先向下滑动一段距离，看不到**加载更多的底部**时，再向上滑动时，不能拖动，初步判断是 ```mFooterLocked == true``` 导致消费了嵌套滚动事件。
``` java
@Override
public void onNestedPreScroll(@NonNull View target, int dx, int dy, @NonNull int[] consumed){
   // ...
   if (dy > 0 && mFooterLocked) {
       consumedY = dy;
        mTotalUnconsumed -= dy;
       moveSpinnerInfinitely(mTotalUnconsumed);
  }
}
```
![Uploading Screenshot_20180806-143025.png…](问题效果图)
* 暂时解决
集成 SmartRefreshLayout 重写以下方法：
``` java
@Override
protected void setStateDirectLoading() {
     super.setStateDirectLoading();
    // mFooterLocked 不为 true
     mFooterLocked = false;
}
```

**Comment by LinXiaoTao** [comment]
![screenshot_20180806-143025](https://user-images.githubusercontent.com/19836925/43700569-b05b0d60-9985-11e8-9a83-a24774a55f91.png)

**Comment by scwang90** [comment]
作用：Footer 正在loading 的时候是否锁住 列表不能向上滚动

在新版本中已经添加 

if (mFooterLocked && dy > mTouchSlop && mSpinner < 0) {
      mFooterLocked = false;//内容向下滚动时 解锁Footer 的锁定
 }
