### ISSUE TITLE
按照listview原理实现recycleview的emptyview时，SmartRefreshLayout会导致emptyview向下偏移一段距离

### ISSUE THREAD

**Issue by kensonliang25** [scwang90/SmartRefreshLayout#618]
布局如下:
<com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#444444"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            app:srlAccentColor="@android:color/white"
            app:srlEnableLoadMore="true"
            app:srlPrimaryColor="@color/colorPrimary">

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <com.example.kenson.demo_databinding.SPEmptyRecycleView
                    android:id="@+id/recyclerView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="#fff"
                    android:overScrollMode="never"
                    android:visibility="visible" />

                <TextView
                    android:id="@+id/tv_empty"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@android:color/holo_blue_bright"
                    android:gravity="center"
                    android:text="没有内容"
                    android:visibility="gone" />
            </FrameLayout>

        </com.scwang.smartrefresh.layout.SmartRefreshLayout>
SPEmptyRecycleView观察到数据集为空时隐藏，并显示emptyview。但textview的文字显示在屏幕的中央偏下。

**Comment by scwang90** [comment]
把 emptyview 放在外面
