### ISSUE TITLE
使用经典风格Header问题

### ISSUE THREAD

**Issue by heweiquan** [scwang90/SmartRefreshLayout#62]
<img  src="https://user-images.githubusercontent.com/13057762/28351847-21d0dc38-6c85-11e7-9a2b-7d1727639c3c.png" width=300/>  <img  src="https://user-images.githubusercontent.com/13057762/28351687-f8c9e484-6c83-11e7-94ed-d6141fc03a05.png" width=300/>
<br/>
### 我在xml中设置Header背景和文字颜色后，刷新是箭头和加载进度条不见了
<br/>
<img src="https://user-images.githubusercontent.com/13057762/28351805-bbd05b34-6c84-11e7-98a2-d244c0006fdf.png" width=500/>

**Comment by heweiquan** [comment]
看了ClassicsHeader的源码。发现主要是用setPrimaryColors()或setAccentColor()方法来设置刷新view的背景和控件的相关颜色，而且我想要的设置header的背景方法是私有的，请问还有什么方法可以设置header的背景和改变文字、进度条颜色的吗？
<img src="https://user-images.githubusercontent.com/13057762/28350463-b8edb136-6c7b-11e7-8161-3ad452bd4478.png" width=500/>

**Comment by heweiquan** [comment]
再补上一张加了列表数据的图
<img  src="https://user-images.githubusercontent.com/13057762/28351687-f8c9e484-6c83-11e7-94ed-d6141fc03a05.png" width=300/>

**Comment by scwang90** [comment]
目前的，Header没有做过兼容图片背景的，不过很具我的直觉，直接黑Header设置图片背景，效果不好，因为header移动的时候，背景也在移动，我建议你不要设置Header的背景，让它透明，然后在 刷新布局或者刷新布局的背后，放置一张背景图片，效果更好，

**Comment by heweiquan** [comment]
我参考了您的建议后做出的效果基本达到我要的效果了，Thanks！

**Comment by Beiler** [comment]
使用出现问题，我在viewpager里放了四个fragment，每个fragment都用到了你的刷新控件，然后跳转到别的界面在回来，调用autoRefresh()方法，或者直接下拉刷新，不会触发刷新回调。过几秒钟后，自动结束刷新。
