### ISSUE TITLE
烦请更新AS版本

### ISSUE THREAD

**Issue by WalkingBlue** [scwang90/SmartRefreshLayout#620]
用的AS版本太低了，用新的3.1.x编译的话，一堆问题，作者能不能更新一下所用AS版本呢？

**Comment by pengMaster** [comment]
没有问题的，我用的AS version 3.1.2  gradle 4.1 plugin 3.0.0 没毛病

**Comment by scwang90** [comment]
开源库的AS版本不可能与每个人的一样的，最好的办法是自己学会适配不同版本的项目

**Comment by chenjingzhang** [comment]
把AS更新到3.0以上吧

**Comment by lianchengtong** [comment]
现在AS 都已经是3.5了，确实需要适配调整一下
