### ISSUE TITLE
未重写onSaveInstanceState保存控件状态

### ISSUE THREAD

**Issue by KeqingLI** [scwang90/SmartRefreshLayout#624]
版本号：1.1.0-alpha-14
复现：如修改系统默认字体大小，activity回收后加载,smartRefreshLayout不能下拉

**Comment by scwang90** [comment]
## 进过测试 如修改系统默认字体大小 之后
1. activity 会重新 调用 OnCreate，
2. 如果在其中调用了，setContentView 之后，原来的 SmartRefreshLayout 已经被销毁
3. 会得到一个新的 SmartRefreshLayout，所以 SmartRefreshLayout 实现 onSaveInstanceState 没有意义。
4. 而且测试下来也不会出现 SmartRefreshLayout 无法下拉的问题
## 建议
1. 应该在 Activity 中 实现 onSaveInstanceState，并保存原有 SmartRefreshLayout的状态
2. 在 onCreate 中把 原来保存的状态还原给 新的 SmartRefreshLayout
