### ISSUE TITLE
内容滑到一半调用autoRefresh()，不会回到顶部刷新，请问有什么好办法吗

### ISSUE THREAD

**Issue by viwenzhang** [scwang90/SmartRefreshLayout#628]

**Comment by ThugKd** [comment]
你好 请问找到办法了吗

**Comment by scwang90** [comment]
ListView RecyclerView 回到顶部，百度一下，很多啊

**Comment by weihongbo1** [comment]
可以先调用recyclerView.smoothScrollToPosition(0); 然后再调用autoRefresh()
或者在刷新监听中返回结果后，调用recyclerView.smoothScrollToPosition
效果都可以回到顶部

**Comment by ThugKd** [comment]
嗯嗯 已经解决了 谢谢

WeiHongbo <notifications@github.com> 于2018年11月16日周五 下午12:54写道：
