### ISSUE TITLE
这个库已经非常完美了，唯一的美中不足就是没有Scroll Bar

### ISSUE THREAD

**Issue by CH-Augustine** [scwang90/SmartRefreshLayout#636]
这个库已经非常完美了，唯一的美中不足就是没有Scroll Bar
我下载了源码尝试自己加一个 Scroll Bar 时，发现异常困难
我希望能有一个像IOS效果一样的Scroll Bar

**Comment by scwang90** [comment]
和刷新无关的功能是不会添加的
