### ISSUE TITLE
使用Materia的头部加载会露出一点点图片

### ISSUE THREAD

**Issue by AmoyJJ** [scwang90/SmartRefreshLayout#637]
[https://github.com/AmoyJJ/LoadingAndRetryManager/blob/master/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180823170315.png](url)

**Comment by scwang90** [comment]
更新版本

**Comment by youlai** [comment]
我最新版也是这个问题，怎么解决啊？？？
 //1.0.5 当1.1.0出现问题可以回退到1.0.5.1
    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-14'
    implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-alpha-14'
    //没有使用特殊Header，可以不加这行
    //如果使用了特殊的Header
    implementation 'com.google.android.material:material:1.1.0-alpha01'

**Comment by FynnJason** [comment]
> 我最新版也是这个问题，怎么解决啊？？？
> //1.0.5 当1.1.0出现问题可以回退到1.0.5.1
> implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-14'
> implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-alpha-14'
> //没有使用特殊Header，可以不加这行
> //如果使用了特殊的Header
> implementation 'com.google.android.material:material:1.1.0-alpha01'

我已解决 app:srlHeaderInsetStart="-10dp" 设置起始高度为负数
