### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by devnns** [scwang90/SmartRefreshLayout#638]
> When I implement a RefreshHeader and use it without RecyclerView between header and footer, sometimes app goes crash with the exception below:

Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView

**Comment by scwang90** [comment]
implementation 'com.android.support:recyclerview-v7:27.1.1'

**Comment by devnns** [comment]
Thank you
