### ISSUE TITLE
NoMoreData is not supported.(不支持NoMoreData)

### ISSUE THREAD

**Issue by e9ab98e991ab** [scwang90/SmartRefreshLayout#639]
很感谢楼主这么强大的库，在使用MaterialHeader时 SmartRefreshLayout调用finishRefresh()方法时会出现
footer.BallPulseFooter{8513b11 V.E...... ........ 0,1967-1080,2132} NoMoreData is not supported.(不支持NoMoreData) 这个log ，请问这个是什么原因造成的呢？

**Comment by scwang90** [comment]
BallPulseFooter 不支持 NoMoreData
