### ISSUE TITLE
如果我的targetSdkVersion 是22 就无法使用了

### ISSUE THREAD

**Issue by wqandroid** [scwang90/SmartRefreshLayout#64]
如果我的targetSdkVersion 是22， support库只能是22.x.x ，而你的库是25.3.0我依赖之后会编译失败，楼主能否吧库的版本号放到主app进行控制

**Comment by scwang90** [comment]
你的描述不对呀，我的App targetSdkVersion 也是 22呀，没问题照样用额，你弄成 22 是为了省去权限处理吗？

**Comment by scwang90** [comment]
~~~
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    targetSdkVersion 22
~~~

compileSdkVersion buildToolsVersion 设置为25就可以了

**Comment by scwang90** [comment]
问题以解决，请使用 8 的版本

**Comment by wqandroid** [comment]
谢谢
