### ISSUE TITLE
[Binary XML file line #71: 最多只支持3个子View，Most only support three sub view]

### ISSUE THREAD

**Issue by cervy** [scwang90/SmartRefreshLayout#641]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/smart_refresh_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <pl.droidsonroids.gif.GifImageView
        android:id="@+id/gifView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="fitCenter"
        android:src="@mipmap/refresh_head"
        app:layout_srlBackgroundColor="@android:color/transparent"/>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/f1f1f1"
        android:orientation="vertical">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/dp_10"
            android:layout_marginEnd="@dimen/dp_20"
            android:layout_marginLeft="@dimen/dp_20"
            android:layout_marginStart="@dimen/dp_20"
            android:layout_marginTop="@dimen/dp_10"
            android:drawableLeft="@drawable/greenrow"
            android:drawablePadding="@dimen/dp_5"
            android:text="@string/csrecent"
            android:textColor="@color/blackthree"
            android:textSize="@dimen/text_big15_size"/>

        <View
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_1"
            android:background="@color/backgroundd"/>

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerViewcsrecent"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />
    </LinearLayout>
</com.scwang.smartrefresh.layout.SmartRefreshLayout>

**Comment by scwang90** [comment]
更新版本

**Comment by larrymeng** [comment]
@scwang90 
当前最新版本 1.1.0-alpha-20 还是报这个错啊：

java.lang.RuntimeException: 最多只支持3个子View，Most only support three sub view

**Comment by larrymeng** [comment]
> Caused by: java.lang.RuntimeException: 最多只支持3个子View，Most only support three sub view
>         at com.scwang.smartrefresh.layout.SmartRefreshLayout.onFinishInflate(SmartRefreshLayout.java:333)
