### ISSUE TITLE
调用finishLoadmore或finishRefresh后有的页面会跳到中间的位置，这是怎么回事

### ISSUE THREAD

**Issue by xwtao** [scwang90/SmartRefreshLayout#643]
调用finishLoadmore或finishRefresh后有的页面会跳到中间的位置

**Comment by Dizner** [comment]
会不会是焦点乱了？清除一下焦点试试

**Comment by xwtao** [comment]
找到原因了，是只有一页时候加载更多又刷新了recycleview出现的。现在还发现的问题是上拉后一直把手指拉在那，上拉加载更多会出现反复跳的现象，这是什么原因？还有个问题是有时候上拉加载更多时候加载结束后加载条不会消失，下拉刷新时候有时候没经过下拉刷新直接弹回去了，这又是什么原因？。用的是1.0.4版本

**Comment by scwang90** [comment]
可以使用最新版本
