### ISSUE TITLE
嵌套StickyDecoration标题无法固定

### ISSUE THREAD

**Issue by liguo-git** [scwang90/SmartRefreshLayout#650]
依靠这几个貌似子组件中找不到view的id
app:srlFixedFooterViewId="@+id/header_fixed"
    app:srlFixedHeaderViewId="@+id/footer_fixed"
    app:srlHeaderTranslationViewId="@+id/header_translation"
    app:srlFooterTranslationViewId="@+id/footer_translation"

**Comment by scwang90** [comment]
不兼容 StickyDecoration，可以试试其他库
