### ISSUE TITLE
为什么删除isEnableRefresh和isEnableLoadMore

### ISSUE THREAD

**Issue by xufangzhen** [scwang90/SmartRefreshLayout#653]
可有替代方法？

**Comment by leeManong** [comment]
setEnableLoadMore

**Comment by scwang90** [comment]
可以自己继承Smart之后，添加 isEnableRefresh 和 isEnableLoadMore方法

**Comment by hzz9600** [comment]
大佬你这移除isEnableRefresh和isEnableLoadMore方法很难受啊，明明常用的API，新版本还得重新继承来暴露，都不兼容之前版本的，搞的项目想升级还得下载下来改源码。不常用就不会有这个issues了

**Comment by 985211yyg** [comment]
我也是醉了 继承Smart 得改多少代码 优秀
