### ISSUE TITLE
滚动时的缓冲效果也会带出一点点HeaderView

### ISSUE THREAD

**Issue by JuZiSang** [scwang90/SmartRefreshLayout#66]
比如，快速滚动时，手指离开屏幕了，ScrollView的缓冲效果也会带出一点点HeaderView

**Comment by scwang90** [comment]
这个是本库的特殊功能，越界回弹，如果不喜欢可以关闭这个功能

**Comment by caik13** [comment]
setEnableOverScrollBounce()
我在文档里没找到，在源码里找到的

**Comment by wilsonapk** [comment]
没找到 - -！
