### ISSUE TITLE
listView 下拉冲突 怎么解决

### ISSUE THREAD

**Issue by YCJDJG** [scwang90/SmartRefreshLayout#665]
布局如下：   
 <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/divide"
        android:background="@color/white">

        <ListView
            android:id="@+id/order_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginLeft="@dimen/qb_px_10"
            android:layout_marginRight="@dimen/qb_px_10"
            android:background="@drawable/corners_white_bg"
            android:divider="@color/colorBackground"
            android:dividerHeight="@dimen/qb_px_20"
            android:overScrollMode="never"
            android:scrollbars="none">

        </ListView>

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

**Comment by scwang90** [comment]
可以之定义滚动边界，看文档
