### ISSUE TITLE
语言可以手动切换吗？

### ISSUE THREAD

**Issue by NestleSprite** [scwang90/SmartRefreshLayout#666]
可以在代码里切换 刷新中，下拉刷新等的语言吗？

**Comment by NestleSprite** [comment]
已解决

**Comment by 3277076046** [comment]
> 可以在代码里切换 刷新中，下拉刷新等的语言吗？

请问怎么切换？

**Comment by zxm1243** [comment]
@NestleSprite 请问怎么切换的？

**Comment by 3277076046** [comment]
没有找到切换的，最后只能强制app重启------------------ 原始邮件 ------------------
发件人: "zxm1243"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 中午11:49
收件人: "scwang90/SmartRefreshLayout"<SmartRefreshLayout@noreply.github.com>;
抄送: "3277076046"<3277076046@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [scwang90/SmartRefreshLayout] 语言可以手动切换吗？ (#666)



@NestleSprite 请问怎么切换的？
 
&mdash;

**Comment by zxm1243** [comment]
@3277076046 重启还是英文，我手机语言环境是中文，怎么会去加载英文呀 奇怪了
