### ISSUE TITLE
pure scroll at the bottom and "pull to zoom" at header?

### ISSUE THREAD

**Issue by amanzan** [scwang90/SmartRefreshLayout#671]
Is this possible? I want to achieve pure scroll at the bottom and "pull to zoom" at header. So when it goes all the way down, there's a rebound effect, and all the way up, a header that zooms when you pull down.

Header would be similar to FlyRefreshHeader, but just with an ImageView

**Comment by amanzan** [comment]
This is the effect I'm trying to achieve:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3911627/45881424-6ec10180-bdab-11e8-87b3-5c7d92c86f4c.gif)

**Comment by scwang90** [comment]
You need to customize Header
