### ISSUE TITLE
关于引入该项目中文乱码问题？

### ISSUE THREAD

**Issue by tangbei** [scwang90/SmartRefreshLayout#674]
![image](https://user-images.githubusercontent.com/16919309/46061914-bfb16b00-c19a-11e8-9148-c4f6e5b3aa5b.png)

![image](https://user-images.githubusercontent.com/16919309/46061856-9a246180-c19a-11e8-85a1-65e802a0df4b.png)

我引入此项目，编译时，写入的R文件出现乱码，我用utf-8尝试过，还是无法解决这个中文和乱码在一起的问题，是R文件出现的乱码，手动更改无效。请问有什么办法吗？

**Comment by scwang90** [comment]
使用最新版本
