### ISSUE TITLE
SmartRefreshLayout 下拉刷新与 FlexboxlayoutManager冲突

### ISSUE THREAD

**Issue by tmxdyf** [scwang90/SmartRefreshLayout#678]
recyclerView使用 FlexboxlayoutManager 时，往上滑到底部，然后下滑，容易出现recyclerview还没有到滑动到顶部就开始出现下拉刷新组件。
FlexboxlayoutManager来自于google.flexboxlayout

**Comment by li-xiaojun** [comment]
我也有这个问题，降级到1.0.5就好了，新版本有这个bug

**Comment by scwang90** [comment]
demo 中有 flexboxlayout 的例子，可以参考一下
