### ISSUE TITLE
请问，“全部加载完成”能否一直显示在底部

### ISSUE THREAD

**Issue by yanboefrei** [scwang90/SmartRefreshLayout#68]
求教，当没有更多数据的时候，能否让“全部加载完成”这种提示语一直显示在底部，并且可以随着内容滑动（类似支付宝滑动到最后那种）？多谢！

**Comment by scwang90** [comment]
那种 footer 需要在 adapter中添加，你可取起使用  BaseRecyclerViewAdapterHelper 这个库

**Comment by Freedomhxb** [comment]
setEnableFooterFollowWhenLoadFinished
