### ISSUE TITLE
在fragment中调用finishRefresh()有时候空指针

### ISSUE THREAD

**Issue by callmecaoye** [scwang90/SmartRefreshLayout#682]
case: fragment onCreateView进行网络请求 在回调中第一行finishRefresh()  有时候会报NullPointerException
reason: 有可能和fragment生命周期有关？
handle: 需要在回调中先判断mSmartRefreshLayout != null ?

谢谢！: )

**Comment by Liberations** [comment]
同遇到。。。

**Comment by wapchief** [comment]
mark

**Comment by callmecaoye** [comment]
我在调用finishRefresh()前 先判断if (isResume()) 或者 if (getUserVisibleHint())

**Comment by Liberations** [comment]
统一判空了。。。fragment中问题就是多
 SmartRefreshLayout?.finishRefresh()
 SmartRefreshLayout?.finishLoadMore()

**Comment by lixiaokuan0819** [comment]
应该是请求没结束，界面被销毁了

**Comment by scwang90** [comment]
if 判断一下就好了
