### ISSUE TITLE
首页RecyclerView+头布局，偶尔出现进首页之后没有列表只有头布局的问题

### ISSUE THREAD

**Issue by Payphone7** [scwang90/SmartRefreshLayout#685]
偶尔出现没有列表只有头布局的情况，不太确定什么原因，列表和头布局的数据是分别请求的数据，列表adapter用的是brvah，刷新用的是SmartRefreshLayout，两边我都提了issue，希望大佬有时间帮看看，非常感谢

**Comment by scwang90** [comment]
这么久了，应该解决了
