### ISSUE TITLE
上拉加载，怎么不是释放之后在加载

### ISSUE THREAD

**Issue by 652028815** [scwang90/SmartRefreshLayout#686]
版本号：1.1.0-alpha-14

**Comment by 652028815** [comment]
目前状态是PullUpToLoad时就开始加载更多了吧，正常习惯是释放之后在开始加载更多的吧，对应的状态应该是ReleaseToLoad，是bug吗

**Comment by Cc599245355** [comment]
这个问题好像都没人理，这属于bug么

**Comment by scwang90** [comment]
关闭自动加载功能，多看文档
