### ISSUE TITLE
上啦问题（最新版本）

### ISSUE THREAD

**Issue by lifuyuan123** [scwang90/SmartRefreshLayout#691]
1.上啦时手指还未离开屏幕就开始加载，未满一屏的情况手指未离开屏幕，界面会跳动，并且会触发下拉，显示下拉图标。横向滑动貌似也有冲突。
2.在fragment中使用，标题栏有隐藏，adapter没有隐藏的item，慢慢上拉会出现不能触发上啦的情况，快速上拉可以触发。隐藏title时有调用smart的requestlayout方法。

**Comment by lifuyuan123** [comment]
1.设置autoLoadmore为false后松开手即可触发
2.自己代码问题

**Comment by kongdeli** [comment]
@lifuyuan123 多谢，我也是发现了你说的第一个问题，没想到这个autoloadMore是默认为true的。
