### ISSUE TITLE
能否把库的compile改为implementation

### ISSUE THREAD

**Issue by magic0908** [scwang90/SmartRefreshLayout#692]
我的studio版本是3.2，每次编译的时候都会提示Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.It will be removed at the end of 2018
我看了一下SmartRefreshLayout的依赖是有用到compile的，不知道是不是这问题

**Comment by Liberations** [comment]
你自己换下就行了啊

**Comment by lixiaokuan0819** [comment]
> @Liberations 我是gradle依赖的，请问如何修改

你自己把compile改为implementation就行了啊- -
