### ISSUE TITLE
我给app设置主题下拉刷新布局花屏问题

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#696]
app主题设置这属性之后
"android:windowBackground">@null</item>
。下拉刷新的布局花屏

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/home_page_fragment_smartRefreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlEnablePreviewInEditMode="true">

        <com.scwang.smartrefresh.layout.header.ClassicsHeader
            android:id="@+id/home_page_fragment_smartRefresh_headerLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/home_page_fragment_smart_head_drawable_size"
            app:srlClassicsSpinnerStyle="FixedBehind"
            app:srlDrawableArrowSize="@dimen/home_page_fragment_smart_head_drawable_size"
            app:srlDrawableMarginRight="@dimen/home_page_fragment_smart_head_drawable_size"
            app:srlDrawableProgress="@drawable/ic_progress_puzzle"
            app:srlDrawableProgressSize="@dimen/home_page_fragment_smart_head_drawable_size"
            app:srlEnableLastTime="true"
            app:srlFinishDuration="500"
            app:srlTextSizeTime="@dimen/home_page_fragment_smart_head_time_size"
            app:srlTextSizeTitle="@dimen/home_page_fragment_smart_head_title_size"
            app:srlTextTimeMarginTop="@dimen/home_page_fragment_smart_head_timeMarginTop_size" />

        <android.support.design.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

这个是我头文件的布局

**Comment by xyZangGit** [comment]
![tim 20181023190557](https://user-images.githubusercontent.com/19574114/47356490-ce863180-d6f6-11e8-908d-4bca20cc1713.png)
![tim 20181023190927](https://user-images.githubusercontent.com/19574114/47356621-32105f00-d6f7-11e8-9f19-4e3c2f4ea574.png)

这是花屏效果

**Comment by scwang90** [comment]
这是正常现象
