### ISSUE TITLE
刷新体验

### ISSUE THREAD

**Issue by ozy20** [scwang90/SmartRefreshLayout#7]
经典刷新 ： 正在刷新状态，往上滑动，header能否设置也随着滚动上去，而不是固定？

**Comment by scwang90** [comment]
你的问题还不是太了解，你是说刷新还没结束的时候，上滑动列表，提前结束刷新动画吗？

**Comment by XiaoQiWen** [comment]
https://github.com/XiaoQiWen/KRefreshLayout @scwang90 这是我也写的刷新框架，可以多交流，另外我体验了下楼主的刷新框架，1、header触摸事件没处理，2、下拉Header会有点Bug,3、ViewPager兼容性问题
可以私下多交流

**Comment by scwang90** [comment]
谢谢 @XiaoQiWen 你提的三点，我去琢磨琢磨

**Comment by ozy20** [comment]
@scwang90  你好，我的意思是，正在刷新的时候，当向上滑动列表，刷新头部随着向上滑动，而不是固定不动。类似https://github.com/jianghejie/XRecyclerView

**Comment by scwang90** [comment]
谢谢 @ozy20 我会去分析分析，如果没大问题我会加上这个功能

**Comment by scwang90** [comment]
@XiaoQiWen 可以具体描述一下你列出问题的第二点吗？
我需要知道：
是某部分Header还是所有Header？
是每次都出现还是偶尔出现？
你测试的手机型号和系统版本？
bug具体描述？

**Comment by 123ufo** [comment]
https://github.com/123ufo/DWRefreshLayout这个是我写的欢迎Star.欢迎讨论.

**Comment by lancewong2014** [comment]
关于体验，我也想说一点。
为什么要限制下拉刷新与上拉加载的同时发生呢？

**Comment by scwang90** [comment]
1.0.2-alpha-3 已经发布，本条问题已经解决
