### ISSUE TITLE
嵌套ListView时，当ListView只有 1条数据时，触摸空白地方无法下拉！！！

### ISSUE THREAD

**Issue by kingboup** [scwang90/SmartRefreshLayout#70]
比如 Demo中 BasicUsingActivity，初始化时只添加2条数据时，不能下拉！ 如下图：

<img width="331" alt="default" src="https://user-images.githubusercontent.com/4961695/28407018-301d2400-6d65-11e7-972d-0dd41f951820.png">
<img width="278" alt="default" src="https://user-images.githubusercontent.com/4961695/28407174-ca299196-6d65-11e7-815b-938244ad2c2f.png">

另：将 布局文件 activity_using_basic 中 <ListView  的属性 android:layout_height="match_parent" 改为 android:layout_height="wrap_content" 就可以下拉了。但是，实际项目中在某些情况下 必须要设置为 android:layout_height="match_parent"。(如我还有嵌套其它自定义控件)   

麻烦楼主看看能否该修复这个问题，谢谢~

**Comment by scwang90** [comment]
关闭嵌套滚动，在属性和方法文档中查找

**Comment by kingboup** [comment]
3Q~
