### ISSUE TITLE
上拉加载更多数据直到最后一页完成，在下拉不能刷新了 

### ISSUE THREAD

**Issue by jjjjbababy** [scwang90/SmartRefreshLayout#701]

**Comment by qczgwxg** [comment]
我也遇到这个问题了，你解决了吗?

**Comment by jjjjbababy** [comment]
没解决

**Comment by qczgwxg** [comment]
可有其它的上拉和下拉的框架

**Comment by jjjjbababy** [comment]
没办法用的BRVAH的上拉 和这个的下拉结合的

**Comment by RaphetS** [comment]
调用下拉之前加行代码mRefreshLayout.resetNoMoreData()

**Comment by jjjjbababy** [comment]
> 调用下拉之前加行代码mRefreshLayout.resetNoMoreData()

你用的哪个？我怎么没有这个方法

**Comment by scwang90** [comment]
用
finishLoadMoreDataWithNoMoreData() 
代替
setNoMoreData（false）

或者
setNoMoreData（false）
之前加上 
finishLoadMore()
setNoMoreData（false）
