### ISSUE TITLE
大佬，Demo里的“嵌套滚动-整体嵌套” 滑动顶部固定的部分会直接触发 下面的加载更多。求助

### ISSUE THREAD

**Issue by Yunme** [scwang90/SmartRefreshLayout#703]
当 “菜单列表” 这几个字固定在上面的时候 ，在这上面滑动会直接触发 下面RecycleView 的加载更多。
不知道有解决办法吗

**Comment by scwang90** [comment]
更新到最新版本 1.1.0-17
并在对应的 VIew xml 中添加 

android:focusableInTouchMode="true"

**Comment by Yunme** [comment]
> 更新到最新版本 1.1.0-17
> 并在对应的 VIew xml 中添加
> 
> android:focusableInTouchMode="true"
> 
> 具体参考新版 demo



> 更新到最新版本 1.1.0-17
> 并在对应的 VIew xml 中添加
> 
> android:focusableInTouchMode="true"
> 
> 具体参考新版 demo

你好，我下载最新的 demo ，上面的问题没有了，但是上拉加载也触发不了了啊 大佬。

**Comment by scwang90** [comment]
是的，失误了，不能用系统变量标记。
更新到 1.1.0-18
改用 android:tag="fixed"
