### ISSUE TITLE
一个activityadd多个fragment场景下,越界回弹

### ISSUE THREAD

**Issue by nicelyjust** [scwang90/SmartRefreshLayout#704]
一个activity add多个fragment场景下,越界回弹 可看到前一个fragment内容, 请问我该如何设置避免?

**Comment by scwang90** [comment]
都过了这么久了，应该自己解决了吧

**Comment by nicelyjust** [comment]
@scwang90 算是 hide不可见的fragment , 还是有些疑问 最上边的fragment应该把点击事件吃掉了才对? anyway , 感谢作者开源这么好用的库,谢谢!
