### ISSUE TITLE
在设置释放后回弹动画时长后影响了 "释放刷新" 到 "开始刷新" 的时间间隔

### ISSUE THREAD

**Issue by evanyu1024** [scwang90/SmartRefreshLayout#706]
具体问题如下：
在设置 srlReboundDuration（释放后回弹动画时长）属性后，该属性对 ReleaseToRefresh（释放刷新） 状态到 Refreshing（刷新中） 状态的时间间隔，比如我设置了1000ms回弹动画时长，那么当我释放刷新后，要间隔一秒才会触发 Refreshing 状态的回调，正常情况应该是松手后，立即触发刷新。现在回弹的默认时长是250ms，所以感知不到这个问题，将时间设置久一点，这个问题就能明显的感知到了。

PS：这应该是加入越界回弹功能后出现的bug，因为在老版本中（1.0.3）中没有这个问题。

**Comment by scwang90** [comment]
ReleaseToRefresh -> Refreshing 有一个释放的动作，然后开始回弹动画，只是回弹位置不是 0点
srlReboundDuration 控制的就是所有的回弹动画时间
