### ISSUE TITLE
头部和底部是否可以同时设置成加载？

### ISSUE THREAD

**Issue by SilenceGo** [scwang90/SmartRefreshLayout#707]
你好。有一个疑问，假如有一个列表需要展示当前时间之前和当前时间之后的数据，此时，想把顶部刷新效果做成底部加载的效果（PS：上下都是加载），在框架里试了几种方法，没有找到合适的，请问，有什么办法能实现我说的这种效果么？

**Comment by scwang90** [comment]
自定义 Header，或者吧 Footer 当成 Header 来用
