### ISSUE TITLE
mFooterLocked always true in some case

### ISSUE THREAD

**Issue by lixi0912** [scwang90/SmartRefreshLayout#716]
* SmartRefreshLayout: [1.1.0-alpha-14, 1.1.0-andx-4]

	In my case, LoadStatePresenter will replace SmartRefreshLayout with LoadStateLayout and then cannot reset mFooterLocked because onDetachedFromWindow is called.

    在一些特殊情况下，当触发上拉加载更多后，如果 `onDetachedFromWindow` 在 `finishLoadMore` 的 Runnable 执行之前被调用，将会导致 mFooterLocked 一直为 true，再也无法上滑列表，建议在  `onDetachedFromWindow` 方法中重置 mFooterLocked = false

**Comment by scwang90** [comment]
非常感谢
