### ISSUE TITLE
下拉刷新头部能不能别自动回弹啊

### ISSUE THREAD

**Issue by nanyeweiwu** [scwang90/SmartRefreshLayout#719]

**Comment by rebelboy** [comment]
当然可以了。你调用mRefreshLayout.autoRefresh() 就是一直开着

**Comment by scwang90** [comment]
嗯，可以的

**Comment by LvBing1995** [comment]
autoRefresh( duration,800,1.0f,false);我这样调用后下拉的动画就不会出现回弹现象，或者你看下源码也可以改下拉的插值动画
