### ISSUE TITLE
设置成阻尼效果,没有上拉加载更多的回调

### ISSUE THREAD

**Issue by wangshufu** [scwang90/SmartRefreshLayout#721]
这是布局
<com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/mSmartRefreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:srlEnablePureScrollMode="true">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/mListLayout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:overScrollMode="never"/>

</com.scwang.smartrefresh.layout.SmartRefreshLayout>

下面的监听回调都没有回调回来
mSmartRefreshLayout.setOnLoadMoreListener {
            Log.d("***","setOnLoadMoreListener")
}

mSmartRefreshLayout.setOnRefreshListener {
            Log.d("***","setOnRefreshListener")
}

mSmartRefreshLayout.setOnRefreshLoadMoreListener(object : OnRefreshLoadMoreListener{
            override fun onLoadMore(refreshLayout: RefreshLayout) {
                Log.d("***","onLoadMore")
            }

            override fun onRefresh(refreshLayout: RefreshLayout) {
                Log.d("***","onRefresh")
            }

})

**Comment by wangshufu** [comment]
mSmartRefreshLayout.setEnablePureScrollMode(false)
        mSmartRefreshLayout.setRefreshHeader(FalsifyHeader(context))
        mSmartRefreshLayout.setRefreshFooter(FalsifyFooter(context))


mSmartRefreshLayout.setOnRefreshLoadMoreListener(object : OnRefreshLoadMoreListener{
            override fun onLoadMore(refreshLayout: RefreshLayout) {
                Log.d("***","onLoadMore")
            }

            override fun onRefresh(refreshLayout: RefreshLayout) {
                Log.d("***","onRefresh")
            }

        })

**Comment by scwang90** [comment]
是的，没有
