### ISSUE TITLE
你好博主，进入页面经典样式的自动刷新能不能去掉往下拉的那个动画啊，页面多了反而觉得适得其反，页面反应慢，还是我没有找到设置的地方

### ISSUE THREAD

**Issue by miweijiafei** [scwang90/SmartRefreshLayout#723]

**Comment by scwang90** [comment]
不调用 autoRefresh() 就好了

**Comment by zjy-programmer** [comment]
同问这个问题 我现在的需求是进入页面需要显示下拉刷新动画 所以需要调用autoRefresh() 但是这个方法会让头部有一个过渡下拉再回弹一点然后执行动画 能不能去掉这个过渡下拉的过程 直接是下滑头部的高度后就开始执行动画

**Comment by LvBing1995** [comment]
> 程 直接是下滑头部的高度后就开
有解决吗，这个问题看的很难受
