### ISSUE TITLE
CoordinatorLayout + AppBarLayout + RecyclerView 快速上滑时，上拉加载获取第二页的数据后，recyclerView 会惯性地往上滑，请教下该怎么解决

### ISSUE THREAD

**Issue by lixiaokuan0819** [scwang90/SmartRefreshLayout#727]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
            app:srlEnableLoadMoreWhenContentNotFull="false"
            android:id="@+id/smartRefreshLayout"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            android:background="@android:color/transparent"
            app:srlAccentColor="@android:color/white"
            app:srlEnablePreviewInEditMode="true">

            <com.scwang.smartrefresh.layout.header.ClassicsHeader
                android:id="@+id/classicsHeader"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@android:color/transparent"/>

            <android.support.design.widget.CoordinatorLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <android.support.design.widget.AppBarLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@android:color/transparent"
                    app:elevation="0dp">

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_below="@+id/titleBar"
                        app:layout_scrollFlags="scroll">

                        <View
                            android:layout_width="match_parent"
                            android:layout_height="86dp"
                            android:layout_alignParentBottom="true"
                            android:background="@android:color/white"/>

                        <android.support.v7.widget.CardView
                            android:id="@+id/coverCard"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_marginLeft="20dp"
                            android:layout_marginTop="15dp"
                            android:layout_marginBottom="48dp"
                            app:cardCornerRadius="5dp">

                            <ImageView
                                android:id="@+id/cover"
                                android:layout_width="105dp"
                                android:layout_height="140dp"
                                android:scaleType="fitXY"
                                android:src="@drawable/ic_default_cover"/>

                            <ImageView
                                android:layout_width="wrap_content"
                                android:layout_height="match_parent"
                                android:src="@drawable/bg_cover_left"/>

                            <TextView
                                android:id="@+id/playNumber"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="bottom|center_horizontal"
                                android:layout_marginBottom="8dp"
                                android:background="@drawable/bg_play_number"
                                android:drawableLeft="@drawable/ic_play"
                                android:drawablePadding="5dp"
                                android:paddingLeft="8dp"
                                android:paddingTop="5dp"
                                android:paddingRight="8dp"
                                android:paddingBottom="5dp"
                                android:textColor="@android:color/white"
                                android:textSize="10sp"
                                tools:text="8888"/>

                            <TextView
                                android:id="@+id/difficulty"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="bottom|right"
                                android:layout_marginBottom="8dp"
                                android:background="@drawable/bg_difficulty"
                                android:gravity="center"
                                android:textColor="@android:color/white"
                                android:textSize="14sp"
                                tools:text="A"/>

                        </android.support.v7.widget.CardView>

                        <ImageView
                            android:id="@+id/avatar"
                            android:layout_width="50dp"
                            android:layout_height="50dp"
                            android:layout_marginLeft="20dp"
                            android:layout_marginTop="23dp"
                            android:layout_toRightOf="@+id/coverCard"
                            android:src="@drawable/ic_default_avatar"/>

                        <ImageView
                            android:id="@+id/vip"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_marginLeft="32dp"
                            android:layout_marginTop="10dp"
                            android:layout_toRightOf="@+id/coverCard"
                            android:src="@drawable/ic_vip_top"
                            android:visibility="gone"/>

                        <TextView
                            android:id="@+id/username"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_marginLeft="8dp"
                            android:layout_marginTop="23dp"
                            android:layout_marginRight="20dp"
                            android:layout_toRightOf="@+id/avatar"
                            android:ellipsize="end"
                            android:gravity="center_vertical"
                            android:maxLines="1"
                            android:textColor="@android:color/white"
                            android:textSize="18sp"
                            tools:text="@string/user_name"/>

                        <TextView
                            android:id="@+id/createTime"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_below="@+id/username"
                            android:layout_marginLeft="8dp"
                            android:layout_marginTop="12dp"
                            android:layout_toRightOf="@+id/avatar"
                            android:textColor="@android:color/white"
                            android:textSize="12sp"
                            tools:text="2018-08-08 20:00"/>

                        <LinearLayout
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_below="@+id/avatar"
                            android:layout_marginLeft="20dp"
                            android:layout_marginTop="14dp"
                            android:layout_toRightOf="@+id/coverCard"
                            android:gravity="center_vertical"
                            android:orientation="horizontal">

                            <com.qicaibear.view.StarView
                                android:id="@+id/starView"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content">
                            </com.qicaibear.view.StarView>

                            <TextView
                                android:id="@+id/score"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="10dp"
                                android:textColor="@android:color/white"
                                android:textSize="18sp"
                                tools:text="100分"/>
                        </LinearLayout>

                        <TextView
                            android:id="@+id/likeNumber"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_alignBottom="@+id/coverCard"
                            android:layout_toRightOf="@+id/coverCard"
                            android:drawableLeft="@drawable/ic_like_gray"
                            android:drawablePadding="8dp"
                            android:gravity="center_vertical"
                            android:paddingLeft="20dp"
                            android:paddingBottom="8dp"
                            android:textColor="@color/contentText"
                            android:textSize="14sp"
                            tools:text="8888"/>

                        <View
                            android:layout_width="match_parent"
                            android:layout_height="10dp"
                            android:layout_alignParentBottom="true"
                            android:background="@color/background"/>

                    </RelativeLayout>

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="@android:color/white"
                        android:orientation="horizontal">

                        <TextView
                            android:id="@+id/latestComments"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_marginLeft="20dp"
                            android:layout_marginTop="30dp"
                            android:layout_marginBottom="15dp"
                            android:text="@string/latest_comments"
                            android:textColor="@color/blackPrimary"
                            android:textSize="18sp"
                            android:textStyle="bold"/>

                        <TextView
                            android:id="@+id/commentNumber"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_marginLeft="10dp"
                            android:layout_marginTop="30dp"
                            android:layout_marginBottom="15dp"
                            android:layout_toRightOf="@+id/latestComments"
                            android:textColor="@color/blackPrimary"
                            android:textSize="18sp"
                            android:textStyle="bold"
                            tools:text="@string/comment_number"/>
                    </RelativeLayout>

                </android.support.design.widget.AppBarLayout>

                <android.support.v7.widget.RecyclerView
                    android:overScrollMode="never"
                    android:id="@+id/recyclerView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@android:color/white"
                    android:descendantFocusability="blocksDescendants"
                    app:layout_behavior="@string/appbar_scrolling_view_behavior">
                </android.support.v7.widget.RecyclerView>
            </android.support.design.widget.CoordinatorLayout>

            <com.scwang.smartrefresh.layout.footer.ClassicsFooter
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:srlAccentColor="@color/blackAssist"/>
        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

**Comment by yuanwenbing** [comment]
我也有这个问题，谁知道怎么解决？

**Comment by yuanwenbing** [comment]
刚才想个办法，算是临时解决了，在 loadmore 的时候，把 Scroll 的滚动停掉。
@Override
    public void onLoadmore(RefreshLayout refreshLayout) {
        mRecyclerView.stopScroll();
        .........

}

**Comment by lixiaokuan0819** [comment]
> 刚才想个办法，算是临时解决了，在 loadmore 的时候，把 Scroll 的滚动停掉。
> @override
> public void onLoadmore(RefreshLayout refreshLayout) {
> mRecyclerView.stopScroll();
> .........
> 
> }

恩 我现在也是这么处理

**Comment by scwang90** [comment]
@yuanwenbing  good!

**Comment by meijingkang** [comment]
这是什么问题导致的,具体是什么原因呢

**Comment by zhupengxiang** [comment]
我用的2.0版本   SmartRefreshLayout+CoordinatorLayout 也是上拉加载完成后rv向上滚动一点点  调用stopScroll无效
