### ISSUE TITLE
下拉刷新和webVeiw 的冲突问题，  当webView里面有滑动事件的时候，WebVeiw 不能滑动到顶部了，只能上划，下拉就会调用下拉刷新

### ISSUE THREAD

**Issue by BayMaxM** [scwang90/SmartRefreshLayout#728]

**Comment by BayMaxM** [comment]
https://www.sonystyle.com.cn/minisite/di/4k_handycam/mobile.html  这是测试链接 进入网页点击其中一个就会出现那种情况

**Comment by scwang90** [comment]
WebView 的问题参考
#394

**Comment by textwang** [comment]
> https://www.sonystyle.com.cn/minisite/di/4k_handycam/mobile.html 这是测试链接 进入网页点击其中一个就会出现那种情况

请问您怎么解决的

**Comment by BayMaxM** [comment]
按楼主说的：让网页端给个交互告诉你网页是否到达了顶部或者底部或者让网页端去掉相关的下拉控件，或者app端不下拉刷新。#394 ，
