### ISSUE TITLE
SmartRefreshLayout在frgament中，复用fragment出现下拉刷新出现bug

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#732]
![tim 20181121144838](https://user-images.githubusercontent.com/19574114/48823698-ca543f00-ed9c-11e8-88ef-746c3b496e46.png)
frgament中有  SmartRefreshLayout+recycleview

此页面是tablayout+viewpage+FragmentStatePagerAdapter+fragment

（FragmentStatePagerAdapter 是为了大于三个页面的时候，进行frgament 的销毁，不在内存中）

二级菜单是直接复用的fragment，左右滑动viewpage，再回到二级菜单的frgament，下拉刷新，失效，
布局不显示，松手之后 布局一闪而过，

这个是不左右滑动viewpage ，没有走销毁，创建状态，

这是正常的情况的：
![default](https://user-images.githubusercontent.com/19574114/48823967-b957fd80-ed9d-11e8-802e-118968234ea9.png)

**Comment by xyZangGit** [comment]
这个是我的层级关系
![_20181121150235](https://user-images.githubusercontent.com/19574114/48824194-85c9a300-ed9e-11e8-9857-268cdbc93394.png)

**Comment by xyZangGit** [comment]
希望大大可以看一下我的问题

**Comment by scwang90** [comment]
fragment 的使用 参考 demo
