### ISSUE TITLE
怎么解决的 我最新版还是有这个问题

### ISSUE THREAD

**Issue by youlai** [scwang90/SmartRefreshLayout#733]
![WX20180916-142024@2x.png](https://i.loli.net/2018/09/16/5b9df6e8de850.png)

_Originally posted by @huclengyue in https://github.com/scwang90/SmartRefreshLayout/issues/637#issuecomment-421707961_

**Comment by youlai** [comment]
//1.0.5 当1.1.0出现问题可以回退到1.0.5.1
    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-14'
    implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-alpha-14'
    //没有使用特殊Header，可以不加这行
    //如果使用了特殊的Header
    implementation 'com.google.android.material:material:1.1.0-alpha01'

这是我依赖的版本。

**Comment by scwang90** [comment]
使用 1.1.0-alpha--16

**Comment by FynnJason** [comment]
我已解决 app:srlHeaderInsetStart="-10dp" 设置起始高度为负数 我使用的 1.1.0-alpha-18
