### ISSUE TITLE
自定义View的问题

### ISSUE THREAD

**Issue by Veykon** [scwang90/SmartRefreshLayout#734]
新手一枚，我在自定义view的时候，xml布局文件有ImageView  ProgressBar 和TextView三个普通的控件，但是只有TextView显示出来，ImageView  ProgressBar没有显示，可以帮忙分析下原因吗，谢谢！

**Comment by NicodeLee** [comment]
原因是：代码都没贴全靠猜

**Comment by Veykon** [comment]
我已经自行解决了，谢谢！
