### ISSUE TITLE
WaveSwipeRefreshLayout特别容易卡住

### ISSUE THREAD

**Issue by asche910** [scwang90/SmartRefreshLayout#735]
如图，特别容易处于某一状态不动了，除非再次刷新恢复
![screenshot_20181121-223414](https://user-images.githubusercontent.com/13347412/48889975-803d8d00-ee72-11e8-9200-d02321963500.jpg)
![screenshot_20181121-225726](https://user-images.githubusercontent.com/13347412/48890039-a6fbc380-ee72-11e8-9e0f-f75b5152962f.jpg)
![screenshot_20181122-111007](https://user-images.githubusercontent.com/13347412/48890095-cd216380-ee72-11e8-8dba-c73c270b5d2a.jpg)

**Comment by scwang90** [comment]
新版版已发布，问题已修复
