### ISSUE TITLE
有情况导致ListView的滚动事件丢失???

### ISSUE THREAD

**Issue by hexu2016** [scwang90/SmartRefreshLayout#736]
就是先拖动ListView,触发了SCROLL_STATE_TOUCH_SCROLL,然后手不松开继续下拉触发刷新,然后SCROLL_STATE_IDLE事件就没有了???

**Comment by scwang90** [comment]
需要自己监听滚动的话，同时开启 ListView 和 Smart  嵌套滚动功能
