### ISSUE TITLE
androidmanifest.xml合并冲突

### ISSUE THREAD

**Issue by figorchen** [scwang90/SmartRefreshLayout#74]
Attribute application@label value=(Intents) from [com.android.support.test.espresso:espresso-intents:2.2.2] AndroidManifest.xml:24:18-41 is also present at [com.scwang.smartrefresh:SmartRefreshHeader:1.0.2-alpha-7] AndroidManifest.xml:13:9-41 value=(@string/app_name).
看起来是espresso的androidmanifest.xml中label和SmartRefreshLayout的androidmanifest.xml中label都设置了属性引起的冲突

**Comment by scwang90** [comment]
使用 1.0.2-alpha-8 的版本

**Comment by figorchen** [comment]
还是不行,同样的错误

**Comment by figorchen** [comment]
而且理论上来说,这个库不应该在androidmanifest中包含太多属性吧

**Comment by scwang90** [comment]
你先百度一下，后面的版本会考虑这个问题的

**Comment by scwang90** [comment]
问题已经修复，使用最新版本解决问题
