### ISSUE TITLE
footer能加个“加载失败，点击重试”的状态吗

### ISSUE THREAD

**Issue by 287257255** [scwang90/SmartRefreshLayout#741]
booter能加个“加载失败，点击重试”的状态吗

**Comment by 287257255** [comment]
另外啊，还有一个bug就是，上拉加载失败的时候，底布局并不总是能够拉出来，飞滑的时候好些！！

**Comment by scwang90** [comment]
所提功能建议在 Adapter 中添加 footer 来实现，小问题已修复
