### ISSUE TITLE
只要显示下拉效果，不回调接口

### ISSUE THREAD

**Issue by stiflerfang** [scwang90/SmartRefreshLayout#744]
我的项目里以前用的是SwipeRefreshLayout，它是有setRefresh方法来显示下拉效果的，但是该方法不回调下拉借口，我的项目都是基于这种逻辑实现的，现在用smartrefreshlayout，他只要autorefresh显示下来效果，但是显示下拉效果以后会回调接口，是否有API只显示下拉效果，不回调下拉接口。

**Comment by scwang90** [comment]
新版已经添加 此功能
