### ISSUE TITLE
setNestedScrollingEnabled问题

### ISSUE THREAD

**Issue by lihaodong** [scwang90/SmartRefreshLayout#746]
Demo中ScrollView实例如果RecyclerView数据为空，会出现滑出屏幕。默认RecyclerView占满一屏幕。导致空数据的时候，也有一个空白页面。
于是切换成NestedScrollView包裹，是用 mRecyclerView.setNestedScrollingEnabled(false);导致下拉刷新上拉加载被禁用。
大神求指教。

**Comment by scwang90** [comment]
NestedScrollView 不能放在 Smart 的外面
