### ISSUE TITLE
使用经典风格Header问题

### ISSUE THREAD

**Issue by zgnckzn** [scwang90/SmartRefreshLayout#748]
使用版本如下：    
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-16'
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-alpha-16'

问题描述：
使用经典风格的header，调用RefreshLayout.setPrimaryColors(Color.parseColor("#1381f8"), Color.parseColor("#ffffff"));更改背景颜色和文字以及箭头的颜色后，下拉发现背景和文字颜色都变为设置的颜色，箭头还是更改之前的颜色，在未触发更新前松开后，再次下来，发现箭头颜色也变为更改的颜色了。

发现以上问题，反馈给大神。
最后，感谢大神的库，太好用了。

**Comment by scwang90** [comment]
感谢，问题已修复
