### ISSUE TITLE
添加design库之后还是不能预览

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#749]
![_20181206192241](https://user-images.githubusercontent.com/19574114/49581260-54e79180-f98c-11e8-9541-69a660c5e3b4.png)

**Comment by sunjiaxin** [comment]
Android studio 3.5.1  Androidx 环境, 
引入 com.android.support:design:25.3.1'//版本随意（非必须，引用可以解决无法预览问题） 
无法预览
引入 com.google.android.material:material:1.0.0
无法预览

求解决
