### ISSUE TITLE
下拉刷新的问题

### ISSUE THREAD

**Issue by NerdAnonymous** [scwang90/SmartRefreshLayout#750]
下拉刷新的时候，手势松开，正在刷新的状态时，此时网络比较慢，没有禁用刷新时手势时，在往上推，推到动画一半，就会停顿到那，提个建议，如果刷新时，用户手动上拉算是取消刷新，是不是更智能一些

**Comment by scwang90** [comment]
谢谢

**Comment by FY6** [comment]
但是有时候不想用户在往上推取消呢？
