### ISSUE TITLE
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1' grade版本

### ISSUE THREAD

**Issue by mingabc** [scwang90/SmartRefreshLayout#752]
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1' 支持的grade版本是多少，目前导入工程，run报错org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugKotlin'.   1.1.0-alpha-16可以正常使用 ， Demo工程 grade版本 gradle:3.1.3  buildToolsVersion '27.0.3'

**Comment by scwang90** [comment]
使用 1.1.0 版本就可以了
