### ISSUE TITLE
mlastOpenTime为0时的异常

### ISSUE THREAD

**Issue by ruodezizaiyi** [scwang90/SmartRefreshLayout#755]
public SmartRefreshLayout finishLoadMore() {
        long passTime = System.currentTimeMillis() - this.mLastOpenTime;
        return this.finishLoadMore(Math.max(0, 300 - (int)passTime));
    }

复现：如果没有调用autofresh（）一类的方法，直接使用finishLoadMore，mLastOpenTime为0，passTime再转为int类型的时候会变成负数，所有delayTime会非常大，如果是设置刷新或加载的时候禁止列表的操作，后续列表将无法更新数据。

**Comment by scwang90** [comment]
没看到 Math.max 会取最大吗？

**Comment by ruodezizaiyi** [comment]
long类型passTime再转为int类型的时候会变成负数,300 - 负数 会很大，比如 11000000这样的，max取最大不就是11000000

**Comment by scwang90** [comment]
这一把，新版Smart 中是没有问题的，因为自从 1.1.0 版本以后，这个地方的代码已经改成下面了，最大也是 300

```
    @Override
    public SmartRefreshLayout finishRefresh() {
        long passTime = System.currentTimeMillis() - mLastOpenTime;
        return finishRefresh(Math.min(Math.max(0, 300 - (int) passTime), 300));//保证刷新动画有300毫秒的时间
    }
```

老版本的问题，智能在新版本中修复，如果必须使用老版本，需要忽略这些问题。
