### ISSUE TITLE
请问是否支持上拉加载更多后，footer直接隐藏，不显示加载完成的状态

### ISSUE THREAD

**Issue by gitJusth** [scwang90/SmartRefreshLayout#760]
请问是否支持上拉加载更多后，footer直接隐藏，不显示加载完成的状态

**Comment by wuyinlei** [comment]
请问解决了么？怎么解决的

**Comment by wuyinlei** [comment]
mRefreshLayout.finishRefresh(0)
 mRefreshLayout.finishLoadMore(0)
作者的代码默认的是给了1000毫秒的延迟   可以设置动画时长

**Comment by MIkeeJY** [comment]
请问是否支持上拉加载更多后，footer直接隐藏，不显示加载完成的状态，现在1.0.5的版本怎么加载过程中还显示了加载完成的footer啊？

**Comment by MIkeeJY** [comment]
classicsFooter.setFinishDuration(0);

**Comment by scwang90** [comment]
3楼正解

**Comment by hukejia** [comment]
> 3楼正解

设置后finishLoadMore不是显示加载完成了，但是调用finishLoadMoreWithNoMoreData还是会显示加载完成，这个加载完成的体验太差了，除了增加用户等待时间，没有一点用处，强烈建议去掉

**Comment by lijinshanmx** [comment]
new ClassicsFooter().setFinishDuration(0)即可.

**Comment by lijinshanmx** [comment]
翻翻源码就能找到怎么优化这个体验

**Comment by sorrybeman** [comment]
### 也可以设置xml

```xml
 <com.scwang.smart.refresh.footer.ClassicsFooter
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:srlFinishDuration="0"/>
