### ISSUE TITLE
数据没满屏时Footer的效果

### ISSUE THREAD

**Issue by ymqq** [scwang90/SmartRefreshLayout#763]
这行的底部提示如何实现，数据没满屏的时候。

![wx20181221-180007](https://user-images.githubusercontent.com/3469590/50336894-4c758600-054a-11e9-855d-5937d58889ef.png)

**Comment by zhaoyongjiang** [comment]
哥们，效果实现了吗？赐教

**Comment by ymqq** [comment]
没有，用这个组件，几乎没有想到啥好的处理方式。

目前能够想到的就是，在列表最后追加一个没有更多的元素，然后将recyclerview背景也设置成一样，

同时禁止展示Footer

**Comment by scwang90** [comment]
myqq 使用的是正确的方法

**Comment by zhaoyongjiang** [comment]
ok
