### ISSUE TITLE
CoordinatorLayout+AppBarLayout+ViewPager,在最外层加刷新控件，在上拉加载的时候会出现图片所示情况

### ISSUE THREAD

**Issue by SuperAton** [scwang90/SmartRefreshLayout#764]
![_20181222113748](https://user-images.githubusercontent.com/25004643/50370373-37e3cd00-05e0-11e9-8555-b6c82944e0a6.png)
![_20181222113737](https://user-images.githubusercontent.com/25004643/50370370-2ef2fb80-05e0-11e9-8645-8e378784de27.png)

**Comment by scwang90** [comment]
这个问题需要加群解决
