### ISSUE TITLE
1.0.5版本问题

### ISSUE THREAD

**Issue by tanzhihao1qaz** [scwang90/SmartRefreshLayout#765]
此版本的setEnableRefresh为false的时候，下拉时只是不见了刷新头部，整体还是可以下拉拖动，1.0.3倒没有这个问题，希望UP看到这个问题（一开始我以为是代码问题，搞了很久换了个版本才发现不是代码问题OTZ）

**Comment by scwang90** [comment]
这是新版本的功能，可以关闭
