### ISSUE TITLE
大大，代码和demo里面的没有变化，在安卓9.0小米mix2s下拉刷新箭头不见了

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#767]
，但是刷新旋转的控件没问题

**Comment by Xxxxxxyk** [comment]
亲测,升级到1.1.0版本正常,手机 1+6 Android9.0

**Comment by xyZangGit** [comment]
> 亲测,升级到1.1.0版本正常,手机 1+6 Android9.0

好的，我尝试一下，

**Comment by xyZangGit** [comment]
> 亲测,升级到1.1.0版本正常,手机 1+6 Android9.0

感谢，已解决
