### ISSUE TITLE
当SmartRefreshLayout嵌套包过scrollview的时候有个小问题。

### ISSUE THREAD

**Issue by itsgm** [scwang90/SmartRefreshLayout#77]
当SmartRefreshLayout嵌套包过scrollview的时候
refreshLayout.setEnableAutoLoadmore(true);//开启自动加载功能
这一行代码不生效，不会开启自动加载的功能。
嵌套listview的时候，这行代码是ok的。

**Comment by scwang90** [comment]
已经修复，更换最新版本解决
