### ISSUE TITLE
fragmentOne嵌套frgamentTwo+viewpage 下拉刷新失效

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#771]
fragmentTwo中的下拉刷新失效，下拉可以刷新不会变成 释放立即刷新，并且不会走刷新方法
  viewpageadapter使用的是FragmentStatePagerAdapter，当frgament过多的时候 ，
FragmentStatePagerAdapter 使用原因的是因为frgament过多，销毁除了当前页面和左右页面的其他fragment  左右滑动，在回到销毁的页面，下拉刷新会失效，  如果不左右滑动，不走销毁方法，下拉舒心是不会失效的，这个问题我反映过一次，如果大大看到，我可以给您复现的demo

**Comment by xyZangGit** [comment]
麻烦大大看一眼，frgamnet嵌套frgament的时候，内部的frgament的下拉刷新失效，希望大大看一下怎么回事

**Comment by xiaoguiYY** [comment]
> 麻烦大大看一眼，frgamnet嵌套frgament的时候，内部的frgament的下拉刷新失效，希望大大看一下怎么回事

我的是里面的fragment上拉加载更多失效，你有找到解决办法了吗？

**Comment by xyZangGit** [comment]
> 进群并上传 复现问题的 demo 代码（要求使用最新版本的smart）
好的，我先demo写好

**Comment by scwang90** [comment]
Smart demo 中由很多 frgament+viewpage 的示例，好好参考一下
