### ISSUE TITLE
使用ClassicsHeader的Scale模式，下拉的时候，提示箭头被压扁

### ISSUE THREAD

**Issue by zl277287818** [scwang90/SmartRefreshLayout#772]
1.当前使用的版本号 1.1.0-alpha-18
2.使用代码 
<com.scwang.smartrefresh.layout.header.ClassicsHeader
            style="@style/MatchWrap"
            app:srlClassicsSpinnerStyle="Scale"
            app:srlDrawableArrowSize="12dp"
            app:srlDrawableProgress="@drawable/ic_progress_hojder"
            app:srlDrawableProgressSize="16dp"
            app:srlEnableLastTime="true"
            app:srlTextSizeTitle="12sp" />

**Comment by scwang90** [comment]
1.1.0-alpha-20 已经发布解决
