### ISSUE TITLE
ConstraintLayout+SmartRefreshLayout快速上拉没有更多，底部未隐藏的问题

### ISSUE THREAD

**Issue by EdminhPeng** [scwang90/SmartRefreshLayout#780]
ConstraintLayout中嵌套SmartRefreshLayout，SmartRefreshLayout嵌套一个RecyclerView，当加载更多完成后，底部显示没有更多了，并且跟随RecyclerView底部，当滑动到底部，再快速下拉滑动至头部时，偶先：没有更多View部分或者全部没有隐藏，浮在RecyclerView上。
![image](https://user-images.githubusercontent.com/21301463/51153024-874cae80-18a9-11e9-8a67-6ecca73c3de1.png)

**Comment by MIkeeJY** [comment]
是的~

**Comment by scwang90** [comment]
提供的信息太少，建议参考demo来做

**Comment by MIkeeJY** [comment]
@scwang90 最新版 已经修复 但是1.0.5.1 版本仍然有此bug

**Comment by EdminhPeng** [comment]
> 提供的信息太少，建议参考demo来做，也可以手动调用 closeHeaderOrFooter 来关闭，或者关闭Smart 的加载功能， 使用 Adapter开源库 的方法来实现加载更多

是参照Demo写的呢，就是快速滑动，底部View有时候并没有关闭，调用closeHeaderOrFooter关闭也只是在滑动停止后才能关闭上，整个滑动过程中底部View并没有连贯着RecyclerView的滑动，使用第三方Adapter是可以解决该问题，可是这样子就违背了当初使用这套SmartRefreshLayout的初衷。

**Comment by EdminhPeng** [comment]
> @scwang90 最新版 已经修复 但是1.0.5.1 版本仍然有此bug

我用的就是最新版本了，快速滑动确实存在底部跟随内容不连贯的问题

**Comment by MIkeeJY** [comment]
@EdminhPeng  加载完成强制调用 closeHeaderOrFooter方法 暂时OK

**Comment by scwang90** [comment]
如果是对Footer 的连贯性要求高的话，Smart 无法满足的，需要使用 BRVAH 开源库来实现上拉加载
