### ISSUE TITLE
为什么，上拉加载更多的时候，页面会往下回弹呢

### ISSUE THREAD

**Issue by littlezan** [scwang90/SmartRefreshLayout#781]
如果还是没有找到答案，提问请带上这几个必要信息
1.当前使用的版本号：最新版本
2.复现操作描述：往上拉，加载更多

![gif](https://user-images.githubusercontent.com/5358278/50967779-1b1e2380-1514-11e9-9d7e-2cc97dc5f927.gif)

**Comment by scwang90** [comment]
如果在 调用 finishLoadMore的时候，列表没有新数据就会回弹，由新数据的话就会显示显示新数据
