### ISSUE TITLE
状态切换：推荐一个数据成功失败的状态切换类库StateLayout

### ISSUE THREAD

**Issue by li-xiaojun** [scwang90/SmartRefreshLayout#789]
这种状态切换的逻辑一般是必须的，但是不适合SmartRefreshlayout来实现，大家可以试试我的UI状态切换库，与界面解耦，任何界面可以直接使用。
地址是：https://github.com/li-xiaojun/StateLayout

感谢作者编写这么优秀的刷新库！

**Comment by scwang90** [comment]
不知道这个地方的广告效益怎样，不过过一段时间要关闭了

**Comment by li-xiaojun** [comment]
@scwang90 好的
