### ISSUE TITLE
调用setLoadmoreFinished(true)之后没有占位的View在滑到底部提示已经没有数据了.

### ISSUE THREAD

**Issue by bxhuhu** [scwang90/SmartRefreshLayout#79]
如题 , 设置之后只有不能触发加载更多的效果,但是不能有个占位的文本在用户每次拉到底部的时候提醒没有更多数据了.
------------------------------------------------------------
例如支付宝滑到底部没有更多数据了会有这个占位的文本.
@scwang90

**Comment by scwang90** [comment]
你好，本库不支持给列表添加 占位 item，你需要自己添加或者使用其他的 Adapter开源库来实现

本库开发的目的时为了进行 刷新布局和列表的解耦，如果本控件去给列表添加 占位item，那么就不能完成解耦的目的，增加 刷新布局与列表的耦合度，
所以在以后也不会添加这个功能

**Comment by bxhuhu** [comment]
不考虑在调用setLoadmoreFinished(true) 之后依然可以上拉但不响应加载更多方法   但是拉上来的View显示没有更多数据了吗?
@scwang90

**Comment by scwang90** [comment]
你所说的功能逻辑混乱，并不适合大部分需求，你的意见不会被采纳

**Comment by bxhuhu** [comment]
好吧,不能都算了,  如果能支持这个扩展就好了 , 还是得自己折腾一个...
