### ISSUE TITLE
VerticalViewPager, 上拉动画，可能会没有回滚到正确位置

### ISSUE THREAD

**Issue by Raynor999** [scwang90/SmartRefreshLayout#796]
自定义的ViewPager 继承自ViewGroup （ copy ViewPager,额外添加了支持横向滚动）
### bug描述：
上拉加载到更多数据后，触发ViewPager 刷新，同时 finishLoadMore()  会导致 ViewPager 没有回滚到正确位置。
### 调试问题原因 和猜测：
代码调试，出问题时，ViewPager 的mScrollY 没有滚到到当前页 正确对应的值。  手指随便滑动一下，就可以正常了。  怀疑SmartRefreshLayout 没有正确分发事件导致。  

 用例中没有可以参考的情况，没有ViewPager的例子很少，而且横向滚动的例子多是RecyclerView，xxxScrollView 等。

目前在看跟进源码， 不过源码 从dispatchEvent 就开始拦截了事件，理清逻辑稍显复杂， 希望能得到作者帮助

**Comment by Raynor999** [comment]
另外补充一个问题，setFooterInsetStartPx 方法为什么给去掉了。 如果去掉，也应该保留默认设置PX的方法吧？而不是DP,  限制了灵活性。   代码中根据不同手机 具体View 之间的间距 计算来设setFooterInsetStart 都是计算出的px, 结果只能设置DP.    DP 毕竟是抽象逻辑。

**Comment by scwang90** [comment]
finishLoadMore 默认会去滚动 mScrollY ，你可以尝试关闭Smart 的，【加载完成是滚动内容显示新数据】的功能，如果还有问题，解决的话，需要提供你的 ViewPager  源码和 能复现 问题的 demo

dp/px 的问题，后面会考虑再作调整，你目前可以通过 px2dp 先转换一下

**Comment by Raynor999** [comment]
> finishLoadMore 默认会去滚动 mScrollY ，你可以尝试关闭Smart 的，【加载完成是滚动内容显示新数据】的功能，如果还有问题，解决的话，需要提供你的 ViewPager 源码和 能复现 问题的 demo
> 
> dp/px 的问题，后面会考虑再作调整，你目前可以通过 px2dp 先转换一下

抱歉这么晚回复，年前版本，使用ViewPager 提供的 fakeDragBy() 方法hack 修复了bug.
目前 setEnableScrollContentWhenLoaded(false) 看起来可能解决了问题. 由于问题本就是小概率，当前界面需求的数据获取有诸多限制，测试样本不足，需要继续验证。

**Comment by Raynor999** [comment]
另外提一个建议： 当前需求使用只需要footer, 但是源码中默认初始化Header，只能设置隐藏不启用。为什么不能自己灵活指定呢？  有可能会多 inflate 无用的View.

**Comment by scwang90** [comment]
SmartRefreshLayout 作为刷新库，Header 设计之初就是必要的，如果吧 Header 设计成 nullable，Smart 的源码逻辑要改动很多，如果你只是想要求 节省内存，优化性能，你可以先 
setEnableRefresh(false), 
setRefreshHeader(new RefreshHeaderWrapper(new View(context)));
