### ISSUE TITLE
正在刷新的状态下刷新列表，loading动画会有点卡顿感

### ISSUE THREAD

**Issue by sunkeding** [scwang90/SmartRefreshLayout#799]
需求是：每次下拉刷新都要走完loading动画（动画持续1300ms），header是自定义的；但是如果在正在刷新的状态（Refreshing）下时，recycleview走了几次notifyDataSetChanged();会导致loading动画有卡顿感。请问如何做到即使是在loading的过程中刷新列表也不会造成卡顿的感觉呢

**Comment by scwang90** [comment]
这样的情况，只能让 loading 和 notifyDataSetChanged 错开了
如：给 notifyDataSetChanged 添加延时，保证 loading 动画结束之后再执行 notifyDataSetChanged
