### ISSUE TITLE
支持5.0系统下拉的样式吗？

### ISSUE THREAD

**Issue by csh159** [scwang90/SmartRefreshLayout#8]

**Comment by scwang90** [comment]
不太明白你的意思，能具体描述或者截图吗？

**Comment by csh159** [comment]
swiperefreshlayout 下拉样式

**Comment by scwang90** [comment]
哈哈，当然有的，你每看仔细而已

![](https://github.com/scwang90/SmartRefreshLayout/blob/master/art/gif_Material.gif)

**Comment by csh159** [comment]
好的，谢谢啊
