### ISSUE TITLE
RecycleView嵌套RecycleView滑动冲突（1.10-alpha-19）

### ISSUE THREAD

**Issue by Nstd** [scwang90/SmartRefreshLayout#800]
横向的RecycleView中，item是个纵向的RecycleView，纵向RV有下拉刷新的功能
在1.1.0-alpha-14中没有滑动冲突
在1.10-alpha-19中有滑动冲突：先下拉一段距离，然后往左或往右滑动，左右可以滑动（需要，在下拉刷新的时候左右不能滑动）

环境：
华为 Honor 9 Lite/LLD-AL10
EMUI 8.0.0
Android 8.0.0

**Comment by scwang90** [comment]
1.10-alpha-19 中，嵌套滚动是默认打开的，你可以关闭Smart的【嵌套滚动】功能试试

**Comment by Nstd** [comment]
好的，但这个可能比较麻烦，因为主项目和子项目都引用了你这个库，出问题的是子项目的，我这边暂时改不了，到时候和同事协商一下再看看。

还发现两个问题：
1. 调用了`finishLoadMoreWithNoMoreData()` 虽然禁止了加载更多的事件，但是上拉的时候还是能看到footer，且显示“加载更多”，而不是“无更多数据”，这个不太友好，不知道是不是我使用上的问题。
2. 以下这种布局
```xml
<FrameLayout ...>
      <SmartRefreshLayout andriod:id="@+id/result" > ... 搜索结果 </SmartRefreshLayout>
      <FrameLayout android:id="@+id/candidate" > ... 搜索后选词 </FrameLayout>
</FrameLayout>
```
默认展示搜索候选词，result `GONE`
有结果以后，candidate `GONE`, result `VISIBLE`
此时如果下拉刷新，布局会一直在抖动，当把两处的`GONE`，替换为`INVISIBLE`以后，能正常显示

**Comment by Nstd** [comment]
用demo试了下，没有触发这个问题，可能是特定逻辑引发的。。
