### ISSUE TITLE
事件冲突

### ISSUE THREAD

**Issue by a741762308** [scwang90/SmartRefreshLayout#803]
您好，我这边发现您源码有mFalsifyEvent用来伪造事件发送，但是我的子View有相应的事件处理，怎样才能解决这个事件冲突

**Comment by scwang90** [comment]
可以把滚动控件 换成 RecyclerView 或者 NestScrollView 等支持嵌套滚动的View，然后开启 Smart 的嵌套滚动功能，这样就不会在触发伪造事件了
