### ISSUE TITLE
您好，下拉超过header高度后释放，为什么onStartAnimator不是在回到header高度后调用？

### ISSUE THREAD

**Issue by KaelInvoker** [scwang90/SmartRefreshLayout#808]
如题，我使用的是1.0.5.1版本，看发布日志上说1.0.4已经修复了，为什么我自己试了下还是存在这种现象？

**Comment by KaelInvoker** [comment]
再补充一句，换了一台oppo手机没有问题。好像我这个华为CAM-TL00H 6.0上一直会出现这个问题

**Comment by KaelInvoker** [comment]
您好，再反馈个问题；上拉的时候，如果未上拉到触发刷新距离，只回调了onPulling，为什么没有回调onReleased？

**Comment by scwang90** [comment]
1.华为手机这边测试也没问题，如果这个问题对你影响很大，往自己能调试 Smart 的源码，并找出问题，然后到github来提出 pull request 为开源事业做贡献
2.onPulling onReleased 没调用是因为，footer 开启了，自动加载功能，没有pulling 和 release 事件，只有 Animator 动画事件，如果需要这两个事件，可以关闭自动加载功能，setAutoEnableLoadMore(false)
