### ISSUE TITLE
autoRefreshAnimationOnly()瞬间消失

### ISSUE THREAD

**Issue by Zheng-Shuo** [scwang90/SmartRefreshLayout#809]
如题，我想已进入到界面就自动刷新列表，然后加载完成时调用finishRefresh()来结束下拉刷新，但是autoRefreshAnimationOnly()调用之后一瞬间就消失了，这个是为什么？已经设置setOnRefreshListener()

**Comment by scwang90** [comment]
1.1.0-21 修复

**Comment by Zheng-Shuo** [comment]
@scwang90 你好，之前刷新动画瞬间消失的问题已经修好了，但是我又发现了一个问题，如果在调用autoRefreshAnimationOnly()之后没等它的动画完成的时候就调用finishRefresh()的话，头就一直在停留在等待刷新完成的状态了，我这边有的时候数据回的特别快就会发生这样的问题

**Comment by scwang90** [comment]
1.1.0-22 修复

**Comment by daiziyu** [comment]
> 1.1.0-22 修复

你好，我也碰到了这个问题，今天使用的com.scwang.smartrefresh:SmartRefreshLayout:1.1.0 
会出现头回弹了，再下拉刷新不触发onRefresh 一直停留在刷新状态了就
