### ISSUE TITLE
长时间翻页使用会crash,崩溃日志如下

### ISSUE THREAD

**Issue by JackFung2015** [scwang90/SmartRefreshLayout#811]
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@1408b7f

com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:748)

**Comment by scwang90** [comment]
注意不要使用已经回收的 bitmap

**Comment by JackFung2015** [comment]
额，已经找到原因了，与本框架无关。

**Comment by ForeverLover** [comment]
可以问下，这个是怎么解决的么，我这也遇到这个问题，关键我这没有那个地方有recycle bitmap啊。是列表项的问题么，求大佬指教啊

**Comment by JackFung2015** [comment]
> 
> 
> 可以问下，这个是怎么解决的么，我这也遇到这个问题，关键我这没有那个地方有recycle bitmap啊。是列表项的问题么，求大佬指教啊

列表用glide加载图片时有闪烁问题，为了解决闪烁问题，使用了下面的代码设置占位图
.placeholder(imageView.getDrawable())
虽然解决了闪烁，但出现标题描述的问题，把占位图设置成一张固定图片就解决了。
![图片](https://user-images.githubusercontent.com/12047712/62606479-eac62880-b92e-11e9-8e7f-aac8a9bdd5d4.png)

**Comment by ForeverLover** [comment]
我这边的glideoptonisnew RequestOptions().dontAnimate().error(R.drawable.vshow_default_img).placeholder(R.drawable.vshow_default_img).fallback(R.drawable.vshow_default_img).关键它没报出错的具体问题，报错信息太笼统了，不好排查。谢谢了



# main(2)

java.lang.RuntimeException

Canvas: trying to use a recycled bitmap android.graphics.Bitmap@9b43883

解析原始

1 android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:55)

2 android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)

3 android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)

4 android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)

5 android.view.View.getDrawableRenderNode(View.java:19403)

6 android.view.View.drawBackground(View.java:19339)

7 android.view.View.draw(View.java:19136)

8 android.view.View.updateDisplayListIfDirty(View.java:18095)

9 android.view.View.draw(View.java:18873)

10 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

11 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

12 android.view.View.draw(View.java:19148)

13 android.view.View.updateDisplayListIfDirty(View.java:18095)

14 android.view.View.draw(View.java:18873)

15 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

16 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

17 android.view.View.updateDisplayListIfDirty(View.java:18086)

18 android.view.View.draw(View.java:18873)

19 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

20 android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)

21 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

22 android.view.View.draw(View.java:19148)

23 android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)

24 android.view.View.updateDisplayListIfDirty(View.java:18095)

25 android.view.View.draw(View.java:18873)

26 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

27 com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:838)

28 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

29 android.view.View.updateDisplayListIfDirty(View.java:18086)

30 android.view.View.draw(View.java:18873)

31 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

32 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

33 android.view.View.draw(View.java:19148)

34 android.view.View.updateDisplayListIfDirty(View.java:18095)

35 android.view.View.draw(View.java:18873)

36 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

37 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

38 android.view.View.updateDisplayListIfDirty(View.java:18086)

39 android.view.View.draw(View.java:18873)

40 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

41 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

42 android.view.View.draw(View.java:19148)

43 android.view.View.updateDisplayListIfDirty(View.java:18095)

44 android.view.View.draw(View.java:18873)

45 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

46 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

47 android.view.View.updateDisplayListIfDirty(View.java:18086)

48 android.view.View.draw(View.java:18873)

49 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

50 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

51 android.view.View.updateDisplayListIfDirty(View.java:18086)

52 android.view.View.draw(View.java:18873)

53 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

54 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

55 android.view.View.updateDisplayListIfDirty(View.java:18086)

56 android.view.View.draw(View.java:18873)

57 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

58 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

59 android.view.View.updateDisplayListIfDirty(View.java:18086)

60 android.view.View.draw(View.java:18873)

61 android.view.ViewGroup.drawChild(ViewGroup.java:4216)

62 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)

63 android.view.View.draw(View.java:19148)

64 com.android.internal.policy.DecorView.draw(DecorView.java:788)

65 android.view.View.updateDisplayListIfDirty(View.java:18095)

66 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:652)

67 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:658)

68 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:766)

69 android.view.ViewRootImpl.draw(ViewRootImpl.java:3045)

70 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2840)

71 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2393)

72 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1426)

73 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6873)

74 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)

75 android.view.Choreographer.doCallbacks(Choreographer.java:841)

76 android.view.Choreographer.doFrame(Choreographer.java:772)

77 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)

78 android.os.Handler.handleCallback(Handler.java:793)

79 android.os.Handler.dispatchMessage(Handler.java:98)

80 android.os.Looper.loop(Looper.java:176)

81 android.app.ActivityThread.main(ActivityThread.java:6701)

82 java.lang.reflect.Method.invoke(Native Method)

83 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)

84 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)








------------------ 原始邮件 ------------------
发件人: "Jack"<notifications@github.com>; 
发送时间: 2019年8月7日(星期三) 下午4:18
收件人: "scwang90/SmartRefreshLayout"<SmartRefreshLayout@noreply.github.com>; 
抄送: "天外飞仙$#@1"<516885817@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [scwang90/SmartRefreshLayout] 长时间翻页使用会crash,崩溃日志如下 (#811)



 
可以问下，这个是怎么解决的么，我这也遇到这个问题，关键我这没有那个地方有recycle bitmap啊。是列表项的问题么，求大佬指教啊
  
列表用glide加载图片时有闪烁问题，为了解决闪烁问题，使用了下面的代码设置占位图
 .placeholder(imageView.getDrawable())
 虽然解决了闪烁，但出现标题描述的问题，把占位图设置成一张固定图片就解决了。

**Comment by wlmxj** [comment]
> getDrawable

你好，你怎么确定的和getDrawable有关系的？我现在也遇到这个问题了，而且排查不到，也是为了解决闪烁增加的getDrawable

**Comment by JackFung2015** [comment]
> > getDrawable
> 
> 你好，你怎么确定的和getDrawable有关系的？我现在也遇到这个问题了，而且排查不到，也是为了解决闪烁增加的getDrawable

把你怀疑出问题的代码先注掉，自己测试是否还会出现问题，没有的话就证明问题在被注释部分，再定位找原因。我当时就是这样做的。
