### ISSUE TITLE
上拉加载问题（禁用刷新，启用加载更多，加载更多布局可能无法自动收回）

### ISSUE THREAD

**Issue by chengqian0109** [scwang90/SmartRefreshLayout#813]
在【禁用下拉刷新】而【启用上拉加载】功能时，慢慢将【上拉加载布局】拖拽出来，在【上拉加载布局】未完全被拖拽出来时，【上拉加载布局】会停在页面上而无法自动收回。

**Comment by scwang90** [comment]
这个问题，没能重现，你可以进群讨论群，在群里发一个 出现问题的视频，然后贴上相应的代码。

**Comment by yzbzz** [comment]
我也发现了这个问题，必现的，把SmartRefreshLayout放在DialogFragment中，设定死高度，必现。DialogFragment加了一个从底部出来的动画

**Comment by RoadsInFarAway** [comment]
我也有这个问题，禁止刷新，上拉加载更多就会出现这个问题
