### ISSUE TITLE
 AndroidRuntime: at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:655)

### ISSUE THREAD

**Issue by scsfwgy** [scwang90/SmartRefreshLayout#815]
@scwang90 你好，从系统默认刷新组件迁移过来的，线上出现了几个用户报这个错误，暂时还没有排查出来具体原因。能看一下吗？

compileSdkVersion 27
minSdkVersion 16
targetSdkVersion 25

`1902-14 18:07:09.337 2664 2664 E AndroidRuntime: at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:655)`

`

02-14 18:07:09.337 2664 2664 E AndroidRuntime: FATAL EXCEPTION: main
--
102-14 18:07:09.337 2664 2664 E AndroidRuntime: Process: com.tophold.xcfd, PID: 2664
202-14 18:07:09.337 2664 2664 E AndroidRuntime: java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
302-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6687)
402-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
502-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
602-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
702-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
802-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
902-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
1002-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
1102-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
1202-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
1302-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
1402-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
1502-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
1602-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
1702-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
1802-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
1902-14 18:07:09.337 2664 2664 E AndroidRuntime: at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:655)
2002-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
2102-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
2202-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
2302-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
2402-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
2502-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
2602-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

`

_Originally posted by @scsfwgy in https://github.com/scwang90/SmartRefreshLayout/issues/533#issuecomment-463907041_

**Comment by scwang90** [comment]
https://www.baidu.com/s?tn=98010089_dg&ch=16&ie=UTF-8&wd=ViewHolder%20views%20must%20not%20be%20attached%20when%20created.

**Comment by zcwfeng** [comment]
我最近也反复出现，这个难道不是bug
