### ISSUE TITLE
SmartRefreshLayout 中嵌套ScrollView setNoMoreData后footer无法自动收起

### ISSUE THREAD

**Issue by Bruce-jun** [scwang90/SmartRefreshLayout#816]
SmartRefreshLayout 中嵌套ScrollView setNoMoreData后footer无法自动收起

**Comment by Bruce-jun** [comment]
找到原因了：设置了 app:srlEnableRefresh="false"

 case PullDownCanceled:
                    if (!mState.opening && isEnableRefresh()) {
                        notifyStateChanged(RefreshState.PullDownCanceled);
                        resetStatus();
                    } else {
                        setViceState(RefreshState.PullDownCanceled);
                    }
                    break;

@Override
    public boolean isEnableRefresh() {
        return mEnableRefresh && !mEnablePureScrollMode;
    }
为false的话  就不会执行 resetStatus();

**Comment by scwang90** [comment]
setNoMoreData 确实不会收起，
finishLoadMore 才会收起
