### ISSUE TITLE
Android P 自定义header 增加箭头不显示

### ISSUE THREAD

**Issue by weikjblue** [scwang90/SmartRefreshLayout#817]
Android P 自定义header 增加箭头不显示,箭头样式与自带header 箭头类似 ,p以下版本无此问题  

`
  private void initView(Context context) {
        setGravity(Gravity.CENTER);
        mHeaderText = new TextView(context);
        mProgressDrawable = new ProgressDrawable();
        mArrowView = new PathsView(context);
        mProgressView = new ImageView(context);
        mProgressView.setImageDrawable(mProgressDrawable);
        mArrowView.parserColors(ContextCompat.getColor(context, R.color.gray_4e4d4e));
        mArrowView.parserPaths("M11.89,6.58a0.74,0.74 0,0 1,-1.06 0L7,2.73a0.11,0.11 0,0 0,-0.18 0.08V20.94a0.75,0.75 0,0 1,-1.5 0V2.8a0.1,0.1 0,0 0,-0.17 -0.07L1.28,6.58a0.74,0.74 0,0 1,-1.06 0,0.75 0.75,0 0,1 0,-1.06L5.52,0.22a0.75,0.75 0,0 1,1.06 0l5.31,5.3A0.75,0.75 0,0 1,11.89 6.58Z");
        addView(mProgressView, DensityUtil.dp2px(20), DensityUtil.dp2px(20));
        addView(mArrowView, DensityUtil.dp2px(12), DensityUtil.dp2px(22));
        addView(new View(context), DensityUtil.dp2px(20), DensityUtil.dp2px(20));
        addView(mHeaderText, LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
        setMinimumHeight(DensityUtil.dp2px(60));
    }
`

**Comment by scwang90** [comment]
使用的哪个版本？

**Comment by weikjblue** [comment]
> 使用的哪个版本？

1.0.4

**Comment by scwang90** [comment]
你需要使用新版本

**Comment by weikjblue** [comment]
> 你需要使用新版本

1.1.0-alpha-20 已经可以正常使用
