### ISSUE TITLE
嵌套webview时 , webview中的弹窗或者底部升窗的列表,滑动冲突

### ISSUE THREAD

**Issue by hply** [scwang90/SmartRefreshLayout#818]
嵌套webview时 , webview中的弹窗或者底部升窗的列表,滑动冲突

**Comment by Danniel-yan** [comment]
这个问题解决了没，我也遇到了 真实坑

**Comment by walker8** [comment]
我也遇到这个坑了，有些网页会有滑动冲突

**Comment by hply** [comment]
> 我也遇到这个坑了，有些网页会有滑动冲突
只要H5的底下的页面是在屏幕顶部scrolTop=0 , 然后弹窗一个长列表 , 这个列表下拉就会触发SmartRefreshLayout的下拉

**Comment by sxy6** [comment]
只能上滑不能下滑,,,,,,下滑就下拉刷新

**Comment by scwang90** [comment]
https://github.com/scwang90/SmartRefreshLayout/issues/916
