### ISSUE TITLE
vlayout中吸顶布局在加载更多过程中的时候会滑出屏幕,加载更多完成的时候又重新恢复吸顶状态

### ISSUE THREAD

**Issue by lqq1312** [scwang90/SmartRefreshLayout#820]
vlayout中的StickyLayoutHelper实现吸顶,在加载更多过程中吸顶布局会滑出屏幕,加载更多完成的时候又重新恢复吸顶状态.

**Comment by yorling** [comment]
我也遇到了，我用的是CoordinatorLayout+AppBarLayout+CollapsingToolbarLayout做的吸顶布局，最外层是SmartRefreshLayout，出现的异常情况跟你一样。在加载更多时，吸顶的控件会滑出屏幕，加载完再恢复正常。我感觉是加载更多时，禁止了界面的绘制，但是翻遍了api好像也没找到可以更改的设置。或者我没找到，请知道的人指导一下~

**Comment by yorling** [comment]
已完美解决，感谢QQ讨论群的[独钓寒江雪]提供的解决方案：在吸顶布局外层，做刷新功能。在吸顶布局的下半部分布局里，做加载更多的功能。不要把刷新+加载更多一起做在吸顶布局外层，就不会有问题了。

想看界面效果的，应用宝搜索下载【19八3TOYS】商城页面

**Comment by scwang90** [comment]
这个问题不能使用 Smart 来实现 加载更多

**Comment by hloong** [comment]
在吸顶布局的外出做刷新不满足需求吧，最好是有布局代码，看了2个关闭的都没有代码示例

**Comment by Edgar-Dong** [comment]
> 已完美解决，感谢QQ讨论群的[独钓寒江雪]提供的解决方案：在吸顶布局外层，做刷新功能。在吸顶布局的下半部分布局里，做加载更多的功能。不要把刷新+加载更多一起做在吸顶布局外层，就不会有问题了。

遇到同样的问题，有代码可以参考一下吗？

**Comment by yorling** [comment]
> > 已完美解决，感谢QQ讨论群的[独钓寒江雪]提供的解决方案：在吸顶布局外层，做刷新功能。在吸顶布局的下半部分布局里，做加载更多的功能。不要把刷新+加载更多一起做在吸顶布局外层，就不会有问题了。
> 
> 遇到同样的问题，有代码可以参考一下吗？

布局：上部是吸顶+下部是fragment
然后在fragment里做“加载更多”的功能，这样就不会冲突了

**Comment by Erichkko** [comment]
> 已完美解决，感谢QQ讨论群的[独钓寒江雪]提供的解决方案：在吸顶布局外层，做刷新功能。在吸顶布局的下半部分布局里，做加载更多的功能。不要把刷新+加载更多一起做在吸顶布局外层，就不会有问题了。

同问

**Comment by SpriteLisen** [comment]
> 已完美解决，感谢QQ讨论群的[独钓寒江雪]提供的解决方案：在吸顶布局外层，做刷新功能。在吸顶布局的下半部分布局里，做加载更多的功能。不要把刷新+加载更多一起做在吸顶布局外层，就不会有问题了。

这个可以，就只能在最外层是一个 SmartRefreshLayout，禁用最外层这个 SmartRefreshLayout 的加载更多，然后在内层的 rv 外部再套一个 SmartRefreshLayout，内层的 SmartRefreshLayout 禁用下拉刷新，这样就可以套用了
