### ISSUE TITLE
竖直的recyclerview嵌套竖直的recyclerview 

### ISSUE THREAD

**Issue by cleVSokc** [scwang90/SmartRefreshLayout#821]
竖直的recyclerview嵌套竖直的recyclerview ，当滑动内部的recyclerview时  如果当前外部recyclerview是第一个条目（滑动了外部recyclerview第一个条目的内部recyclerview） 则只能向上滑动  向下滑动时与您的SmartRefreshLayout的下拉刷新冲突
如果滑动的时外部recyclerview的最后一个条目的内部recyclerview   则只能向下滑动切 不流畅  与您的SmartRefreshLayout 的上拉加载冲突了  

上述内容就只有在最后一个和第一个条目时遇到的bug  在中间的没有滑动时的冲突出现一切良好
 望给出意见期待解决

**Comment by scwang90** [comment]
1. 尝试打开 Smart 的嵌套滚动功能
2. 尝试自定义滚动边界，自己决定 canRefresh 的时机

**Comment by cleVSokc** [comment]
已经解决 。

**Comment by cleVSokc** [comment]
已经解决 。

**Comment by cleVSokc** [comment]
已经解决 。

**Comment by cleVSokc** [comment]
已经解决 。

**Comment by cleVSokc** [comment]
已经解决 。

**Comment by cleVSokc** [comment]
已经解决 。

**Comment by YiMenHuiShou** [comment]
> 解决



> 已经解决 。

你好，请问怎么解决的？
