### ISSUE TITLE
嵌套 linearLayout +  recyclerview  滑动冲突

### ISSUE THREAD

**Issue by small-tree** [scwang90/SmartRefreshLayout#823]
版本
com.scwang.smartrefresh:SmartRefreshLayout:1.0.4-7

SmartRefreshLayout
       ---LinearLayout
       ------        LinearLayout  首页 banner  广告模块  其他模块的入口
       ------        RecyclerView   底部有个列表

已经设置 
refreshLayout.setEnableNestedScroll(true);
rl_home_asserts.setNestedScrollingEnabled(false);

问题  refreshLayout 无法和 recyclerview 同步滑动，请帮忙解答

**Comment by cleVSokc** [comment]
设置recyclerview不可滑动就行了啊

**Comment by scwang90** [comment]
你这样的布局，确实无法同步滚动，这是正常的，关于给列表添加banner Smart demo 中时有例子的
