### ISSUE TITLE
使用MaterialHeader一点小瑕疵

### ISSUE THREAD

**Issue by longdw** [scwang90/SmartRefreshLayout#83]
你好，首先感谢您开源的项目。
使用MaterialHeader，目前有个小问题，如果“下拉刷新”还没有结束，用户可以继续“下拉刷新”，而且此时加载的loading动画已经出现重叠的情况了。
我在想，能否做到当“下拉刷新”还没有完成的时候禁止用户进一步操作“下拉刷新”的操作。（我不知道您是否已经提供了某个方法来做此操作）。

**Comment by longdw** [comment]
还有一个小问题，当自动加载更多还没有加载完成的时候，向上无法拉到顶部（也就是第一个item只能显示一小部分）。

**Comment by scwang90** [comment]
使用 最新版本 1.0.3-alpha-2 解决问题
