### ISSUE TITLE
1.0.5版本，用CoordinatorLayout嵌套SmartLayout下拉的问题

### ISSUE THREAD

**Issue by KaelInvoker** [scwang90/SmartRefreshLayout#833]
您好，布局如下
![image](https://user-images.githubusercontent.com/37531571/54184785-689e1900-44e2-11e9-85f3-3ee818b6e1fe.png)
在ViewPager里面放的是Fragment，Fragment布局如下
![image](https://user-images.githubusercontent.com/37531571/54184841-8d928c00-44e2-11e9-83f5-bd90ea2bad88.png)
就是一个Smart+RV
当手指下拉的时候，appbarLayout还没下拉完毕，下拉的刷新头就出来了，怎么做到等appBarLayout全部出来后，再进行下拉刷新呢?

**Comment by KaelInvoker** [comment]
另外上拉的时候，也发现一个bug，上拉刷新尾布局刚刚消失，突然之前的item好像出现了惯性自动猛地往上走了好多... 不知道我有没有描述清楚

**Comment by KaelInvoker** [comment]
这边还有另外一个问题，CoordinatorLayout 版本是26.0.1，缓慢下拉appbar，发现下滑困难出现抖动的bug

**Comment by KaelInvoker** [comment]
ViewPager有时候也会出现左右滑动困难的问题

**Comment by scwang90** [comment]
用新版本
