### ISSUE TITLE
com.scwang.smartrefresh.layout.SmartRefreshLayout.onMeasure(SmartRefreshLayout.java:588)

### ISSUE THREAD

**Issue by Abelzzg** [scwang90/SmartRefreshLayout#837]
目前这个crash还无法复现，但是线上已经爆出来不少，

![20190315161600](https://user-images.githubusercontent.com/9277534/54417636-bbbfd800-473d-11e9-8e76-af50d5c16f6c.jpg)

**Comment by scwang90** [comment]
与 smart 无关的错误，自行百度解决
