### ISSUE TITLE
1.1.0-alpha-21设置底部上拉加载字体颜色无效

### ISSUE THREAD

**Issue by limhGeek** [scwang90/SmartRefreshLayout#838]
<com.scwang.smartrefresh.layout.footer.ClassicsFooter
                android:layout_width="match_parent"
                app:srlAccentColor="@color/colorLine"
                app:srlPrimaryColor="@color/colorPage"
                android:layout_height="wrap_content"/>

我这么设置了底部文本颜色，但是看效果貌似srlAccentColor没起作用，请问该如何做？

**Comment by AndSync** [comment]
````
ClassicsFooter refreshFooter= (ClassicsFooter) mRefreshLayout.getRefreshFooter();
refreshFooter.setAccentColor(Color.parseColor("#ffffffff"));
````

**Comment by sunnyamuren** [comment]
mTitleText.setTextColor(0xff666666);
查了下源代码，在最后 又设置了下颜色。
应该在判断 if (ta.hasValue(R.styleable.ClassicsFooter_srlAccentColor)) {
            super.setAccentColor(ta.getColor(R.styleable.ClassicsFooter_srlAccentColor, 0));
        }
增加下 else 分支设置下mTitleText 颜色

**Comment by scwang90** [comment]
1.1.0-22 修复
