### ISSUE TITLE
希望大大能看一下这个问题   两个库冲突问题（只能弃用一个库让我很痛苦）

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#843]
https://github.com/KingJA/LoadSir/issues/117      有解决的办法就是再嵌套一层，这样的办法不是很好

**Comment by scwang90** [comment]
由于 SmartRefrehLayout 继承 ViewGroup ，所以没有 FrameLayout 和 RelativeLayout 的功能。
LoadSir 的功能实现又 依赖于 FrameLayout 和 RelativeLayout  的功能
所以两库结合方法只有你现在使用的嵌套 RelativeLayout 的方法。

不过 SmartRefreshLayout 中有 LoadSir 空布局的 demo，建议把 FrameLayout 套在 Smart 的外面，即空页面或者错误页面 没有下拉刷新功能，而是点击刷新功能， 只有列表出现了才有下拉刷新（下拉刷新的单身就是从列表开始的，空页面下拉刷新不符合下拉刷新的设计初衷）。

**Comment by xyZangGit** [comment]
空页面下拉刷新不符合下拉刷新的设计初衷    最开始我也是这样写的，但是我们设计的需求就是这样的，我也很无奈，胳膊拧不过大腿，谢谢您的回答
