### ISSUE TITLE
嵌套cardview问题

### ISSUE THREAD

**Issue by scarlee** [scwang90/SmartRefreshLayout#848]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.CardView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/size_12dp"
                android:layout_marginEnd="@dimen/size_12dp"
                app:cardCornerRadius="@dimen/size_4dp">

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recyclerView"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                     />
            </android.support.v7.widget.CardView>

        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

下拉刷新的MaterialHeader不显示，但是动作仍然执行

**Comment by scwang90** [comment]
手动修改 MaterialHeader 的 Z 轴 或 因应距离，使其位于 CardView 之上
