### ISSUE TITLE
用这个框架怎么样能实现吸顶

### ISSUE THREAD

**Issue by yedashen** [scwang90/SmartRefreshLayout#849]
我自己会吸顶，但是加上这样类似的 下拉出现头部刷新的功能的刷新框架就会出现 “吸顶布局”遮住下拉刷新的部分。。。

**Comment by danxinzhicheng** [comment]
同问，解决没

**Comment by yedashen** [comment]
解决了，你可以看我csdn地址:  https://blog.csdn.net/qq_34723470/article/details/88715381
