### ISSUE TITLE
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-21' 无法导入该库

### ISSUE THREAD

**Issue by qzw9231000** [scwang90/SmartRefreshLayout#851]
请问该库是托管在哪个仓库？我新建了一个项目，只有默认的maven仓库
`
allprojects {
    repositories {
        google()
        jcenter()
    }
}
`

使用compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-21'导入项目后直接报错，无法解析
`
app/build.gradle |  
-- | --
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-21. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-21. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-21. Show Details Affected Modules: app |  

`

**Comment by qzw9231000** [comment]
![image](https://user-images.githubusercontent.com/18062819/54741661-194e9b80-4bfa-11e9-9ca0-ae17597c2067.png)

**Comment by YLAndsoft** [comment]
同求，1.1.0无法解析仓库地址，1.0.5版本可以。

**Comment by LAXlerbo** [comment]
使用  **1.1.0-alpha-14** 版本

**Comment by qzw9231000** [comment]
谢谢
