### ISSUE TITLE
小米手机上UncaughtException detected: java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by wangshilsj** [scwang90/SmartRefreshLayout#852]

**Comment by wangshilsj** [comment]
小米9.0系统上全面屏手机UncaughtException detected: java.lang.IllegalArgumentException: width and height must be > 0

**Comment by WwhOS** [comment]
作者已处理，更换版本进行兼容处理：1.1.0-alpha-5，原地址https://github.com/scwang90/SmartRefreshLayout/issues/458
