### ISSUE TITLE
alpha-21  上拉加载更多有问题

### ISSUE THREAD

**Issue by scarlee** [scwang90/SmartRefreshLayout#853]
操作如下：
一、
  1 、首次打开页面，不要操作
  2、再刷新一次，由于数据不足十条调用了finishLoadMoreWithNoMoreData（）
  3、上拉飞滑（一定要飞滑）
  结果加载更多接口仍然走了回调！！
二、
  首次打开页面无数据，调用finishLoadMoreWithNoMoreData，上拉时底部偶尔会执行加载中动画，但回调没有执行

初始化配置如下：
  setEnableAutoLoadMore(true);
  setEnableFooterFollowWhenNoMoreData(true);

alpha-19无上述问题！！

**Comment by scwang90** [comment]
刷新的时候 用 setNoMoreData(true)

**Comment by scarlee** [comment]
调用了啊
