### ISSUE TITLE
看readme上说1.0.5版本有重大bug，那现在要使用哪个版本？

### ISSUE THREAD

**Issue by KaelInvoker** [scwang90/SmartRefreshLayout#856]
如题，请问大佬1.0.5的重大bug是什么?需要升级到哪个版本呢？

**Comment by AndSync** [comment]
还有一个问题 感觉一直都是alpha 版本 没有稳定版吗？

**Comment by jjn2004** [comment]
这个问题没有人遇到吗

**Comment by scwang90** [comment]
1.1.0 预览版比 1.0.5 还要稳定，现在已经发不到 -29 了
1.0.5 的bug 本人没有遇到，是其他开发者报给我的，分析崩溃信息，是与Android P 的兼容问题导致
