### ISSUE TITLE
BUG   snaphelp上拉加载更多,下一页的数据显示到了上一页的页面,正好是foot的高度

### ISSUE THREAD

**Issue by leifu1107** [scwang90/SmartRefreshLayout#858]
我的item正好是一整页,上拉加载数据,下面居然foot的距离是下一页的内容,急急急

**Comment by scwang90** [comment]
refreshLayout.setEnableScrollContentWhenLoadFinish(false)
或者
app:srlEnableScrollContentWhenLoadFinish=false
