### ISSUE TITLE
WaveSwipeHeader之黑球BUG

### ISSUE THREAD

**Issue by op123355569** [scwang90/SmartRefreshLayout#860]
操作步骤如下：
1.进入列表界面，不执行刷新和加载
2.列表填充几十条数据
3.列表滑倒底部，执不执行上拉加载随意
4.不间断的滑动，快速滑倒顶部，但不执行下拉刷新操作
5.此时会有个小黑球卡在界面上

PS：只要执行过下拉刷新操作，手动自动随意，都不会再出现该BUG

**Comment by scwang90** [comment]
使用最新版本
