### ISSUE TITLE
基本使用中，花哨的东西太多

### ISSUE THREAD

**Issue by FunnyLee** [scwang90/SmartRefreshLayout#862]
在SmartRefreshLayout的基本使用中，花哨的效果太多了。基本使用能不能去掉花哨的效果，实现上拉加载和下拉刷新就够了，如果想增加效果，再去增加代码。现在的情况是：我只想使用加载和刷新功能，还得把一些花哨的功能手动设为false，感觉有点不友好。
正常的使用是：最基本的功能什么都不需要设置，如果想增加功能，再去找API手动设置。

以上纯属个人意见，不喜勿喷，哈哈

**Comment by xyZangGit** [comment]
开源不易，作者已经做了相应的 减少包的大小  的引入方法了
