### ISSUE TITLE
加载更多完成后，列表会自动往下滑动，如果禁用这个效果

### ISSUE THREAD

**Issue by FunnyLee** [scwang90/SmartRefreshLayout#863]

**Comment by SunnyLy** [comment]
我也遇到这个问题，看源码里面它是在onAnimationUpdate()回调里面调用了ScrollView.scrollBy()自动滚动

**Comment by FunnyLee** [comment]
那只能修改源码了，希望作者能暴露出这个设置开关，哈哈

**Comment by SunnyLy** [comment]
你自己继承它的写一个，复写那个方法，把ScrollView.scrollBy()那一句代码注释掉就可以了。

**Comment by iamlfc** [comment]
大佬们 你们说的是 RefreshContentWrapper 这个类里边的  scrollBy() 吗  ？ 为啥我注释掉了 还是会嗖嗖的滑动一段距离。

  @Override
    public void onAnimationUpdate(ValueAnimator animation) {
        int value = (int) animation.getAnimatedValue();
        try {
            if (mScrollableView instanceof AbsListView) {
                scrollListBy((AbsListView) mScrollableView, value - mLastSpinner);
            } else {
//           TOOD//:     控制滑动？
                mScrollableView.scrollBy(0, value - mLastSpinner);
            }
        } catch (Throwable ignored) {
            //根据用户反馈，此处可能会有BUG
        }
        mLastSpinner = value;
    }

**Comment by scwang90** [comment]
loadMore 时候调用
recyclerView.stopScroll()

**Comment by pxpxp** [comment]
loadMore 时候调用
recyclerView.stopScroll()
没效果，是我写错地方了？
