### ISSUE TITLE
这里强设颜色，导致属性xml中设置无效

### ISSUE THREAD

**Issue by OptimusPrimeRen** [scwang90/SmartRefreshLayout#864]
https://github.com/scwang90/SmartRefreshLayout/blob/b2cd9fa1ff76711b0b3554e66dd260bc212cf255/refresh-layout/src/main/java/com/scwang/smartrefresh/layout/footer/ClassicsFooter.java#L165

**Comment by scwang90** [comment]
非常感谢！
