### ISSUE TITLE
上滑悬停 如何固定悬停在顶部的TabLayout，在加载更多时候完全显示？以看问题#375

### ISSUE THREAD

**Issue by xyZangGit** [scwang90/SmartRefreshLayout#866]
以看问题https://github.com/scwang90/SmartRefreshLayout/issues/375
按照 上面链接的写法，我的布局这样向上滑动加载更多之后，页面直接不能滑动，加载完成 底部布局不消失
![image](https://user-images.githubusercontent.com/19574114/55532104-3ba6e580-56df-11e9-8e06-ca044b9a1440.png)

下面是我的页面布局：

<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    tools:context=".fragment.HomePageFragment">

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/home_page_fragment_smartRefreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:srlFooterTranslationViewId="@+id/home_page_fragment_recyclerView">

        <com.scwang.smartrefresh.layout.header.ClassicsHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/home_page_fragment_smart_head_drawable_size"
            app:srlAccentColor="@android:color/black"
            app:srlDrawableProgress="@drawable/ic_progress_puzzle" />

        <android.support.design.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/home_page_fragment_recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_behavior="@string/appbar_scrolling_view_behavior" />

            <android.support.design.widget.AppBarLayout
                android:id="@+id/home_page_fragment_AppBarLayout"
                android:layout_width="match_parent"
                android:layout_height="@dimen/home_page_fragment_appbar_height"
                android:theme="@style/AppTheme">

                <android.support.design.widget.CollapsingToolbarLayout
                    android:id="@+id/home_page_fragment_CollapsingToolbarLayout"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/home_page_fragment_banner_height"
                    android:fitsSystemWindows="true"
                    app:contentScrim="@color/blue"
                    app:layout_scrollFlags="scroll|exitUntilCollapsed|snap"
                    app:statusBarScrim="@android:color/transparent"
                    app:titleEnabled="false">

                    <com.youth.banner.Banner
                        android:id="@+id/home_page_fragment_banner"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/home_page_fragment_banner_height"
                        app:delay_time="5000"
                        app:image_scale_type="fit_xy"
                        app:indicator_drawable_selected="@color/white"
                        app:indicator_drawable_unselected="@color/tab_color_false90"
                        app:indicator_height="@dimen/home_page_fragment_banner_indicator_height"
                        app:indicator_margin="@dimen/home_page_fragment_banner_indicator_margin"
                        app:indicator_width="@dimen/home_page_fragment_banner_indicator_width"
                        app:layout_collapseMode="parallax"
                        app:layout_collapseParallaxMultiplier="1" />

                    <android.support.v7.widget.Toolbar
                        android:id="@+id/home_page_fragment_Toolbar"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/home_page_fragment_toolbar_height"
                        app:contentInsetStart="0dp"
                        app:layout_collapseMode="pin">

                        
                        
                    </android.support.v7.widget.Toolbar>

                </android.support.design.widget.CollapsingToolbarLayout>

                
                <include
                    layout="@layout/fragment_home_page_title"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/home_page_title_height"
                    android:layout_gravity="bottom"
                    app:layout_scrollFlags="scroll" />

            </android.support.design.widget.AppBarLayout>

        </android.support.design.widget.CoordinatorLayout>

        <com.scwang.smartrefresh.layout.footer.ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    <include
        android:id="@+id/include_ly"
        layout="@layout/layout_homepage_toolbar" />

</android.support.constraint.ConstraintLayout>

**Comment by scwang90** [comment]
demo 中有例子
