### ISSUE TITLE
数据不满一页的情况下无法自定触发加载更多的问题

### ISSUE THREAD

**Issue by yygood1000** [scwang90/SmartRefreshLayout#867]
Appication的初始化：
  
         SmartRefreshLayout.setDefaultRefreshFooterCreator(new DefaultRefreshFooterCreator() {
            @NonNull
            @Override
            public RefreshFooter createRefreshFooter(@NonNull Context context, @NonNull RefreshLayout layout) {
                return new ClassicsFooter(context)
                        .setSpinnerStyle(SpinnerStyle.Translate);
            }
        });

        SmartRefreshLayout.setDefaultRefreshHeaderCreator(new DefaultRefreshHeaderCreator() {
            @NonNull
            @Override
            public RefreshHeader createRefreshHeader(@NonNull Context context, @NonNull RefreshLayout layout) {
                return new MaterialHeader(context)
                        .setColorSchemeResources(R.color.colorAccent);
            }
        });

Activity中使用时的初始化：

        mSmartRefreshLayout.setEnableLoadMore(true);
        mSmartRefreshLayout.setEnableAutoLoadMore(true);
        mSmartRefreshLayout.setEnableLoadMoreWhenContentNotFull(true);
        mSmartRefreshLayout.setOnRefreshLoadMoreListener(new OnRefreshLoadMoreListener() {
            @Override
            public void onRefresh(@NonNull RefreshLayout refreshLayout) {
                mPresenter.mPage = 0;
                mPresenter.getListData();
            }

            @Override
            public void onLoadMore(@NonNull RefreshLayout refreshLayout) {
                mPresenter.mPage += 1;
                mPresenter.getListData();
            }
        });

XML的使用代码：

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/smart_refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingEnd="@dimen/dp_12"
            android:paddingStart="@dimen/dp_12"
            tools:listitem="@layout/item_none_picture" />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

这些是初始化的代码。已经设置setEnableLoadMoreWhenContentNotFull，但是不起作用。无法自动触发onLoadMore回调，页面效果也没有“加载更多...”的footer 弹出。

**Comment by protectedMan** [comment]
同问

**Comment by scwang90** [comment]
smart 的自动加载更多要滚动的惯性才会触发
