### ISSUE TITLE
第一页刷新问题

### ISSUE THREAD

**Issue by kevengreat10** [scwang90/SmartRefreshLayout#868]
列表有下拉刷新和上拉加载更多功能，当第一页并且是最后一页时,获取完数据调用代码
refreshLayout.finishRefresh();
refreshLayout.finishLoadMoreWithNoMoreData();
偶尔会导致上拉加载更多功能还能使用

**Comment by guoyongsheng** [comment]
这个问题解决了吗

**Comment by kevengreat10** [comment]
看了下源码，应该是refreshLayout.finishLoadMoreWithNoMoreData();比refreshLayout.finishRefresh();先执行完毕(里面都用Handler.postDelayed)，导致resetNoMoreData()调用复位了上拉加载更多功能。
我现在的改法是
refreshLayout.finishRefresh(0);
refreshLayout.finishLoadMore(0, true, true);
应该只要finishRefresh的时间<=finishLoadMore的时间都没问题的。
希望这边能类似出一个refreshLayout.finishRefreshWithNoMoreData()方法。

**Comment by android-1995** [comment]
+1....

**Comment by HaowenLee** [comment]
+1....
1. 设置setNoMoreData(true)【此时没有更多好使】
2. 下拉刷新完成后
3. 再次设置setNoMoreData(true)【此时没有更多不好使，会出加载】

**Comment by scwang90** [comment]
1.1.0 - 23 添加 finishRefreshWithNoMoreData
