### ISSUE TITLE
把refresh-layout作为一个library导入工程

### ISSUE THREAD

**Issue by zy4569575** [scwang90/SmartRefreshLayout#87]
/.../refresh-layout/src/main/java/android/support/v4/view/PagerAdapterWrapper.java
Error:(20, 18) 错误: mAdapter可以在ViewPager中访问private

build可以成功运行的时候报这个错

**Comment by scwang90** [comment]
你使用兼容包 是那个版本的？ compile 'com.android.support:appcompat-v7:25.3.1'

**Comment by zy4569575** [comment]
解决了，有没有listview滑动监听失效的解决方案？

**Comment by zy4569575** [comment]
根据滑动的距离处理title的透明度

**Comment by scwang90** [comment]
使用 最新版本 1.0.3-alpha-2 解决问题
