### ISSUE TITLE
在一个类里面继承RelativeLayout之后，用代码添加smartRefreshLayout后无法下拉刷新

### ISSUE THREAD

**Issue by oyo775881** [scwang90/SmartRefreshLayout#875]
代码如下，是我少设置了什么吗？

public class PullRefreshView extends RelativeLayout {
    
    private Context context = getContext();
    private SmartRefreshLayout smartRefreshLayout = new SmartRefreshLayout(context);
    private RecyclerView recyclerView = new RecyclerView(context);

    public PullRefreshView(Context context) {
        super(context);
        initialization();
    }

    public PullRefreshView(Context context, AttributeSet attrs) {
        super(context, attrs);
        initialization();
    }

    public PullRefreshView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        initialization();
    }

    private void initialization() {
        LayoutParams layoutParams = new LayoutParams(LayoutParams.MATCH_PARENT,                                  LayoutParams.MATCH_PARENT);
        smartRefreshLayout.setLayoutParams(layoutParams);
        recyclerView.setLayoutManager(new LinearLayoutManager(context));
        recyclerView.setItemAnimator(new DefaultItemAnimator());
        recyclerView.setLayoutParams(layoutParams);
        recyclerView.setBackgroundColor(Color.RED);
       smartRefreshLayout.addView(recyclerView);
       addView(smartRefreshLayout);
    }
}

**Comment by scwang90** [comment]
建议直接继承 SmartRefreshLayout 而不是包裹
