### ISSUE TITLE
提交2个小问题，使用Footer时 结合AppBar使用 和 tab 切换 

### ISSUE THREAD

**Issue by aiLvXuan** [scwang90/SmartRefreshLayout#879]
<img src="https://user-images.githubusercontent.com/22241686/56270583-0b246a00-6129-11e9-8487-abfc0151f21d.jpg" alt="Sample"  width="200" height="400"><img src="https://user-images.githubusercontent.com/22241686/56270593-11b2e180-6129-11e9-89b8-b28dfa46091e.jpg" alt="Sample"  width="200" height="400"><img src="https://user-images.githubusercontent.com/22241686/56270600-15466880-6129-11e9-8430-13e615acc94b.jpg" alt="Sample"  width="200" height="400">

-----------------
布局：
```
SmartRefreshLayout
    --CoordinatorLayout
       --AppBarLayout
          --CollapsingToolbarLayout
              --Toolbar
```
图1 是正常图。

图2 是有很多条数据 滑动到最底部没有数据，这时候 Footer 显示出来，把这个页面往上移了，把toolbar顶上去了。

图3 是点上最上面的 tab 切换到其的，在切换回来，下面还有已经加载完的更多数据。  复用同一个RecyclerView，数据只有一两条，滑到底，出现了 图2 的问题，然后，因为数据不多，所以最顶部的 tab 还处于可见状态，点击tab之后，切换到另一个数据很多的tab，这个时候页面可以往下滑动了，但是依旧显示 没有更多数据，toolbar依旧被顶上去，只有滑动到底部或者下拉才会显示正常

**Comment by scwang90** [comment]
参考demo->用例->嵌套滚动->整体滚动
