### ISSUE TITLE
无法刷新或加载更多

### ISSUE THREAD

**Issue by DCRain** [scwang90/SmartRefreshLayout#88]
SmartRefreshLayout中包含ListView,当ListView内容为空的时候，不能刷新也不能加载更多。
mListView.setNestedScrollingEnabled(false)也不能解决问题。代码如下： 
```xml
    <com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/mRefreshView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlDisableContentWhenRefresh="true"
        app:srlEnableAutoLoadmore="false"
        app:srlEnableHeaderTranslationContent="false"
        app:srlEnableLoadmore="true">

        <ListView
            android:id="@+id/mListView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

**Comment by scwang90** [comment]
你所描述的问题无法重现

**Comment by zhuozhao** [comment]
确实存在这个问题，当分页显示，有些手机屏幕长，第一页数据没显示全屏，导致加载更多不触发
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="40dp">

        <TextView
            android:id="@+id/startTv"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="@drawable/com_item_selector"
            android:clickable="true"
            android:drawableRight="@drawable/arrow_down_gray"
            android:gravity="center" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:background="@color/white"
            android:gravity="center"
            android:text="@string/zhi" />

        <TextView
            android:id="@+id/endTv"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="@drawable/com_item_selector"
            android:clickable="true"
            android:drawableRight="@drawable/arrow_down_gray"
            android:gravity="center" />

        <View
            android:layout_width="1px"
            android:layout_height="match_parent"
            android:layout_marginBottom="5dp"
            android:layout_marginTop="5dp"
            android:background="@color/gray" />

        <TextView
            android:id="@+id/companyTv"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="@drawable/com_item_selector"
            android:clickable="true"
            android:drawableRight="@drawable/arrow_down_gray"
            android:gravity="center" />

    </LinearLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1px"
        android:background="@color/gray" />

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        >

        <ListView
            android:id="@+id/listView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:nestedScrollingEnabled="false"/>

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

</LinearLayout>`
![image](https://user-images.githubusercontent.com/20083232/29595400-c810316e-87e9-11e7-915f-8fe7810df8e6.png)

**Comment by scwang90** [comment]
@zhuozhao 看 常见问题 #71

**Comment by shijunxing0130** [comment]
解决了吗，我也遇到这问题

**Comment by zhuozhao** [comment]
![image](https://user-images.githubusercontent.com/20083232/29648019-c2901c74-88be-11e7-894e-50f1108f9d41.png)
https://github.com/scwang90/SmartRefreshLayout/blob/master/art/md_property.md
我在属性方法里找到了改配置，希望作者把改配置默认开启，thanks~

**Comment by shijunxing0130** [comment]
能下拉刷新吗

**Comment by quanqiuheike** [comment]
下拉刷新有时候调用了，有时候不调用

**Comment by scwang90** [comment]
@quanqiuheike 使用 1.0.4-alpha-0 版本

**Comment by quanqiuheike** [comment]
#下拉刷新有时候调用了，有时候不调用，有刷新的效果 
之前使用的1.03-alpha-6的版本，平时测试的时候没有注意这个问题呢，抓包没有看到调用，重新debug就正常了，然后数据源为空的时候就没有调用，debug的时候都没有走到，结果今天发现了，然后跟现在的正式版本比对一下，后面改为稳定版本就可以了，感谢大神。
