### ISSUE TITLE
回掉函数如何终止刷新或加载动画

### ISSUE THREAD

**Issue by Easoncheng0405** [scwang90/SmartRefreshLayout#881]
我有如下请求刷新代码
`refreshLayout.setOnRefreshListener(refreshLayout -> listService.refresh());`
在监测到refreshLayout刷新时，listService开启一个线程发起网络请求，请求完成后回掉
`public void onRefresh(List<ListItemModel> list)`函数，
在回掉函数中无法使用`refreshLayout.finishRefresh`来终止刷新，我发现如下原因：

1. `refreshLayout.setOnRefreshListener(refreshLayout -> listService.refresh());`中两个refreshLayout(前者记为A，后者为B)对象不是同一个对象。
2. 即使使用一个成员变量保存refreshLayout B ，该对象也会在setOnRefreshListener回掉结束后变为null，即使每次刷新 refreshLayout B 都是同一个对象

**Comment by scwang90** [comment]
问题无法重现
