### ISSUE TITLE
这个问题根本没有解决，希望作者重视一下

### ISSUE THREAD

**Issue by scarlee** [scwang90/SmartRefreshLayout#882]
#853 
调用setNoMoreData和调用finishLoadMoreWithNoMoreData结果都是一样的，刷新再快速飞滑，几乎必现，alpha-22同样！
我本来想给你录屏的，但是这里发不出来动态图！

我回退到alpha-19了，以后不更新了！

**Comment by scwang90** [comment]
1.1.0-23 添加 finishRefreshWithNoMoreData

**Comment by pengbs** [comment]
alpha-14也是，设置了setNoMoreData为true还是会触发加载更多
