### ISSUE TITLE
双刘海屏问题

### ISSUE THREAD

**Issue by CodingCodersCode** [scwang90/SmartRefreshLayout#884]
既是一个bug，也是一个建议

问题发现所处环境：Android P、AndroidStudio模拟器、开发者选项—模拟具有凹口的显示屏—双显示屏凹口、列表展示形式

问题现象：1.列表底部最后一条会被遮挡；2.加载更多动画部分被遮挡

以上为问题复现环境和现象，至于真机和其余版本Android系统未做测试，但猜测同样存在此问题

建议：**建议考虑下双刘海屏幕(双显示屏凹口)情况下的适配**

**Comment by scwang90** [comment]
最新demo已经适配
