### ISSUE TITLE
调用autoRefresh方法,刷新顶部高度异常

### ISSUE THREAD

**Issue by weiwenhuaming01** [scwang90/SmartRefreshLayout#887]
![08BE6F4A-1065-4484-9B32-92CF5CAAF5EF](https://user-images.githubusercontent.com/24544494/56857591-19347f00-69a2-11e9-9aa7-99cabe58277d.png)
如图,默认刷新高度应该是图上的一半,现在刷新高度变成两倍而且文字在顶部

**Comment by weiwenhuaming01** [comment]
@scwang90

**Comment by weiwenhuaming01** [comment]
现在发现不调用,直接下拉也会变这样

**Comment by scwang90** [comment]
提供的信息太少，无法重现
