### ISSUE TITLE
布局中自设置了自定义的头，想要获取当前刷新状态，显示在其他textview上

### ISSUE THREAD

**Issue by Zhangxd77** [scwang90/SmartRefreshLayout#889]
比如下拉刷新，释放刷新，刷新中这样的三个，然后如果在布局中写了ClassicsHeader，我的自定义的头就没了。活着可以怎么监听，可以获取当前状态吗，？？
谢谢谢谢谢谢

**Comment by scwang90** [comment]
可以的，看自定义 Header 的文档
