### ISSUE TITLE
网络请求很快的时候Bug

### ISSUE THREAD

**Issue by quq603654536** [scwang90/SmartRefreshLayout#894]
在调用autoRefreshOnlyAnimation时候然后进行网络请求,网络请求很快返回成功后调用finishRefresh()会出现刷新动画无法消失。

一般出现在动画刚好再下探的时候调用finishRefresh()

**Comment by jmhjmh** [comment]
20可以！24不行

**Comment by scwang90** [comment]
1.1.0-25 已经发布
