### ISSUE TITLE
1.1.0-alpha-16以后界面不能预览了?????

### ISSUE THREAD

**Issue by hcd2016** [scwang90/SmartRefreshLayout#896]
新建的demo项目,加了app:srlEnablePreviewInEditMode="true"属性,16版本可以预览布局.16以后都不能了,之前用的14,现在最新是24,不仅仅下拉布局预览不了,就连整个页面的布局也盖了,显示自定义view那个灰灰的,应该懂吧.

**Comment by 18297793087** [comment]
试了下，可以呀。

**Comment by 18297793087** [comment]
s

**Comment by 18297793087** [comment]
![1557460052(1)](https://user-images.githubusercontent.com/29698106/57501415-f9924480-7319-11e9-89ba-2627f72c9d97.jpg)
![Uploading 1557460069(1).jpg…]()
试了下，可以呀。
