### ISSUE TITLE
现在的编译器都要求最低版本为14的

### ISSUE THREAD

**Issue by lianchengtong** [scwang90/SmartRefreshLayout#897]
Gradle.properties 添加
android.useAndroidX=true
android.enableJetifier=true
错误: 程序包android.support.annotation不存在
整个项目变成androidx系统包之后，类都找不到啦

**Comment by lianchengtong** [comment]
整个项目变成androidx系统包之后，类都找不到啦

**Comment by 18297793087** [comment]
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-andx-8'
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-andx-8'
