### ISSUE TITLE
请问autoRefresh()方法，设置刷新时间设置了没有用，可以帮看看吗？

### ISSUE THREAD

**Issue by Zhangxd77** [scwang90/SmartRefreshLayout#900]
refreshLayout.autoRefresh(0,10000,0.6f,false);
我想问，是和我刷新高度没写成>=1有关系吗？我想刷新就显示正常高度的一点，然后刷新但是，时间已经给很大了，但是没有用，

**Comment by scwang90** [comment]
autoRefresh 并不是没错调用都会成功，只有 Smart 闲置状态时候才行，比如 状态为 Refreshing 或者 回弹 还有其他状态 时调用就是没有任何效果的
