### ISSUE TITLE
BottomSheet 与OverScrollDrag不兼容

### ISSUE THREAD

**Issue by scarlee** [scwang90/SmartRefreshLayout#905]
在CoordinatorLayout 里使用BottomSheetBehavior想上拉时越界拖动，发现与OverScrollDrag这个属性无法兼容，但如果我想实现上拉时越界拖动效果，请问作者有什么好的建议吗？

**Comment by scwang90** [comment]
是 smart 的 bug 下一 28 版本  即将修复

**Comment by scarlee** [comment]
好的
