### ISSUE TITLE
特定版本配合CoordinatorLayout无法组合滑动

### ISSUE THREAD

**Issue by zhangzhichaolove** [scwang90/SmartRefreshLayout#907]
问题版本：SmartRefreshLayout:1.1.0-alpha-25
退回到SmartRefreshLayout:1.1.0-alpha-23正常工作。

**Comment by KrishuCN** [comment]
我的CoordinatorLayout回到SmartRefreshLayout:1.1.0-alpha-23 也无法和RecyclerView正常工作

**Comment by CSnowStack** [comment]
问题版本  1.1.0-andx-8

**Comment by CSnowStack** [comment]
问题版本 1.1.0-andx-8

**Comment by scwang90** [comment]
1.1.0-alpha-26
1.1.0-andx-9
发布修复
