### ISSUE TITLE
内嵌webView时，上拉加载数据不出来

### ISSUE THREAD

**Issue by wlwlxgg** [scwang90/SmartRefreshLayout#91]
1、内嵌webView下拉刷新没有问题，上拉加载时webview不能滚动了
2、下拉刷新时和webview内部的touch事件冲突

**Comment by scwang90** [comment]
请问你使用的版本是？ demo apk 也有内嵌 webview，但是demo并没有是说的问题，是否你使用的姿势不对？

**Comment by wlwlxgg** [comment]
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.3-alpha-2'
`<com.scwang.smartrefresh.layout.SmartRefreshLayout
	android:id="@+id/jssdk_bgarl"
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent">
	<com.ai.kara.jssdk.jsbridge.KaraWebView
		android:id="@+id/jssdk_wv"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:overScrollMode="never"/>
</com.scwang.smartrefresh.layout.SmartRefreshLayout>`
`private void initRefreshLayout() {
		refreshLayout = (SmartRefreshLayout) contentView.findViewById(R.id.jssdk_bgarl);
		refreshLayout.setRefreshHeader(new ClassicsHeader(getActivity()));
		refreshLayout.setRefreshFooter(new ClassicsFooter(getActivity()));
		refreshLayout.setOnRefreshListener(this);
		refreshLayout.setOnLoadmoreListener(this);
	}`

**Comment by wlwlxgg** [comment]
private void initRefreshLayout() {
		refreshLayout = (SmartRefreshLayout) contentView.findViewById(R.id.jssdk_bgarl);
		refreshLayout.setRefreshHeader(new ClassicsHeader(getActivity()));
		refreshLayout.setRefreshFooter(new ClassicsFooter(getActivity()));
		refreshLayout.setEnableRefresh(false);
		refreshLayout.setEnableLoadmore(false);
		refreshLayout.setOnRefreshListener(this);
		refreshLayout.setOnLoadmoreListener(this);
	}

	@Override
	public void onLoadmore(RefreshLayout refreshlayout) {
		LogUtils.i(TAG, "--开始加载更多--");
		if (supportFooter) {
			if (onLoadMoreListener != null && isTriggerLoadMore)
				onLoadMoreListener.onLoadMore();
		}
	}

	@Override
	public void onRefresh(RefreshLayout refreshlayout) {
		if (supportHeader && onRefreshingListener != null && isTriggerRefresh)
			onRefreshingListener.onRefreshing();
	}

**Comment by scwang90** [comment]
你的使用代码，确实没问题，不过你描述的问题我这边无法重现，也无法修复

**Comment by wlwlxgg** [comment]
Demo里的webView是禁用了上拉加载的~

**Comment by scwang90** [comment]
问题将会在下一个版本修复

**Comment by scwang90** [comment]
新版本已经发布，问题已经修复

**Comment by wlwlxgg** [comment]
问题复现，Gif动图，请用Chrome浏览器打开预览。

**Comment by scwang90** [comment]
你的动图看不到，发到群里吧
