### ISSUE TITLE
当列表在滑动的时候clear掉数据，会触发到达底部的回调

### ISSUE THREAD

**Issue by yushilong** [scwang90/SmartRefreshLayout#910]
当列表在滑动的时候clear掉数据，会触发到达底部的回调，然后就会触发加载更多的逻辑，这样列表又会出现数据了，其实clear掉了 应该就没有数据了，但是我又想使用加载更多的逻辑

其实业务场景是这样的：
比如顶部有4个tab公用下面一个recyclerview，当点击tab切换当时候需要先clear掉recyclerview里面的数据，然后再请求一下接口。就是每次切换的时候都会先触发加载更多的逻辑

**Comment by scwang90** [comment]
建议在 clear 的同时先设置 noMoreData=true，新的数据加载回来后 在设置 noMoreData=false
