### ISSUE TITLE
冲突,无论上下拉都无法使用

### ISSUE THREAD

**Issue by LLXBH** [scwang90/SmartRefreshLayout#913]
我想要实现个人信息界面能查看收藏, 每次滑动切换到这个界面就请求获取收藏数据,(ViewPager) , 但切换的次数多点后, 会发现, 我调用autoRefresh(), 但不会调用我写在里面的方法, 而且无论是上下拉他们的动画都不会再出现了
![image](https://user-images.githubusercontent.com/34165598/58082520-c25d4680-7be9-11e9-99f1-774bde9e4c7d.png)

下面是我的布局
![image](https://user-images.githubusercontent.com/34165598/58081486-bf615680-7be7-11e9-8306-92d99dedba1b.png)
![image](https://user-images.githubusercontent.com/34165598/58081521-cd16dc00-7be7-11e9-8efc-d6cb58fab0e3.png)

**Comment by scwang90** [comment]
autoRefresh 建议在页面初始化的时候值调用异常，后面不要再调用
