### ISSUE TITLE
自定义Footer的问题，求指导～

### ISSUE THREAD

**Issue by payneHwang** [scwang90/SmartRefreshLayout#914]
1、自定义Footer如何设置没有更多数据时的文字，我现在是在设置setNoMoreData(true)之后，上拉文字还是“上拉加载更多”，只是回弹没有加载数据，我现在是在onStateChange()回调设置的：
![51558490167_ pic_hd](https://user-images.githubusercontent.com/16483463/58141958-de0f2e00-7c77-11e9-99cc-e53999a18082.jpg)

2、上拉加载之后回到顶部总是会有Footer高度距离的偏差，无法完全回到顶部，把footer高度设置为10或者更低，偏移量更小，请指导～
谢谢～

**Comment by scwang90** [comment]
问题1: 在自定义Footer中重写 setNoMoreData 方法
问题2: 调用 finishLoadMore
