### ISSUE TITLE
怎么注释了？

### ISSUE THREAD

**Issue by Sing1** [scwang90/SmartRefreshLayout#921]
![image](https://user-images.githubusercontent.com/15246585/58413363-26c94b80-80ab-11e9-8eae-2d2f0e2ff951.png)
 注释掉了之后全是空指针！！！

**Comment by scwang90** [comment]
新版本为了减少 dex 的方法数量，和代码量 采用了 xml 方式构建布局
如果你的 自定义Header 直接己尝这个类的话你需要加入这个代码 


        View.inflate(context, R.layout.srl_classics_header, this);
或者
        View.inflate(context, R.layout.srl_classics_footer, this);
