### ISSUE TITLE
finishRefreshWithNoMoreData

### ISSUE THREAD

**Issue by KobeBryant824** [scwang90/SmartRefreshLayout#925]
1.1.0-alpha-28，进入页面->刷新完，调用finishRefreshWithNoMoreData，上拉还能触发loadMore，但是如果先手动下拉一次，结果就是正常的了，期望：不再出发上拉加载

**Comment by yaolv7** [comment]
这个问题我也发现了, 我用的 1.1.0-andx-10 ,还没更新到11,目前 
 #finishLoadMoreWithNoMoreData()  必须在#finishRefresh() 之后调用,不然就会像你描述这种
还有 #setEnableLoadMore(false)  需要在#closeHeaderOrFooter() 前,不然会有滑动冲突, 
目前我只发现这两个先后调用顺序的问题

**Comment by scwang90** [comment]
finishRefreshWithNoMoreData 的使用请参考 demo
注意：finishRefresh 会恢复 NoMoreData 的状态
