### ISSUE TITLE
作者是否可以支持预加载功能？

### ISSUE THREAD

**Issue by ljackChen001** [scwang90/SmartRefreshLayout#93]
使用BaseRecyclerViewAdapterHelper 上拉预加载功能  NestedScrollView 嵌套RecyclerView 会无限触发上拉加载，BaseRecyclerViewAdapterHelper作者建议使用其他的上拉加载框架， 在滑到的过程中请求数据，而不是一次性全部加载完，上拉加载的时候隐藏Footer，当没有数据的时候才显示Footer？您看是否可以支持改预加载功能？

**Comment by scwang90** [comment]
暂时不支持
