### ISSUE TITLE
下拉刷新无法点击item

### ISSUE THREAD

**Issue by puppet16** [scwang90/SmartRefreshLayout#931]
下拉头部类型：**ClassicsHeader**
有个属性是**setEnableHeaderTranslationContent**默认为`true`，因此每次下拉都会让列表下移。  
复现操作：当下拉刷新时，在还未结束刷新之前向上滑动列表，之后列表item无法点击。
原因：追踪代码所知：经过以上操作后再点击item，此时的recyclerview处于`SCROLL_STATE_SETTLING`状态，所以点击被拦截了。

**Comment by scwang90** [comment]
在demo 中重复操作，没有出现不可点击的情况，

**Comment by scwang90** [comment]
建议更新到最新版本

**Comment by longshishui** [comment]
是的，我使用最新版也遇到了这个问题。不过触发条件较特殊，触发几率不大，不影响使用。
