### ISSUE TITLE
关于同时下拉和上拉的问题

### ISSUE THREAD

**Issue by nangonghuang** [scwang90/SmartRefreshLayout#932]
现在用的 1.1.0-andx-11 版本， 底部刷新没用结束的时候，下拉刷新显示需要等待底部刷新完成，这里的限制是出于什么考虑呢？

现在这边想要同时都可以，或者做成下拉刷新的时候直接停止掉底部的刷新，这个能做到吗（没有找到比如startPull之类的接口，不然想直接设置 `finishLoadMore(false)`）？自己改源码的话大概要改哪些内容呢？

**Comment by nangonghuang** [comment]
另外发现在`SmartRefreshLayout` 里面，`moveSpinnerInfinitely`方法还有东西没有删除掉 
```java
String egg = "你这么死拉，臣妾做不到啊！";
Toast.makeText(thisView.getContext(), egg, Toast.LENGTH_SHORT).show();
```

**Comment by scwang90** [comment]
Smart为了让刷新机制不混乱，使用了 state 状态， state 要么 等于 loading 要么 等于 refreshing，不能同时处于两个状态。
你后面提到的 startPull 可以在 Smart 的多功能监听器中找到类似的 方法
