### ISSUE TITLE
使用沉浸式状态栏后，刷新头部被遮挡了

### ISSUE THREAD

**Issue by wr1024** [scwang90/SmartRefreshLayout#934]
App设置沉浸式状态后，界面布局显示在状态栏下面，此时下拉刷新时，刷新头布局会被状态栏遮挡。
通过设置什么属性，可以解决刷新头布局被状态栏遮挡的问题。

**Comment by scwang90** [comment]
可以通过设置 Header 的 maginTop 来解决

**Comment by Ymars1990** [comment]
楼主解决了吗？我看了Demo，没发现这个高度要怎么计算的，作者用的toolbar 可以计算出，如果SML 上面没有任何控件怎么计算？SML 侵入状态栏以外了

**Comment by wr1024** [comment]
我是给父View 添加 paddingTop&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ymars1990"<notifications@github.com&gt;; 
发送时间: 2020年3月26日(星期四) 中午11:54
收件人: "scwang90/SmartRefreshLayout"<SmartRefreshLayout@noreply.github.com&gt;; 
抄送: "王冉"<735074170@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [scwang90/SmartRefreshLayout] 使用沉浸式状态栏后，刷新头部被遮挡了 (#934)





 
楼主解决了吗？我看了Demo，没发现这个高度要怎么计算的，作者用的toolbar 可以计算出，如果SML 上面没有任何控件怎么计算？SML 侵入状态栏以外了

**Comment by wr1024** [comment]
&nbsp; &nbsp; &nbsp; &nbsp;计算状态栏告诉，然后设置一下。&nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;int result = 0;
&nbsp; &nbsp; &nbsp; &nbsp; int resourceId = context.getResources().getIdentifier(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "status_bar_height", "dimen", "android");
&nbsp; &nbsp; &nbsp; &nbsp; if (resourceId &gt; 0) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; result = context.getResources().getDimensionPixelSize(resourceId);
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; return result;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ymars1990"<notifications@github.com&gt;; 
发送时间: 2020年3月26日(星期四) 中午11:54
收件人: "scwang90/SmartRefreshLayout"<SmartRefreshLayout@noreply.github.com&gt;; 
抄送: "王冉"<735074170@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [scwang90/SmartRefreshLayout] 使用沉浸式状态栏后，刷新头部被遮挡了 (#934)





 
楼主解决了吗？我看了Demo，没发现这个高度要怎么计算的，作者用的toolbar 可以计算出，如果SML 上面没有任何控件怎么计算？SML 侵入状态栏以外了

**Comment by Ymars1990** [comment]
计算出来还是会有一部分在外面，这个计算不对少了把

**Comment by Ymars1990** [comment]
我发现是我外层ConstraintLayout  的问题，好尴尬
