### ISSUE TITLE
动画失效

### ISSUE THREAD

**Issue by LLXBH** [scwang90/SmartRefreshLayout#935]
我是创建的一个组合布局，在多个地方通过 `include` 使用的， 
在调用的地方给 `include 指定 android:layout_height="wrap_content"` 就会出现动画消失的现象，无论是上拉还是下拉，也无法再触发齐上下拉的回调
![image](https://user-images.githubusercontent.com/34165598/59322539-249cf900-8d09-11e9-8fd0-98e4215cbade.png)

**Comment by scwang90** [comment]
wrap_content 会导致 smart 高度=0
