### ISSUE TITLE
 java.lang.IllegalArgumentException报错

### ISSUE THREAD

**Issue by SmallStoneDD** [scwang90/SmartRefreshLayout#938]
java.lang.IllegalArgumentException
pointerIndex out of range
com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(Unknown Source:87)
机型 小米6

**Comment by RoyWallace** [comment]
遇到了同样的问题

**Comment by scwang90** [comment]
参考 https://www.jianshu.com/p/5113c110bc36
