### ISSUE TITLE
1.1.0 androidx 版本与CoordinatorLayout 无法联动

### ISSUE THREAD

**Issue by OumaSyuu** [scwang90/SmartRefreshLayout#939]
我使用CoordinatorLayout 嵌套NestedScrollView， 再用NestedScrollView嵌套SmartRefreshLayout，结果可以联动，但是无法实现下拉或者上拉刷新;
如果去掉NestedScrollView直接用CoordinatorLayout 嵌套SmartRefreshLayout，就无法联动CoordinatorLayout ，可以实现下拉或者上拉刷新
版本号为1.1.0-andx-11

**Comment by OumaSyuu** [comment]
` 
<androidx.coordinatorlayout.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:orientation="vertical"
        android:clipToPadding="true"
        android:fitsSystemWindows="true"
        android:background="@color/color_f0f0f0"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <com.google.android.material.appbar.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:clipToPadding="true"
            android:fitsSystemWindows="true">

        <androidx.appcompat.widget.Toolbar
                android:id="@+id/tool_bar"
                android:layout_width="match_parent"
                android:layout_height="@dimen/toolBarHeight"
                android:layout_marginTop="24dp"
                android:background="@color/colorPrimaryDark"
                android:theme="@style/ActionBar"
                app:contentInsetStart="0dp"
                app:layout_scrollFlags="scroll|enterAlways"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
        >

            <TextView
                    android:id="@+id/tool_bar_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:textColor="@color/black"
                    android:textSize="18sp"/>

        </androidx.appcompat.widget.Toolbar>


        <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_scrollFlags="scroll|snap">

            <ImageView
                    android:id="@+id/iv_tab"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    app:layout_constraintDimensionRatio="h,2:1"
                    android:src="@mipmap/beauty_cosmetics_depth_of_field_1571585"
                    android:scaleType="fitXY"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintRight_toRightOf="parent"
                    app:layout_constraintLeft_toLeftOf="parent"
            />

            <TextView
                    android:id="@+id/tv_brand_desc" android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="dsfpdjpdfmpdmgpdfmgldfmhpsdfmlbhdflmhbdfp;sgdfgsdgf
                        dfgdfgdsfgdsgfdsgfdsfgdsfgdsgfsgssgs
                        sgsgdfgdfgdfgdsfgdfgdfsgsdfgdsfgs"
                    android:textSize="@dimen/t_26"
                    android:textColor="@color/color_999999"
                    android:background="@color/white"
                    android:paddingTop="@dimen/a_90"
                    android:paddingLeft="@dimen/a_20"
                    android:paddingRight="@dimen/a_20"
                    android:paddingBottom="@dimen/a_30"
                    app:layout_constraintTop_toBottomOf="@id/iv_tab"
                    app:layout_constraintLeft_toLeftOf="parent"
                    app:layout_constraintRight_toRightOf="parent"/>

            <com.aojun.massiveoffer.util.ui.widgets.NiceImageView
                    android:id="@+id/niv_brand"
                    android:layout_width="@dimen/a_120"
                    android:layout_height="@dimen/a_120"
                    android:scaleType="fitXY"
                    app:srcCompat="@mipmap/beijing6"
                    app:radius_conner="@dimen/a_10"
                    app:layout_constraintLeft_toLeftOf="parent"
                    android:layout_marginLeft="@dimen/a_30"
                    app:layout_constraintBottom_toBottomOf="@id/iv_tab"
                    app:layout_constraintTop_toBottomOf="@id/iv_tab"/>

            <TextView
                    android:layout_width="wrap_content" android:layout_height="wrap_content"
                    android:id="@+id/tv_brand"
                    android:text="植村秀"
                    android:textColor="@color/color_333333"
                    android:textSize="@dimen/t_30"
                    app:layout_constraintBottom_toBottomOf="@id/niv_brand"
                    app:layout_constraintLeft_toRightOf="@id/niv_brand"
                    android:layout_marginLeft="@dimen/a_20"/>

            <TextView
                    android:layout_width="wrap_content" android:layout_height="wrap_content"
                    android:id="@+id/tv_brand_indicator"
                    android:text="国家"
                    android:textColor="@color/color_333333"
                    android:textSize="@dimen/t_30"
                    app:layout_constraintBottom_toBottomOf="@id/niv_brand"
                    app:layout_constraintRight_toRightOf="parent"
                    android:layout_marginRight="@dimen/a_20"/>


        </androidx.constraintlayout.widget.ConstraintLayout>
        <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_marginTop="@dimen/a_20"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white">

            <androidx.constraintlayout.widget.Guideline
                    android:id="@+id/guideline1" android:layout_width="0dp" android:layout_height="0dp"
                    android:orientation="vertical"
                    app:layout_constraintGuide_percent=".25"/>

            <TextView
                    android:id="@+id/tv_tab_sales" android:layout_width="wrap_content"
                    android:layout_height="@dimen/a_80"
                    android:text="销量"
                    android:gravity="center"
                    android:textSize="@dimen/t_26"
                    android:textColor="@color/color_333333"
                    android:drawableRight="@mipmap/paixu1"
                    android:drawablePadding="@dimen/a_20"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintLeft_toLeftOf="parent"
                    app:layout_constraintRight_toLeftOf="@id/guideline1"
                    app:layout_constraintBottom_toBottomOf="parent"/>

            <View android:layout_width="@dimen/a_1" android:layout_height="@dimen/a_60"
                  android:background="@color/color_e5e5e5"
                  app:layout_constraintLeft_toLeftOf="@id/guideline1"
                  app:layout_constraintRight_toRightOf="@id/guideline1"
                  app:layout_constraintTop_toTopOf="parent"
                  app:layout_constraintBottom_toBottomOf="parent"/>

            <androidx.constraintlayout.widget.Guideline
                    android:id="@+id/guideline2" android:layout_width="0dp" android:layout_height="0dp"
                    android:orientation="vertical"
                    app:layout_constraintGuide_percent=".5"/>

            <TextView
                    android:id="@+id/tv_tab_new" android:layout_width="wrap_content"
                    android:layout_height="@dimen/a_80"
                    android:text="新品"
                    android:gravity="center"
                    android:textSize="@dimen/t_26"
                    android:textColor="@color/color_333333"
                    android:drawableRight="@mipmap/paixu1"
                    android:drawablePadding="@dimen/a_20"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintLeft_toRightOf="@id/guideline1"
                    app:layout_constraintRight_toLeftOf="@id/guideline2"
                    app:layout_constraintBottom_toBottomOf="parent"/>

            <View android:layout_width="@dimen/a_1" android:layout_height="@dimen/a_60"
                  android:background="@color/color_e5e5e5"
                  app:layout_constraintLeft_toLeftOf="@id/guideline2"
                  app:layout_constraintRight_toRightOf="@id/guideline2"
                  app:layout_constraintTop_toTopOf="parent"
                  app:layout_constraintBottom_toBottomOf="parent"/>
            <androidx.constraintlayout.widget.Guideline
                    android:id="@+id/guideline3" android:layout_width="0dp" android:layout_height="0dp"
                    android:orientation="vertical"
                    app:layout_constraintGuide_percent=".75"/>
            <TextView
                    android:id="@+id/tv_tab_price" android:layout_width="wrap_content"
                    android:layout_height="@dimen/a_80"
                    android:text="价格"
                    android:gravity="center"
                    android:textSize="@dimen/t_26"
                    android:textColor="@color/color_333333"
                    android:drawableRight="@mipmap/paixu1"
                    android:drawablePadding="@dimen/a_20"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintLeft_toRightOf="@id/guideline2"
                    app:layout_constraintRight_toLeftOf="@id/guideline3"
                    app:layout_constraintBottom_toBottomOf="parent"/>

            <View android:layout_width="@dimen/a_1" android:layout_height="@dimen/a_60"
                  android:background="@color/color_e5e5e5"
                  app:layout_constraintLeft_toLeftOf="@id/guideline3"
                  app:layout_constraintRight_toRightOf="@id/guideline3"
                  app:layout_constraintTop_toTopOf="parent"
                  app:layout_constraintBottom_toBottomOf="parent"/>

            <TextView
                    android:id="@+id/tv_tab_select" android:layout_width="wrap_content"
                    android:layout_height="@dimen/a_80"
                    android:text="筛选"
                    android:gravity="center"
                    android:textSize="@dimen/t_26"
                    android:textColor="@color/color_333333"
                    android:drawableRight="@mipmap/xiala_1"
                    android:drawablePadding="@dimen/a_20"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintLeft_toRightOf="@id/guideline3"
                    app:layout_constraintRight_toRightOf="parent"
                    app:layout_constraintBottom_toBottomOf="parent"/>

        </androidx.constraintlayout.widget.ConstraintLayout>

    </com.google.android.material.appbar.AppBarLayout>

    <androidx.core.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior">

        <com.scwang.smartrefresh.layout.SmartRefreshLayout
                android:id="@+id/srl_list"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical">

            <com.scwang.smartrefresh.layout.header.ClassicsHeader
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"/>

            <com.aojun.massiveoffer.util.ui.widgets.NestedGridView
                    android:paddingTop="@dimen/a_20"
                    android:id="@+id/gv_list"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:numColumns="2"
                    android:stretchMode="columnWidth"
                    android:horizontalSpacing="@dimen/a_20"
                    android:verticalSpacing="@dimen/t_30"
                    android:paddingRight="@dimen/a_20"
                    android:paddingLeft="@dimen/a_20"/>

            <com.scwang.smartrefresh.layout.footer.ClassicsFooter
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"/>

        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    </androidx.core.widget.NestedScrollView>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
 `

**Comment by OumaSyuu** [comment]
我这边并没有全局设置SmartRefreshLayout配置，同时相应的activity中只有在view加载完成后只调用了
`
srl_list.setEnableNestedScroll(true)
        srl_list.setOnRefreshListener(this)
        srl_list.setOnLoadMoreListener(this)
`这三个方法，listener中是常规的finish刷新方法

**Comment by scwang90** [comment]
让 SmartRefreshLayout 和 外面的  NestedScrollView 换个位置

**Comment by DancingDuck** [comment]
@OumaSyuu  同样的问题  请问你解决了么

**Comment by stevenwsg** [comment]
同样的问题， 有解决嘛
