### ISSUE TITLE
ClassicsFooter 的提示语颜色设置不了

### ISSUE THREAD

**Issue by onesand** [scwang90/SmartRefreshLayout#94]
app:srlAccentColor="@android:color/holo_blue_dark"
        app:srlPrimaryColor="@android:color/holo_blue_dark"
        android:background="#444440"
这样写 head 整体变为了蓝色  footer 的整体是灰色  字体也是灰色

**Comment by scwang90** [comment]
ClassicsFooter 不支持主题颜色，需要自定义 footer
