### ISSUE TITLE
相邻两个fragment，smartrefreshlayout不显示刷新头部，并且smartrefreshlayout的高度为零

### ISSUE THREAD

**Issue by AndMy** [scwang90/SmartRefreshLayout#943]
首页有4个tab分别对应4个fragment，其中位置1和2相邻两个fragment，每个fragment包含viewpage，viewpage里的fragment都用autorefresh自动刷新属性，这是页面布局
遇到的问题：
1、启动app，
点击位置1的fragment会执行刷新头部的动画；
然后接着点击2位置的fragment不显示刷新头部的动画（头部的布局也不显示），并且smartrefreshlayout控件的高度为零，通过log观察，执行了下拉刷新的监听方法，网络数据请求成功，最终效果是smartrefreshlayout里recycleview空白，通过设置背景色，观察到smartrefreshlayout控件的高度为零
2、启动app，
点击位置2的fragment会执行刷新头部的动画；
然后接着点击1位置的fragment不显示刷新头部的动画（头部的布局也不显示），并且smartrefreshlayout控件的高度为零，通过log观察，执行了下拉刷新的监听方法，网络数据请求成功，最终效果是smartrefreshlayout里recycleview空白，通过设置背景色，观察到smartrefreshlayout控件的高度为零。

就是相邻的两个fragment里包含viewpage，首次点击的fragment没问题，接着点击的fragment就会出现smartrefreshlayout控件不显示刷新头部布局、也没有动画、高度为零的问题
用到的版本：implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-andx-11'

**Comment by wangtonggen** [comment]
这个问题我也遇到了,你是怎么解决的
