### ISSUE TITLE
为什么我们app打包后软件名称都变成了智能刷新!!!

### ISSUE THREAD

**Issue by badboy-tian** [scwang90/SmartRefreshLayout#947]
```
 <string name="app_name">智能刷新</string>
```
反编译后,  发现app名称变了

implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5'

**Comment by jmhjmh** [comment]
'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-28'试试

**Comment by badboy-tian** [comment]
@jmhjmh 可以了 谢谢
