### ISSUE TITLE
refreshLayout.autoRefresh()毫无规律的导致数据刷新后无法正常渲染的问题

### ISSUE THREAD

**Issue by kmlixh** [scwang90/SmartRefreshLayout#950]
偶然发现，在Fragment中使用RefreshLayout，执行refreshLayout.autoRefresh()，虽然可以正确触发onRefresh方法，但是存在很高的概率导致Adapter获取数据之后，notifyItemRangeInserted之类的方法完全不起作用，如果将refreshlayout直接在Activity的布局中运行，则完全没有问题。另外，在下拉刷新的过程中，百分百导致UI渲染超过16ms的流畅阈值，麻烦开发者大佬优化一下下这块的业务逻辑。

**Comment by scwang90** [comment]
目前没发现问题，建议autoRefresh 值在第一次界面加载的时候调用，避免导致混乱
