### ISSUE TITLE
demo sync不成功

### ISSUE THREAD

**Issue by tzt1994** [scwang90/SmartRefreshLayout#953]
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.squareup.leakcanary:leakcanary-android:1.6.3: Skipped due to earlier error

**Comment by sansecy** [comment]
把app模块下的build.gradle里的 maven { url "https://jitpack.io" } 移到 主工程的 build.gradle的allprojects下

![image](https://user-images.githubusercontent.com/15917610/60323061-9638a080-99b3-11e9-9f71-8748c4fe8a12.png)

![image](https://user-images.githubusercontent.com/15917610/60323137-c8e29900-99b3-11e9-9ba5-a6cd58cf3414.png)
