### ISSUE TITLE
自定义footer怎么在Nomoredata的时候贴在列表的底部

### ISSUE THREAD

**Issue by dnwalter** [scwang90/SmartRefreshLayout#954]
继承InternalAbstract的自定义的footer要怎么才能实现，当mSmartRefreshLayout.finishLoadMoreWithNoMoreData();时，footer是贴在列表的底部，而不是SmartRefreshLayout底部。ClassicsFooter就能有这种效果。
一般自定义的footer只要继承ClassicsFooter就能满足效果了。但我的footer比较不同，布局比较复杂。
虽然其实我继承ClassicsFooter也可以，但是我就要在我的布局文件写多几个没用的控件

**Comment by dnwalter** [comment]
我看了一前的一些回答，作者也建议在adapter里面加个footer。那ClassicsFooter是怎么实现会跟着列表底部的效果的

**Comment by scwang90** [comment]
实现 setNoMoreData 方法 并返回 true 就可以了
