### ISSUE TITLE
设置setEnableRefresh(false)后  Footer失去弹性了。。。

### ISSUE THREAD

**Issue by wangzixu5678** [scwang90/SmartRefreshLayout#955]
设置禁止下拉刷新后 上拉加载更多的footer在上拉之后 不会隐藏了  而且上拉的时候 footer布局遮盖住列表。

**Comment by Panjianan** [comment]
> 设置禁止下拉刷新后 上拉加载更多的footer在上拉之后 不会隐藏了 而且上拉的时候 footer布局遮盖住列表。

我也是这样，不过没有禁止下拉刷新。

**Comment by scwang90** [comment]
问题无法重现
