### ISSUE TITLE
TwoLevelHeader中嵌套RecyclerView滑动事件冲突

### ISSUE THREAD

**Issue by Yange820** [scwang90/SmartRefreshLayout#957]
TwoLevelHeader中放置了一个RecyclerView，两者的滑动事件冲突了，RecyclerView的滑动事件无法触发，设置了nestedScrollingEnabled=true也无效

**Comment by Yange820** [comment]
版本：  1.1.0-alpha-26

**Comment by santa222** [comment]
遇到同样问题

**Comment by santa222** [comment]
> 遇到同样问题

通过关闭嵌套滑动解决了                
` android:nestedScrollingEnabled="false"`
