### ISSUE TITLE
向下滑动事件无法传递到外层

### ISSUE THREAD

**Issue by LeoYe168** [scwang90/SmartRefreshLayout#961]
enableRefresh和enableLoadMore设置为false后，向下滑动事件无法传递到外层。。我最外层用的是BottomSheetDialogFragment，需要滑动事件传递出来。

**Comment by scwang90** [comment]
1.1.0 版本发布修复

**Comment by jiasongs** [comment]
1.1.0版本，enableRefresh设置为false之后，布局中的点击事件失效
