### ISSUE TITLE
当在viewpager中刷新，然后滑动几次后出现的问题

### ISSUE THREAD

**Issue by adminLiu-s** [scwang90/SmartRefreshLayout#963]
这是问题页面，右边部分直接缺失了，甚至有可能整个页面都不见，下拉刷新后滑动页面产生的
![image](https://user-images.githubusercontent.com/11938143/60853542-17532b80-a22f-11e9-96a5-e169c9719c7f.png)
这是正常的，没有下拉刷新，无论怎么滑动页面都不会出现，生命周期方法也没走，很奇怪
![image](https://user-images.githubusercontent.com/11938143/60853575-3baf0800-a22f-11e9-8bb3-9241da3c72cf.png)

**Comment by scwang90** [comment]
问题无法重现，如需解决，加群发代码
