### ISSUE TITLE
下拉刷新时，Header在下拉超出长度时可不可以不随着下拉距离往下移动，而是固定在一个位置

### ISSUE THREAD

**Issue by 1017161726** [scwang90/SmartRefreshLayout#966]
下拉刷新时，Header在下拉超出长度时可不可以不随着下拉距离往下移动，而是固定在一个位置。
readme里面找到有设置SpinnerStyle.FixedBehind，但设置无效，还是会滚动到最底部。

**Comment by scwang90** [comment]
SpinnerStyle 设置之后就不能再改了
可以一开始就指定 SpinnerStyle.FixedBehind
在开始的时候，自己用代码模拟 下移动作，超出距离之后，就不下移了
