### ISSUE TITLE
setEnableRefresh(false)后再设置setEnableRefresh(true)自定义头部会隐藏不显示问题

### ISSUE THREAD

**Issue by CalmCenter** [scwang90/SmartRefreshLayout#968]
如题
因为事件太多我需要在某个阶段关闭滑动，setEnableRefresh 方法是一直调用的
使用内置 ClassicsHeader 也有同样的问题，但是当 onStateChanged 状态返回 ReleaseToRefresh 时，设置文字和执行动画后，它神奇的出现了，我仿照它的方法也使用旋转动画并更换图片(我使用的是帧图)，然而并没有效果。
有没有小伙伴遇到了同样的问题？？
锅在哪？

**Comment by scwang90** [comment]
···
    /**
     * 是否启用下拉刷新（默认启用）
     * @param enabled 是否启用
     * @return SmartRefreshLayout
     */
    @Override
    public RefreshLayout setEnableRefresh(boolean enabled) {
        this.mEnableRefresh = enabled;
        return this;
    }
···

setEnableRefresh  实现很简单，它只能作为初始条件设置，或者闲置状态下设置。并不支持在事件华东过程中对它进行设置，这样比如会导致不可预料的问题。

如果只是因为 事件冲突而想关闭滑动功能，应该使用 Smart 提供的滚动边界设置来直接控制 
···
    /**
     * 根据内容视图状态判断是否可以开始下拉刷新
     * @param content 内容视图
     * @return true 将会触发下拉刷新
     */
    boolean canRefresh(View content);
···

**Comment by gehaojie** [comment]
尊敬的作者，您好！

我也是想在滑动的时候关闭/开启下拉刷新，这个canRefresh方法看起来像是判断，不像是设置的方法。

我的场景，Smart->ScrollView->FrameLayout->(下层是RV)（上层是垂直线性布局，跟下层同高度的透明View+Rv），当FrameLayout上层滑动到顶部，再滑动下来。通过setEnableRefresh设置开关，下滑出现刷新动画已经下来，刷新状态已经该笔那，但是页面上不展示动画提示，松开手势会直接显示出来，然后走刷新方法。

如果没描述清楚，实在抱歉

**Comment by gehaojie** [comment]
接上面：

我需求：下层RV，上层View+RV也不可以向下滑动的时候，开启刷新。

但是每次下层View滑上去一点，抬起，下滑，就会被刷新事件拦截掉。
