### ISSUE TITLE
把触发刷新距离设置短一点后，Header动画异常

### ISSUE THREAD

**Issue by CuiZhaoHui** [scwang90/SmartRefreshLayout#969]
使用的是 `MaterialHeader`
`setHeaderTriggerRate(0.6f);`设置触发刷新距离，然后下拉到能触发的距离松手。
第一圈的动画会有异常。猜测是第一圈rotation计算错误，头没转。之后会恢复正常。
如图：
![RECORD](https://user-images.githubusercontent.com/18044789/61104875-71abf080-a4aa-11e9-84b6-4dd1c84960c3.gif)

请问有解决方案么。

**Comment by scwang90** [comment]
你应该设置 HeaderHeight 而不是设置 setHeaderTriggerRate 同样会改变 触发距离
