### ISSUE TITLE
为什么回刷新两次？

### ISSUE THREAD

**Issue by qzqs** [scwang90/SmartRefreshLayout#970]
每次调用refreshLayout.autoRefresh();//自动刷新 的方法总是会出发一次setOnRefreshListener()方法。这样会导致两次的刷新，怎么让调用autoRefresh()的时候不调用到setOnRefreshListener()方法呢

**Comment by qzqs** [comment]
refreshLayout.autoRefreshAnimationOnly()，原来还有这个方法。
但是还有一个问题，为什么动态改变不了下拉刷新的颜色呢？我用的是MD风格的下拉刷新。总是蓝色和红色，灰色。

**Comment by qzqs** [comment]
而且有时候向下滑动也会出发setOnRefreshListener()监听，不知道是什么情况。

**Comment by wxiangle** [comment]
我也 遇到了这个问题，自动向下滑竟然触发了下拉刷新的监听。很怪的逻辑，这倒是无所谓了，更气的是自动下拉刷新无法复位状态，导致再次调用refreshLayout.autoRefreshAnimationOnly() 无效

**Comment by scwang90** [comment]
调用 autoRefreshAnimationOnly 就不会有 回调了
修改演示需要手动调用方法setColorSchemeColors

**Comment by qzqs** [comment]
setColorSchemeColors都没有这个方法？

**Comment by liangxianshen** [comment]
我发现autoRefreshAnimationOnly也会回调onRefresh，不过概率很小，大概几十次会出现一次。
