### ISSUE TITLE
依赖成功使用失败

### ISSUE THREAD

**Issue by JumpingError** [scwang90/SmartRefreshLayout#972]
Error:(99, 30) 错误: 无法访问NestedScrollingParent
找不到androidx.core.view.NestedScrollingParent的类文件

**Comment by tujingwu** [comment]
我也遇到了

**Comment by tang5011235** [comment]
我也遇到了

**Comment by tang5011235** [comment]
这个问题我解决了，是到的包错了，我的项目没有使用androidx，但是导入的是com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-x 把后面这个-x去掉ok

**Comment by davidgerka** [comment]
项目了改用androidx，就报这个问题了，如下图。猜测原因是androidx不能与support包一起用，然后androidx又没有NestedScrollingParent接口，这该如何是好呢请大神指导@scwang90
![image](https://user-images.githubusercontent.com/13624423/64237731-86978400-cf2f-11e9-8903-0dc0db14abfd.png)
