### ISSUE TITLE
如何在未滑动到底部的时候就开始预加载下一页的数据？

### ISSUE THREAD

**Issue by zhaoziliang01** [scwang90/SmartRefreshLayout#974]

**Comment by XiFanYin** [comment]
同问  @scwang90

**Comment by guowanxin** [comment]
同问 @scwang90

**Comment by LaiZN** [comment]
同问

**Comment by hegaojian** [comment]
+1

**Comment by l476175728** [comment]
同问+1

**Comment by android-1995** [comment]
扩展adapter，参考[BaseRecyclerViewAdapterHelper](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)的实现

**Comment by MyMoonCat** [comment]
监听RecyclerView滑动事件，拿到当前可视的最后一个item position，然后用adapter.getItemCount()- position  == i  去手动调用onLoadMore(refreshlayout) 。i就是你想在滑动到倒数第几个item的时候去预加载。

**Comment by scwang90** [comment]
根据 smart 的实现原理，不支持这个功能，请使用 BaseRecyclerViewAdapterHelper 来实现

**Comment by RaymanMartin** [comment]
> 监听RecyclerView滑动事件，拿到当前可视的最后一个item position，然后用adapter.getItemCount()- position == i 去手动调用onLoadMore(refreshlayout) 。i就是你想在滑动到倒数第几个item的时候去预加载。

不满一屏的情况下，SmartRefreshLayout会拦截了RecyclerView的滚动事件，这个怎么处理？

**Comment by MyMoonCat** [comment]
不满一屏的情况下，一次请求的数据多一些啊

**Comment by MyMoonCat** [comment]
> > 监听RecyclerView滑动事件，拿到当前可视的最后一个item position，然后用adapter.getItemCount()- position == i 去手动调用onLoadMore(refreshlayout) 。i就是你想在滑动到倒数第几个item的时候去预加载。
> 
> 不满一屏的情况下，SmartRefreshLayout会拦截了RecyclerView的滚动事件，这个怎么处理？

一页请求的数据尽量超过一屏吧，要处理就是adapter.setData 完 调用 RecyclerView.poseDelayed  里去判断当前可视的最后一个item position  == adapter.getItemCount() ， true 就是不满一页然后手动调用onLoadMore(refreshlayout)

**Comment by Dazmk** [comment]
https://juejin.im/post/6885146484791050247

我参考掘金的这个帖子实现的预加载功能，核心思路就是监听 RecyclerView 的滑动，通过 LinearLayoutManager 计算是否需要触发加载更多逻辑代码，核心代码如下（仅供参考）：


        int preloadCount = 5;
        bindingView.homeTimelineRv.setOnScrollChangeListener(new View.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {
                if (linearLayoutManager.findLastVisibleItemPosition() == linearLayoutManager.getItemCount() - 1 - preloadCount) {
                    loadMoreTimeline();
                }
            }
        });
