### ISSUE TITLE
1.当页面使用顶部EditText时 ，键盘回收后  页面不能完全恢复 2.部分情况，当页面有EditText时使用Dialog(底部显示)，关闭dialog后页面会上滑一段距离

### ISSUE THREAD

**Issue by skpy5272** [scwang90/SmartRefreshLayout#977]
1.当页面使用顶部EditText时 ，键盘回收后  页面不能完全恢复 
无盘 无码 无毒 
原谅我这low13  图片在百度网盘
链接：https://pan.baidu.com/s/1zC2G2Xl-DYaQdQ_lR8Nw2g 
提取码：mruy 
 2.部分情况，当页面有EditText时使用Dialog(底部显示)，关闭dialog后页面会上滑一段距离
异常视频 百度网盘
链接：https://pan.baidu.com/s/1-T69Aphjs5KDN5wKGA9NAQ 
提取码：wa5m

**Comment by scwang90** [comment]
这个问题需要加群解决
