### ISSUE TITLE
怎么加入EmptyView或者ErrorView

### ISSUE THREAD

**Issue by Alex861** [scwang90/SmartRefreshLayout#98]

**Comment by AndSync** [comment]
这个问题我提过了 作者不打算支持，我的方案是用footer的形式来做 加载中 加载失败 没有数据用一个EmptyView 添加到footer中
对于ListView来说是有EmptyView的 但是有两个问题
1、设置emptyView需要包裹一层布局 这样滑动可能就会有问题
2、如果有Header ，当列表没有数据 Header有数据的话 这时候会显示出EmptyView， Header就显示不出来了
对于RecyclerView 没有支持empty 也没有header footer的支持，只能自己重写添加支持了
综上还是采用addFooter的形式比较好

**Comment by scwang90** [comment]
本库没有这个功能，以后也不会支持，请使用其他的开源库来切换状态页面
