### ISSUE TITLE
autoRefresh在Onstart中调用的问题

### ISSUE THREAD

**Issue by Wurigen** [scwang90/SmartRefreshLayout#982]
1.在 1.1.0-alpha-31版本中在onStart中调用autoReresh() 不会自动调用onRefresh()方法
2.并且在调用autoRefreshAnimationOnly();方法时 同样会响应onRefresh()方法

**Comment by KAICW** [comment]
1.1.0 autoReresh 不调用

**Comment by scwang90** [comment]
更新到最新版本
