### ISSUE TITLE
网络请求过快导致下拉刷新不触发OnRefreshListener

### ISSUE THREAD

**Issue by ooftf** [scwang90/SmartRefreshLayout#983]
版本：1.1.0-andx-14
调用过程：  网络开始->调用autoRefreshAnimationOnly ->网络请求很快结束->调用finishRefresh同时调用了finishLoadMoreWithNoMoreData     
手动触发下拉刷新，但是SmartRefereshLayout内部没有触发OnRefreshListener

猜想：有可能是“网络请求很快结束”才会触发，因为事偶发事件

**Comment by lxr17** [comment]
我也遇到了这个问题，可以再finishRefresh的时候加一个延迟：finishRefresh(500);
这样能够解决该问题。
