### ISSUE TITLE
内嵌recyclerview配合ItemTouchHelper实现item拖动排序时，会触发下拉刷新

### ISSUE THREAD

**Issue by guyuepeng** [scwang90/SmartRefreshLayout#985]
内嵌recyclerview配合ItemTouchHelper实现item拖动排序时，长按拖住一个item下拉，原本应该item随手拖动，但是会触发refreshlayout下拉刷新

**Comment by appdev** [comment]
我也有这问题。

**Comment by cascoxbw** [comment]
同问，解决了吗？

**Comment by cascoxbw** [comment]
> 内嵌recyclerview配合ItemTouchHelper实现item拖动排序时，长按拖住一个item下拉，原本应该item随手拖动，但是会触发refreshlayout下拉刷新

解决了吗？

**Comment by GokHoLee** [comment]
我也遇到这个问题了, 权宜之计是通过将SmartRefreshLayout传入到自定义ItemTouchHelper, 然后在onSelectedChanged里面根据状态设置刷新可用性的来实现的

**Comment by scwang90** [comment]
建议在开始拖动的时候，关闭下拉刷新功能
