### ISSUE TITLE
设置 srlEnableHeaderTranslationContent=false，Header 不可见

### ISSUE THREAD

**Issue by chiemy** [scwang90/SmartRefreshLayout#987]
从 1.1.0-alpha-27 升级到  1.1.0-alpha-32，设置 srlEnableHeaderTranslationContent=false 的页面，Header 不可见，推测跟 onAttachedToWindow 中重新排序部分的代码变动有关系，延迟一段时间调用 header.bringToFront 能显示了。自定义 RefreshHeader 的 SpinnerStyle 为 SpinnerStyle.Translate。

**Comment by chiemy** [comment]
1.1.0-alpha-27 升级 1.1.0-alpha-32 后，设置 srlEnableHeaderTranslationContent=false 的地方， Header 不见了，我延迟了一段时间将 header bringToFront 就好了。
`
refreshLayout.postDelayed(new Runnable() {
            @Override
            public void run() {
                refreshHeader.bringToFront();
            }
        }, 1000);
`
推测跟 SmartRefreshLayout#onAttachedToWindow 方法中重新排序那部分有关。

**Comment by scwang90** [comment]
1.1.0-beta-1 发布修复
