### ISSUE TITLE
java.lang.RuntimeException Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e08489

### ISSUE THREAD

**Issue by ForeverLover** [scwang90/SmartRefreshLayout#989]
版本是1.0.5.1.这个跟列表项有关么
android.view.View.draw(View.java:21607)
--
26 android.view.ViewGroup.drawChild(ViewGroup.java:4558)
27 com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:838)

**Comment by scwang90** [comment]
参考 #811
