### ISSUE TITLE
遇到内存泄露问题，请看详情！

### ISSUE THREAD

**Issue by chunca** [scwang90/SmartRefreshLayout#99]
版本号：1.0.3-alpha-3（之前的版本也遇到过）
使用代码：
//-----------------------------------------------------------------
private void initRefreshLayout() {
    mRecyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
    mRecyclerView
        .addItemDecoration(new RecyclerViewDivider(getContext(), DividerItemDecoration.VERTICAL));

    mRecyclerView.setItemAnimator(new DefaultItemAnimator());
    mRecyclerView
        .setAdapter(mAdapter = new BaseRecyclerAdapter<CourseReply>(mList,
            R.layout.adapter_item_course_reply) {
          @Override
          protected void onBindViewHolder(SmartViewHolder holder, CourseReply model, int position) {
            holder.text(R.id.reply_content, model.getContent());
            holder.text(R.id.reply_time, model.getCreateTime());
            ((RatingBar) holder.findViewById(R.id.rating_reply))
                .setRating((float) model.getOverallScore());
            holder.text(R.id.reply_name, model.getCreateUserName());
            if (!TextUtils.isEmpty(String.valueOf(model.getCreateUserId()))) {
              String headUri = ConstsData.HOST + "/common/head/"
                  + model.getCreateUserId() + "/100";
              GlideUtils.loadUserAvatar(getActivity(), headUri,
                  (CircleImageView) holder.findViewById(R.id.reply_avatar));
            }
          }
        });
    mRefreshLayout.setRefreshHeader(new MaterialHeader(getActivity()));
    mRefreshLayout.setRefreshFooter(new BallPulseFooter(getActivity()));
    mRefreshLayout.setEnableHeaderTranslationContent(false);
    mRefreshLayout.setOnRefreshListener(new OnRefreshListener() {
      @Override
      public void onRefresh(RefreshLayout refreshlayout) {
        mRefreshLayout.setLoadmoreFinished(false);
        curPageIndex = 1;
        httpCommentList();
      }
    });
    mRefreshLayout.setOnLoadmoreListener(new OnLoadmoreListener() {
      @Override
      public void onLoadmore(RefreshLayout refreshlayout) {
        curPageIndex += 1;
        httpCommentList();

      }
    });
  }
//-----------------------------------------------------------------
全局配置header和footer也会遇到内存泄漏，请问大佬我写的代码有问题吗？

**Comment by chunca** [comment]
![5341ac49f77af90b6808591de9068d6a](https://user-images.githubusercontent.com/13847079/28760349-ed6cfbc2-75d8-11e7-996b-46f7123767c8.jpg)

**Comment by xiang473535976** [comment]
我也遇到了   全局配置了头部 就内存泄漏了

**Comment by a512509050** [comment]
同上

**Comment by LailaiMaster** [comment]
同上

**Comment by scwang90** [comment]
新版版 1.0.3-xxxx-5 发布，大家试试看是否还有问题

**Comment by chunca** [comment]
内存泄漏问题还在，而且这次出现了个新问题，下拉刷新后，想上拉浏览上面的内容，header直接被拉出来刷新了，1.0.3-xxxx-4版本也存在这个问题，麻烦看一下

**Comment by scwang90** [comment]
麻烦把 泄漏的截图再发过来

**Comment by chunca** [comment]
![e25bb3ce6e826a91f4452259b85dfe00](https://user-images.githubusercontent.com/13847079/28805382-2e4c38d8-769c-11e7-881f-4c6255c9a786.jpg)

**Comment by scwang90** [comment]
新的泄漏问题看起来和本刷新库无关呀~

**Comment by chunca** [comment]
好的

**Comment by xiang473535976** [comment]
看嘛 内存泄漏
![screenshot_2017-08-01-10-49-23-794_aichen stopcar](https://user-images.githubusercontent.com/18111614/28807358-a8e4b2fe-76a7-11e7-8d1e-de91fd686d35.png)

**Comment by scwang90** [comment]
后面发的这个 泄漏和本库没关系呀

**Comment by xiang473535976** [comment]
加了全局配置头部 就会这样
