### ISSUE TITLE
BottomSheetDialogFragment 嵌套 RecyclerView 无法正常滑动

### ISSUE THREAD

**Issue by moyiciai** [scwang90/SmartRefreshLayout#994]
RecyclerView 只能上拉，但是不能下拉，下拉的话 BottomSheetDialogFragment 会滑动关闭，禁用掉 SmartRefreshLayout 的上拉和下拉后是正常的。

**Comment by hoop208** [comment]
BottomSheetDialogFragment 里面做下拉,期待的结果是刷新数据还是滑动关闭,这个听起来冲突吧?

**Comment by mxruan** [comment]
> RecyclerView只能上拉，但是不能拖动，拖动的话BottomSheetDialogFragment会滑动关闭，替换掉SmartRefreshLayout的上拉和下拉后是正常的。

我也遇到同样的问题，请最后你是如何解决的？

**Comment by moyiciai** [comment]
> 我也遇到同样的问题，请最后你是如何解决的？

我在 SmartRefreshLayout 外层嵌套了一个 NestedScrollView，而且我禁用了刷新，只保留了加载更多。

**Comment by scwang90** [comment]
demo 中有 BottomSheetDialogFragment  的例子

**Comment by liulang-alin** [comment]
> > 我也遇到同样的问题，请最后你是如何解决的？
> 
> 我在 SmartRefreshLayout 外层嵌套了一个 NestedScrollView，而且我禁用了刷新，只保留了加载更多。

正好解决了在弹框里面只需要上拉加载的问题   6666

**Comment by chenkexu** [comment]
> > 我也遇到同样的问题，请最后你是如何解决的？
> 
> 我在 SmartRefreshLayout 外层嵌套了一个 NestedScrollView，而且我禁用了刷新，只保留了加载更多。

外层嵌套了一个 NestedScrollView 不会影响SmartRefreshLayout 加载更多吗？

**Comment by wallfacert** [comment]
加个属性就行了：app:srlEnableNestedScrolling="false"

**Comment by P3rryW4ng** [comment]
> 加个属性就行了：app:srlEnableNestedScrolling="false"

加了这个属性就好用了😊
