### ISSUE TITLE
下拉刷新完成没有数据我怎么加提示？

### ISSUE THREAD

**Issue by xiaofengff** [scwang90/SmartRefreshLayout#995]
如题，finishLoadMoreWithNoMoreData 只是在底部有个没有更多数据，我想在空白的页面上提示一个，“没有数据” 这个框架有没有这个功能

**Comment by scwang90** [comment]
把 列表设置 wrap_content 然后设置 smart footer 跟随列表，参考demo 基本使用

**Comment by 15629061018** [comment]
加个ViewStub 自己控制下
