### ISSUE TITLE
文档中的maven地址描述错误

### ISSUE THREAD

**Issue by cultivation-of-taoism** [scwang90/SmartRefreshLayout#996]
文档中的maven地址描述
//1.1.0 （1.0.5及以前版本的老用户升级需谨慎，API改动过大）
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-beta-1'
compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-beta-1'//没有使用特殊Header，可以不加这行
经过实际测试，com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-beta-1 这个地址是错误的，
改成com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-bata-1就可以了，估计是作者发布到maven仓库的时候把文件名打错了

**Comment by scwang90** [comment]
问题已修复
