### ISSUE TITLE
java.lang.IllegalStateException ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)  com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(Unknown Source:419)

### ISSUE THREAD

**Issue by fadedHYC** [scwang90/SmartRefreshLayout#998]
![image](https://user-images.githubusercontent.com/22925521/62819105-1b9e9b80-bb83-11e9-8e04-c37109e1a36b.png)
版本： api 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-14'
    api 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-alpha-14'//没有使用特殊Header，可以不加这行

**Comment by scwang90** [comment]
自行百度
