### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by snpmyn** [scwang90/SmartRefreshLayout#999]
你好！

`implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'`这个是androidx版本吗？按照你的主页提示，`implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-x'`报黄，提示升级至1.1.0

请问哪个是androidx版本？谢谢！

**Comment by scwang90** [comment]
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-x' 是 androidx
不过可以直接使用 
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'
不会有问题的，记得加上

android.useAndroidX=true
android.enableJetifier=true

就好

**Comment by snpmyn** [comment]
好的，谢谢！
